Repository mlrun/ui, pull requests merged in 2020-03, with the labels that each got.

#42 Development
  package.json
  src/common/Download/Download.js
  src/common/Download/download.scss
  src/common/Loader/loader.scss
  src/common/ProgressRing/ProgressRing.js
  src/common/Tooltip/Tooltip.js
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/Details/details.scss
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsArtifacts/detailsArtifacts.scss
  src/components/FilterMenu/FilterMenu.js
  src/components/FilterMenu/filterMenu.scss
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/elements/ChipCell/ChipCell.js
  src/elements/PreviewModal/previewmodal.scss
  src/elements/TooltipTemplate/ProducerTooltipTemplate.js
  src/elements/TooltipTemplate/TextTooltipTemplate.js
  src/images/close.png
  src/images/download.png
Labels: bug

#43 [Artifacts] Info tab: Add Sources
  package.json
  src/actions/artifacts.js
  src/common/ActionsMenu/ActionsMenu.js
  src/common/ActionsMenu/actionsMenu.scss
  src/common/YamlModal/yamlmodal.scss
  src/components/ArtifactSources/ArtifactSources.js
  src/components/ArtifactSources/artifactsources.scss
  src/components/Artifacts/Artifacts.js
  src/components/Artifacts/artifactsData.json
  src/components/Details/Details.js
  src/components/Details/details.scss
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/DetailsResults/DetailsResults.js
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/elements/ArtifactsDetailsInfoItem/ArtifactsDetailsInfoItem.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/elements/PreviewModal/PreviewModal.js
  src/elements/TableCell/TableCell.js
  src/images/yaml.png
  src/layout/Content/content.scss
  src/reducers/artifactReducer.js
  src/scss/mixins.scss
Labels: enhancement

#45 Development
  package.json
  src/common/ActionsMenu/ActionsMenu.js
  src/components/Details/Details.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/elements/ArtifactsDetailsInfoItem/ArtifactsDetailsInfoItem.js
  src/elements/ChipCell/ChipCell.js
  src/elements/JobsDetailsInfoItem/JobsDetailsInfoItem.js
  src/elements/PreviewModal/previewmodal.scss
  src/elements/TableCell/TableCell.js
  src/scss/mixins.scss
  src/utils/object.js
Labels: bug

#44 Group by name filter
  src/actions/jobs.js
  src/common/ActionsMenu/ActionsMenu.js
  src/common/ActionsMenu/actionsMenu.scss
  src/common/Select/selectData.json
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/Details/Details.js
  src/components/Details/details.scss
  src/components/DetailsInfo/detailsInfo.scss
  src/components/DetailsLogs/DetailsLogs.js
  src/components/DetailsResults/DetailsResults.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FilterMenu/filterMenu.scss
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.json
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/Chip/Chip.js
  src/elements/ChipCell/ChipCell.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/elements/TableCell/TableCell.js
  src/images/collapse.png
  src/images/download-icon.png
  src/images/expand.png
  src/images/horovod.png
  src/images/nuclio.png
  src/images/spark.png
  src/layout/Content/Content.js
  src/layout/Content/content.scss
  src/scss/colors.scss
  src/scss/main.scss
  src/utils/createJobsContent.js
Labels: bug, enhancement

#46 Development
  src/api/artifacts-api.js
  src/common/ActionsMenu/ActionsMenu.js
  src/common/Download/Download.js
  src/common/Tooltip/Tooltip.js
  src/components/ArtifactFilterLabels/ArtifactFilterLabels.js
  src/components/ArtifactFilterLabels/artifactfilterlabels.scss
  src/components/ArtifactInfoSources/ArtifactInfoSources.js
  src/components/ArtifactInfoSources/artifactinfosources.scss
  src/components/Artifacts/Artifacts.js
  src/components/Artifacts/artifactsData.json
  src/components/ArtifactsFilterTree/artifactsfiltertree.scss
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/FilterMenu/FilterMenu.js
  src/components/NotificationDownload/NotificationDownload.js
  src/components/NotificationDownload/NotificationDownloadView.js
  src/components/NotificationDownload/notificationdownloadview.scss
  src/components/Table/Table.js
  src/components/Table/table.scss
  src/elements/ArtifactsDetailsInfoItem/ArtifactsDetailsInfoItem.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/Chip/Chip.js
  src/elements/ChipCell/ChipCell.js
  src/elements/ChipCell/SizeChips.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/layout/Content/content.scss
  src/scss/colors.scss
  src/scss/main.scss
  src/scss/mixins.scss
Labels: enhancement

#47 Development
  src/components/JobsPage/Jobs.js
  src/components/Table/table.scss
  src/elements/JobsTableRow/JobsTableRow.js
  src/scss/mixins.scss
Labels: bug

#49 Change port
  package.json
Labels: enhancement

#50 Development
  src/actions/jobs.js
  src/actions/projects.js
  src/common/Tooltip/Tooltip.js
  src/components/ArtifactInfoSources/artifactinfosources.scss
  src/components/ArtifactsFilterTree/ArtifactsFilterTree.js
  src/components/ArtifactsFilterTree/artifactsfiltertree.scss
  src/components/Details/Details.js
  src/components/DetailsLogs/DetailsLogs.js
  src/components/NotificationDownload/NotificationDownloadView.js
  src/components/ProjectsPage/Projects.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/elements/TableCell/TableCell.js
  src/layout/Content/content.scss
  src/reducers/jobReducer.js
  src/reducers/projectReducer.js
  src/utils/createJobsContent.js
Labels: enhancement

#53 Impl [Artifacts] Add Metadata tab
  src/components/ArtifactFilterLabels/ArtifactFilterLabels.js
  src/components/ArtifactInfoMetadata/ArtifactInfoMetada.js
  src/components/ArtifactInfoMetadata/artifactinfometadata.scss
  src/components/ArtifactInfoSources/ArtifactInfoSources.js
  src/components/Artifacts/Artifacts.js
  src/components/Artifacts/artifactsData.json
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/Details/Details.js
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/FilterMenu/FilterMenu.js
  src/components/JobsPage/Jobs.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/elements/TableCell/TableCell.js
Labels: enhancement

#52 fixed capitalize header in the table preview
  src/components/DetailsArtifacts/detailsArtifacts.scss
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/detailsInfo.scss
Labels: enhancement

#56 Fix [Artifacts] Metadata: UI breaks when there is no STD
  src/components/ArtifactInfoMetadata/ArtifactInfoMetada.js
Labels: bug

#57 Development
  src/actions/jobs.js
  src/api/artifacts-api.js
  src/api/jobs-api.js
  src/components/ArtifactFilterLabels/ArtifactFilterLabels.js
  src/components/ArtifactInfoMetadata/ArtifactInfoMetada.js
  src/components/ArtifactInfoMetadata/artifactinfometadata.scss
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/DetailsArtifacts/detailsArtifacts.scss
  src/components/FilterMenu/FilterMenu.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.json
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/images/ic-key.png
  src/images/ic_key.png
Labels: enhancement

#58 Development
  src/api/projects-api.js
  src/components/ArtifactInfoMetadata/ArtifactInfoMetada.js
  src/components/FilterMenu/FilterMenu.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/projects.scss
  src/elements/JobsTableRow/JobsTableRow.js
  src/elements/ProjectCard/ProjectCard.js
  src/scss/colors.scss
Labels: enhancement

#59 Impl [Projects] Change background and spacing
  src/components/ProjectsPage/projects.scss
Labels: enhancement

#60 Cleanup [General] Remove `console` so eslint passes on prod
  src/store/store.js
Labels: Cleanup

#61 Create job screen
  src/App.js
  src/actions/functions.js
  src/actions/jobs.js
  src/api/functions-api.js
  src/colorConstants.js
  src/common/Breadcrumbs/Breadcrumbs.js
  src/common/Download/Download.js
  src/common/Download/download.scss
  src/common/PageActionsMenu/PageActionsMenu.js
  src/common/PageActionsMenu/pageActionsMenu.scss
  src/common/ProgressRing/ProgressRing.js
  src/common/ProgressRing/progressRing.scss
  src/common/Search/search.scss
  src/common/Select/Select.js
  src/common/Select/select.scss
  src/common/Select/selectData.json
  src/common/TableActionsMenu/TableActionsMenu.js
  src/common/TableActionsMenu/tableActionsMenu.scss
  src/components/CreateJobPage/CreateJobPage.js
  src/components/CreateJobPage/CreateJobPageView.js
  src/components/CreateJobPage/createJobPage.scss
  src/components/Details/Details.js
  src/components/Details/details.scss
  src/components/DetailsCode/DetailsCode.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FunctionsPage/Functions.js
  src/components/JobsPage/Jobs.js
  src/components/Table/table.scss
  src/constants.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/CreateJobCardTemplate/CreateJobCardTemplate.js
  src/elements/CreateJobCardTemplate/createJobCardTemplate.scss
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/elements/SelectOption/SelectOption.js
  src/images/arrow.svg
  src/images/back-arrow.svg
  src/images/filter.svg
  src/images/plus.svg
  src/images/search-icon.png
  src/images/search.svg
  src/layout/Content/Content.js
  src/reducers/jobReducer.js
Labels: enhancement

#62 Development
  src/common/Accordion/Accordion.js
  src/common/Accordion/accordion.scss
  src/components/CreateJobPage/CreateJobPage.js
  src/components/CreateJobPage/CreateJobPageView.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/jobspanel.scss
  src/constants.js
  src/elements/CreateJobCardTemplate/CreateJobCardTemplate.js
  src/elements/CreateJobCardTemplate/createJobCardTemplate.scss
  src/images/close.svg
  src/images/run.png
  src/scss/colors.scss
Labels: enhancement

#63 Create job screen
  package.json
  src/actions/artifacts.js
  src/actions/functions.js
  src/actions/jobs.js
  src/actions/projects.js
  src/common/Accordion/Accordion.js
  src/common/Accordion/accordion.scss
  src/common/Input/Input.js
  src/common/Input/input.scss
  src/common/PageActionsMenu/pageActionsMenu.scss
  src/components/CreateJobPage/createJobPage.scss
  src/components/Details/details.scss
  src/components/JobsPage/jobs.scss
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/jobspanel.scss
  src/components/JobsPanel/panelData.json
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
  src/constants.js
  src/elements/CreateJobCardTemplate/createJobCardTemplate.scss
  src/elements/JobsPanelSection/JobsPanelSection.js
  src/elements/JobsPanelSection/jobsPanelSection.scss
  src/elements/JobsPanelTable/JobsPanelTable.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
  src/elements/JobsPanelTableAddItemRow/JobsPanelTableAddItemRow.js
  src/elements/ProjectCard/ProjectCard.js
  src/elements/TableCell/TableCell.js
  src/layout/Content/Content.js
  src/layout/Content/content.scss
  src/reducers/jobReducer.js
  src/scss/main.scss
Labels: enhancement

#65 Development
  src/App.js
  src/components/ArtifactFilterLabels/ArtifactFilterLabels.js
  src/components/ArtifactFilterLabels/artifactFilterLabels.scss
  src/components/ArtifactInfoMetadata/ArtifactInfoMetada.js
  src/components/ArtifactInfoMetadata/artifactInfoMetadata.scss
  src/components/ArtifactInfoSources/ArtifactInfoSources.js
  src/components/ArtifactInfoSources/artifactInfoSources.scss
  src/components/Artifacts/Artifacts.js
  src/components/ArtifactsFilterTree/ArtifactsFilterTree.js
  src/components/ArtifactsFilterTree/ArtifactsFilterTreeDropDown.js
  src/components/ArtifactsFilterTree/artifactsFilterTree.scss
  src/components/Details/Details.js
  src/components/Details/DetailsView.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsResults/DetailsResults.js
  src/components/DetailsResults/detailsResults.scss
  src/components/FilterMenu/FilterMenu.js
  src/components/FunctionsPage/Functions.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/NotificationDownload/NotificationDownloadView.js
  src/components/NotificationDownload/notificationDownloadView.scss
  src/components/ProjectsPage/Projects.js
  src/elements/ArtifactsDetailsInfoItem/ArtifactsDetailsInfoItem.js
  src/elements/DetailsMenuItem/DetailsMenuItem.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/elements/JobsDetailsInfoItem/JobsDetailsInfoItem.js
  src/elements/PreviewModal/PreviewModal.js
  src/elements/PreviewModal/previewModal.scss
  src/elements/ProjectCard/ProjectCard.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/elements/TooltipTemplate/ProducerTooltipTemplate.js
  src/elements/TooltipTemplate/TextTooltipTemplate.js
  src/elements/TooltipTemplate/producerTooltipTemplate.scss
  src/elements/TooltipTemplate/textTooltipTemplate.scss
  src/images/close.svg
  src/layout/Content/Content.js
Labels: bug

#66 Development
  package.json
  src/actions/artifacts.js
  src/components/Artifacts/Artifacts.js
  src/components/Details/Details.js
  src/components/Details/DetailsView.js
  src/components/Details/details.scss
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsArtifacts/detailsArtifacts.scss
  src/components/DetailsCode/DetailsCode.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/constants.js
  src/elements/ArtifactsDetailsInfoItem/ArtifactsDetailsInfoItem.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/Chip/Chip.js
  src/elements/ChipCell/ChipCell.js
  src/elements/DetailsMenuItem/DetailsMenuItem.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/elements/HiddenChipsBlock/HiddenChipsBlock.js
  src/elements/HiddenChipsBlock/hiddenChipsBlock.scss
  src/elements/JobsDetailsInfoItem/JobsDetailsInfoItem.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/elements/PreviewModal/PreviewModal.js
  src/elements/TableCell/TableCell.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/layout/Content/Content.js
  src/reducers/artifactReducer.js
Labels: bug, enhancement

#67 Fix [Artifacts] Info: Path starts with `://`
  src/elements/ArtifactsDetailsInfoItem/ArtifactsDetailsInfoItem.js
Labels: bug

#68 Impl [Jobs] Results: add tooltip to Best Iteration icon
  src/components/DetailsResults/DetailsResults.js
Labels: enhancement

#69 Impl [Artifacts] Use `db_key` instead of `key` for name
  src/actions/artifacts.js
  src/components/Details/DetailsView.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsInfo/DetailsInfo.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/PreviewModal/PreviewModal.js
  src/layout/Content/Content.js
  src/utils/createArtifactsContent.js
Labels: bug, enhancement
