Repository mlrun/ui, pull requests merged in 2020-05, with the labels that each got.

#91 Impl [General] Change document title from "Iguazio" to "MLRun"
  public/index.html
Labels: enhancement

#92 Refactoring on job wizard
  src/common/Select/Select.js
  src/common/Select/selectData.json
  src/components/CreateJobPage/CreateJobPage.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanel/panelData.json
  src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
  src/components/JobsPanelParameters/JobsPanelParameters.js
  src/components/JobsPanelParameters/JobsPanelParametersView.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
Labels: enhancement

#94 Fixed prettier bug
  .gitattributes
Labels: bug

#95 Development
  src/common/CheckBox/CheckBox.js
  src/common/DatePicker/DatePicker.js
  src/common/DatePicker/DatePickerView.js
  src/common/Input/Input.js
  src/common/Input/input.scss
  src/common/RangeInput/RangeInput.js
  src/common/Select/Select.js
  src/common/Select/select.scss
  src/common/Select/selectData.json
  src/common/TimePicker/TimePicker.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/ScheduleJob/ScheduleJob.js
  src/components/ScheduleJob/ScheduleJobView.js
  src/components/ScheduleJob/recurringReducer.js
  src/components/ScheduleJobSimple/ScheduleJobSimple.js
  src/components/ScheduleJobSimple/scheduleJobSimple.scss
  src/elements/ScheduleRecurring/ScheduleRecurring.js
  src/elements/ScheduleRecurring/scheduleRecurring.scss
  src/elements/SelectOption/SelectOption.js
  src/scss/borders.scss
  src/setupProxy.js
  src/utils/datePicker.util.js
Labels: enhancement

#96 Impl [General] Enable proxying to function templates relatively
  nginx/nginx.conf.tmpl
  src/actions/functions.js
  src/api/artifacts-api.js
  src/api/functions-api.js
  src/api/jobs-api.js
  src/api/projects-api.js
  src/common/Download/Download.js
  src/components/NotificationDownload/NotificationDownload.js
  src/httpClient.js
  src/setupProxy.js
Labels: enhancement

#97 Fix [Jobs] Artifacts: preview sent wrong request URL for file
  src/api/artifacts-api.js
Labels: bug

#98 Impl [Config] Add `x-v3io-session-key` req header in dev proxy
  src/setupProxy.js
Labels: enhancement

#99 [Jobs] Wizard: Add version and method selection for selected function
  src/actions/jobs.js
  src/common/Select/Select.js
  src/common/Select/select.scss
  src/common/Select/selectData.json
  src/common/Tooltip/Tooltip.js
  src/common/Tooltip/tooltip.scss
  src/components/CreateJobPage/CreateJobPage.js
  src/components/CreateJobPage/CreateJobPageView.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FunctionsPage/functionsData.json
  src/components/JobsPage/jobsData.json
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
  src/components/JobsPanelParameters/JobsPanelParameters.js
  src/components/JobsPanelParameters/JobsPanelParametersView.js
  src/components/JobsPanelResources/JobsPanelResources.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/components/ScheduleJob/ScheduleJob.js
  src/components/ScheduleJob/ScheduleJobView.js
  src/components/ScheduleJobSimple/ScheduleJobSimple.js
  src/constants.js
  src/elements/CreateJobCardTemplate/CreateJobCardTemplate.js
  src/elements/EditableParametersRow/EditableParametersRow.js
  src/elements/JobsPanelTable/JobsPanelTable.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
  src/elements/JobsPanelTableRow/JobsPanelTableRow.js
  src/elements/JobsPanelTableRow/jobsPanelTableRow.scss
  src/elements/JobsPanelTitle/JobsPanelTitle.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/elements/JobsPanelTitle/jobsPanelTitle.scss
  src/elements/JobsPanelTitleEdit/JobsPanelTitleEdit.js
  src/elements/ScheduleRecurring/ScheduleRecurring.js
  src/elements/ScheduleRecurring/scheduleRecurring.scss
  src/elements/SelectOption/SelectOption.js
  src/elements/TooltipTemplate/ProducerTooltipTemplate.js
  src/elements/TooltipTemplate/TextTooltipTemplate.js
  src/elements/TooltipTemplate/producerTooltipTemplate.scss
  src/elements/TooltipTemplate/textTooltipTemplate.scss
  src/reducers/jobReducer.js
Labels: enhancement

#100 [Jobs] Add grouping by workflow
  src/actions/artifacts.js
  src/actions/jobs.js
  src/actions/workflow.js
  src/api/workflow-api.js
  src/common/Download/Download.js
  src/components/Artifacts/Artifacts.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FunctionsPage/Functions.js
  src/components/JobsPage/Jobs.js
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/constants.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/elements/TableCell/TableCell.js
  src/elements/TableTypeCell/TableTypeCell.js
  src/images/workflow-icon.svg
  src/layout/Content/Content.js
  src/reducers/jobReducer.js
  src/reducers/reducers.js
  src/reducers/workflowReducer.js
  src/utils/createJobsContent.js
  src/utils/generateGroupLatestItem.js
  src/utils/generateTableContent.js
Labels: enhancement

#101 Bug with link and nested rows
  src/components/Table/Table.js
  src/elements/JobsTableRow/JobsTableRow.js
Labels: bug

#103 Fix [Jobs] Artifacts: preview not working, wrong user value sent
  src/components/DetailsArtifacts/DetailsArtifacts.js
Labels: bug

#102 Fixed bug with showing untagged functions
  src/actions/functions.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FunctionsPage/Functions.js
  src/layout/Content/Content.js
  src/reducers/functionReducer.js
Labels: bug

#104 [Jobs] Fixed wrongly putted WF icon for job when grouped by name
  src/App.js
  src/utils/createJobsContent.js
Labels: bug

#105 Fixed bug with generating table content on Artifacts screen
  src/components/Table/Table.js
  src/utils/generateTableContent.js
Labels: bug

#107 Impl [General] Add stylelint
  .eslintrc.js
  .stylelintrc.json
  package.json
Labels: enhancement

#108 Impl [Config] Add `x-v3io-session-key` req header to nginx proxy
  Dockerfile
  nginx/nginx.conf.tmpl
Labels: enhancement

#109 [Jobs] Wrongly put WF icon for job when grouped by name
  src/components/Table/Table.js
  src/utils/createJobsContent.js
Labels: bug

#110 Impl [Config] Default MLRUN_V3IO_ACCESS_KEY env var to empty
  Dockerfile
Labels: enhancement

#111 [Jobs] Make more room for Results
  package.json
  src/components/Artifacts/Artifacts.js
  src/components/Details/Details.js
  src/components/Details/DetailsView.js
  src/components/Details/details.scss
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/DetailsResults/DetailsResults.js
  src/components/JobsPage/jobsData.json
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/elements/ArtifactsDetailsInfoItem/ArtifactsDetailsInfoItem.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/Chip/Chip.js
  src/elements/ChipCell/SizeChips.js
  src/elements/ChipCell/chipCell.scss
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/elements/DetailsMenuItem/DetailsMenuItem.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/elements/HiddenChipsBlock/HiddenChipsBlock.js
  src/elements/JobsDetailsInfoItem/JobsDetailsInfoItem.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/elements/TableCell/TableCell.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/layout/Content/Content.js
  src/utils/createJobsContent.js
  src/utils/resultsTable.js
  src/utils/roundFloats.js
Labels: enhancement

#112 [Functions] Fixed bug on Kind column
  src/components/FunctionsPage/Functions.js
  src/elements/TableTypeCell/TableTypeCell.js
Labels: bug

#113 [Jobs] Fix columns overflowing each other
  src/components/Table/table.scss
  src/elements/Chip/Chip.js
  src/elements/ChipCell/chipCell.scss
  src/elements/TableCell/TableCell.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/scss/main.scss
Labels: bug

#114 [Artifacts] Refactoring Metadata tab
  src/components/ArtifactInfoMetadata/ArtifactInfoMetada.js
  src/components/ArtifactInfoMetadata/artifactInfoMetadata.scss
  src/components/Details/DetailsView.js
Labels: bug, enhancement
