Repository mlrun/ui, pull requests merged in 2020-02, with the labels that each got.

#9 Refactored Tooltip component, scss and some other components
  src/actions/artifacts.js
  src/common/Search/Search.js
  src/components/Arifacts/Artifacts.js
  src/components/Arifacts/artifacts.scss
  src/components/ArtifacstFilterMenu/ArtifactsFilerMenu.js
  src/components/ArtifacstFilterMenu/artifactsfiltermenu.scss
  src/components/ArtifactsTooltip/Tooltip.js
  src/components/ArtifactsView/ArtifactsView.js
  src/components/ArtifactsView/artifactsview.scss
  src/components/JobsItemInternal/jobItemInternal.scss
  src/components/JobsPage/jobs.scss
  src/elements/ArtifactsTable/ArtifactsTable.js
  src/elements/ArtifactsTable/artifactstable.scss
  src/scss/variables.scss
Labels: enhancement

#10 Development
  package.json
  src/actions/artifacts.js
  src/common/Select/Select.js
  src/common/Select/select.js
  src/common/Select/select.scss
  src/components/Arifacts/Artifacts.js
  src/components/Arifacts/artifacts.scss
  src/components/ArtifacstFilterMenu/ArtifactsFilerMenu.js
  src/components/ArtifactsView/ArtifactsView.js
  src/components/ArtifactsView/artifactsview.scss
  src/elements/ArtifactsTable/ArtifactsTable.js
  src/elements/ArtifactsTable/artifactstable.scss
  src/images/checkbox-checked.png
  src/images/checkbox-unchecked.png
Labels: enhancement

#11 Impl [General] Dockerize the web-app, add `npm run docker` script
  package-lock.json
  package.json
  src/actions/jobs.js
  src/serviceWorker.js
Labels: enhancement

#12 Updated Artifacts tab view
  package.json
  src/actions/artifacts.js
  src/actions/jobs.js
  src/common/Breadcrumbs/Breadcrumbs.js
  src/components/ArtifacstFilterMenu/ArtifactsFilerMenu.js
  src/components/JobsItemInternal/JobsItemInternal.js
  src/components/JobsItemInternal/JobsItemInternalView.js
  src/components/JobsItemInternal/jobItemInternal.scss
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/JobsView.js
  src/components/JobsPage/jobs.scss
  src/elements/JobInternalArtifacts/JobInternalArtifacts.js
  src/elements/JobInternalArtifacts/JobInternalArtifactsView.js
  src/elements/JobInternalResults/JobInternalResults.js
  src/elements/JobsTable/JobsTable.js
  src/elements/JobsTable/JobsTableView.js
  src/elements/JobsTable/jobs-table.scss
  src/images/arrow.png
  src/scss/main.scss
  src/utils/resultsTable.js
Labels: enhancement

#14 Impl [General] REALLY dockerize the web-app
  .dockerignore
  Dockerfile
  nginx/nginx.conf.tmpl
  package.json
Labels: enhancement

#16 Development
  package.json
  src/App.js
  src/components/Arifacts/Artifacts.js
  src/components/Arifacts/artifacts.scss
  src/components/ArtifactsDetails/ArtifactsDetails.js
  src/components/ArtifactsDetails/artifactsdetails.scss
  src/components/ArtifactsTooltip/Tooltip.js
  src/components/ArtifactsTree/ArtifactsIterTree.js
  src/components/ArtifactsTree/ArtifactsTemplate.js
  src/components/ArtifactsTree/ArtifactsTree.js
  src/components/ArtifactsView/ArtifactsView.js
  src/components/ArtifactsView/artifactsview.scss
  src/elements/ArtifactsTable/ArtifactsTable.js
  src/elements/ArtifactsTable/artifactstable.scss
Labels: enhancement

#17 Development
  package.json
  src/App.js
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/components/Arifacts/Artifacts.js
  src/components/Arifacts/artifacts.scss
  src/components/ArtifactsDetails/ArtifactsDetails.js
  src/components/ArtifactsDetails/artifactsdetails.scss
  src/components/ArtifactsDetailsInfo/ArtifactDetailsInfo.js
  src/components/ArtifactsDetailsPreview/ArtifactsDetailsPreview.js
  src/components/ArtifactsDetailsPreview/artifactsdetailspreview.scss
  src/components/ArtifactsDetailsTab/ArtifactDetailsTab.js
  src/components/ArtifactsIterTree/ArtifactsIterTree.js
  src/components/ArtifactsTooltip/ArtifactsDetailsTab/ArtifactDetailsTab.js
  src/components/ArtifactsTooltip/Tooltip.js
  src/components/ArtifactsTree/ArtifactsTemplate.js
  src/components/ArtifactsTree/ArtifactsTree.js
  src/components/ArtifactsView/ArtifactsView.js
  src/components/ArtifactsView/artifactsview.scss
  src/elements/ArtifactsTable/ArtifactsTable.js
  src/elements/ArtifactsTable/artifactstable.scss
  src/reducers/artifactReducer.js
Labels: enhancement

#18 Development
  src/common/Download/Download.js
  src/common/Download/download.scss
  src/common/ProgressRing/ProgressRing.js
  src/components/ArtifactsDetails/ArtifactsDetails.js
  src/components/ArtifactsDetails/artifactsdetails.scss
  src/components/ArtifactsDetailsInfo/ArtifactDetailsInfo.js
  src/components/ArtifactsDetailsPreview/artifactsdetailspreview.scss
  src/components/ArtifactsIterTree/ArtifactsIterTree.js
  src/components/ArtifactsTree/ArtifactsTree.js
  src/components/ArtifactsTree/ArtifactsTreeView.js
  src/elements/ArtifactsTable/ArtifactsTable.js
  src/elements/ArtifactsTable/artifactstable.scss
  src/images/download-cancel.png
  src/scss/variables.scss
Labels: enhancement

#19 Refactored code, added Actions Menu
  package-lock.json
  package.json
  src/App.js
  src/api/jobs-api.js
  src/common/ActionsMenu/ActionsMenu.js
  src/common/Breadcrumbs/breadcrums.scss
  src/common/Download/Download.js
  src/common/Loader/loader.scss
  src/common/YamlModal/YamlModal.js
  src/components/ArtifactsDetails/ArtifactsDetails.js
  src/components/ArtifactsDetails/artifactsdetails.scss
  src/components/ArtifactsDetailsPreview/artifactsdetailspreview.scss
  src/components/ArtifactsTree/ArtifactsTreeView.js
  src/components/ArtifactsView/ArtifactsView.js
  src/components/ArtifactsView/artifactsview.scss
  src/components/JobInternalArtifacts/JobInternalArtifacts.js
  src/components/JobInternalArtifacts/JobInternalArtifactsView.js
  src/components/JobInternalInfo/JobInternalInfo.js
  src/components/JobInternalInputs/JobInternalInputs.js
  src/components/JobInternalLogs/JobInternalLogs.js
  src/components/JobInternalResults/JobInternalResults.js
  src/components/JobsItemInternal/JobsItemInternal.js
  src/components/JobsItemInternal/JobsItemInternalView.js
  src/components/JobsItemInternal/jobItemInternal.scss
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/JobsView.js
  src/components/JobsPage/jobs.scss
  src/components/JobsTable/JobsTable.js
  src/components/JobsTable/JobsTableView.js
  src/components/JobsTable/jobs-table.scss
  src/components/SideBar/SideBar.js
  src/elements/ArtifactsTable/artifactstable.scss
  src/elements/JobInternalArtifacts/JobInternalArtifacts.js
  src/elements/JobInternalArtifacts/JobInternalArtifactsView.js
  src/images/cancel.png
  src/images/download-icon.png
  src/images/elipsis.png
  src/layout/Header/Header.js
  src/layout/Header/header.scss
  src/layout/Page/Page.js
  src/layout/Page/PageView.js
  src/layout/SideBar/SideBar.js
  src/layout/SideBar/SideBarView.js
  src/layout/SideBar/sidebar.scss
  src/scss/main.scss
  src/scss/mixins.scss
  src/scss/variables.scss
Labels: Cleanup, enhancement

#21 Development
  src/App.js
  src/actions/artifacts.js
  src/common/Download/Download.js
  src/common/Download/download.scss
  src/common/Select/Select.js
  src/components/Arifacts/Artifacts.js
  src/components/Arifacts/artifacts.scss
  src/components/ArtifacstFilterMenu/ArtifactsFilerMenu.js
  src/components/ArtifactsDetails/ArtifactsDetails.js
  src/components/ArtifactsDetails/artifactsdetails.scss
  src/components/ArtifactsDetailsInfo/ArtifactDetailsInfo.js
  src/components/ArtifactsDetailsPreview/ArtifactsDetailsPreview.js
  src/components/ArtifactsDetailsPreview/artifactsdetailspreview.scss
  src/components/ArtifactsDetailsTab/ArtifactDetailsTab.js
  src/components/ArtifactsIterTree/ArtifactsIterTree.js
  src/components/ArtifactsTableBody/ArtifactsTableBody.js
  src/components/ArtifactsTooltip/ArtifactsDetailsTab/ArtifactDetailsTab.js
  src/components/ArtifactsTooltip/Tooltip.js
  src/components/ArtifactsTree/ArtifactsTree.js
  src/components/ArtifactsTree/ArtifactsTreeView.js
  src/elements/ArtifactsTable/ArtifactsTable.js
  src/elements/ArtifactsTable/artifactstable.scss
  src/scss/main.scss
Labels: enhancement

#22 Development
  src/App.js
  src/components/ArtifacstFilterMenu/ArtifactsFilterMenu.js
  src/components/Artifacts/Artifacts.js
  src/components/Artifacts/artifacts.scss
  src/components/ArtifactsDetailsPreview/ArtifactsDetailsPreview.js
  src/components/ArtifactsTableBody/ArtifactsTableBody.js
  src/components/ArtifactsView/ArtifactsView.js
Labels: enhancement

#23 Impl [Artifacts] Rename "Started at" to "Updated at"
  src/components/ArtifactsTableBody/ArtifactsTableBody.js
  src/elements/ArtifactsTable/ArtifactsTable.js
  src/elements/ArtifactsTable/artifactstable.scss
Labels: enhancement

#24 Development
  src/App.js
  src/actions/artifacts.js
  src/actions/jobs.js
  src/actions/projects.js
  src/api/jobs-api.js
  src/api/projects-api.js
  src/common/ActionsMenu/ActionsMenu.js
  src/common/ActionsMenu/actionsmenu.scss
  src/common/YamlModal/YamlModal.js
  src/common/YamlModal/yamlmodal.scss
  src/components/Artifacts/Artifacts.js
  src/components/ArtifactsDetails/ArtifactsDetails.js
  src/components/ArtifactsDetailsTab/ArtifactDetailsTab.js
  src/components/ArtifactsTableBody/ArtifactsTableBody.js
  src/components/ArtifactsView/artifactsview.scss
  src/components/JobInternalLogs/JobInternalLogs.js
  src/components/JobsItemInternal/JobsItemInternalView.js
  src/components/JobsTable/JobsTableView.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/projects.scss
  src/elements/ArtifactsTable/ArtifactsTable.js
  src/elements/ArtifactsTable/artifactstable.scss
  src/images/projects.png
  src/layout/SideBar/SideBarView.js
  src/layout/SideBar/sidebar.scss
  src/reducers/projectReducer.js
  src/reducers/reducers.js
Labels: enhancement

#25 Development
  package.json
  src/common/Download/Download.js
  src/common/Download/download.scss
  src/common/YamlModal/YamlModal.js
  src/common/YamlModal/yamlmodal.scss
  src/components/Artifacts/Artifacts.js
  src/components/ArtifactsTableBody/ArtifactsTableBody.js
  src/components/Details/details.scss
  src/components/JobsPage/Jobs.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/projects.scss
  src/elements/ArtifactsTable/artifactstable.scss
  src/images/Vector.png
  src/layout/SideBar/sidebar.scss
Labels: bug

#27 Fix [Build] Missing dependency `yamljs`
  package-lock.json
  package.json
Labels: bug

#28 Refactoring project structure
  package-lock.json
  package.json
  src/common/Download/Download.js
  src/common/Search/search.scss
  src/common/YamlModal/yamlmodal.scss
  src/components/Artifacts/Artifacts.js
  src/components/ArtifactsTableBody/ArtifactsTableBody.js
  src/components/Details/Details.js
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/JobsPage/jobs.scss
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/utils/createArtifactsContent.js
Labels: Cleanup, enhancement

#29 Refactoring project structure
  src/actions/jobs.js
  src/api/jobs-api.js
  src/common/Select/select.scss
  src/components/Artifacts/Artifacts.js
  src/components/Artifacts/artifactsData.json
  src/components/ArtifactsDetails/ArtifactsDetails.js
  src/components/ArtifactsDetails/artifactsdetails.scss
  src/components/ArtifactsDetailsInfo/ArtifactDetailsInfo.js
  src/components/ArtifactsDetailsPreview/ArtifactsDetailsPreview.js
  src/components/ArtifactsDetailsPreview/artifactsdetailspreview.scss
  src/components/ArtifactsDetailsTab/ArtifactDetailsTab.js
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/Details/Details.js
  src/components/Details/details.scss
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInputs/DetailsInputs.js
  src/components/DetailsResults/DetailsResults.js
  src/components/JobsPage/Jobs.js
  src/components/ProjectsPage/projects.scss
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/elements/ArtifactsDetailsInfoItem/ArtifactsDetailsInfoItem.js
  src/elements/ArtifactsTable/ArtifactsTable.js
  src/elements/ArtifactsTable/artifactstable.scss
  src/elements/DetailsMenuItem/DetailsMenuItem.js
  src/elements/TableCell/TableCell.js
  src/images/popout.png
  src/reducers/jobReducer.js
  src/scss/main.scss
  src/utils/createArtifactsContent.js
Labels: enhancement

#30 Impl [Artifacts] Request artifacts per project
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/components/Artifacts/Artifacts.js
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/scss/main.scss
Labels: bug

#32 Ivan voznyi development
  package.json
  src/common/YamlModal/YamlModal.js
  src/common/YamlModal/yamlmodal.scss
  src/components/ArtifacstFilterMenu/ArtifactsFilterMenu.js
  src/components/Artifacts/Artifacts.js
  src/components/ArtifactsFilterTree/ArtifactsFilterTree.js
  src/components/ArtifactsFilterTree/artifactsfiltertree.scss
  src/components/ProjectsPage/Projects.js
  src/elements/ProjectCard/ProjectCard.js
Labels: enhancement

#35 Development
  public/index.html
  src/actions/notificationDownload.js
  src/common/Download/Download.js
  src/common/Download/download.scss
  src/components/Artifacts/artifactsData.json
  src/components/Details/details.scss
  src/components/FilterMenu/FilterMenu.js
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/elements/ArtifactsDetailsInfoItem/ArtifactsDetailsInfoItem.js
  src/elements/NotificationDownload/NotificationDownload.js
  src/elements/NotificationDownload/notificationdownload.scss
  src/elements/TableCell/TableCell.js
  src/images/download-cancel.png
  src/images/download-icon.png
  src/images/success_done.png
  src/images/unsuccess_alert.png
  src/layout/Content/Content.js
  src/reducers/notificationDownloadReducer.js
  src/reducers/reducers.js
  src/scss/colors.scss
  src/scss/main.scss
  src/scss/variables.scss
  src/utils/createArtifactsContent.js
  src/utils/downloadFile.js
Labels: bug, enhancement

#36 Refactoring project structure
  src/components/ArtifactsFilterTree/artifactsfiltertree.scss
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/elements/ArtifactsDetailsInfoItem/ArtifactsDetailsInfoItem.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/DetailsMenuItem/DetailsMenuItem.js
  src/elements/TableCell/TableCell.js
Labels: enhancement

#37 Impl [Artifacts][Jobs] Show path as-is from `target_path`
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/elements/ArtifactsDetailsInfoItem/ArtifactsDetailsInfoItem.js
  src/elements/TableCell/TableCell.js
Labels: bug

#38 Development
  src/common/Download/Download.js
  src/common/Download/download.scss
  src/common/ProgressRing/ProgressRing.js
  src/components/ArtifactsFilterTree/ArtifactsFilterTree.js
  src/components/ArtifactsFilterTree/artifactsfiltertree.scss
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/Details/Details.js
  src/components/Details/details.scss
  src/components/DetailsArtifacts/detailsArtifacts.scss
  src/components/DetailsInputs/DetailsInputs.js
  src/components/FilterMenu/FilterMenu.js
  src/components/Table/Table.js
  src/components/Table/table.scss
  src/elements/ArtifactsDetailsInfoItem/ArtifactsDetailsInfoItem.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/NotificationDownload/notificationdownload.scss
  src/elements/PreviewModal/PreviewModal.js
  src/elements/PreviewModal/previewmodal.scss
  src/elements/TableCell/TableCell.js
  src/images/close.png
  src/images/download-cancel.png
  src/images/download-icon.png
  src/images/download.png
  src/images/eye.png
  src/scss/main.scss
  src/scss/shadows.scss
Labels: enhancement

#40 Refactoring project structure, added Duration column and status filter
  package.json
  src/actions/jobs.js
  src/api/jobs-api.js
  src/common/Select/Select.js
  src/common/Select/select.scss
  src/common/Select/selectData.json
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/Details/details.scss
  src/components/DetailsArtifacts/detailsArtifacts.scss
  src/components/DetailsResults/DetailsResults.js
  src/components/FilterMenu/FilterMenu.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.json
  src/components/Table/table.scss
  src/elements/ArtifactsDetailsInfoItem/ArtifactsDetailsInfoItem.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/elements/NotificationDownload/notificationdownload.scss
  src/elements/TableCell/TableCell.js
  src/layout/Content/Content.js
  src/scss/colors.scss
  src/scss/main.scss
  src/scss/mixins.scss
  src/utils/createJobsContent.js
  src/utils/measureTime.js
Labels: enhancement

#39 Development
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/common/Download/Download.js
  src/components/Artifacts/Artifacts.js
  src/components/ArtifactsFilterTree/ArtifactsFilterTree.js
  src/components/ArtifactsFilterTree/artifactsfiltertree.scss
  src/components/FilterMenu/FilterMenu.js
  src/components/FilterMenu/filterMenu.scss
  src/components/NotificationDownload/NotificationDownload.js
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/elements/NotificationDownloadView/NotificationDownloadView.js
  src/elements/NotificationDownloadView/notificationdownloadview.scss
  src/elements/PreviewModal/PreviewModal.js
  src/elements/ProjectCard/ProjectCard.js
  src/elements/TableCell/TableCell.js
  src/layout/Content/Content.js
  src/layout/Content/content.scss
  src/scss/main.scss
  src/scss/mixins.scss
Labels: enhancement
