Repository mlrun/ui, pull requests merged in 2020-06, with the labels that each got.

#116 [Artifacts] Path: add copy-to-clipboard
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/TableCell/TableCell.js
  src/utils/copyToClipboard.js
Labels: enhancement

#115 [Artifacts] Support `model` artifact kind
  src/common/Accordion/Accordion.js
  src/common/Accordion/accordion.scss
  src/common/Tooltip/Tooltip.js
  src/components/Artifacts/Artifacts.js
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/ArtifactsPreview/artifactaPreview.scss
  src/components/Details/DetailsView.js
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsArtifacts/detailsArtifacts.scss
  src/components/DetailsPreview/DetailsPreview.js
  src/components/DetailsResults/detailsResults.scss
  src/components/Table/Table.js
  src/elements/PreviewModal/PreviewModal.js
  src/elements/PreviewModal/previewModal.scss
  src/elements/TableCell/TableCell.js
  src/reducers/artifactReducer.js
  src/utils/generateArtifactPreviewData.js
Labels: enhancement

#117 [Jobs] Wizard: preload parameters, data inputs and resources of the s…
  src/actions/jobs.js
  src/common/Accordion/accordion.scss
  src/common/Select/Select.js
  src/common/TableActionsMenu/TableActionsMenu.js
  src/common/TableActionsMenu/tableActionsMenu.scss
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanel/panelData.json
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
  src/components/JobsPanelParameters/JobsPanelParameters.js
  src/components/JobsPanelParameters/JobsPanelParametersView.js
  src/components/ScheduleJobSimple/scheduleJobSimple.scss
  src/constants.js
  src/elements/EditableDataInputsRow/EditableDataInputsRow.js
  src/elements/EditableParametersRow/EditableParametersRow.js
  src/elements/EditableVolumesRow/EditableVolumesRow.js
  src/elements/EditableVolumesRow/editableVolumesRow.scss
  src/elements/JobsPanelTable/JobsPanelTable.js
  src/elements/JobsPanelTable/JobsPanelTableView.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
  src/elements/JobsPanelTableRow/JobsPanelTableRow.js
  src/elements/JobsPanelTableRow/jobsPanelTableRow.scss
  src/elements/JobsPanelTitle/JobsPanelTitle.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/elements/JobsPanelTitle/jobsPanelTitle.scss
  src/reducers/functionReducer.js
  src/reducers/jobReducer.js
  src/scss/main.scss
  src/utils/parseDefaultContent.js
  src/utils/string.js
Labels: enhancement

#118 [Job] Wizard: start accordion sections expanded
  src/components/JobsPanel/JobsPanelView.js
Labels: enhancement

#119 1 q9 uzf y4/409
  src/actions/artifacts.js
  src/common/TableActionsMenu/TableActionsMenu.js
  src/components/Artifacts/Artifacts.js
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsArtifacts/detailsArtifacts.scss
  src/components/Table/TableView.js
  src/constants.js
  src/reducers/artifactReducer.js
Labels: bug, enhancement

#120 [Jobs] Results: content overflow (Qbr9 lxo1/429)
  src/components/Details/details.scss
  src/components/DetailsResults/DetailsResults.js
  src/components/Table/table.scss
  src/scss/mixins.scss
Labels: bug

#121 [Jobs] Job wizard: view version/method details before apply
  src/actions/jobs.js
  src/components/CreateJobPage/CreateJobPage.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanel/panelReducer.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputsReducer.js
  src/components/JobsPanelParameters/JobsPanelParameters.js
  src/components/JobsPanelParameters/JobsPanelParametersView.js
  src/components/JobsPanelParameters/jobsPanelParameters.util.js
  src/components/JobsPanelParameters/jobsPanelParametersReducer.js
  src/components/JobsPanelResources/JobsPanelResources.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/constants.js
  src/elements/EditableParametersRow/EditableParametersRow.js
  src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
  src/elements/JobsPanelTable/JobsPanelTable.js
  src/elements/JobsPanelTable/JobsPanelTableView.js
  src/elements/JobsPanelTitle/JobsPanelTitle.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/elements/JobsPanelTitleEdit/JobsPanelTitleEdit.js
  src/elements/JobsPanelVolumesTable/JobsPanelVolumesTable.js
  src/reducers/jobReducer.js
  src/utils/createVolumeOfNewJob.js
  src/utils/isEveryObjectValueEmpty.js
Labels: enhancement

#122 [Jobs] Info: link to function hash
  src/components/DetailsInfo/DetailsInfo.js
  src/components/FunctionsPage/Functions.js
  src/components/JobsPage/Jobs.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
Labels: enhancement

#123 [Jobs] Artifacts: preview content overflows
  src/common/Accordion/accordion.scss
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/ArtifactsPreview/artifactaPreview.scss
  src/components/Details/details.scss
  src/components/DetailsArtifacts/detailsArtifacts.scss
  src/elements/PreviewModal/previewModal.scss
Labels: bug

#124 Fix [Artifacts][Jobs] Broken download button for artifacts
  src/components/Details/DetailsView.js
  src/elements/PreviewModal/PreviewModal.js
Labels: bug

#125 [Jobs] Wizard: made cron string editable
  src/common/Input/Input.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanel/jobsPanel.util.js
  src/components/ScheduleCron/ScheduleCron.js
  src/components/ScheduleCron/scheduleCron.scss
  src/components/ScheduleJob/ScheduleJob.js
  src/components/ScheduleJob/ScheduleJobView.js
  src/components/ScheduleJob/scheduleJob.scss
  src/components/ScheduleJobSimple/ScheduleJobSimple.js
  src/components/ScheduleJobSimple/scheduleJobSimple.scss
  src/scss/borders.scss
  src/scss/colors.scss
Labels: enhancement

#126 [Jobs] Results: Round decimals values
  src/components/DetailsResults/DetailsResults.js
Labels: enhancement

#127 Impl [Build] Use MLRun docker image env vars in `docker` script
  package.json
Labels: enhancement

#128 Fix [Jobs] Info: function link broken for non-default projects
  src/components/FunctionsPage/Functions.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
Labels: bug

#129 [Artifacts] Info: add link to job
  src/components/Artifacts/artifactsData.json
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/FunctionsPage/functionsData.json
  src/components/JobsPage/jobsData.json
  src/elements/DetailsInfoItem/DetailsInfoItem.js
Labels: enhancement

#130 Impl [Header] Add "BETA" next to the title "MLRun"
  src/layout/Header/Header.js
  src/layout/Header/header.scss
Labels: enhancement

#132 Docs [NPM scripts][Docker] Edit README.md file
  README.md
Labels: documentation

#133 Docs [Readme] Production: add npm run build command
  README.md
Labels: documentation

#134 Docs [Readme] Redesign; Add COMMIT_HASH and BUILD_DATE
  README.md
  package.json
Labels: documentation

#135 [Jobs] Wizard: add Secrets section
  src/actions/jobs.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanel/panelData.json
  src/components/JobsPanel/panelReducer.js
  src/components/JobsPanelAdvanced/JobsPanelAdvanced.js
  src/components/JobsPanelAdvanced/JobsPanelAdvancedView.js
  src/components/JobsPanelAdvanced/jobsPanelAdvanced.util.js
  src/components/JobsPanelAdvanced/jobsPanelAdvancedReducer.js
  src/constants.js
  src/elements/EditableAdvancedRow/EditableAdvancedRow.js
  src/elements/EditableParametersRow/EditableParametersRow.js
  src/elements/JobsPanelAdvancedTable/JobsPanelAdvancedTable.js
  src/elements/JobsPanelTable/JobsPanelTable.js
  src/elements/JobsPanelTable/JobsPanelTableView.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
  src/reducers/jobReducer.js
Labels: enhancement

#136 [Jobs] Condense columns, expand results
  src/components/DetailsArtifacts/detailsArtifacts.scss
  src/components/JobsPage/jobsData.json
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/elements/ChipCell/ChipCell.js
  src/elements/ChipCell/SizeChips.js
  src/utils/createJobsContent.js
Labels: enhancement

#137 [Jobs] Fixed error on grouping by workflow
  src/actions/workflow.js
  src/api/workflow-api.js
  src/components/JobsPage/Jobs.js
  src/reducers/workflowReducer.js
  src/utils/generateTableContent.js
Labels: bug

#138 Docs [Readme] Replace example and default of MLRUN_DOCKER_TAG
  README.md
Labels: documentation

#139 Docs [Readme] Improve some texts; Add links
  README.md
Labels: documentation

#140 [Jobs] Crash on filtering by label
  src/elements/TableLinkCell/TableLinkCell.js
Labels: bug

#141 Docs [Readme] Improve styles (use tables and break lines)
  README.md
Labels: documentation

#142 [Jobs] Results chips overflow their container
  src/common/Chip/Chip.js
  src/common/ChipCell/ChipCell.js
  src/common/ChipCell/SizeChips.js
  src/common/ChipCell/chipCell.scss
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/elements/HiddenChipsBlock/HiddenChipsBlock.js
  src/elements/TableCell/TableCell.js
Labels: bug

#143 [Functions] Info: added Code Origin
  src/components/DetailsInfo/DetailsInfo.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functionsData.json
Labels: enhancement

#144 [Jobs] Wizard: Parameters: switched Value and Simple/Hyper
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanel/panelData.json
  src/components/JobsPanelParameters/JobsPanelParameters.js
  src/components/JobsPanelParameters/JobsPanelParametersView.js
  src/components/JobsPanelParameters/jobsPanelParametersReducer.js
  src/elements/EditableParametersRow/EditableParametersRow.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
Labels: enhancement

#145 [Jobs] Wizard: add method description
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/panelReducer.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/elements/JobsPanelTitle/jobsPanelTitle.scss
  src/elements/JobsPanelTitleEdit/JobsPanelTitleEdit.js
  src/elements/MethodDescription/MethodDescription.js
  src/elements/MethodDescription/methodDescription.scss
Labels: enhancement

#147 [Functions] Add filter by name
  src/actions/functions.js
  src/api/functions-api.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functionsData.json
Labels: enhancement

#149 [Artifacts] Remove Path; Copy on clicking path in Info
  src/components/Artifacts/artifactsData.json
  src/components/DetailsInfo/detailsInfo.scss
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/elements/TableCell/TableCell.js
  src/utils/createArtifactsContent.js
Labels: enhancement

#148 [Jobs] Wizard: edit list fields without "Edit" action
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanelAdvanced/JobsPanelAdvanced.js
  src/components/JobsPanelAdvanced/jobsPanelAdvanced.util.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
  src/components/JobsPanelParameters/JobsPanelParameters.js
  src/components/JobsPanelParameters/jobsPanelParameters.util.js
  src/elements/EditableAdvancedRow/EditableAdvancedRow.js
  src/elements/EditableDataInputsRow/EditableDataInputsRow.js
  src/elements/EditableParametersRow/EditableParametersRow.js
  src/elements/EditableVolumesRow/EditableVolumesRow.js
  src/elements/JobsPanelTable/JobsPanelTable.js
  src/elements/JobsPanelTable/JobsPanelTableView.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
  src/elements/JobsPanelTableRow/JobsPanelTableRow.js
  src/elements/JobsPanelTableRow/jobsPanelTableRow.scss
  src/elements/MethodDescription/methodDescription.scss
  src/scss/main.scss
Labels: enhancement

#150 [Jobs] Wizard: toggle method description with button
  src/elements/MethodDescription/MethodDescription.js
  src/elements/MethodDescription/methodDescription.scss
  src/scss/colors.scss
Labels: enhancement

#151 [Artifacts] Moved hash from list to Info tab
  src/components/Artifacts/artifactsData.json
  src/components/DetailsInfo/DetailsInfo.js
  src/components/Table/table.scss
  src/utils/createArtifactsContent.js
Labels: enhancement

#152 [Artifacts][Functions] Remove the "monitor" tab
  src/elements/ContentMenu/contentMenu.scss
  src/layout/Content/Content.js
  src/layout/Content/content.scss
Labels: enhancement

#153 [Jobs][Artifacts][Functions] Made column headers sticky
  src/components/Table/table.scss
Labels: enhancement
