Repository mlrun/ui, pull requests merged in 2020-07, with the labels that each got.

#154 [Jobs] Fixed bug with infinite loop when no workflows returned
  src/actions/workflow.js
  src/components/Details/details.scss
  src/components/Table/TableView.js
  src/utils/createJobsContent.js
Labels: bug

#155 [Jobs] Wizard: add help icon to parameters
  src/common/Tip/Tip.js
  src/common/Tip/tip.scss
  src/elements/JobsPanelTableRow/JobsPanelTableRow.js
  src/elements/JobsPanelTableRow/jobsPanelTableRow.scss
  src/images/question-mark.svg
Labels: enhancement

#156 [Projects] Added "New project" dialog
  src/actions/projects.js
  src/api/projects-api.js
  src/common/ErrorMessage/ErrorMessage.js
  src/common/ErrorMessage/errorMessage.scss
  src/common/Input/Input.js
  src/common/Input/input.scss
  src/common/PageActionsMenu/PageActionsMenu.js
  src/common/PageActionsMenu/pageActionsMenu.scss
  src/common/PopUpDialog/PopUpDialog.js
  src/common/PopUpDialog/popUpDialog.scss
  src/components/JobsPanel/jobsPanel.scss
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/projects.scss
  src/components/ProjectsPage/projectsData.js
  src/constants.js
  src/elements/TooltipTemplate/TextTooltipTemplate.js
  src/elements/TooltipTemplate/textTooltipTemplate.scss
  src/images/warning.svg
  src/reducers/projectReducer.js
  src/scss/borders.scss
  src/scss/colors.scss
  src/scss/main.scss
Labels: enhancement

#157 [Jobs] Wizard: Add hyper params URL and strategy fields
  src/actions/jobs.js
  src/common/Select/Select.js
  src/common/Select/select.scss
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanelParameters/JobsPanelParameters.js
  src/components/JobsPanelParameters/JobsPanelParametersView.js
  src/components/JobsPanelParameters/jobsPanelParameters.util.js
  src/constants.js
  src/elements/EditableParametersRow/EditableParametersRow.js
  src/elements/JobsPanelTable/JobsPanelTable.js
  src/elements/JobsPanelTable/JobsPanelTableView.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
  src/elements/SelectOption/SelectOption.js
  src/reducers/jobReducer.js
  src/scss/borders.scss
Labels: enhancement

#158 [Projects][Jobs] Restyle "New Job" & "New Project" buttons
  src/common/PageActionsMenu/PageActionsMenu.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/ScheduleJob/ScheduleJobView.js
  src/scss/colors.scss
  src/scss/main.scss
Labels: enhancement

#160 [Jobs] Wizard: Changed edit flow
  src/common/Accordion/Accordion.js
  src/common/Accordion/accordion.scss
  src/common/Input/Input.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanel/panelReducer.js
  src/components/ProjectsPage/Projects.js
  src/elements/JobsPanelTitle/JobsPanelTitle.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/elements/JobsPanelTitle/jobsPanelTitle.scss
  src/elements/JobsPanelTitleEdit/JobsPanelTitleEdit.js
  src/elements/MethodDescription/MethodDescription.js
  src/elements/MethodDescription/methodDescription.scss
Labels: enhancement

#161 Override x-v3io-session-key header only if it's empty
  nginx/nginx.conf.tmpl
Labels: enhancement

#162 [Artifacts] Add "Register Artifact" button and dialog
  package.json
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/common/Input/input.scss
  src/common/PageActionsMenu/PageActionsMenu.js
  src/common/PopUpDialog/PopUpDialog.js
  src/common/PopUpDialog/popUpDialog.scss
  src/common/Select/select.scss
  src/common/UploadFile/UploadFile.js
  src/common/UploadFile/uploadFile.scss
  src/components/ArtifactInfoSources/ArtifactInfoSources.js
  src/components/Artifacts/Artifacts.js
  src/components/ArtifactsFilterTree/artifactsFilterTree.scss
  src/components/FilterMenu/filterMenu.scss
  src/components/ProjectsPage/Projects.js
  src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
  src/components/RegisterArtifactPopup/registerArtifactPopup.scss
  src/components/ScheduleJobSimple/scheduleJobSimple.scss
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/DetailsMenuItem/DetailsMenuItem.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
  src/elements/RegisterArtifactForm/RegisterArtifactForm.js
  src/elements/RegisterArtifactForm/registerArtifactForm.scss
  src/images/drop-file.svg
  src/layout/Content/Content.js
  src/scss/borders.scss
  src/scss/colors.scss
  src/utils/createArtifactsContent.js
Labels: bug, enhancement

#163 [Jobs] Wizard: reordered sections
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanelAdvanced/JobsPanelAdvanced.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputsReducer.js
  src/components/JobsPanelParameters/JobsPanelParameters.js
  src/components/JobsPanelParameters/JobsPanelParametersView.js
  src/components/JobsPanelResources/JobsPanelResources.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/components/JobsPanelResources/jobsPanelResources.util.js
  src/components/JobsPanelResources/jobsPanelResourcesReducer.js
  src/elements/JobsPanelTable/JobsPanelTable.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
  src/elements/JobsPanelTableRow/JobsPanelTableRow.js
  src/elements/JobsPanelTableRow/jobsPanelTableRow.scss
  src/elements/JobsPanelVolumesTable/JobsPanelVolumesTable.js
Labels: enhancement

#164 [Jobs] Details panel: fixed bug when clicking on tab headers
  src/components/Details/DetailsView.js
  src/elements/DetailsMenuItem/DetailsMenuItem.js
Labels: bug

#165 [Artifacts] Added "Analysis" tab for dataset kind.
  src/components/Artifacts/Artifacts.js
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/ArtifactsPreview/artifactaPreview.scss
  src/components/Details/DetailsView.js
  src/components/DetailsAnalysis/DetailsAnalysis.js
  src/components/DetailsArtifacts/detailsArtifacts.scss
  src/components/Table/table.scss
  src/utils/generateArtifactPreviewData.js
Labels: bug, enhancement

#166 [Artifacts] Download artifacts with their original name
  src/common/Download/Download.js
  src/components/Details/DetailsView.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/elements/PreviewModal/PreviewModal.js
  src/elements/TableCell/TableCell.js
  src/images/check-all.png
  src/images/file-chart.png
  src/images/iguazio-logo-corner.png
  src/images/run.png
  src/layout/SideBar/SideBarView.js
  src/setupProxy.js
Labels: enhancement

#167 [Functions] Fixed bug when function hash overlaps other columns
  src/components/Table/table.scss
  src/elements/TableLinkCell/TableLinkCell.js
Labels: bug

#168 [Jobs] Wizard: Use `@` instead of `:` for function link
  src/components/JobsPanel/JobsPanel.js
Labels: bug

#170 Added logo image
  src/images/iguazio-corner-logo.png
  src/layout/Header/Header.js
Labels: bug

#171 Fixed bug with logo
  src/images/iguazio-logo-corner.png
  src/layout/Header/Header.js
Labels: bug

#172 Line breaks bug
  .gitattributes
Labels: bug

#169 [Artifacts] Fixed bug with artifact preview
  src/components/ArtifactsPreview/ArtifactsPreview.js
Labels: bug

#174 [Artifacts] Details: Fixed bug with several requests for preview
  src/components/ArtifactsPreview/ArtifactsPreview.js
Labels: bug

#175 Refactored .gitattributes config
  .gitattributes
Labels: enhancement

#176 [Jobs] Artifacts: fixed "view details" link
  src/components/DetailsArtifacts/DetailsArtifactsView.js
Labels: bug

#177 Impl [Jobs] Wizard: reduce vertical spacing in accordion secitons
  src/components/JobsPanelAdvanced/JobsPanelAdvancedView.js
  src/elements/JobsPanelSection/JobsPanelSection.js
  src/elements/JobsPanelSection/jobsPanelSection.scss
Labels: enhancement

#178 Impl [Jobs] Wizard: Advanced & Resources collapsed by default
  src/components/JobsPanel/JobsPanelView.js
Labels: enhancement

#179 Impl [Jobs] Wizard: swap places of Advanced & Resources sections
  src/components/JobsPanel/JobsPanelView.js
Labels: enhancement

#181 [Jobs] Wizard: Fixed bug with "0" at the bottom
  src/components/CreateJobPage/CreateJobPage.js
Labels: bug

#182 [Jobs] Fixed bug with negative duration
  src/utils/measureTime.js
Labels: bug

#180 [Jobs] Wizard: Added error message on failure
  src/actions/jobs.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.scss
  src/constants.js
  src/reducers/jobReducer.js
Labels: enhancement

#184 [Jobs] Wizard: made output path required+default
  src/common/Input/input.scss
  src/components/JobsPanel/panelReducer.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
Labels: enhancement

#183 [Artifacts] Renamed Key to Name and added help text
  src/common/Input/Input.js
  src/common/Input/input.scss
  src/common/Tip/Tip.js
  src/common/Tip/tip.scss
  src/elements/RegisterArtifactForm/RegisterArtifactForm.js
Labels: enhancement

#185 [Jobs] Fixed bug when job has no start time
  src/components/Details/DetailsView.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/JobsPage/jobsData.json
  src/elements/PreviewModal/PreviewModal.js
  src/elements/TableCell/TableCell.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/utils/createArtifactsContent.js
  src/utils/createFunctionsContent.js
  src/utils/createJobsContent.js
  src/utils/datetime.js
Labels: bug, enhancement

#186 [Jobs] Wizard: added handler in request to create a job
  src/components/JobsPanel/JobsPanel.js
Labels: bug

#187 [Jobs] Wizard: Fixed bug with error message
  src/components/JobsPanel/JobsPanel.js
Labels: bug

#188 [General] Hide unimplemented UI elements
  src/components/CreateJobPage/createJobPage.scss
  src/components/FilterMenu/FilterMenu.js
  src/components/FilterMenu/filterMenu.scss
  src/components/ScheduleJob/ScheduleJob.js
  src/components/ScheduleJobSimple/scheduleJobSimple.scss
Labels: enhancement

#191 Impl [Create job] Respect newlines in method description
  src/elements/MethodDescription/methodDescription.scss
Labels: enhancement

#194 [Projects] Create project dialog looks weird
  src/common/PopUpDialog/popUpDialog.scss
  src/components/ProjectsPage/projects.scss
  src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
  src/components/RegisterArtifactPopup/registerArtifactPopup.scss
  src/elements/RegisterArtifactForm/RegisterArtifactForm.js
  src/elements/RegisterArtifactForm/registerArtifactForm.scss
Labels: bug

#192 [Create Job] Issues with schedule
  src/actions/jobs.js
  src/common/RangeInput/RangeInput.js
  src/components/CreateJobPage/CreateJobPage.js
  src/components/JobsPanel/JobsPanel.js
  src/components/ScheduleCron/ScheduleCron.js
  src/components/ScheduleJob/ScheduleJob.js
  src/components/ScheduleJob/ScheduleJobView.js
  src/components/ScheduleJob/recurringReducer.js
  src/components/ScheduleJob/scheduleData.json
  src/components/ScheduleJob/scheduleJobData.js
  src/components/ScheduleJobSimple/ScheduleJobSimple.js
  src/elements/ScheduleRecurring/ScheduleRecurring.js
  src/reducers/jobReducer.js
  src/utils/datePicker.util.js
Labels: bug

#193 [Artifacts] Screen crashes when GET fails
  src/actions/artifacts.js
  src/components/Artifacts/Artifacts.js
Labels: bug

#190 [General] Chip list: edit mode; Use in job wizard labels
  src/common/Chip/Chip.js
  src/common/ChipCell/ChipCell.js
  src/common/ChipCell/ChipCellView.js
  src/common/ChipCell/SizeChips.js
  src/components/ChipForm/ChipForm.js
  src/components/ChipForm/chipForm.scss
  src/components/JobsPanel/panelReducer.js
  src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/elements/JobsPanelTitle/jobsPanelTitle.scss
  src/images/add.svg
  src/scss/borders.scss
  src/utils/cutChips.js
Labels: enhancement

#195 [Jobs] Incorrectly saying "Not yet started" create_at exists
  src/utils/createJobsContent.js
  src/utils/generateTableContent.js
Labels: bug

#196 [General] Chips have redundant scrollbars
  src/scss/main.scss
Labels: bug

#197 [Jobs] Workflow jobs have wrong type icon
  src/utils/createJobsContent.js
Labels: bug

#198 Impl [Create Job] Schedule: Simple tab: hide entire "Ends" part
  src/elements/ScheduleRecurring/ScheduleRecurring.js
  src/elements/ScheduleRecurring/scheduleRecurring.scss
Labels: enhancement

#199 [Artifacts] Fixed bug with missing Metadata tab for dataset artifacts
  src/components/Artifacts/Artifacts.js
Labels: bug

#200 [Artifacts] Missing `tag=latest` query param on refresh
  src/components/ArtifactsFilterTree/ArtifactsFilterTree.js
  src/components/ArtifactsFilterTree/ArtifactsFilterTreeDropDown.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FilterMenu/filterMenu.settings.js
Labels: bug

#201 [Artifacts] Tree filter: `tag=latest` should not be sent
  src/components/Artifacts/Artifacts.js
  src/components/ArtifactsFilterTree/ArtifactsFilterTree.js
  src/components/FilterMenu/FilterMenu.js
  src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
Labels: bug

#202 added a parameter filter to update the query on the Artifact page
  src/actions/artifacts.js
  src/components/Artifacts/Artifacts.js
  src/components/FilterMenu/FilterMenu.js
  src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
  src/constants.js
  src/layout/Content/Content.js
  src/reducers/artifactReducer.js
  src/utils/parseTargetPath.js
Labels: bug
