Repository mlrun/ui, pull requests merged in 2020-11, with the labels that each got.

#277 Fix [Config] Proxy to Nuclio API not working in production
  src/httpClient.js
Labels: bug

#276 [Create Job][Scheduled Job] Show human-readable schedule
  package.json
  src/components/JobsPage/jobsData.js
  src/components/ScheduleCron/ScheduleCron.js
  src/utils/createJobsContent.js
Labels: enhancement

#278 Impl [Create Job] Schedule: Add note about UTC in Simple tab
  src/elements/ScheduleRecurring/ScheduleRecurring.js
Labels: enhancement

#279 Impl [Config][Project Overview] Properly pass Nuclio UI URL
  Dockerfile
  config.js.tmpl
  nginx/run_nginx
  package.json
  public/config.js
  public/index.html
  src/components/Project/project.utils.js
  src/elements/ProjectFunctions/ProjectFunctions.js
Labels: enhancement

#281 Impl [Pkg] Enable to trigger workflows manually
  .github/workflows/build.yaml
Labels: enhancement

#280 [General] Navigate via breadcrumbs
  src/common/Breadcrumbs/Breadcrumbs.js
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/common/Breadcrumbs/breadcrums.scss
  src/common/Search/Search.js
  src/components/DataSets/DataSets.js
  src/components/Files/Files.js
  src/components/Models/Models.js
  src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js
  src/elements/BreadcrumbsDropdown/breadcrumbsDropdown.scss
  src/scss/shadows.scss
Labels: enhancement

#282 [Artifacts] Details: added tooltip to download button
  src/components/Details/DetailsView.js
Labels: enhancement

#283 Impl [Details panel] Stick tab headers & actions to top on scroll
  src/components/Details/DetailsView.js
  src/components/Details/details.scss
Labels: enhancement

#284 [Breadcrumbs] Crashes when switching projects
  src/common/Breadcrumbs/Breadcrumbs.js
Labels: enhancement

#286 Impl [Project Overview] Evenly distribute width of counters
  src/components/Project/project.scss
Labels: enhancement

#287 Impl [Project Overview] All Nuclio links to open at top frame
  src/components/ProjectTable/ProjectTable.js
  src/elements/ProjectDataCard/ProjectDataCard.js
  src/elements/ProjectStatistics/ProjectStatistics.js
Labels: enhancement

#288 [Feature store] Add new screen and nest Datasets in it
  src/App.js
  src/common/Breadcrumbs/Breadcrumbs.js
  src/common/Breadcrumbs/Breadcrumbs.test.js
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/common/Input/Input.js
  src/common/PageActionsMenu/PageActionsMenu.js
  src/components/CreateJobPage/CreateJobPageView.js
  src/components/Details/DetailsView.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/feaureStore.util.js
  src/components/FilterMenu/FilterMenu.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/JobsPage.test.js
  src/components/JobsPanel/JobsPanel.js
  src/components/Project/Project.test.js
  src/components/Project/ProjectView.js
  src/components/Project/project.utils.js
  src/components/Table/Table.js
  src/constants.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js
  src/elements/ContentMenu/ContentMenu.js
  src/elements/DetailsMenuItem/DetailsMenuItem.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/layout/Content/Content.js
  src/utils/createArtifactsContent.js
Labels: enhancement

#289 [Artifacts] Wrong register dialog heading
  src/components/Project/Project.js
  src/components/Project/ProjectView.js
  src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
Labels: bug, enhancement

#290 Revert [Config] Proxy to Nuclio API not working in production
  src/httpClient.js
Labels: revert

#291 [Projects] New project: crash on closing error or dialog
  src/actions/projects.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/Projects.test.js
  src/constants.js
  src/reducers/projectReducer.js
Labels: bug

#292 [Projects] Redesigned project tiles
  src/actions/notification.js
  src/actions/nuclio.js
  src/actions/projects.js
  src/api/projects-api.js
  src/common/Download/Download.js
  src/common/Notification/Notification.js
  src/common/YamlModal/yamlmodal.scss
  src/components/FunctionsPage/Functions.js
  src/components/JobsPage/Jobs.js
  src/components/Project/Project.js
  src/components/Project/Project.test.js
  src/components/Project/project.utils.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/Projects.test.js
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projects.scss
  src/components/ProjectsPage/projectsData.js
  src/constants.js
  src/elements/ProjectCard/ProjectCard.js
  src/elements/ProjectCard/ProjectCardView.js
  src/elements/ProjectCard/projectCard.scss
  src/elements/ProjectStatistics/ProjectStatistics.js
  src/elements/ProjectStatistics/projectStatistics.scss
  src/layout/Header/header.scss
  src/reducers/nuclioReducer.js
  src/reducers/projectReducer.js
  src/scss/main.scss
Labels: enhancement

#293 [Jobs] Schedule: added a link to function
  src/components/FunctionsPage/Functions.js
  src/components/JobsPage/Jobs.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/elements/TableCell/TableCell.js
  src/utils/createJobsContent.js
Labels: enhancement

#294 [Project Overview] Running Jobs counter: wrong value
  src/elements/ProjectJobs/projectJobs.utils.js
Labels: bug

#295 [Create Job] Undefined job on entering screen
  src/common/PageActionsMenu/PageActionsMenu.js
  src/components/CreateJobPage/CreateJobPageView.js
Labels: bug

#296 [Jobs] Schedule: Added "Last run (local TZ)" column
  src/api/jobs-api.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/components/Table/table.scss
  src/elements/TableCell/TableCell.js
  src/elements/TableProducerCell/TableProducerCell.js
  src/utils/createJobsContent.js
Labels: enhancement

#297 [Projects] Tweaked some counters
  src/actions/projects.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/elements/ProjectCard/ProjectCard.js
  src/elements/ProjectCard/projectCard.util.js
  src/elements/ProjectStatistics/ProjectStatistics.js
  src/elements/ProjectStatistics/projectStatistics.scss
  src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.js
Labels: enhancement

#299 [Feature store] Added Feature Sets tab
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/common/PageActionsMenu/PageActionsMenu.js
  src/common/Tooltip/Tooltip.js
  src/components/ArtifactInfoMetadata/ArtifactInfoMetada.js
  src/components/ArtifactInfoMetadata/artifactInfoMetadata.scss
  src/components/ArtifactInfoMetadata/artifactInfoMetadata.util.js
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/Details/DetailsView.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/detailsInfo.util.js
  src/components/DetailsPreview/DetailsPreview.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/feaureStore.util.js
  src/components/Table/Table.js
  src/constants.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/PreviewModal/PreviewModal.js
  src/layout/Content/Content.js
  src/reducers/artifactReducer.js
  src/utils/createArtifactsContent.js
  src/utils/datetime.js
  src/utils/generateFeatureSets.js
  src/utils/generateTableContent.js
Labels: enhancement

#300 [Project Overview] Artifact counters are empty instead of 0
  src/elements/ProjectArtifacts/ProjectArtifacts.js
Labels: bug

#301 [Scheduled jobs] Add Labels column
  src/components/JobsPage/jobsData.js
  src/utils/createJobsContent.js
Labels: enhancement

#302 Fix [Feature sets] UI crashes on labels of `null`
  src/utils/object.js
Labels: bug

#303 Impl [Feature store] Add "Features" and "Feature vectors" tabs
  src/components/FeatureStore/feaureStore.util.js
Labels: enhancement

#304 Impl [Project Overview] Rename "Running functions" to "Running"
  src/elements/ProjectFunctions/ProjectFunctions.js
Labels: enhancement

#305 Fix [Scheduled Jobs] Last run: crashes when no last run
  src/elements/TableCell/TableCell.js
Labels: bug
