Repository mlrun/ui, pull requests merged in 2020-04, with the labels that each got.

#70 Development
  src/api/artifacts-api.js
  src/api/jobs-api.js
  src/common/Download/Download.js
  src/common/PageActionsMenu/PageActionsMenu.js
  src/common/TextField/TextField.js
  src/common/TextField/textField.scss
  src/components/Artifacts/artifactsData.json
  src/components/ArtifactsFilterTree/ArtifactsFilterTreeDropDown.js
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/Details/Details.js
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FilterMenu/filterMenu.scss
  src/components/FunctionsPage/Functions.js
  src/components/JobsPage/jobsData.json
  src/components/Table/table.scss
  src/elements/HiddenChipsBlock/HiddenChipsBlock.js
  src/elements/TableCell/TableCell.js
  src/elements/TableLinkCell/TableLinkCell.js
Labels: enhancement

#73 Development
  src/components/DetailsResults/DetailsResults.js
  src/components/DetailsResults/detailsResults.scss
Labels: bug

#74 Development
  src/common/Tooltip/Tooltip.js
  src/components/ArtifactInfoSources/artifactInfoSources.scss
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsResults/detailsResults.scss
  src/components/FunctionsPage/Functions.js
  src/components/JobsPage/jobsData.json
  src/components/Table/table.scss
  src/elements/Chip/Chip.js
  src/elements/ChipCell/chipCell.scss
  src/elements/HiddenChipsBlock/hiddenChipsBlock.scss
  src/elements/TableLinkCell/TableLinkCell.js
  src/elements/TableTypeCell/TableTypeCell.js
Labels: enhancement

#75 Impl [Header] Open GitHub repo in a new browser tab
  src/layout/Header/Header.js
Labels: enhancement

#76 Impl [Header] Make "See on GitHub" link secured
  src/layout/Header/Header.js
Labels: enhancement

#77 Development
  src/common/TextField/TextField.js
  src/common/TextField/textField.scss
  src/common/Tooltip/Tooltip.js
  src/components/Details/DetailsView.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FilterMenu/filterMenu.scss
  src/components/Table/table.scss
  src/elements/JobsTableRow/JobsTableRow.js
  src/images/dropdown.svg
Labels: bug

#81 Impl [Config] Use proxy middleware for dev; Add function catalog
  Dockerfile
  nginx/nginx.conf.tmpl
  package.json
  src/setupProxy.js
Labels: enhancement

#85 Impl [Header] Remove the "UI" from title, leave just "MLRun"
  src/layout/Header/Header.js
Labels: enhancement

#86 Create Job page
  src/actions/jobs.js
  src/api/jobs-api.js
  src/common/Accordion/accordion.scss
  src/common/Input/Input.js
  src/common/Input/input.scss
  src/common/PageActionsMenu/pageActionsMenu.scss
  src/common/RangeInput/RangeInput.js
  src/common/RangeInput/rangeInput.scss
  src/common/Select/Select.js
  src/common/Select/select.scss
  src/common/Select/selectData.json
  src/common/TableActionsMenu/TableActionsMenu.js
  src/common/TableActionsMenu/tableActionsMenu.scss
  src/components/ArtifactsFilterTree/artifactsFilterTree.scss
  src/components/CreateJobPage/CreateJobPage.js
  src/components/Details/Details.js
  src/components/Details/DetailsView.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FilterMenu/filterMenu.scss
  src/components/JobsPage/jobs.scss
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanel/panelData.json
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
  src/components/JobsPanelParameters/JobsPanelParameters.js
  src/components/JobsPanelParameters/JobsPanelParametersView.js
  src/components/JobsPanelResources/JobsPanelResources.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/components/ScheduleJob/scheduleJob.scss
  src/components/ScheduleJobNormal/ScheduleJobNormal.js
  src/components/ScheduleJobNormal/scheduleJobNormal.scss
  src/components/Table/TableView.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/CreateJobCardTemplate/createJobCardTemplate.scss
  src/elements/EditableDataInputsRow/EditableDataInputsRow.js
  src/elements/EditableParametersRow/EditableParametersRow.js
  src/elements/EditableVolumesRow/EditableVolumesRow.js
  src/elements/EditableVolumesRow/editableVolumesRow.scss
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/elements/JobsPanelSection/jobsPanelSection.scss
  src/elements/JobsPanelTable/JobsPanelTable.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
  src/elements/JobsPanelTableRow/JobsPanelTableRow.js
  src/elements/JobsPanelTableRow/jobsPanelTableRow.scss
  src/elements/JobsTableRow/JobsTableRow.js
  src/elements/ScheduleRecurring/scheduleRecurring.scss
  src/images/checkmark.svg
  src/reducers/jobReducer.js
  src/scss/borders.scss
  src/utils/createVolumeOfNewJob.js
Labels: enhancement

#87 Cleanup [Job Wizard] Remove `console.log`
  src/components/ScheduleJobNormal/ScheduleJobNormal.js
Labels: Cleanup

#88 Functions templates
  src/actions/functions.js
  src/api/artifacts-api.js
  src/api/functions-api.js
  src/api/jobs-api.js
  src/api/projects-api.js
  src/common/Accordion/Accordion.js
  src/common/Accordion/accordion.scss
  src/common/Download/Download.js
  src/components/CreateJobPage/CreateJobPage.js
  src/components/CreateJobPage/CreateJobPageView.js
  src/components/CreateJobPage/createJobPage.scss
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/NotificationDownload/NotificationDownload.js
  src/constants.js
  src/elements/CreateJobCardTemplate/CreateJobCardTemplate.js
  src/elements/CreateJobCardTemplate/createJobCardTemplate.scss
  src/elements/JobsPanelTable/jobsPanelTable.scss
  src/httpClient.js
  src/reducers/functionReducer.js
Labels: enhancement

#89 Development
  package.json
  src/common/DatePicker/DatePicker.js
  src/common/DatePicker/DatePickerView.js
  src/common/DatePicker/datePicker.scss
  src/common/Input/input.scss
  src/common/Select/selectData.json
  src/common/TimePicker/TimePicker.js
  src/common/TimePicker/timePicker.scss
  src/components/JobsPanel/jobsPanel.scss
  src/components/ScheduleCron/ScheduleCron.js
  src/components/ScheduleCron/scheduleCron.scss
  src/components/ScheduleJob/ScheduleJob.js
  src/components/ScheduleJob/ScheduleJobView.js
  src/components/ScheduleJob/scheduleData.json
  src/components/ScheduleJobNormal/ScheduleJobNormal.js
  src/components/ScheduleJobSimple/ScheduleJobSimple.js
  src/components/ScheduleJobSimple/scheduleJobSimple.scss
  src/elements/ScheduleRecurring/ScheduleRecurring.js
  src/elements/ScheduleRecurring/scheduleRecurring.scss
  src/elements/TableTypeCell/TableTypeCell.js
  src/images/code.svg
  src/images/jupyter.svg
  src/images/package.svg
  src/scss/borders.scss
  src/scss/main.scss
  src/utils/datePicker.util.js
Labels: enhancement

#90 Grouping on functions
  src/components/FilterMenu/FilterMenu.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functionsData.json
  src/components/JobsPage/Jobs.js
  src/components/ScheduleJobSimple/scheduleJobSimple.scss
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/elements/TableCell/TableCell.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/layout/Content/Content.js
  src/utils/createFunctionsContent.js
Labels: enhancement
