Repository mlrun/ui, pull requests merged in 2021-05, with the labels that each got.

#529 Fix [Jobs] Artifacts: preview is broken for nested objects
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/ArtifactsPreview/artifactaPreview.scss
  src/components/DetailsArtifacts/detailsArtifacts.scss
  src/elements/PreviewModal/PreviewModal.js
Labels: bug

#530 Impl [Jobs] Monitor: disable Abort action for Dask jobs
  src/components/JobsPage/jobsData.js
Labels: enhancement

#531 Fix [Jobs] Monitor: showing error and infinite loader on success
  src/api/jobs-api.js
Labels: bug

#532 Impl [Feature Store][Models] Put Beta on entire feature store
  src/common/Breadcrumbs/Breadcrumbs.js
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Models/models.util.js
  src/components/Project/project.utils.js
Labels: enhancement

#533 Fix [Model Endpoints] Error on selecting a model endpoint
  src/utils/createArtifactsContent.js
Labels: bug

#534 Fix [Model Endpoints] Always fetching from one specific project
  src/actions/details.js
  src/api/details-api.js
  src/components/Models/models.util.js
Labels: bug

#535 Impl [Jobs] Monitor: use abortable function-kind list from BE
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
Labels: enhancement

#536 Fix [Jobs] Sometimes breaks when changing filters
  src/components/JobsPage/jobsData.js
Labels: bug

#537 Impl [Jobs] Pods: Always show pods, not only when pending
  src/actions/details.js
  src/components/DetailsDriftAnalysis/DetailsDriftAnalysis.js
  src/components/DetailsFeaturesAnalysis/DetailsFeaturesAnalysis.js
  src/components/DetailsPods/DetailsPods.js
  src/utils/generatePods.js
Labels: enhancement

#538 Fix [Project] Clickable area is too large
  src/components/Project/project.scss
Labels: bug

#539 Fix [General] config.js not always loading and all breaks
  Dockerfile
  config.js.tmpl
  config.json.tmpl
  nginx/run_nginx
  public/config.js
  public/config.json
  public/index.html
  src/index.js
Labels: bug

#540 Impl [Functions] Reorder action menu: Move Delete before Run
  src/components/FunctionsPage/Functions.js
Labels: enhancement

#541 Impl [Feature sets] Create: hide Schedule field from Source
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
Labels: enhancement

#542 Impl [Feature sets] Create: Remove Stream target & rename button
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
  src/components/FeatureSetsPanel/FeatureSetsPanelView.js
Labels: enhancement

#543 Fix [General] Only Projects screen load properly, others fail
  src/index.js
Labels: bug

#544 [Features] Error on adding a feature to empty feature vectors
  src/elements/AddFeatureButton/AddFeatureButton.js
Labels: bug

#545 [Jobs] Monitor: initially filter to "Any time"
  src/components/FilterMenu/FilterMenu.js
Labels: enhancement

#546 [Feature store] Enrich usage snippets and allow to copy
  src/components/DetailsInfo/detailsInfo.scss
  src/components/FeatureStore/featureStore.util.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/utils/generateUsageSnippets.js
Labels: enhancement

#547 [Features] Newly-created vector not showing for selection
  src/common/Select/Select.js
  src/components/ArtifactsFilterTree/ArtifactsFilterTree.js
  src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
  src/scss/mixins.scss
Labels: bug

#548 Revert [Feature vectors] Requested features: remove and edit alias
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
Labels: revert

#550 [Jobs] Start Time: Remove upper bound from "Past X" options
  src/common/DatePicker/DatePicker.js
  src/components/FilterMenu/FilterMenu.js
  src/utils/datePicker.util.js
Labels: enhancement

#551 [Jobs] Status not updated immediately after abort succeeded
  src/actions/jobs.js
  src/components/JobsPage/Jobs.js
  src/constants.js
  src/reducers/jobReducer.js
Labels: bug

#549 [Jobs] Monitor: Filters: applying start time disregards name
  src/common/DatePicker/DatePicker.js
  src/components/FilterMenu/FilterMenu.js
Labels: bug

#553 [Feature vectors] List breaks on applying changes and expanding
  src/components/FeatureStore/featureStore.util.js
  src/components/Table/table.scss
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/layout/Content/Content.js
  src/utils/createArtifactsContent.js
  src/utils/generateLinkToDetailsPanel.js
  src/utils/generateUsageSnippets.js
Labels: bug

#554 [Models] Add "Deploy" action
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/common/KeyValueTable/KeyValueTable.js
  src/common/KeyValueTable/keyValueTable.scss
  src/components/Artifacts/Artifacts.js
  src/components/FeatureStore/FeatureStore.js
  src/components/Files/Files.js
  src/components/JobsPanelResources/JobsPanelResources.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/components/Project/ProjectView.js
  src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
  src/constants.js
  src/elements/DeployModelPopUp/DeployModelPopUp.js
  src/elements/DeployModelPopUp/deployModelPopUp.scss
  src/reducers/artifactReducer.js
  src/utils/generateUri.js
Labels: enhancement

#556 Impl [Models] Rename "Select serving function" to "Deploy model"
  src/elements/DeployModelPopUp/DeployModelPopUp.js
Labels: enhancement

#557 Redo [Feature vectors] Requested features: remove and edit alias
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
Labels: enhancement

#555 [Design System] Accommodate text, number & select inputs
  src/common/DatePicker/datePicker.scss
  src/common/Input/Input.js
  src/common/Input/Input.stories.js
  src/common/Input/input.scss
  src/common/RangeInput/RangeInput.js
  src/common/RangeInput/RangeInput.stories.js
  src/common/RangeInput/RangeInput.test.js
  src/common/RangeInput/rangeInput.scss
  src/common/Select/Select.js
  src/common/Select/Select.stories.js
  src/common/Select/select.scss
  src/components/Details/DetailsView.js
  src/components/DetailsTransformations/ConfigSteps/ConfigSteps.js
  src/components/DetailsTransformations/ConfigSteps/configSteps.scss
  src/components/DetailsTransformations/ConfigTargets/ConfigTargets.js
  src/components/DetailsTransformations/ConfigTargets/configTargets.scss
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.scss
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
  src/components/FilterMenu/FilterMenu.js
  src/components/FilterMenu/filterMenu.scss
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanelParameters/JobsPanelParametersView.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/components/Project/ProjectView.js
  src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
  src/elements/AddToFeatureVectorPopUp/addToFeatureVectorPopUp.scss
  src/elements/EditableAdvancedRow/EditableAdvancedRow.js
  src/elements/EditableDataInputsRow/EditableDataInputsRow.js
  src/elements/EditableParametersRow/EditableParametersRow.js
  src/elements/JobsPanelAdvancedTable/JobsPanelAdvancedTable.js
  src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/elements/JobsPanelTitle/jobsPanelTitle.scss
  src/elements/RegisterArtifactForm/RegisterArtifactForm.js
  src/elements/RegisterArtifactForm/registerArtifactForm.scss
  src/elements/ScheduleRecurring/ScheduleRecurring.js
  src/elements/ScheduleRecurring/scheduleRecurring.scss
  src/images/range-arrow-small.svg
  src/images/range-arrow.svg
  src/scss/borders.scss
  src/scss/mixins.scss
Labels: enhancement

#562 Impl [Jobs] Schedule: Rename Remove to Delete and move to last
  src/components/JobsPage/jobsData.js
Labels: enhancement

#564 [Features] Confusing label feature icon
  src/elements/FeaturesTablePanel/FeatureTablePanleRow/FeaturesTablePanelRow.js
  src/elements/FeaturesTablePanel/FeatureTablePanleRow/featuresTablePanelRow.scss
  src/images/ic_target-with-arrow-unset.svg
Labels: enhancement

#561 [General] Action menu icon hover overflow
  src/common/ActionsMenu/ActionsMenu.js
  src/common/ActionsMenu/actionsMenu.scss
Labels: bug

#560 [Jobs] Monitor: add “Aborted” to Status filter
  src/components/FilterMenu/filterMenu.settings.js
Labels: enhancement

#559 [Feature vectors] Requested Features: Delete not working
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
Labels: bug

#563 [Feature vectors] Requested Features: alias edit issue
  src/components/Details/Details.js
  src/components/Details/detailsReducer.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
  src/components/DetailsRequestedFeatures/detailsRequestedFeaturesReducer.js
Labels: bug

#566 [Jobs] Re-run: add loader while waiting for function info
  src/actions/jobs.js
  src/constants.js
  src/reducers/jobReducer.js
Labels: enhancement

#568 [Feature sets] Ingestion fails: targets uniqueness violation
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
Labels: bug

#569 [Datasets] Error on expanding row
  src/api/artifacts-api.js
Labels: bug

#571 [Function] Functions Panel: Added build image
  src/actions/functions.js
  src/common/Input/input.scss
  src/constants.js
  src/elements/FunctionsPanelCode/FunctionsPanelCode.js
  src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
  src/elements/FunctionsPanelCode/functionsPanelCode.scss
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js
  src/reducers/functionReducer.js
Labels: enhancement

#570 [Feature set panel] Made Tag field optional
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitle.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelView.js
Labels: enhancement

#567 [Functions] Add confirmation to Delete action
  src/components/FunctionsPage/Functions.js
Labels: enhancement

#572 [Feature vectors] Requested Features: unexpected confirmation
  src/api/artifacts-api.js
  src/components/Details/Details.js
  src/components/Details/details.util.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
  src/components/DetailsRequestedFeatures/detailsRequestedFeatures.scss
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
Labels: bug

#575 [Job panel] Added loader immediately on submitting form, fixed bug with wrong request and freezing UI
  src/actions/jobs.js
  src/components/FilterMenu/FilterMenu.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPanel/JobsPanel.js
  src/constants.js
  src/reducers/jobReducer.js
Labels: enhancement

#574 [Feature set] New: Offline target set by default
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/reducers/artifactReducer.js
Labels: enhancement

#576 Fix [Feature sets] Overview: remove redundant ")" in snippet
  src/utils/generateUsageSnippets.js
Labels: bug

#580 Impl [e2e-tests] Sprint 122
  .gitignore
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/action-menu.action.js
  tests/features/common/actions/checkbox.action.js
  tests/features/common/actions/common.action.js
  tests/features/common/actions/dropdown.action.js
  tests/features/common/actions/input-group.action.js
  tests/features/common/actions/radio-button.action.js
  tests/features/common/actions/tab-selector.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/components/action-menu.component.js
  tests/features/common/components/checkbox.component.js
  tests/features/common/components/dropdown.component.js
  tests/features/common/components/input-group.component.js
  tests/features/common/components/radio-button.component.js
  tests/features/common/components/table.component.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/project.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/featureStore.feature
  tests/features/projectPage.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
Labels: tests

#577 [Function panel] Resources: changed layout to take less space
  src/common/RangeInput/RangeInput.js
  src/common/RangeInput/rangeInput.scss
  src/common/Select/Select.js
  src/common/Select/select.scss
  src/components/CreateJobPage/createJobPage.scss
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
  src/elements/FunctionsPanelResources/functionsPanelResources.scss
Labels: enhancement

#579 [Data Inputs] Add autocomplete to item tag/UID/iteration
  src/common/Combobox/Combobox.js
  src/common/Combobox/ComboboxView.js
  src/common/Combobox/combobox.scss
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/Files.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputsReducer.js
  src/components/Models/models.util.js
  src/elements/DeployModelPopUp/DeployModelPopUp.js
  src/elements/EditableDataInputsRow/EditableDataInputsRow.utils.js
  src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
  src/types.js
  src/utils/createArtifactsContent.js
  src/utils/generateUri.js
  src/utils/generateUsageSnippets.js
  src/utils/resources.js
Labels: enhancement

#558 [Models][Datasets][Files] Add "Show iterations" filter
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/Files.js
  src/components/Files/files.util.js
  src/components/FilterMenu/FilterMenu.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/layout/Content/Content.js
  src/reducers/artifactReducer.js
  src/utils/createArtifactsContent.js
  src/utils/handleArtifactTreeFilterChange.js
Labels: enhancement

#582 [General] Name filter should not use exact match
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/api/functions-api.js
  src/api/jobs-api.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
Labels: enhancement

#583 [Functions] Auto-select newly-created function
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPanel/FunctionsPanel.js
Labels: enhancement

#584 [General] Name column: value is cropped without ellipsis
  src/elements/TableLinkCell/TableLinkCell.js
Labels: bug

#589 [Feature sets] Version is disregarded on creation
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
Labels: bug

#591 [Models] Console error on deploy
  src/common/KeyValueTable/KeyValueTable.js
Labels: bug

#590 [Job panel] Show error on loading template error
  src/actions/functions.js
  src/components/CreateJobPage/CreateJobPage.js
  src/components/JobsPanel/JobsPanel.js
Labels: enhancement

#592 [Data Inputs, Model Endpoints] Requests contain wrong `project` name
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/components/Artifacts/Artifacts.js
  src/components/Details/Details.js
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/Files.js
  src/components/FunctionsPage/Functions.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
  src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
  src/types.js
  src/utils/handleArtifactTreeFilterChange.js
Labels: bug

#593 [Functions] View YAML opens the wrong item
  src/common/YamlModal/yamlmodal.scss
  src/components/FunctionsPage/Functions.js
  src/components/Table/TableView.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/layout/Content/Content.js
  src/layout/Content/content.util.js
  src/utils/resources.js
Labels: bug

#581 [Data Inputs] Sort projects and resource names by name
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
Labels: enhancement

#594 [ML Functions] Crash on firing the "Run" action of the function
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanelResources/JobsPanelResources.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
Labels: bug

#595 [Projects] Sort projects dropdown is transparent
  src/common/Sort/sort.scss
Labels: bug

#598 [Job panel] Condense resources layout
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanel/panelReducer.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
Labels: enhancement

#599 [Job panel] Omit `selector` when Result is empty
  src/components/JobsPanel/jobsPanel.util.js
Labels: enhancement

#600 [Feature Vectors] Delete feature pop-up isn't aligned
  src/components/Details/details.scss
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
Labels: bug

#601 [Functions] Update name validation; Turn Tag optional
  src/actions/functions.js
  src/api/functions-api.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/constants.js
  src/elements/FunctionsPanelCode/FunctionsPanelCode.js
  src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneral.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js
  src/elements/FunctionsPanelGeneral/functionsPanelGeneral.util.js
  src/layout/Content/Content.js
  src/reducers/functionReducer.js
Labels: enhancement

#603 [General] Rename "Expand" action to "Expand all"
  src/components/FilterMenu/FilterMenu.js
Labels: enhancement

#602 [Data Inputs] Crash on editing the project name
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
Labels: bug

#604 [Feature sets] Show Create Set/Vector buttons only on demo
  src/layout/Content/Content.js
Labels: enhancement

#607 [Feature sets] Use tag when ingesting a feature set
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
  src/utils/generateUsageSnippets.js
Labels: enhancement

#605 [Monitor] Notification doesn't disappear on "Schedule" job
  src/components/Table/Table.js
  src/layout/Content/Content.js
Labels: bug

#606 [Breadcrumbs] Sort projects by name
  src/common/Breadcrumbs/Breadcrumbs.js
  src/components/Project/ProjectView.js
  src/utils/projects.js
Labels: enhancement
