Repository mlrun/ui, pull requests merged in 2021-03, with the labels that each got.

#412 [Breadcrumbs] Add full value in tooltip on menu option hover
  src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js
Labels: enhancement

#413 Fix [Artifacts] Preview: path inconsistently missing schema
  src/elements/PreviewModal/PreviewModal.js
Labels: bug

#415 [Jobs] Filters not working
  src/components/FilterMenu/FilterMenu.js
Labels: bug

#414 [Files] Crash on selecting another file
  src/components/DetailsInfo/DetailsInfoView.js
Labels: bug

#416 [Artifacts] Removed Artifacts screen
  src/App.js
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
Labels: enhancement

#411 [Artifacts] Refactored artifact preview
  src/common/ErrorMessage/ErrorMessage.js
  src/common/ErrorMessage/errorMessage.scss
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/ArtifactsPreview/PreviewError/PreviewError.js
  src/components/ArtifactsPreview/artifactPreview.util.js
  src/components/ArtifactsPreview/artifactaPreview.scss
  src/components/DetailsAnalysis/DetailsAnalysis.js
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsArtifacts/detailsArtifacts.util.js
  src/components/DetailsPreview/DetailsPreview.js
  src/components/Table/table.scss
  src/elements/PreviewModal/PreviewModal.js
  src/elements/ProjectArtifacts/ProjectArtifacts.js
  src/elements/ProjectDataCard/ProjectDataCard.js
  src/scss/main.scss
  src/utils/getArtifactPreview.js
Labels: Cleanup

#418 Fix [Models][Datasets][Files] Details: broken link to producer job
  src/components/DetailsInfo/DetailsInfoView.js
Labels: bug

#421 Fix [Modles][Datasets][Files] Overview: Path value is missing
  src/common/Download/Download.js
  src/components/Details/DetailsView.js
  src/components/Details/details.util.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/Files.js
  src/components/Models/models.util.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/elements/PreviewModal/PreviewModal.js
  src/elements/TableCell/TableCell.js
  src/utils/downloadFile.js
  src/utils/generateArtifactPreviewData.js
  src/utils/generateArtifacts.js
Labels: bug

#422 Impl [Models] Overview: add "Model file" field
  src/components/Models/models.util.js
Labels: enhancement

#417 [Jobs] Monitor: add icon to remote type
  src/elements/TableTypeCell/TableTypeCell.js
  src/images/ic_remote.svg
Labels: enhancement

#419 [Artifacts] Preview: add tooltip to pop-out icon button
  src/components/DetailsPreview/DetailsPreview.js
Labels: enhancement

#420 [General] Chip list pop-over stacking issues
  src/elements/HiddenChipsBlock/HiddenChipsBlock.js
  src/elements/HiddenChipsBlock/hiddenChipsBlock.scss
  src/utils/getFirstScrollableParent.js
Labels: bug

#423 Impl [Models][Datasets][Files] Reflect actual downloaded filename
  src/common/Download/Download.js
  src/components/Details/DetailsView.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/elements/PreviewModal/PreviewModal.js
  src/elements/TableCell/TableCell.js
  src/utils/downloadFile.js
Labels: enhancement

#424 [Models][Datasets][Files] Register: Type: remove or limit
  src/components/FeatureStore/FeatureStore.js
  src/components/Files/Files.js
  src/components/Models/Models.js
  src/components/Project/ProjectView.js
  src/components/Project/project.utils.js
  src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
  src/elements/RegisterArtifactForm/RegisterArtifactForm.js
Labels: enhancement

#425 Impl [Datasets] Preview: when no `header`, use `preview` first row
  src/utils/getArtifactPreview.js
Labels: enhancement

#429 Impl [Create Job] Filter out function templates of kind Remote
  src/utils/generateTemplatesCategories.js
Labels: enhancement

#430 Fix [Filters] Inconsistent order of filters across screens
  package.json
  src/api/artifacts-api.js
  src/api/jobs-api.js
  src/common/Input/input.scss
  src/components/FilterMenu/FilterMenu.js
  src/components/JobsPage/jobsData.js
  src/components/Models/models.util.js
  src/httpClient.js
Labels: bug, enhancement

#428 [Features Sets] Statistics tab: add histogram column
  package.json
  src/colorConstants.js
  src/common/Chart/MlChart.js
  src/common/Chart/mlChart.scss
  src/common/Chart/mlChart.util.js
  src/common/Download/Download.js
  src/common/Input/input.scss
  src/common/Loader/Loader.js
  src/common/Loader/loader.scss
  src/components/Details/Details.js
  src/components/DetailsStatistics/DetailsStatistics.js
  src/components/DetailsStatistics/detailsStatistics.scss
  src/components/DetailsStatistics/detailsStatistics.util.js
  src/elements/ProjectDataCard/ProjectDataCard.js
  src/elements/ProjectStatistics/projectStatistics.scss
  src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.js
  src/scss/colors.scss
Labels: enhancement

#427 [Create Job] Added Selector field to hyperparameters
  src/actions/jobs.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanelParameters/JobsPanelParameters.js
  src/components/JobsPanelParameters/JobsPanelParametersView.js
  src/components/JobsPanelParameters/jobsPanelParameters.util.js
  src/constants.js
  src/elements/EditableParametersRow/EditableParametersRow.js
  src/elements/JobsPanelParametersTable/JobsPanelParametersTable.js
  src/elements/JobsPanelParametersTable/JobsPanelParametersTableView.js
  src/reducers/jobReducer.js
  src/scss/main.scss
  src/scss/mixins.scss
Labels: enhancement

#432 [Jobs] Artifacts: name and target path overlap
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsArtifacts/detailsArtifacts.scss
Labels: bug

#433 [Models][Datasets][Files] Overview: rename Tree to UID + info
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/files.util.js
  src/components/Models/models.util.js
Labels: enhancement

#435 Fix [General] Overview tab: capitalized tooltip messages
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfo.scss
Labels: bug

#434 [General] Filters not cleared on switching tabs
  src/components/FilterMenu/FilterMenu.js
Labels: bug

#431 Added storybook buttons
  .storybook/main.js
  .storybook/preview.js
  package.json
  src/common/Button/Button.js
  src/common/Button/Button.stories.js
  src/common/Button/button.scss
  src/common/LoadButton/LoadButton.js
  src/common/LoadButton/LoadButton.stories.js
  src/common/LoadButton/loadButton.scss
  src/common/PageActionsMenu/PageActionsMenu.js
  src/common/Select/Select.js
  src/components/Details/DetailsView.js
  src/components/Details/details.scss
  src/components/DetailsTransformations/ConfigSteps/ConfigSteps.js
  src/components/FilterMenu/FilterMenu.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projectsData.js
  src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
  src/components/ScheduleJob/ScheduleJobView.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/elements/JobsPanelTitle/jobsPanelTitle.scss
  src/scss/colors.scss
  src/scss/main.scss
Labels: enhancement

#436 [Project Overview] Jobs: Show status of up to last 5 runs
  src/components/ProjectTable/ProjectTable.js
  src/components/ProjectTable/projectTable.scss
  src/elements/ProjectJobs/ProjectJobs.js
  src/elements/ProjectJobs/projectJobs.utils.js
  src/scss/main.scss
Labels: enhancement

#439 [Feature vectors] Overview: Last Updated is N/A
  src/components/Details/details.util.js
Labels: bug

#437 [Create Job] Data Inputs: feature vectors selection in store
  src/common/Combobox/Combobox.js
  src/common/Combobox/ComboboxView.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputsReducer.js
  src/elements/EditableDataInputsRow/EditableDataInputsRow.js
  src/elements/EditableDataInputsRow/EditableDataInputsRow.utils.js
  src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
Labels: enhancement

#438 [Models] Add Metrics column
  src/components/Details/details.util.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/Models/models.util.js
  src/components/Table/table.scss
  src/utils/createArtifactsContent.js
Labels: enhancement

#444 [Features] Search by name crashes UI
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/TableLinkCell/TableLinkCell.js
Labels: bug

#440 [Scheduled Jobs] Allowed editing scheduled jobs
  src/actions/jobs.js
  src/api/jobs-api.js
  src/common/Accordion/Accordion.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.util.js
  src/components/ScheduleJob/ScheduleJob.js
  src/constants.js
  src/elements/JobsPanelTitle/JobsPanelTitle.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/reducers/jobReducer.js
Labels: enhancement

#441 [Feature sets] Transformations: too much zoom on init
  src/common/LoadButton/LoadButton.js
  src/components/DetailsTransformations/DetailsTransformations.js
Labels: bug

#442 [Projects] Nuclio functions not re-fetched on refresh
  src/common/Breadcrumbs/Breadcrumbs.js
  src/components/ProjectsPage/Projects.js
  src/reducers/projectReducer.js
Labels: bug

#445 [General] Missing "Close" tooltip on close icon button
  src/common/ErrorMessage/ErrorMessage.js
  src/common/PopUpDialog/PopUpDialog.js
  src/common/YamlModal/YamlModal.js
  src/components/Details/DetailsView.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/elements/PreviewModal/PreviewModal.js
Labels: bug

#446 Fix [Jobs] Artifacts: crashes if job has no owner/v3io_user label
  src/components/DetailsArtifacts/detailsArtifacts.util.js
Labels: bug

#448 Fix [Feature Store] "Beta" note does not appear by default
  Dockerfile
Labels: bug

#449 [Jobs] Monitor: add links to performance reports
  src/actions/app.js
  src/api/app-api.js
  src/common/Button/Button.js
  src/common/Button/Button.stories.js
  src/common/Button/button.scss
  src/common/TableActionsMenu/TableActionsMenu.js
  src/common/TableActionsMenu/tableActionsMenu.scss
  src/common/Tooltip/Tooltip.js
  src/components/FeatureStore/featureStore.util.js
  src/components/FilterMenu/FilterMenu.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/constants.js
  src/layout/Content/Content.js
  src/layout/Page/Page.js
  src/reducers/appReducer.js
  src/reducers/reducers.js
Labels: enhancement

#447 [Models][Datasets][Files] Added collapse-expand with all tags
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/common/TableActionsMenu/TableActionsMenu.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/Files.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/components/Table/TableView.js
  src/constants.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/TableCell/TableCell.js
  src/elements/TableProducerCell/TableProducerCell.js
  src/layout/Content/Content.js
  src/layout/Content/content.util.js
  src/reducers/artifactReducer.js
  src/utils/createArtifactsContent.js
  src/utils/generateArtifacts.js
Labels: enhancement

#450 Impl [Project][Jobs] Add "Aborted" status
  src/components/Details/DetailsView.js
  src/components/Details/details.util.js
  src/elements/ProjectJobs/projectJobs.utils.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/scss/main.scss
Labels: enhancement

#451 Impl [Model endpoints] Add fields: Model artifact, Function URI
  src/actions/artifacts.js
  src/common/Tooltip/Tooltip.js
  src/components/Details/DetailsView.js
  src/components/Details/details.util.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfo.util.js
  src/components/Models/models.util.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/utils/createArtifactsContent.js
  src/utils/index.js
Labels: enhancement

#452 Fix [General] UI does not come up
  src/utils/parseUri.js
Labels: bug

#453 Cleanup [General] Add some docs to parse URI utility function
  src/utils/parseUri.js
Labels: Cleanup

#455 Impl [Model endpoints] Accommodate to more API changes+more fields
  src/components/Details/DetailsView.js
  src/components/Details/details.util.js
  src/components/DetailsInfo/detailsInfo.util.js
  src/components/Models/models.util.js
  src/utils/createArtifactsContent.js
Labels: enhancement

#454 [Jobs] Monitor: Added "Rerun" action
  src/actions/jobs.js
  src/api/jobs-api.js
  src/common/TableActionsMenu/TableActionsMenu.js
  src/common/TableActionsMenu/tableActionsMenu.scss
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/components/JobsPanelParameters/JobsPanelParameters.js
Labels: enhancement

#456 [General] Add "URI" field and "Copy URI" action
  src/components/Details/details.util.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/Files.js
  src/components/Files/files.util.js
  src/components/Models/models.util.js
  src/constants.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/utils/generateUri.js
Labels: enhancement

#457 [Models][Files] Missing tag in URL on clicking name link
  src/App.js
  src/components/Files/Files.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/utils/createArtifactsContent.js
Labels: bug

#460 Fix [Feature sets][Feature vectors] Error on expanding group row
  src/components/FeatureStore/featureStore.util.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
Labels: bug

#461 [Jobs] Schedule: edit crashes
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#458 [General] Poll for frontend spec every 60 seconds
  src/layout/Page/Page.js
Labels: enhancement

#462 [General] Links style: add underline on hover
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsArtifacts/detailsArtifacts.scss
  src/components/DetailsInfo/detailsInfo.scss
  src/components/Project/ProjectLinks/ProjectLinks.js
  src/components/Project/project.scss
  src/components/ProjectTable/ProjectTable.js
  src/components/ProjectTable/projectTable.scss
  src/components/ScheduleCron/ScheduleCron.js
  src/components/ScheduleCron/scheduleCron.scss
  src/components/Table/table.scss
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/elements/ProjectDataCard/ProjectDataCard.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/elements/TableProducerCell/TableProducerCell.js
  src/scss/main.scss
  src/stories/Link.stories.js
Labels: enhancement

#464 [General] View YAML dialog not closing on switching tabs
  src/layout/Content/Content.js
Labels: bug

#465 [Feature vectors] View YAML always shows YAML of first vector
  src/layout/Content/Content.js
Labels: bug

#468 Fix [Jobs] Artifacts: show details link is broken
  src/components/Artifacts/Artifacts.js
  src/components/Details/DetailsView.js
  src/components/Details/details.util.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsArtifacts/detailsArtifacts.util.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/Files.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/layout/Content/Content.js
  src/layout/Content/content.util.js
  src/utils/createArtifactsContent.js
  src/utils/parseUri.js
Labels: bug

#469 Fix [Project] Real-time functions: missing status values
  src/components/ProjectTable/ProjectTable.js
  src/components/ProjectTable/projectTable.scss
Labels: bug

#471 Impl [Config] Improve performance of Dockerfile
  Dockerfile
Labels: enhancement

#472 Impl [Jobs] Monitor: disable "Monitoring" action for Dask jobs
  src/common/TableActionsMenu/TableActionsMenu.js
  src/components/Details/DetailsView.js
  src/components/JobsPage/jobsData.js
  src/components/Table/TableView.js
  src/elements/JobsTableRow/JobsTableRow.js
Labels: enhancement

#474 Fix [Models][Datasets][Files] Overview: crashes on malformed URI
  src/components/DetailsInfo/DetailsInfoView.js
Labels: bug

#475 Fix [Jobs] Monitor: Rerun operates on wrong item
  src/components/Table/TableView.js
  src/elements/JobsTableRow/JobsTableRow.js
Labels: bug

#476 Fix [Jobs] Schedule: console error
  src/components/Details/Details.js
  src/components/Details/DetailsView.js
  src/components/JobsPage/jobsData.js
  src/elements/JobsTableRow/JobsTableRow.js
Labels: bug

#477 Fix [Jobs] Schedule: wrong button labeled "Button" appears
  src/components/JobsPage/jobsData.js
Labels: bug

#478 [Jobs] Schedule: edit not working for job with secrets
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#473 [Features] Should not have "Copy URI" action
  src/components/FeatureStore/featureStore.util.js
Labels: bug

#481 Impl [StoryBook] Allow import of SVG files in stories
  .storybook/webpack.config.js
Labels: enhancement
