Repository mlrun/ui, pull requests merged in 2021-01, with the labels that each got.

#335 Impl [Create Job] Indicate in filter placeholder it is by name
  src/components/CreateJobPage/CreateJobPageView.js
Labels: enhancement

#336 [General] Make entire area of tab headers clickable
  src/elements/ContentMenu/contentMenu.scss
Labels: enhancement

#337 Fix [Jobs] Monitor: group by workflow always gives an empty list
  src/components/Table/Table.js
Labels: bug

#338 Impl [Feature Sets] Add Transformations & Targets tab headers
  src/components/FeatureStore/FeatureStore.js
Labels: enhancement

#339 [Projects] Hide archived projects from All Projects
  src/components/ProjectsPage/Projects.js
Labels: enhancement

#341 [Jobs] Monitor: add status indicator to workflows
  src/components/Table/table.scss
  src/elements/TableCell/TableCell.js
  src/scss/main.scss
Labels: enhancement

#342 Impl [Project Overview] Append "(Nuclio)" to API GWs quick link
  src/components/Project/project.utils.js
Labels: enhancement

#343 Impl [Features] Add Description, Targets & Validator columns
  src/components/DetailsMetadata/detailsMetadata.scss
  src/components/DetailsMetadata/detailsMetadata.util.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/feaureStore.util.js
  src/components/JobsPage/jobsData.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/ContentMenu/ContentMenu.js
  src/elements/ContentMenu/contentMenu.scss
  src/elements/FeatureValidator/FeatureValidator.js
  src/elements/FeatureValidator/FeatureValidator.scss
  src/elements/TableCell/TableCell.js
  src/utils/createArtifactsContent.js
  src/utils/object.js
Labels: enhancement

#346 Revert [Projects] Allow delete for archived projects only
  src/components/ProjectsPage/projectsData.js
Labels: revert

#347 [Project Overview] Make name non-editable
  src/components/Project/ProjectView.js
  src/components/Project/project.scss
Labels: enhancement

#351 Fix [Jobs] Columns unaligned with nested rows
  src/elements/JobsTableRow/JobsTableRow.js
Labels: bug

#352 Fix [Projects] Project name overflows its tile
  src/elements/ProjectCard/ProjectCard.js
Labels: bug

#353 Fix [Projects] Missing "No data to show" message when no projects
  src/components/ProjectsPage/Projects.js
Labels: bug

#350 [Project Overview] Add Goals, Source, and Labels
  src/actions/projects.js
  src/api/projects-api.js
  src/common/ChipCell/ChipCell.js
  src/common/ChipCell/ChipCellView.js
  src/components/ChipForm/chipForm.scss
  src/components/Project/Project.js
  src/components/Project/ProjectView.js
  src/components/Project/project.scss
  src/constants.js
  src/elements/HiddenChipsBlock/HiddenChipsBlock.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/reducers/projectReducer.js
Labels: enhancement

#349 [Projects][Project Overview] Counters: count distinct names
  src/components/Project/ProjectView.js
  src/elements/ProjectCard/projectCard.util.js
  src/elements/ProjectFunctions/ProjectFunctions.js
  src/elements/ProjectJobs/projectJobs.utils.js
  src/utils/groupByUniqName.js
Labels: enhancement

#354 Impl [Create Job] Update default artifact path
  src/components/JobsPanel/panelReducer.js
Labels: enhancement

#355 [Create Job] Data Inputs: enhance scheme options
  src/common/Combobox/combobox.scss
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
  src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
Labels: enhancement

#356 Allow to forcefully delete a non-empty project
  src/actions/projects.js
  src/api/projects-api.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/scss/main.scss
Labels: enhancement

#357 [Feature Sets] Allow editing fields and cancel/apply them
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/common/Chip/Chip.js
  src/common/ChipCell/ChipCell.js
  src/common/PopUpDialog/PopUpDialog.js
  src/common/PopUpDialog/popUpDialog.scss
  src/components/Details/Details.js
  src/components/Details/DetailsView.js
  src/components/Details/details.scss
  src/components/Details/details.util.js
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/DetailsInfo/detailsInfo.util.js
  src/components/DetailsInfo/detailsInfoReducer.js
  src/components/DetailsInfo/detailsReducer.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/feaureStore.util.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FunctionsPage/functions.util.js
  src/components/JobsPage/jobsData.js
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/elements/DetailsMenuItem/DetailsMenuItem.js
  src/elements/TooltipTemplate/TextTooltipTemplate.js
  src/layout/Content/Content.js
  src/layout/Content/content.scss
  src/reducers/artifactReducer.js
  src/scss/borders.scss
  src/scss/colors.scss
  src/scss/main.scss
Labels: enhancement

#358 Impl [Feature Sets] Rename "Metadata" tab header to "Features"
  src/components/Details/details.util.js
  src/components/FeatureStore/FeatureStore.js
  src/constants.js
Labels: enhancement

#359 Impl [Feature Sets] Apply button: default cursor on idle+hover
  src/components/Details/details.scss
Labels: enhancement

#362 Cleanup [Feature Sets] Rename `uid` to `tag` on `PATCH` endpoint
  src/actions/artifacts.js
  src/api/artifacts-api.js
Labels: Cleanup

#363 Impl [Projects] Delete non-empty: do not rely on error text
  src/components/ProjectsPage/Projects.js
Labels: enhancement

#365 [Feature store] Added Feature Vectors tab contents
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/components/Artifacts/artifactsData.json
  src/components/ArtifactsFilterTree/ArtifactsFilterTree.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/feaureStore.util.js
  src/components/Files/files.util.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FunctionsPage/functions.util.js
  src/components/JobsPage/jobsData.js
  src/components/Models/models.util.js
  src/components/ProjectsPage/Projects.js
  src/constants.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/layout/Content/Content.js
  src/reducers/artifactReducer.js
  src/utils/createArtifactsContent.js
  src/utils/parseFeatureStoreDataRequest.js
Labels: enhancement

#364 [Create Job] Empty name is unexpectedly valid
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/elements/JobsPanelTitle/JobsPanelTitle.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/scss/main.scss
Labels: bug

#367 Impl [General] Labels filter: rename to Label, reword placeholder
  src/components/FilterMenu/FilterMenu.js
Labels: enhancement

#368 Impl [General] Reword Label placeholder to "key or key=value"
  src/components/FilterMenu/FilterMenu.js
Labels: enhancement

#366 [Models][Files] View YAML is broken
  src/actions/artifacts.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/feaureStore.util.js
  src/components/Files/Files.js
  src/components/Models/Models.js
  src/layout/Content/Content.js
Labels: bug

#369 Impl [Project Overview] Features counter: rename to Datasets
  src/components/Project/ProjectView.js
Labels: enhancement

#370 [Projects][Scheduled Jobs] Add confirmation before delete
  .eslintrc.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
Labels: enhancement

#371 Fix [Projects] Delete non-empty project confirm: missing space
  src/components/ProjectsPage/Projects.js
Labels: bug

#372 Fix [Create Job] Duplicated template in the same category
  package.json
  src/utils/generateTemplatesCategories.js
Labels: Cleanup, bug

#374 Impl [Feature Store] Rename tab header to "Datasets"
  src/components/FeatureStore/feaureStore.util.js
Labels: enhancement

#373 [Feature Vectors] Added nested tabs
  .eslintrc.js
  package.json
  src/actions/artifacts.js
  src/components/Details/DetailsView.js
  src/components/Details/details.util.js
  src/components/DetailsMetadata/detailsMetadata.util.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
  src/components/DetailsRequestedFeatures/detailsRequestedFeatures.scss
  src/components/DetailsStatistics/detailsStatistics.util.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/feaureStore.util.js
  src/components/FilterMenu/FilterMenu.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/Project/ProjectView.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/constants.js
  src/elements/JobsPanelTitle/JobsPanelTitle.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/layout/Content/Content.js
  src/scss/main.scss
  src/utils/generateTemplatesCategories.js
  src/utils/parseFeatureVectors.js
Labels: enhancement

#376 Impl [General] Rename "labels" filter to "label" + merge development
  src/components/FeatureStore/feaureStore.util.js
Labels: enhancement
