Repository mlrun/ui, pull requests merged in 2021-09, with the labels that each got.

#776 [Files] Details pane cannot be opened
  src/actions/artifacts.js
  src/components/Files/Files.js
Labels: bug

#775 [Function panel] Do not confirm overwrite on edit
  src/common/Button/Button.js
  src/common/Button/Button.stories.js
  src/common/DatePicker/DatePickerView.js
  src/common/EditorModal/EditorModalView.js
  src/common/LoadButton/LoadButton.js
  src/common/LoadButton/LoadButton.stories.js
  src/common/PageActionsMenu/PageActionsMenu.js
  src/common/Select/Select.js
  src/components/Details/DetailsView.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
  src/components/DetailsTransformations/ConfigSteps/ConfigSteps.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelView.js
  src/components/FeatureSetsPanel/ScheduleFeatureSet/ScheduleFeatureSetView.js
  src/components/FeatureStore/featureStore.util.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projectsData.js
  src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
  src/components/ScheduleJob/ScheduleJobView.js
  src/constants.js
  src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
  src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
  src/elements/DeployModelPopUp/DeployModelPopUp.js
  src/elements/FeaturesTablePanel/FeaturesTablePanel.js
  src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/elements/MembersPopUp/MembersPopUp.js
  src/types.js
Labels: enhancement

#768 [Jobs] Hide "Re-run" for kind local
  src/components/JobsPage/jobsData.js
Labels: enhancement

#771 [Function panel] Pre-populate with default values
  src/actions/functions.js
  src/common/Input/Input.js
  src/common/TextArea/TextArea.js
  src/common/TextArea/textArea.scss
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/constants.js
  src/elements/FunctionsPanelCode/FunctionsPanelCode.js
  src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
  src/reducers/functionReducer.js
Labels: enhancement

#777 [Breadcrumbs] Project list overflows viewport
  src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js
  src/elements/BreadcrumbsDropdown/breadcrumbsDropdown.scss
Labels: bug

#778 [Feature Sets] App crashes on entering Statistics tab
  src/components/DetailsStatistics/DetailsStatistics.js
Labels: bug

#779 Impl [Functions] Move "New" and "Edit" to production
  src/components/FunctionsPage/Functions.js
Labels: enhancement

#780 Fix [Jobs] "Re-run" not always hidden for kind local
  src/components/JobsPage/jobsData.js
Labels: bug

#781 [Project Overview][Jobs] Inconsistent job type
  src/elements/ProjectJobs/projectJobs.utils.js
  src/elements/TableTypeCell/TableTypeCell.js
  src/utils/createJobsContent.js
Labels: bug

#784 [Feature vectors] Pre-populate Tag filter
  src/actions/artifacts.js
  src/actions/filters.js
  src/api/artifacts-api.js
  src/components/FeatureStore/FeatureStore.js
  src/components/Files/Files.js
  src/components/FilterMenu/FilterMenu.js
  src/components/Models/Models.js
  src/constants.js
  src/reducers/filtersReducer.js
Labels: enhancement

#785 [Jobs] Crashes when filter by status error
  src/common/ActionsMenu/ActionsMenu.js
  src/components/JobsPage/jobsData.js
  src/components/Table/TableView.js
Labels: bug

#783 [Project overview] Project data is not updated properly
  src/components/Project/Project.js
Labels: bug

#786 [Features] Pre-populate Tag filter
  src/actions/artifacts.js
  src/actions/featureStore.js
  src/api/artifacts-api.js
  src/api/featureStore-api.js
  src/components/FeatureStore/FeatureStore.js
Labels: enhancement

#789 [Functions] Build Log: Loader area in tab only
  src/components/DetailsLogs/DetailsLogs.js
  src/reducers/functionReducer.js
Labels: enhancement

#790 [Jobs panel] Wrong combobox suggestions flow for Data inputs
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.util.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
  src/elements/EditableDataInputsRow/EditableDataInputsRow.js
  src/elements/EditableDataInputsRow/EditableDataInputsRow.utils.js
  src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
Labels: bug

#791 Impl [e2e-tests] Sprint 126
  package.json
  scripts/collectUITestsSteps.js
  tests/features/common/components/combo-box.component.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/featureStore.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
Labels: tests

#792 [Function panel] with_mlrun on wrong request and wrong value
  src/actions/functions.js
  src/api/functions-api.js
  src/common/TextArea/textArea.scss
  src/components/FunctionsPanel/FunctionsPanel.js
  src/constants.js
  src/elements/FunctionsPanelCode/FunctionsPanelCode.js
  src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
  src/reducers/functionReducer.js
Labels: bug

#788 [Job Panel] Function parts are not reflected
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#793 Impl [Feature set panel] Name: Reduce max length from 63 to 56
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
  src/components/FeatureSetsPanel/featureSetPanel.util.js
Labels: enhancement

#794 [Jobs] Monitor: pending has no color indicator
  src/scss/main.scss
  src/utils/getState.js
Labels: bug

#747 [Function panel] Added Serving runtime
  src/actions/functions.js
  src/common/Input/Input.js
  src/common/KeyValueTable/KeyValueTable.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functions.util.js
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/components/FunctionsPanel/functionsPanel.util.js
  src/constants.js
  src/elements/EditableVolumesRow/editableVolumesRow.scss
  src/elements/FunctionPanelTopologyModelTable/AddRouteRow.js
  src/elements/FunctionPanelTopologyModelTable/EditableRouteRow.js
  src/elements/FunctionPanelTopologyModelTable/FunctionPanelTopologyModelTable.js
  src/elements/FunctionPanelTopologyModelTable/FunctionPanelTopologyModelTableView.js
  src/elements/FunctionPanelTopologyModelTable/functionPanelTopologyModelTable.scss
  src/elements/FunctionPanelTopologyModelTable/functionPanelTopologyModelTable.util.js
  src/elements/FunctionsPanelAdvanced/FunctionsPanelAdvanced.js
  src/elements/FunctionsPanelCode/FunctionsPanelCode.js
  src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
  src/elements/FunctionsPanelCode/functionsPanelCode.scss
  src/elements/FunctionsPanelCode/functionsPanelCode.util.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneral.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js
  src/elements/FunctionsPanelGeneral/functionsPanelGeneral.scss
  src/elements/FunctionsPanelGeneral/functionsPanelGeneral.util.js
  src/elements/FunctionsPanelParameters/AddFunctionParameterRow.js
  src/elements/FunctionsPanelParameters/EditableFunctionParameterRow.js
  src/elements/FunctionsPanelParameters/FunctionsPanelParameters.js
  src/elements/FunctionsPanelParameters/FunctionsPanelParametersView.js
  src/elements/FunctionsPanelParameters/functionsPanelParameters.scss
  src/elements/FunctionsPanelParameters/functionsPanelParameters.util.js
  src/elements/FunctionsPanelRuntime/FunctionsPanelRuntime.js
  src/elements/FunctionsPanelRuntime/FunctionsPanelRuntimeView.js
  src/elements/FunctionsPanelRuntime/functionsPanelRuntime.scss
  src/elements/FunctionsPanelSecrets/FunctionsPanelSecrets.js
  src/elements/FunctionsPanelSecrets/FunctionsPanelSecretsView.js
  src/elements/FunctionsPanelSecrets/functionsPanelSecrets.scss
  src/elements/FunctionsPanelTopology/FunctionsPanelTopology.js
  src/elements/FunctionsPanelTopology/FunctionsPanelTopologyView.js
  src/elements/FunctionsPanelTopology/functionsPanelTopology.scss
  src/elements/FunctionsPanelTopology/functionsPanelTopology.util.js
  src/elements/NewFunctionPopUp/NewFunctionPopUp.js
  src/elements/NewFunctionPopUp/newFuctionPopUp.util.js
  src/elements/NewFunctionPopUp/newFunctionPopUp.scss
  src/elements/VolumesTable/volumesTable.scss
  src/reducers/functionReducer.js
  src/scss/mixins.scss
Labels: enhancement

#800 [Functions] Error on editing functions of type job
  src/components/FunctionsPanel/FunctionsPanel.js
Labels: bug

#795 [Job Panel] Volumes not reflected properly
  src/common/ActionsMenu/ActionsMenu.js
  src/components/FunctionsPage/Functions.js
Labels: bug

#796 [Features] Endless scroll down
  src/components/DetailsInfo/detailsInfo.scss
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.scss
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/Files.js
  src/components/Files/files.util.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functions.util.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/components/Table/Table.js
  src/components/Table/table.scss
  src/elements/FeaturesTablePanel/FeatureTablePanleRow/FeaturesTablePanelRow.js
  src/elements/FeaturesTablePanel/FeatureTablePanleRow/featuresTablePanelRow.scss
  src/elements/FeaturesTablePanel/featuresTablePanel.scss
  src/elements/JobsTableRow/JobsTableRow.js
  src/layout/Content/content.scss
  src/scss/mixins.scss
  src/utils/createArtifactsContent.js
  src/utils/createFeatureStoreContent.js
  src/utils/createFunctionsContent.js
  src/utils/createJobsContent.js
  src/utils/generateTableContent.js
Labels: bug

#797 [General] Can't open actions menu for the last table item
  src/common/ActionsMenu/ActionsMenu.js
  src/common/ActionsMenu/actionsMenu.scss
Labels: bug

#799 [Breadcrumbs] Wrong projects list after erasing search value
  src/common/Breadcrumbs/Breadcrumbs.js
  src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js
Labels: bug

#802 [Project Overview] Source URL disappears on page reload
  src/actions/projects.js
  src/components/Project/Project.js
  src/components/Project/ProjectSource/ProjectSource.js
  src/constants.js
  src/reducers/projectReducer.js
Labels: bug

#803 [Function panel] Pre-populate Resulting Image
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/elements/FunctionsPanelCode/FunctionsPanelCode.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneral.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js
  src/elements/FunctionsPanelGeneral/functionsPanelGeneral.scss
  src/elements/NewFunctionPopUp/NewFunctionPopUp.js
  src/elements/NewFunctionPopUp/newFunctionPopUp.scss
Labels: enhancement

#801 [General] Tooltip text might get unexpectedly wrapped
  src/common/Tooltip/Tooltip.js
  src/elements/TooltipTemplate/TextTooltipTemplate.js
  src/elements/TooltipTemplate/textTooltipTemplate.scss
Labels: bug

#798 [Project Overview] Add "Feature set" to "Create New" button
  src/components/CreateJobPage/CreateJobPage.js
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FunctionsPage/Functions.js
  src/components/Project/Project.js
  src/components/Project/ProjectSource/ProjectSource.js
  src/components/Project/ProjectView.js
  src/components/Project/project.utils.js
  src/components/ProjectsPage/ProjectsView.js
  src/layout/Content/Content.js
  src/layout/Page/PageView.js
Labels: enhancement

#807 Impl [Project Overview] Owner and Members: Add missing CSS class
  src/components/Project/ProjectView.js
Labels: bug

#805 [General] View YAML modal begins not from the start
  src/common/PopUpDialog/PopUpDialog.js
  src/common/PopUpDialog/popUpDialog.scss
  src/common/YamlModal/YamlModal.js
  src/common/YamlModal/yamlmodal.scss
  src/components/ArtifactsPreview/artifactsPreview.scss
  src/components/ProjectsPage/CreateProjectDialog/createProjectDialog.scss
  src/components/ProjectsPage/ProjectsView.js
  src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
  src/elements/AddToFeatureVectorPopUp/addToFeatureVectorPopUp.scss
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
  src/elements/DeployModelPopUp/DeployModelPopUp.js
  src/elements/MembersPopUp/MembersPopUp.js
  src/elements/PreviewModal/PreviewModal.js
  src/elements/PreviewModal/previewModal.scss
  src/layout/Content/Content.js
  src/scss/main.scss
Labels: bug

#808 [Functions] Error when failed to fetch functions
  src/components/FunctionsPage/Functions.js
Labels: bug

#809 [Jobs] Status filter: unaligned option labels
  src/scss/main.scss
Labels: bug

#811 [Jobs] Error when failed to fetch jobs
  src/actions/jobs.js
  src/components/JobsPage/Jobs.js
Labels: bug

#812 [Jobs] Error when grouping by workflows
  src/components/JobsPage/jobsData.js
  src/components/Table/Table.js
Labels: bug

#813 [Features] Remove tooltip for hidden element
  src/elements/FeaturesTablePanel/FeatureTablePanleRow/FeaturesTablePanelRow.js
  src/elements/FeaturesTablePanel/FeaturesTablePanel.js
Labels: bug

#814 [General] Row is not collapsed on filter change
  src/components/FilterMenu/FilterMenu.js
Labels: bug

#815 [Project] Project data overflows container
  src/components/Project/ProjectView.js
  src/components/Project/project.scss
Labels: bug

#810 [Features] List all entities
  src/common/ChipCell/ChipCell.js
  src/common/ChipCell/SizeChips.js
  src/components/FeatureStore/featureStore.util.js
  src/utils/createFeatureStoreContent.js
Labels: enhancement

#816 [Feature Sets] Add Tag filter and lazy-load nested rows
  src/actions/featureStore.js
  src/api/featureStore-api.js
  src/common/TagFilter/TagFilter.js
  src/common/TagFilter/tagFilter.scss
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
  src/components/FilterMenu/FilterMenu.js
  src/constants.js
  src/reducers/featureStoreReducer.js
  src/utils/generateUsageSnippets.js
Labels: enhancement

#817 [Models] Different height of the table header
  src/components/Table/table.scss
Labels: bug

#818 [General] Tooltip text with dashes may be wrapped incorrectly
  src/elements/TooltipTemplate/TextTooltipTemplate.js
  src/elements/TooltipTemplate/textTooltipTemplate.scss
Labels: bug

#824 Impl [e2e-tests] Sprint 127
  package.json
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common-tools/common-tools.js
  tests/features/common/actions/common.action.js
  tests/features/common/actions/dropdown.action.js
  tests/features/common/actions/input-group.action.js
  tests/features/common/actions/input-with-autocomplete.action.js
  tests/features/common/actions/radio-button.action.js
  tests/features/common/actions/tab-selector.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/components/combo-box.component.js
  tests/features/common/components/single-date-picker.component.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/ml-functions.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/backend_synchronizator.py
  tests/mockServer/mock.js
Labels: tests

#825 Impl [Projects] Move to new project summaries endpoint
  src/actions/projects.js
  src/api/projects-api.js
Labels: enhancement

#820 [Function panel] Added auto-mount option to new functions
  src/actions/functions.js
  src/constants.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
  src/elements/FunctionsPanelResources/functionsPanelResources.scss
  src/elements/FunctionsPanelResources/functionsPanelResources.util.js
  src/reducers/functionReducer.js
Labels: enhancement

#819 [Models] Sources overflows container in Details pane
  src/components/ArtifactInfoSources/ArtifactInfoSources.js
  src/components/ArtifactInfoSources/artifactInfoSources.scss
Labels: bug

#823 [Job panel] JSON parameter values not parsed properly
  src/utils/object.js
Labels: bug

#826 [General] Almost all tooltips do not show on hover
  src/common/Tip/Tip.js
  src/common/Tip/tip.scss
Labels: bug

#822 [Feature Store][Models][Files] Unexpected redirect on Details panel close
  src/components/Details/Details.js
  src/components/Details/DetailsView.js
  src/components/JobsPage/Jobs.js
  src/components/Workflow/Workflow.js
Labels: bug

#827 [Function panel] Topology: missing discard button
  src/common/KeyValueTable/KeyValueTable.js
  src/common/KeyValueTable/KeyValueTableView.js
  src/common/RangeInput/RangeInput.js
  src/elements/EditableVolumesRow/EditableVolumesRow.js
  src/elements/FunctionPanelTopologyModelTable/AddRouteRow.js
  src/elements/FunctionPanelTopologyModelTable/EditableRouteRow.js
  src/elements/FunctionPanelTopologyModelTable/FunctionPanelTopologyModelTable.js
  src/elements/FunctionPanelTopologyModelTable/FunctionPanelTopologyModelTableView.js
  src/elements/FunctionPanelTopologyModelTable/functionPanelTopologyModelTable.scss
  src/elements/FunctionPanelTopologyModelTable/functionPanelTopologyModelTable.util.js
  src/elements/FunctionsPanelParameters/AddFunctionParameterRow.js
  src/elements/FunctionsPanelParameters/EditableFunctionParameterRow.js
  src/elements/FunctionsPanelParameters/FunctionsPanelParameters.js
  src/elements/FunctionsPanelParameters/FunctionsPanelParametersView.js
  src/elements/FunctionsPanelParameters/functionsPanelParameters.util.js
Labels: bug

#828 [Data Inputs] V3IO: Fixed leading slash
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.util.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
  src/constants.js
  src/utils/panelPathScheme.js
Labels: enhancement
