Repository mlrun/ui, pull requests merged in 2021-08, with the labels that each got.

#711 Impl [General] Reduce vertical spacing
  src/components/DetailsInfo/detailsInfo.scss
  src/components/Table/table.scss
  src/elements/JobsPanelTable/jobsPanelTable.scss
  src/layout/Content/content.scss
  src/scss/mixins.scss
Labels: enhancement

#703 [General] Expand button has wrong tooltip
  src/layout/Content/Content.js
Labels: bug

#705 [Jobs panel] Can't edit parameter type and value type
  src/elements/EditableParametersRow/EditableParametersRow.js
Labels: bug

#706 [Feature set panel] Missing validation for name
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitle.js
Labels: bug

#712 Fix [Feature set panel] Missing validation for name
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitle.js
Labels: bug

#713 Impl [General] Reduce vertical spacing
  src/components/DetailsInfo/detailsInfo.scss
  src/components/Table/table.scss
  src/elements/JobsPanelTable/jobsPanelTable.scss
  src/layout/Content/content.scss
  src/scss/mixins.scss
Labels: enhancement

#709 [Create new Job panel] App crashes on adding empty secret
  src/components/JobsPanelAdvanced/JobsPanelAdvanced.js
  src/components/JobsPanelAdvanced/jobsPanelAdvanced.util.js
  src/elements/EditableAdvancedRow/EditableAdvancedRow.js
  src/elements/JobsPanelParametersTable/JobsPanelParametersTableView.js
  src/elements/JobsPanelTable/JobsPanelTable.js
  src/elements/JobsPanelTable/JobsPanelTableView.js
  src/elements/JobsPanelTableRow/JobsPanelTableRow.js
  src/utils/string.js
Labels: bug

#707 [Function panel] Cannot add env vars on edit function
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/elements/FunctionsPanelEnvironmentVariables/FunctionsPanelEnvironmentVariables.js
Labels: bug

#714 Fix [Functions] Overview: Code Origin value missing
  src/components/Details/details.util.js
Labels: bug

#715 Fix [Functions] Overview: Code Origin value missing
  src/components/Details/details.util.js
Labels: bug

#710 [Features] List entities too
  src/actions/artifacts.js
  src/actions/featureStore.js
  src/api/featureStore-api.js
  src/components/Artifacts/Artifacts.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/Files.js
  src/components/FunctionsPage/Functions.js
  src/components/JobsPage/Jobs.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/constants.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/FeatureStoreTableRow/FeatureStoreTableRow.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/layout/Content/Content.js
  src/layout/Content/content.util.js
  src/reducers/artifactReducer.js
  src/reducers/featureStoreReducer.js
  src/utils/createArtifactsContent.js
  src/utils/createFeatureStoreContent.js
  src/utils/createFunctionsContent.js
  src/utils/createJobsContent.js
  src/utils/generateArtifacts.js
  src/utils/getUniqueIdentifier.js
  src/utils/parseFeatureSets.js
  src/utils/parseFeatureVectors.js
  src/utils/parseFeatures.js
Labels: enhancement

#716 Fix [Function panel] Cannot add env vars on edit function
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/elements/FunctionsPanelEnvironmentVariables/FunctionsPanelEnvironmentVariables.js
Labels: bug

#717 Impl [Project Members] Reword tooltip (users -> members)
  src/elements/MembersPopUp/MembersPopUp.js
Labels: enhancement

#718 [Job panel][Function panel] Volumes: missing delete action
  src/components/CreateJobPage/CreateJobPage.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanelResources/JobsPanelResources.js
  src/constants.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelResources/functionsPanelResources.util.js
  src/elements/VolumesTable/VolumesTable.js
Labels: bug

#719 Fix [Job panel][Function panel] Volumes: missing delete action
  src/components/CreateJobPage/CreateJobPage.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanelResources/JobsPanelResources.js
  src/constants.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelResources/functionsPanelResources.util.js
  src/elements/VolumesTable/VolumesTable.js
Labels: bug

#720 [Notification] Moved to bottom-right corner
  src/common/Notification/Notification.js
Labels: enhancement

#721 Impl [Functions] Show "Edit" action in demo only
  src/components/FunctionsPage/Functions.js
Labels: enhancement

#724 Impl [Fucntions] Show "Edit" action for kind Local
  src/components/FunctionsPage/Functions.js
Labels: enhancement

#723 [Feature sets] Refresh doesn't show notification with changes on Details
  src/components/Details/DetailsView.js
  src/components/FeatureStore/featureStore.util.js
Labels: bug

#725 [Chips] After removing a chip, the next one becomes active
  src/common/Chip/Chip.js
  src/common/ChipCell/ChipCell.js
  src/common/ChipForm/ChipForm.js
  src/common/ChipForm/chipForm.scss
Labels: bug

#726 [Feature vectors] Statistics: added Histogram
  src/components/DetailsStatistics/detailsStatistics.util.js
Labels: enhancement

#727 [Functions] Hide Run action when not in Ready state
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functions.util.js
Labels: enhancement

#722 [Function] Status wrong or not updated
  src/components/Details/DetailsView.js
  src/components/Details/details.util.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functions.util.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/scss/main.scss
  src/utils/getState.js
Labels: bug

#728 [Functions] Renamed "Logs" tab header to "Build Log"
  src/components/Artifacts/Artifacts.js
  src/components/Artifacts/artifactsData.json
  src/components/Details/Details.js
  src/components/Details/DetailsView.js
  src/components/Details/details.util.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/files.util.js
  src/components/FunctionsPage/functions.util.js
  src/components/JobsPage/jobsData.js
  src/components/Models/models.util.js
  src/constants.js
  src/elements/DetailsMenuItem/DetailsMenuItem.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/elements/TableProducerCell/TableProducerCell.js
  src/utils/isDetailsTabExists.js
Labels: enhancement

#729 [Function panel] Volumes: wrong field name
  src/elements/EditableVolumesRow/EditableVolumesRow.js
  src/elements/VolumesTable/VolumesTable.js
  src/elements/VolumesTable/VolumesTableView.js
  src/elements/VolumesTable/volumesTable.util.js
  src/utils/createNewVolume.js
  src/utils/panelResources.util.js
Labels: bug

#730 [Functions] Hide Edit action when not in Ready state
  src/components/FunctionsPage/Functions.js
Labels: enhancement

#704 [Feature set panel] Entities have space in their name
  src/components/FeatureSetsPanel/FeatureSetsPanelSchema/FeatureSetsPanelSchema.js
  src/components/FeatureSetsPanel/FeatureSetsPanelSchemaTable/FeatureSetsPanelSchemaTable.js
Labels: bug

#732 Impl [e2e-tests] Sprint 125
  package.json
  tests/features/common-tools/common-consts.js
  tests/features/common-tools/common-tools.js
  tests/features/common/actions/common.action.js
  tests/features/common/actions/input-group.action.js
  tests/features/common/actions/number-input-group.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/components/label.component.js
  tests/features/common/components/number-input-group.component.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/step-definitions/steps.js
Labels: tests

#733 [Breadcrumbs] Remove smaller levels
  src/common/Breadcrumbs/Breadcrumbs.js
Labels: enhancement

#734 [Function panel] Description not properly loaded on edit
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneral.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/types.js
Labels: bug

#735 [Function panel][Job panel] Volumes: all fields mandatory
  src/elements/EditableVolumesRow/EditableVolumesRow.js
  src/elements/VolumesTable/VolumesTable.js
  src/elements/VolumesTable/VolumesTableView.js
Labels: enhancement

#736 [Volumes] Added uniqueness validity for path
  src/elements/EditableVolumesRow/EditableVolumesRow.js
  src/elements/VolumesTable/VolumesTable.js
  src/elements/VolumesTable/VolumesTableView.js
  src/elements/VolumesTable/volumesTable.util.js
Labels: enhancement

#737 Fix [Model Endpoints] Error when an item has model_uri of null
  src/utils/parseUri.js
Labels: bug

#741 Impl [Model Endpoints] Remove accuracy, add Function, reorder
  src/api/artifacts-api.js
  src/components/Details/details.util.js
  src/components/Models/models.util.js
  src/utils/createArtifactsContent.js
Labels: enhancement

#739 [Feature vectors] Change the label_feature on editing the feature
  src/components/Details/details.util.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
Labels: bug

#740 [Function panel] Handler: remove default value, add tooltip
  src/elements/FunctionsPanelCode/FunctionsPanelCode.js
  src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
  src/elements/FunctionsPanelCode/functionsPanelCode.util.js
Labels: enhancement

#743 Fix [Model Endpoints] Version: Router not displayed for routers
  src/utils/createArtifactsContent.js
Labels: bug

#745 [Functions] Show Edit for Created state
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functions.util.js
Labels: enhancement

#746 Impl [Feature set panel] Source: Reword description
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.scss
Labels: enhancement

#744 [Model Endpoints] Retrieve average latency
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/components/Models/models.util.js
Labels: enhancement

#748 [Model Endpoints] Details: View YAML not working
  src/actions/artifacts.js
  src/components/Models/models.util.js
  src/utils/generateModelEndpoints.js
Labels: bug

#749 merged changes[Models] Unexpected redirection to Models from Endpoints
  src/common/Breadcrumbs/Breadcrumbs.js
  src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js
Labels: bug

#750 Impl [Model Endpoints] Populate "Average Latency" column
  src/utils/createArtifactsContent.js
Labels: enhancement

#751 Impl [Functions] Show "Edit" action on demo mode only
  src/components/FunctionsPage/Functions.js
Labels: bug

#752 [Job Panel] Stuck when function resources not empty
  src/components/JobsPanel/JobsPanel.js
Labels: bug

#753 [Volumes] Made Container Name and Resource Path optional
  src/elements/EditableVolumesRow/EditableVolumesRow.js
  src/elements/VolumesTable/VolumesTable.js
  src/elements/VolumesTable/VolumesTableView.js
Labels: enhancement

#764 [Functions] First row Name cell is clipped on expand
  src/components/Table/table.scss
Labels: bug

#765 [Feature sets][Feature vectors] Histograms: added min/max
  src/components/DetailsStatistics/DetailsStatistics.js
  src/scss/mixins.scss
Labels: enhancement

#763 [Resources] Add validation and grow width
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanelResources/JobsPanelResources.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/components/JobsPanelResources/jobsPanelResources.util.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
  src/elements/FunctionsPanelResources/functionsPanelResources.scss
  src/elements/FunctionsPanelResources/functionsPanelResources.util.js
Labels: enhancement

#766 [General] Improve new item creation experience
  src/common/KeyValueTable/KeyValueTable.js
  src/common/KeyValueTable/KeyValueTableView.js
  src/common/KeyValueTable/keyValueTable.scss
  src/components/JobsPanelAdvanced/JobsPanelAdvanced.js
  src/components/JobsPanelAdvanced/JobsPanelAdvancedView.js
  src/components/JobsPanelAdvanced/jobsPanelAdvanced.util.js
  src/components/JobsPanelAdvanced/jobsPanelAdvancedReducer.js
  src/components/JobsPanelParameters/JobsPanelParametersView.js
  src/elements/EditableAdvancedRow/EditableAdvancedRow.js
  src/elements/EditableDataInputsRow/EditableDataInputsRow.js
  src/elements/EditableDataInputsRow/EditableDataInputsRow.utils.js
  src/elements/FunctionsPanelEnvironmentVariables/FunctionsPanelEnvironmentVariablesView.js
  src/elements/JobsPanelAdvancedTable/JobsPanelAdvancedTable.js
  src/elements/JobsPanelTable/JobsPanelTable.js
  src/elements/JobsPanelTable/JobsPanelTableView.js
  src/elements/JobsPanelTableRow/JobsPanelTableRow.js
  src/elements/VolumesTable/VolumesTable.js
  src/elements/VolumesTable/VolumesTableView.js
  src/scss/mixins.scss
Labels: enhancement

#767 [Function panel] Disable name and tag on edit
  src/common/Input/Input.js
  src/common/Input/input.scss
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneral.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js
Labels: enhancement

#769 [General] Chips pop-over is cropped
  src/utils/getFirstScrollableParent.js
Labels: bug

#772 [Function panel] Can't empty Build Commands
  src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
  src/utils/string.js
Labels: bug

#773 [Function panel] Confirm overwrite when name already exists
  src/actions/functions.js
  src/api/functions-api.js
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/FunctionsPanel/FunctionsPanelView.js
Labels: enhancement

#774 Impl [Functions] Show "Edit" action for error state
  src/components/FunctionsPage/functions.util.js
Labels: enhancement

#770 [Models][Files][Datasets] Selected item is not highlighted
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
Labels: bug
