Repository mlrun/ui, pull requests merged in 2021-04, with the labels that each got.

#483 Fix [Project] Register file: wrong redirection and heading
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/Files.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/components/Project/project.utils.js
  src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
  src/utils/handleArtifactTreeFilterChange.js
Labels: bug

#485 [Projects] Cancel pending requests on leaving screen
  src/actions/projects.js
  src/api/projects-api.js
  src/elements/ProjectCard/ProjectCard.js
Labels: enhancement

#480 [Jobs] Monitor: Rename “Rerun” to “Re-run”
  src/components/JobsPage/jobsData.js
Labels: enhancement

#467 [General] Chip with count has redundant tooltip
  src/common/ChipCell/ChipCellView.js
Labels: bug

#484 [Project] Avoid having ellipsis on counter label
  src/components/Project/project.scss
  src/components/ProjectTable/projectTable.scss
  src/elements/ProjectDataCard/ProjectDataCard.js
  src/elements/ProjectJobs/projectJobs.utils.js
  src/elements/ProjectStatistics/projectStatistics.scss
  src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.js
Labels: enhancement

#482 [Create Job] Dropdown options overlap
  src/components/CreateJobPage/createJobPage.scss
  src/elements/SelectOption/SelectOption.js
Labels: bug

#486 [Projects] Reduce number of requests per project
  src/actions/projects.js
  src/api/projects-api.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/constants.js
  src/elements/ProjectCard/ProjectCard.js
  src/elements/ProjectCard/projectCard.util.js
  src/reducers/projectReducer.js
Labels: enhancement

#487 [Projects] Counters are 0 before loaders are shown
  src/elements/ProjectCard/projectCard.util.js
Labels: bug

#491 Fix [Create Job][Functions] Fails on not-yet deployed functions
  src/components/FunctionsPage/Functions.js
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#490 Fix [Jobs] Monitor: disabled "Monitoring" action still opens link
  src/components/JobsPage/jobsData.js
Labels: bug

#493 [Projects] Create new project: buttons distorted
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
  src/components/ProjectsPage/CreateProjectDialog/createProjectDialog.scss
Labels: bug

#494 [Projects] Create new project: submitted on invalid input
  src/common/Button/Button.js
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
Labels: bug

#492 [Breadcrumbs] Request names only; Do not request on Projects
  src/actions/projects.js
  src/api/projects-api.js
  src/common/Breadcrumbs/Breadcrumbs.js
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/constants.js
  src/reducers/projectReducer.js
Labels: enhancement

#459 [Jobs] Monitor: added "Abort" action
  src/actions/jobs.js
  src/api/jobs-api.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
Labels: enhancement

#495 [Feature store][Jobs] Retain selected tab on switching items
  src/components/DetailsPreview/DetailsPreview.js
  src/components/DetailsTransformations/DetailsTransformations.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/utils/createArtifactsContent.js
  src/utils/createJobsContent.js
  src/utils/generateLinkToDetailsPanel.js
Labels: enhancement

#479 [General] Move "Copy URI" from action menu to an icon button
  src/common/TableActionsMenu/TableActionsMenu.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/files.util.js
  src/components/Models/models.util.js
  src/elements/TableCell/TableCell.js
  src/images/ic_copy-to-clipboard.svg
  src/utils/createArtifactsContent.js
Labels: enhancement

#488 [Create Job] Inconsistent card height
  src/components/CreateJobPage/CreateJobPageView.js
  src/components/CreateJobPage/createJobPage.scss
  src/elements/CreateJobCardTemplate/CreateJobCardTemplate.js
  src/elements/CreateJobCardTemplate/createJobCardTemplate.scss
Labels: bug

#466 [Models][Datasets][Files] Tree filter: populated dropdown
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/components/ArtifactsFilterTree/ArtifactsFilterTree.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/Files.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FilterMenu/filterMenu.settings.js
  src/components/Models/Models.js
  src/utils/handleArtifactTreeFilterChange.js
Labels: enhancement

#496 [Functions] Added "Run" action to run the function in a job
  src/components/FunctionsPage/Functions.js
  src/components/JobsPanel/JobsPanel.js
Labels: enhancement

#497 [Jobs] Filter by start time
  .storybook/preview.js
  src/actions/jobs.js
  src/api/jobs-api.js
  src/common/Button/button.scss
  src/common/DatePicker/DatePicker.js
  src/common/DatePicker/DatePicker.stories.js
  src/common/DatePicker/DatePickerView.js
  src/common/DatePicker/datePicker.scss
  src/common/DatePicker/datePickerReducer.js
  src/components/ArtifactsFilterTree/ArtifactsFilterTree.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FilterMenu/filterMenu.scss
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/components/Project/Project.js
  src/components/ProjectTable/projectTable.scss
  src/components/ScheduleJob/ScheduleJob.js
  src/components/ScheduleJobSimple/ScheduleJobSimple.js
  src/constants.js
  src/elements/ScheduleRecurring/ScheduleRecurring.js
  src/scss/borders.scss
  src/utils/createAutoCorrectedDatePipe.js
  src/utils/datePicker.util.js
Labels: enhancement

#498 [Jobs] Re-run: Added job panel for editing
  src/components/JobsPage/Jobs.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/Table/Table.js
  src/utils/createJobsContent.js
  src/utils/generateTableContent.js
Labels: enhancement

#500 Cleanup [Jobs] Remove redundant code for hiding actions
  src/elements/JobsTableRow/JobsTableRow.js
Labels: Cleanup

#502 Fix [Models][Datasets][Files] Wrong key and iter delimiter in URI
  src/utils/generateUri.js
Labels: bug

#501 [Jobs] Monitor: add count of pending pods
  src/actions/details.js
  src/api/details-api.js
  src/components/Details/Details.js
  src/components/Details/DetailsView.js
  src/components/Details/details.scss
  src/components/JobsPage/Jobs.js
  src/constants.js
  src/reducers/detailsReducer.js
  src/reducers/reducers.js
  src/utils/generatePods.js
Labels: enhancement

#503 [Functions] Hide "Run" action for failed functions
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functions.util.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
Labels: enhancement

#499 [Model endpoints] Add "Drift analysis" tab
  src/actions/details.js
  src/api/details-api.js
  src/components/Details/Details.js
  src/components/Details/details.util.js
  src/components/DetailsDriftAnalysis/DetailsDriftAnalysis.js
  src/components/DetailsDriftAnalysis/detailsDriftAnalysis.scss
  src/components/DetailsDriftAnalysis/detailsDriftAnalysis.util.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/constants.js
  src/reducers/detailsReducer.js
Labels: enhancement

#504 [Model endpoints] Error on entering tab after selecting model
  src/actions/details.js
  src/components/Details/Details.js
  src/components/Details/details.util.js
  src/components/DetailsDriftAnalysis/DetailsDriftAnalysis.js
  src/components/DetailsDriftAnalysis/detailsDriftAnalysis.scss
  src/components/DetailsDriftAnalysis/detailsDriftAnalysis.util.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/reducers/detailsReducer.js
Labels: Cleanup, bug

#506 [Model endpoints] Add "Features analysis" tab
  src/components/Details/details.util.js
  src/components/DetailsFeaturesAnalysis/DetailsFeaturesAnalysis.js
  src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.scss
  src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.util.js
  src/components/DetailsStatistics/DetailsStatistics.js
  src/components/DetailsStatistics/detailsStatistics.util.js
  src/components/Models/models.util.js
  src/constants.js
  src/reducers/detailsReducer.js
  src/utils/getHistogramChartConfig.js
Labels: enhancement

#508 [Feature Store] Crashes on expanding feature sets
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
Labels: bug

#509 Impl [e2e-tests] Add e2e-tests infra + project scripts
  .gitignore
  package.json
  scripts/testui.js
  tests/config.js
  tests/features/common-tools/common-tools.js
  tests/features/common/actions/action-menu.action.js
  tests/features/common/actions/common.action.js
  tests/features/common/actions/dropdown.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/components/action-menu.component.js
  tests/features/common/components/dropdown.component.js
  tests/features/common/components/table.component.js
  tests/features/common/page-objects.js
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
  tests/features/support/hooks.js
  tests/features/support/world.js
  tests/report.js
Labels: tests

#512 Fix [Feature vectors] Preview: error when preview is empty
  src/utils/getArtifactPreview.js
Labels: bug

#513 [Feature Vectors] Requested features: remove and edit alias
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/components/Details/Details.js
  src/components/Details/DetailsView.js
  src/components/Details/details.util.js
  src/components/Details/detailsReducer.js
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
  src/components/DetailsRequestedFeatures/detailsRequestedFeatures.scss
  src/components/DetailsRequestedFeatures/detailsRequestedFeatures.utils.js
  src/components/DetailsRequestedFeatures/detailsRequestedFeaturesReducer.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
Labels: enhancement

#515 Fix [Model Endpoints] Drift and Feature analysis tabs break on nulls
  src/components/DetailsDriftAnalysis/detailsDriftAnalysis.util.js
  src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.util.js
Labels: bug

#516 [Jobs] Monitor: initially filter to last 24 hours
  src/components/FilterMenu/FilterMenu.js
  src/components/JobsPage/Jobs.js
Labels: enhancement

#514 [Features] Add features to feature vector
  src/actions/artifacts.js
  src/actions/table.js
  src/api/artifacts-api.js
  src/common/Breadcrumbs/Breadcrumbs.js
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/common/Input/Input.js
  src/common/Input/input.scss
  src/common/Loader/loader.scss
  src/common/PopUpDialog/popUpDialog.scss
  src/common/Select/Select.js
  src/common/Select/select.scss
  src/common/Tip/Tip.js
  src/common/Tip/tip.scss
  src/common/Tooltip/tooltip.scss
  src/components/Details/details.scss
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
  src/components/FilterMenu/FilterMenu.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/components/Project/Project.js
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/constants.js
  src/elements/AddFeatureButton/AddFeatureButton.js
  src/elements/AddFeatureButton/addFeatureButton.scss
  src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
  src/elements/AddToFeatureVectorPopUp/addToFeatureVectorPopUp.scss
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
  src/elements/CreateFeatureVectorPopUp/createFeatureVectorPopUp.scss
  src/elements/FeaturesTablePanel/FeatureTablePanleRow/FeaturesTablePanelRow.js
  src/elements/FeaturesTablePanel/FeatureTablePanleRow/featuresTablePanelRow.scss
  src/elements/FeaturesTablePanel/FeaturesTablePanel.js
  src/elements/FeaturesTablePanel/featuresTablePanel.scss
  src/elements/TableCell/TableCell.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/elements/TooltipTemplate/textTooltipTemplate.scss
  src/images/add-circle-question.svg
  src/images/add-circle.svg
  src/images/ic_target-with-arrow-unset.svg
  src/layout/Content/Content.js
  src/layout/Page/PageView.js
  src/reducers/reducers.js
  src/reducers/tableReducer.js
  src/scss/main.scss
  src/scss/shadows.scss
  src/utils/createArtifactsContent.js
  src/utils/generateTableContent.js
  src/utils/object.js
  src/utils/parseFeatureTemplate.js
  src/utils/projects.js
Labels: enhancement

#518 Fix [Create job] GPU: label overflows value; Error on empty values
  src/common/Input/Input.js
  src/common/RangeInput/RangeInput.js
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#517 [Project Overview] Count aborted jobs in Failed counter
  src/elements/ProjectJobs/projectJobs.utils.js
Labels: enhancement

#511 [Jobs] Add new Pods tab
  src/components/Details/DetailsView.js
  src/components/Details/details.util.js
  src/components/DetailsPods/DetailsPods.js
  src/components/DetailsPods/detailsPods.scss
  src/components/DetailsPods/detailsPods.util.js
  src/components/JobsPage/jobsData.js
  src/components/Table/TableView.js
  src/constants.js
Labels: enhancement

#520 [Features] Add tooltips to icon buttons
  src/elements/FeaturesTablePanel/FeatureTablePanleRow/FeaturesTablePanelRow.js
Labels: enhancement

#519 [Projects] Counter loaders in front of dialog
  src/common/Loader/loader.scss
  src/common/PopUpDialog/popUpDialog.scss
Labels: bug

#521 [Feature sets] Sidebar: Wrong feature set is marked as selected
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/utils/generateGroupLatestItem.js
Labels: bug

#522 [Jobs] Status filter: add Pending option
  src/actions/jobs.js
  src/api/jobs-api.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FilterMenu/filterMenu.settings.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/layout/Content/Content.js
Labels: enhancement

#523 Impl [General] Reword success/failure notification texts
  src/common/Download/Download.js
  src/components/FeatureStore/featureStore.util.js
  src/components/JobsPage/Jobs.js
Labels: enhancement

#524 [Jobs] Monitor: Add predefined options to Start From filter
  src/common/DatePicker/DatePicker.js
  src/common/DatePicker/DatePickerView.js
  src/common/DatePicker/datePicker.scss
  src/common/Select/select.scss
  src/components/FilterMenu/FilterMenu.js
  src/elements/SelectOption/SelectOption.js
  src/elements/SelectOption/selectOption.scss
  src/utils/datePicker.util.js
Labels: enhancement

#525 [Feature sets] New feature set: added Start Ingestion button
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/common/Input/Input.js
  src/common/RadioButtons/RadioButtons.js
  src/common/RadioButtons/radioButtons.scss
  src/components/DetailsMetadata/DetailsMetadata.js
  src/components/DetailsMetadata/detailsMetadata.util.js
  src/components/DetailsTransformations/DetailsTransformations.js
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureSetsPanel/FeatureSetsPanelSchema/featureSetPanelSchema.util.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTransformations/FeatureSetsPanelTransformations.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTransformations/FeatureSetsPanelTransformationsView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTransformations/featureSetsPanelTransformations.scss
  src/components/FeatureSetsPanel/FeatureSetsPanelTransformations/featureSetsPanelTransformations.util.js
  src/components/FeatureSetsPanel/FeatureSetsPanelView.js
  src/components/FeatureSetsPanel/featureSetsPanel.scss
  src/components/FeatureSetsPanel/featureSetsPanel.util.js
  src/components/FeatureStore/FeatureStore.js
  src/constants.js
  src/images/db-icon.svg
  src/reducers/artifactReducer.js
  src/setupProxy.js
Labels: enhancement

#526 Impl [Data inputs] Store: Remove duplicate item names
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
Labels: bug

#527 [Models] Preview does not show extra data
  src/api/artifacts-api.js
  src/common/Download/Download.js
  src/components/Details/DetailsView.js
  src/components/DetailsAnalysis/DetailsAnalysis.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsPreview/DetailsPreview.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/elements/TableCell/TableCell.js
  src/utils/createArtifactPreviewContent.js
  src/utils/generateArtifactPreviewData.js
  src/utils/generateArtifacts.js
  src/utils/getArtifactPreview.js
Labels: bug

#528 [Jobs] Fixed bug on Artifacts preview
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsArtifacts/detailsArtifacts.util.js
Labels: bug
