Repository mlrun/ui, pull requests merged in 2021-10, with the labels that each got.

#832 [Projects] Archived Projects label is cropped
  src/components/ProjectsPage/projects.scss
Labels: bug

#831 [Project Overview] Add Project Settings screen
  src/App.js
  src/actions/projects.js
  src/api/projects-api.js
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/components/Project/Project.js
  src/components/Project/ProjectSource/ProjectSource.js
  src/components/Project/ProjectView.js
  src/components/Project/project.scss
  src/components/ProjectSettings/ProjectSettings.js
  src/components/ProjectSettings/projectSettings.scss
  src/components/ProjectSettings/projectSettings.util.js
  src/constants.js
  src/elements/CreateNewSecretPopUp/CreateNewSecretPopUp.js
  src/elements/CreateNewSecretPopUp/createNewSecretPopUp.scss
  src/elements/ProjectSecretRow/ProjectSecretRow.js
  src/elements/ProjectSecretRow/projectSecretRow.scss
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js
  src/elements/ProjectSettingsGeneral/projectSettingsGeneral.scss
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecrets.js
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecretsView.js
  src/elements/ProjectSettingsSource/ProjectSettingsSource.js
  src/elements/ProjectSettingsSource/projectSettingsSource.scss
  src/reducers/projectReducer.js
Labels: enhancement

#829 [Workflows] Add columns to list view of workflow
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/components/Workflow/Workflow.js
  src/components/Workflow/workflow.scss
  src/components/Workflow/workflow.util.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/layout/Content/Content.js
  src/utils/createJobsContent.js
  src/utils/generateGroupLatestItem.js
  src/utils/generateTableContent.js
Labels: enhancement

#833 [Functions panel] Cannot edit single secret value
  src/common/KeyValueTable/KeyValueTableView.js
  src/common/Select/Select.js
  src/common/Select/select.scss
  src/elements/FunctionsPanelSecrets/FunctionsPanelSecrets.js
Labels: bug

#830 [Jobs] Implement drill-down view on selecting a job
  src/actions/jobs.js
  src/api/jobs-api.js
  src/components/Details/Details.js
  src/components/Details/DetailsView.js
  src/components/Details/details.scss
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/constants.js
  src/reducers/jobReducer.js
  src/utils/parseJob.js
Labels: enhancement

#836 [Feature sets] UI crashes on row expand
  src/components/FeatureStore/featureStore.util.js
Labels: bug

#834 [Job panel][Function panel] Remove Secrets
  src/components/JobsPanelAdvanced/JobsPanelAdvanced.js
  src/components/JobsPanelAdvanced/JobsPanelAdvancedView.js
  src/elements/FunctionsPanelRuntime/FunctionsPanelRuntime.js
  src/elements/FunctionsPanelRuntime/FunctionsPanelRuntimeView.js
Labels: enhancement

#835 [Build] ESLint warnings
  src/components/ProjectSettings/ProjectSettings.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecretsView.js
Labels: Cleanup

#837 [Project Settings] Add General and Secrets tabs
  src/App.js
  src/components/ProjectSettings/ProjectSettings.js
  src/components/ProjectSettings/projectSettings.scss
  src/components/ProjectSettings/projectSettings.util.js
  src/constants.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecrets.js
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecretsView.js
  src/elements/ProjectSettingsSource/ProjectSettingsSource.js
  src/reducers/projectReducer.js
Labels: enhancement

#842 [Feature Sets] Shift "Create" out of demo mode
  src/common/PageActionsMenu/PageActionsMenu.js
  src/components/Artifacts/Artifacts.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/Files.js
  src/components/Files/files.util.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/components/Project/Project.js
  src/components/Project/project.utils.js
  src/components/ProjectsPage/ProjectsView.js
  src/layout/Content/Content.js
Labels: enhancement

#853 [General] Wrong redirection on "MLRun" logo click
  src/layout/Page/Page.js
Labels: bug

#857 [Job panel][Function panel] Added "Auto-generate access key"
  src/actions/featureStore.js
  src/actions/functions.js
  src/actions/jobs.js
  src/api/featureStore-api.js
  src/api/jobs-api.js
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureSetsPanel/FeatureSetsPanelView.js
  src/components/FeatureSetsPanel/featureSetsPanel.scss
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanel/panelReducer.js
  src/components/ScheduleJob/ScheduleJob.js
  src/components/ScheduleJob/ScheduleJobView.js
  src/constants.js
  src/elements/JobsPanelCredentialsAccessKey/JobsPanelCredentialsAccessKey.js
  src/elements/JobsPanelCredentialsAccessKey/jobsPanelCredentialsAccessKey.scss
  src/elements/JobsPanelTitle/JobsPanelTitle.js
  src/elements/PanelCredentialsAccessKey/PanelCredentialsAccessKey.js
  src/elements/PanelCredentialsAccessKey/panelCredentialsAccessKey.scss
  src/reducers/featureStoreReducer.js
  src/reducers/functionReducer.js
  src/reducers/jobReducer.js
  src/utils/parseFunction.js
Labels: enhancement

#855 [Files] UI stuck on entering preview tab with numerous rows
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
Labels: bug

#856 [Jobs] Two loaders exists on entering Details Logs tab
  src/components/DetailsLogs/DetailsLogs.js
  src/reducers/jobReducer.js
Labels: bug

#849 [Function panel] Resources overflows container
  src/components/JobsPanel/jobsPanel.scss
  src/elements/FunctionsPanelResources/functionsPanelResources.scss
Labels: bug

#864 [Functions] Show Edit for serving kind in demo only
  src/components/FunctionsPage/Functions.js
Labels: enhancement

#871 [Models] Error when selecting a model
  src/components/Details/Details.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
Labels: bug

#872 [Project Overview] Filter users selected as owner
  src/api/projects-iguazio-api.js
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
Labels: enhancement

#880 Impl [Project Settings] Parameters: Add description
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js
Labels: enhancement

#883 [Function panel] Empty environment variables list
  src/elements/FunctionsPanelEnvironmentVariables/FunctionsPanelEnvironmentVariables.js
Labels: bug

#887 [Workflows] Skip node with type of DAG
  src/components/Workflow/Workflow.js
Labels: enhancement

#921 Impl [Config] Add `generate-rn` NPM script for release notes
  generate-release-notes.js
  package.json
Labels: enhancement

#922 Impl [Config] `generate-rn`: Clone repo to temp dir
  generate-release-notes.js
  package.json
Labels: enhancement
