Repository mlrun/ui, pull requests merged in 2021-07, with the labels that each got.

#665 Fix [Model Endpoints] Link to model is broken (files --> models)
  src/components/Details/details.util.js
  src/components/FeatureStore/featureStore.util.js
  src/utils/isDetailsTabExists.js
Labels: bug

#667 Fix [Feature sets] Analysis: Breaks on non-string paths
  src/components/DetailsAnalysis/DetailsAnalysis.js
Labels: bug

#668 Impl [e2e-tests] Sprint 124
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/date-picker.action.js
  tests/features/common/actions/dropdown.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/components/date-picker.component.js
  tests/features/common/components/table.component.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
  tests/mockServer/backend_synchronizator.py
  tests/mockServer/mock.js
Labels: tests

#669 [General] Tooltip with long text content has redundant space
  src/common/Tooltip/Tooltip.js
  src/common/Tooltip/tooltip.scss
  src/components/Table/table.scss
  src/elements/TableLinkCell/TableLinkCell.js
  src/elements/TableLinkCell/tableLinkCell.scss
  src/elements/TooltipTemplate/TextTooltipTemplate.js
  src/elements/TooltipTemplate/textTooltipTemplate.scss
Labels: bug

#672 Fix [Feature sets] Overview: no delimiter in entity list
  src/components/Details/details.util.js
Labels: bug

#673 Fix [Feature sets] Preview: boolean values are not displayed
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/ArtifactsPreview/artifactsPreview.scss
Labels: bug

#671 [General] History navigation is blocked
  src/components/Artifacts/Artifacts.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/Files.js
  src/components/FunctionsPage/Functions.js
  src/components/JobsPage/Jobs.js
  src/components/Models/models.util.js
  src/utils/isDetailsTabExists.js
Labels: bug

#670 [Feature sets] Overview: remove Partition Keys field
  src/components/Details/details.util.js
  src/components/FeatureStore/featureStore.util.js
Labels: enhancement

#674 Impl [Features] Re-introduce Validtor column
  src/components/FeatureStore/featureStore.util.js
  src/utils/createArtifactsContent.js
Labels: revert

#675 [Functions] Show status indicator for more states
  src/components/Details/DetailsView.js
  src/components/Details/details.util.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/FeatureStore/featureStore.util.js
  src/components/FunctionsPage/Functions.js
  src/components/JobsPage/Jobs.js
  src/components/JobsPage/jobsData.js
  src/components/Models/models.util.js
  src/elements/SelectOption/selectOption.scss
  src/elements/TableLinkCell/TableLinkCell.js
  src/scss/main.scss
  src/scss/mixins.scss
  src/utils/createJobsContent.js
  src/utils/getState.js
  src/utils/parseFeatureSets.js
  src/utils/parseFeatureStoreDataRequest.js
  src/utils/parseFeatureVectors.js
Labels: enhancement

#676 [Feature sets] Transformations: Collapse sections by default
  src/components/DetailsTransformations/ConfigFunctionTemplate/ConfigFunctionTemplate.js
  src/components/DetailsTransformations/ConfigSource/ConfigSource.js
  src/components/DetailsTransformations/ConfigTargets/ConfigTargets.js
Labels: enhancement

#677 [Feature sets] Overview: hide Relations field
  src/components/ArtifactInfoSources/ArtifactInfoSources.js
  src/components/ArtifactInfoSources/artifactInfoSources.scss
  src/components/ArtifactInfoSources/artifactInfoSources.utils.js
  src/components/Artifacts/artifactsData.json
  src/components/Details/details.util.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/files.util.js
  src/components/Models/models.util.js
Labels: enhancement

#641 Impl [StoryBook] Add styles for mandatory input fields
  src/common/Input/Input.js
  src/common/Input/Input.stories.js
  src/common/Input/input.scss
  src/common/KeyValueTable/KeyValueTable.js
  src/common/KeyValueTable/keyValueTable.scss
  src/common/RangeInput/RangeInput.js
  src/common/RangeInput/RangeInput.stories.js
  src/common/RangeInput/rangeInput.scss
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSourceTable/FeatureSetsPanelDataSourceTable.js
  src/components/FeatureSetsPanel/FeatureSetsPanelSchemaTable/FeatureSetsPanelSchemaTable.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
  src/components/JobsPanelParameters/JobsPanelParametersView.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
  src/elements/EditableAdvancedRow/EditableAdvancedRow.js
  src/elements/EditableDataInputsRow/EditableDataInputsRow.js
  src/elements/EditableParametersRow/EditableParametersRow.js
  src/elements/EditableVolumesRow/EditableVolumesRow.js
  src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
  src/elements/JobsPanelAdvancedTable/JobsPanelAdvancedTable.js
  src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/elements/PartitionFields/PartitionFields.js
  src/elements/RegisterArtifactForm/RegisterArtifactForm.js
  src/elements/ScheduleRecurring/ScheduleRecurring.js
  src/elements/VolumesTable/VolumesTableView.js
  src/images/invalid.svg
  src/scss/mixins.scss
Labels: enhancement

#678 [Functions] Added "Edit" action
  src/actions/functions.js
  src/components/Details/details.util.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/components/JobsPanel/jobsPanel.util.js
  src/constants.js
  src/elements/FunctionsPanelCode/FunctionsPanelCode.js
  src/elements/FunctionsPanelEnvironmentVariables/FunctionsPanelEnvironmentVariables.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneral.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelResources/functionsPanelResources.util.js
  src/elements/FunctionsPanelTitle/FunctionsPanelTitle.js
  src/reducers/functionReducer.js
  src/utils/panelResources.util.js
Labels: enhancement

#679 [Feature sets][Feature vectors] Statistics: add icons
  src/components/DetailsMetadata/DetailsMetadata.js
  src/components/DetailsMetadata/detailsMetadata.scss
  src/components/DetailsMetadata/detailsMetadata.util.js
  src/components/DetailsStatistics/DetailsStatistics.js
  src/components/DetailsStatistics/detailsStatistics.scss
  src/components/DetailsStatistics/detailsStatistics.util.js
  src/scss/mixins.scss
Labels: enhancement

#681 [Projects] Created project has no counters
  src/components/ProjectsPage/Projects.js
Labels: bug

#682 [Feature sets] Overview: Usage example: plant entity
  src/utils/generateUsageSnippets.js
Labels: enhancement

#683 Cleanup [General] parseUri: add jobs and functions to kind list
  src/utils/parseUri.js
Labels: Cleanup

#685 [Feature vectors] Overview: populate Label Column correctly
  src/components/Details/details.util.js
Labels: bug

#684 [Files, Functions] Filters aren't cleared on project change
  src/components/Details/details.util.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functions.util.js
  src/components/JobsPage/jobsData.js
  src/layout/Content/Content.js
  src/reducers/filtersReducer.js
  src/utils/createJobsContent.js
Labels: bug

#686 [Feature sets] Make empty description & labels editable
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfo.scss
  src/elements/DetailsInfoItem/DetailsInfoItem.js
Labels: enhancement

#687 [Feature sets] Transformations: text overflows
  src/components/DetailsTransformations/ConfigFunctionTemplate/ConfigFunctionTemplate.js
  src/components/DetailsTransformations/ConfigSource/ConfigSource.js
  src/components/DetailsTransformations/detailsTransformations.scss
  src/components/DetailsTransformations/detailsTransformations.util.js
Labels: bug

#689 [Details] Tooltip is broken
  src/components/Details/DetailsView.js
  src/components/Details/details.scss
Labels: bug

#690 [Feature sets] Show first two entities instead of one
  src/components/FeatureStore/featureStore.util.js
  src/utils/createFeatureStoreContent.js
Labels: enhancement

#691 [Jobs Panel] Invalid input icon has wrong position
  src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
Labels: bug

#692 [Feature set panel] Various changes
  src/common/CheckBox/checkBox.scss
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelSchema/FeatureSetsPanelSchema.js
  src/components/FeatureSetsPanel/FeatureSetsPanelSchema/FeatureSetsPanelSchemaView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
  src/components/FeatureSetsPanel/FeatureSetsPanelView.js
  src/reducers/featureStoreReducer.js
Labels: enhancement

#693 [Feature Sets] App crashes on Features tab
  src/components/DetailsMetadata/DetailsMetadata.js
Labels: bug

#694 [Project] Add members dialog
  src/actions/projects.js
  src/api/projects-api.js
  src/api/projects-iguazio-api.js
  src/common/Accordion/Accordion.js
  src/common/Button/Button.js
  src/common/Chip/Chip.js
  src/common/Chip/chip.scss
  src/common/ChipCell/ChipCell.js
  src/common/ChipCell/ChipCellView.js
  src/common/ChipCell/chipCell.scss
  src/common/ChipInput/ChipInput.js
  src/common/ChipInput/chipInput.scss
  src/common/Input/Input.js
  src/common/Input/input.scss
  src/common/PopUpDialog/PopUpDialog.js
  src/common/PopUpDialog/popUpDialog.scss
  src/common/Select/Select.js
  src/common/Select/select.scss
  src/components/ArtifactsPreview/artifactsPreview.scss
  src/components/JobsPanelParameters/JobsPanelParameters.js
  src/components/JobsPanelParameters/JobsPanelParametersView.js
  src/components/JobsPanelParameters/jobsPanelParameters.util.js
  src/components/Project/Project.js
  src/components/Project/ProjectView.js
  src/components/Project/project.scss
  src/constants.js
  src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
  src/elements/AddToFeatureVectorPopUp/addToFeatureVectorPopUp.scss
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
  src/elements/ChangeOwnerPopUp/changeOwnerPopUp.scss
  src/elements/EditableParametersRow/EditableParametersRow.js
  src/elements/HiddenChipsBlock/HiddenChipsBlock.js
  src/elements/HiddenChipsBlock/hiddenChipsBlock.scss
  src/elements/JobsPanelParametersTable/JobsPanelParametersTable.js
  src/elements/JobsPanelParametersTable/JobsPanelParametersTableView.js
  src/elements/MembersPopUp/MembersPopUp.js
  src/elements/MembersPopUp/membersPopUp.scss
  src/elements/MembersPopUp/membersPopUp.util.js
  src/elements/MembersPopUp/membersReducer.js
  src/elements/SelectOption/SelectOption.js
  src/elements/SelectOption/selectOption.scss
  src/elements/TableCell/TableCell.js
  src/images/user.svg
  src/images/users.svg
  src/scss/colors.scss
  src/scss/main.scss
  src/types.js
  src/utils/getChipLabelAndValue.js
  src/utils/string.js
Labels: enhancement

#696 [Feature sets] Horizontal scroll on Transformations tab
  src/components/DetailsTransformations/detailsTransformations.scss
Labels: bug

#697 [Feature Sets] Switching to another feature set doesn't close edit mode on Details
  src/common/LoadButton/LoadButton.js
  src/components/Details/Details.js
  src/components/Details/DetailsView.js
  src/components/Details/details.util.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfoReducer.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
  src/components/DetailsRequestedFeatures/detailsRequestedFeaturesReducer.js
  src/components/FeatureStore/featureStore.util.js
Labels: bug

#695 [Projects] Page refresh erases the search value
  src/common/Search/Search.js
  src/components/ProjectsPage/ProjectsView.js
Labels: bug

#700 Impl [e2e-tests] Sprint 124
  tests/features/common-tools/common-consts.js
  tests/features/common-tools/common-tools.js
  tests/features/common/actions/date-picker.action.js
  tests/features/common/actions/dropdown.action.js
  tests/features/common/actions/input-group.action.js
  tests/features/common/actions/input-with-autocomplete.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/components/input-with-autocomplete.component.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
  tests/features/support/hooks.js
  tests/features/support/world.js
  tests/mockServer/backend_synchronizator.py
  tests/mockServer/mock.js
Labels: tests

#699 [Feature set panel] Added resource autocomplete to data source URL
  src/common/Combobox/Combobox.js
  src/common/Combobox/ComboboxView.js
  src/common/Combobox/combobox.scss
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.scss
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.util.js
  src/components/FeatureSetsPanel/FeatureSetsPanelView.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
  src/constants.js
  src/elements/EditableDataInputsRow/EditableDataInputsRow.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
  src/scss/main.scss
  src/utils/panelPathScheme.js
Labels: enhancement

#701 Fix [Functions] Overview: Status shows the word "empty"
  src/utils/getState.js
Labels: bug

#702 Fix [Build] Broken build
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
Labels: bug
