Repository mlrun/ui, pull requests merged in 2021-02, with the labels that each got.

#378 Fix [Create Job] Crashes when adding a new label (Firefox only)
  src/components/ChipForm/ChipForm.js
Labels: bug

#379 [Project Overview] Visual overlap issues
  src/components/Project/project.scss
  src/components/ProjectTable/projectTable.scss
  src/elements/ProjectStatistics/projectStatistics.scss
Labels: bug

#381 Impl [Projects] Hide Delete for default project on enabled Nuclio
  .env
  config.js.tmpl
  nginx/run_nginx
  public/config.js
  src/components/ProjectsPage/projectsData.js
Labels: enhancement

#382 Impl [Projects] Creation pop-up: add name validation tooltip
  src/common/Input/Input.js
  src/common/Input/input.scss
  src/common/Tip/tip.scss
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
Labels: enhancement

#383 [Features] Grouped features by name expand to all versions
  .env
  Dockerfile
  config.js.tmpl
  nginx/nginx.conf.tmpl
  nginx/run_nginx
  public/config.js
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/common/ErrorMessage/ErrorMessage.js
  src/common/Input/Input.js
  src/common/Input/input.scss
  src/common/TableActionsMenu/TableActionsMenu.js
  src/common/Tip/tip.scss
  src/components/ArtifactsFilterTree/ArtifactsFilterTree.js
  src/components/ChipForm/ChipForm.js
  src/components/Details/Details.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/feaureStore.util.js
  src/components/FilterMenu/FilterMenu.js
  src/components/Project/project.scss
  src/components/ProjectTable/projectTable.scss
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projectsData.js
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/constants.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/ProjectStatistics/projectStatistics.scss
  src/layout/Content/Content.js
  src/layout/Content/content.util.js
  src/reducers/artifactReducer.js
  src/utils/createArtifactsContent.js
  src/utils/generateGroupLatestItem.js
  src/utils/parseFeatures.js
Labels: enhancement

#385 [Feature Store] Added some dummy controls
  src/common/PopUpDialog/popUpDialog.scss
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/feaureStore.util.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FilterMenu/filterMenu.scss
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/TableCell/TableCell.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/layout/Content/Content.js
  src/scss/mixins.scss
  src/utils/createArtifactsContent.js
Labels: enhancement

#386 [Feature Vectors] Requested Features: converted to a table
  src/components/Details/details.util.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
  src/components/DetailsRequestedFeatures/detailsRequestedFeatures.scss
Labels: enhancement

#387 Fix [General] Failed to build production build due to console.log
  src/elements/TableCell/TableCell.js
Labels: bug

#388 Impl [Projects] Create project: limit length of Name to 63
  src/common/Input/input.scss
  src/components/ProjectsPage/ProjectsView.js
Labels: enhancement

#380 [Project Overview] Trim project name from Nuclio function name
  src/components/ProjectTable/ProjectTable.js
Labels: enhancement

#389 [Create Job] Data Inputs: Add auto-completion on edit
  src/common/Combobox/Combobox.js
  src/common/Combobox/ComboboxView.js
  src/common/Combobox/combobox.scss
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputsReducer.js
  src/constants.js
  src/elements/EditableDataInputsRow/EditableDataInputsRow.js
  src/elements/EditableDataInputsRow/EditableDataInputsRow.utils.js
  src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
  src/elements/JobsPanelTable/JobsPanelTable.js
  src/elements/JobsPanelTable/JobsPanelTableView.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
  src/elements/JobsPanelTableRow/JobsPanelTableRow.js
  src/scss/mixins.scss
Labels: enhancement

#390 Fix [Create Job] Parameters: null values are wrongly sent
  src/components/JobsPanelParameters/JobsPanelParameters.js
  src/components/JobsPanelParameters/jobsPanelParameters.util.js
  src/components/JobsPanelParameters/jobsPanelParametersReducer.js
Labels: bug, enhancement

#391 [Feature Store] Default to Feature Sets and reorder tabs
  src/App.js
  src/common/Combobox/Combobox.js
  src/common/Combobox/ComboboxView.js
  src/common/Combobox/combobox.scss
  src/common/Input/input.scss
  src/components/FeatureStore/feaureStore.util.js
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputsReducer.js
  src/components/ProjectTable/ProjectTable.js
  src/components/ProjectsPage/ProjectsView.js
  src/constants.js
  src/elements/EditableDataInputsRow/EditableDataInputsRow.js
  src/elements/EditableDataInputsRow/EditableDataInputsRow.utils.js
  src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
  src/elements/JobsPanelTable/JobsPanelTable.js
  src/elements/JobsPanelTable/JobsPanelTableView.js
  src/elements/JobsPanelTable/jobsPanelTable.scss
  src/elements/JobsPanelTableRow/JobsPanelTableRow.js
  src/scss/mixins.scss
Labels: enhancement

#394 [Feature Store] Fix transformation tab with empty data. Fix tabs order
  src/components/DetailsTransformations/ConfigSource/ConfigSource.js
  src/components/DetailsTransformations/ConfigSteps/ConfigSteps.js
  src/components/DetailsTransformations/ConfigTargets/ConfigTargets.js
  src/components/DetailsTransformations/DetailsTransformations.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/feaureStore.util.js
Labels: bug

#396 [Project Overview] Added Refresh button
  src/components/Project/Project.js
  src/components/Project/ProjectDescription/ProjectDescription.js
  src/components/Project/ProjectGoals/ProjectGoals.js
  src/components/Project/ProjectLinks/ProjectLinks.js
  src/components/Project/ProjectName/ProjectName.js
  src/components/Project/ProjectSource/ProjectSource.js
  src/components/Project/ProjectView.js
  src/components/Project/project.scss
  src/elements/ProjectFunctions/ProjectFunctions.js
Labels: enhancement

#392 [Models] Added Model Endpoints tab
  src/App.js
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/common/Breadcrumbs/Breadcrumbs.js
  src/common/Chip/Chip.js
  src/common/ChipCell/chipCell.scss
  src/common/Select/Select.js
  src/common/Select/select.scss
  src/components/Details/DetailsView.js
  src/components/Details/details.util.js
  src/components/DetailsInfo/detailsInfo.util.js
  src/components/Files/files.util.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/constants.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/ContentMenu/ContentMenu.js
  src/elements/ContentMenu/contentMenu.scss
  src/elements/TableLinkCell/TableLinkCell.js
  src/images/severity-error.svg
  src/images/severity-ok.svg
  src/images/severity-warning.svg
  src/layout/Content/Content.js
  src/reducers/artifactReducer.js
  src/scss/main.scss
  src/utils/createArtifactsContent.js
  src/utils/object.js
Labels: enhancement

#397 [Create Job] Added job name pattern and max length validation
  src/common/Input/Input.js
  src/common/Tip/Tip.js
  src/common/Tip/tip.scss
  src/components/JobsPanel/JobsPanel.js
  src/components/ProjectsPage/ProjectsView.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/elements/JobsPanelTitle/jobsPanelTitle.scss
Labels: enhancement

#398 [Projects] Add sorting, filtering and refresh
  src/actions/projects.js
  src/common/Search/search.scss
  src/common/Sort/Sort.js
  src/common/Sort/sort.scss
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projects.scss
  src/components/ProjectsPage/projectsData.js
  src/constants.js
  src/reducers/projectReducer.js
Labels: enhancement

#399 Impl [Projects] Default sorting to ascending order
  src/components/ProjectsPage/Projects.js
Labels: enhancement

#401 [Feature Sets] Group name repeats in nested rows, selected nested row not highlighted
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/utils/createArtifactsContent.js
Labels: bug

#402 [Projects][Project Overview] Count feature sets, not features
  src/actions/projects.js
  src/api/projects-api.js
  src/components/FeatureStore/feaureStore.util.js
  src/components/Files/files.util.js
  src/components/FunctionsPage/functionsData.json
  src/components/Models/models.util.js
  src/components/Project/Project.js
  src/components/Project/ProjectView.js
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projectsData.js
  src/constants.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/elements/ProjectCard/ProjectCard.js
  src/elements/ProjectCard/projectCard.util.js
  src/reducers/projectReducer.js
Labels: enhancement

#403 Fix [General] Details panel: actions not sticking to top on scroll
  src/components/Details/details.scss
Labels: bug

#404 Fix [Jobs] Error when a job has a parameter with `null` value
  src/utils/object.js
Labels: bug

#405 Revert[General]Details panel:actions not sticking to top on scroll
  src/components/Details/details.scss
Labels: revert

#406 Fix [Breadcrumbs] Links to Nuclio are static instead of dynamic
  src/common/Breadcrumbs/breadcrumbs.util.js
Labels: bug

#407 Impl [Feature Store] Add "Beta" note (configurable thru env var)
  .env
  Dockerfile
  config.js.tmpl
  nginx/run_nginx
  public/config.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
  src/elements/ContentMenu/ContentMenu.js
  src/elements/ContentMenu/contentMenu.scss
Labels: enhancement

#408 [Feature Sets][Feature Vectors] Added Analysis tab content
  src/api/artifacts-api.js
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/ArtifactsPreview/PreviewError/PreviewError.js
  src/components/ArtifactsPreview/artifactPreview.util.js
  src/components/ArtifactsPreview/artifactaPreview.scss
  src/components/Details/details.scss
  src/components/Details/details.util.js
  src/scss/main.scss
  src/utils/createArtifactPreviewContent.js
Labels: enhancement

#409 [Analysis] Removed popout icon button
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/Details/Details.js
  src/components/Details/details.util.js
  src/components/DetailsAnalysis/DetailsAnalysis.js
Labels: bug

#410 [Project Overview] Jobs list shows all iterations of same job
  src/actions/projects.js
  src/components/Project/Project.js
  src/components/Project/ProjectView.js
  src/components/ScheduleJob/ScheduleJobView.js
  src/components/ScheduleJob/scheduleJob.scss
  src/elements/ProjectFunctions/ProjectFunctions.js
  src/elements/ProjectJobs/ProjectJobs.js
Labels: bug
