Repository mlrun/ui, pull requests merged in 2022-05, with the labels that each got.

#1251 Fix [Model Endpoints] Page crash when trying to drill down
  src/components/DetailsFeaturesAnalysis/DetailsFeaturesAnalysis.js
  src/components/Models/models.util.js
  src/utils/createArtifactsContent.js
  src/utils/generateModelEndpoints.js
Labels: bug

#1256 Fix [Features] Feature vector creation from the UI is broken when selecting an entity field
  src/elements/FeaturesTablePanel/FeaturesTablePanel.js
  src/elements/FeaturesTablePanel/FeaturesTablePanelView.js
  src/reducers/tableReducer.js
  src/utils/createFeatureStoreContent.js
Labels: bug

#1257 Fix [Models] Table reload when opening Deploy model popup
  src/actions/artifacts.js
  src/actions/functions.js
  src/components/Models/Models.js
  src/constants.js
  src/elements/DeployModelPopUp/DeployModelPopUp.js
  src/reducers/artifactReducer.js
Labels: bug

#1258 Fix [Jobs] Click on a scheduled name opens up the entire list of functions
  src/utils/createJobsContent.js
Labels: bug

#1255 Fix [Jobs] Show 'Run on spot node' in new job panel
  src/common/Backdrop/Backdrop.js
  src/common/Backdrop/Backdrop.scss
  src/common/Modal/Modal.js
  src/components/JobsPanel/jobsPanel.util.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
Labels: bug

#1260 Fix [Settings] Members: "Invite new members" returns up to 50 users
  src/api/projects-iguazio-api.js
  src/common/ChipInput/chipInput.scss
  src/elements/MembersPopUp/MembersPopUp.js
  src/elements/MembersPopUp/membersPopUp.scss
Labels: bug

#1261 Fix [Project Overview] Some runs not shown in project overview screen
  src/actions/projects.js
  src/components/Jobs/Jobs.js
Labels: bug

#1265 Fix [General] Projects screen is empty - 'SyntaxError: Unexpected token '<' (at main.d5697fce.js:1:1)'
  Dockerfile
  package.json
  scripts/start.js
Labels: bug

#1264 Fix [Functions/Jobs] Wrong validation for CPU units
  src/utils/panelResources.util.js
Labels: bug

#1266 Fix [UI] Change icon plus to check when applying new key-value
  package.json
  src/common/KeyValueTable/KeyValueTableView.js
Labels: bug

#1269 Fix [Consumer Groups] Filter by name should be case insensitive
  src/components/ConsumerGroup/ConsumerGroup.js
  src/components/ConsumerGroups/ConsumerGroups.js
Labels: bug

#1222 Fix [Jobs] Create job fails with 400 error code
  src/actions/jobs.js
Labels: bug

#1270 Impl [Jobs] Refactored Jobs components
  package.json
  src/App.js
  src/actions/jobs.js
  src/common/Breadcrumbs/Breadcrumbs.js
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/common/ChipCell/ChipCell.js
  src/common/Input/Input.js
  src/components/Details/Details.js
  src/components/Details/DetailsView.js
  src/components/FilterMenu/FilterMenu.js
  src/components/Jobs/Jobs.js
  src/components/Jobs/JobsView.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorJobs/MonitorJobsView.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflowsView.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/components/Jobs/ScheduledJobs/ScheduledJobsView.js
  src/components/Jobs/jobs.util.js
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Workflow/Workflow.js
  src/components/Workflow/workflow.util.js
  src/elements/JobTable/JobsTable.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/hooks/usePods.hook.js
  src/layout/Content/Content.js
  src/layout/Content/content.scss
  src/reducers/tableReducer.js
  src/scss/main.scss
  src/utils/createJobsContent.js
  src/utils/generateTableContent.js
  src/utils/rerunJob.js
Labels: enhancement, Cleanup

#1271 Fix [Models] No data for Model framework in the Model overview screen
  src/components/Details/details.util.js
Labels: bug

#1274 Fix [Settings Members] 'Invite new members' returns up to 50 users
  src/api/projects-iguazio-api.js
  src/elements/MembersPopUp/MembersPopUp.js
  src/elements/MembersPopUp/membersPopUp.scss
Labels: bug

#1276 Fix [Jobs] Crash on attempt to open "Artifacts" tab - TypeError: Cannot read properties of undefined (reading 'match')"
  src/components/DetailsArtifacts/detailsArtifacts.util.js
  src/components/Jobs/Jobs.js
  src/components/Jobs/MonitorJobs/MonitorJobsView.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflowsView.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
Labels: bug

#1277 Fix [UI] Cannot View Build Image Step in Pipeline UI
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Workflow/Workflow.js
Labels: bug

#1278 Fix [Project Overview] Changes in members are reflected only after a refresh
  src/api/projects-iguazio-api.js
  src/components/ProjectSettings/ProjectSettings.js
  src/components/ProjectSettings/projectSettings.util.js
  src/elements/MembersPopUp/MembersPopUp.js
Labels: bug

#1279 Fix [Feature Vectors] Discard changes button doesn't work on edit alias
  src/components/Details/Details.js
  src/components/Details/details.util.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeaturesView.js
  src/components/DetailsRequestedFeatures/detailsRequestedFeatures.utils.js
  src/components/FeatureStore/FeatureStore.js
  src/constants.js
  src/utils/validationService.js
Labels: bug

#1280 Fix [UI] Jobs creation panel doesn't work properly
  src/common/CheckBox/CheckBox.js
  src/common/CheckBox/checkBox.scss
  src/common/KeyValueTable/KeyValueTable.js
  src/common/KeyValueTable/KeyValueTableView.js
  src/common/KeyValueTable/keyValueTable.scss
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanel/panelReducer.js
  src/components/JobsPanelAdvanced/JobsPanelAdvancedView.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
  src/components/JobsPanelParameters/JobsPanelParameters.js
  src/components/JobsPanelParameters/JobsPanelParametersView.js
  src/components/JobsPanelResources/JobsPanelNodeSelector/JobsPanelNodeSelector.js
  src/components/JobsPanelResources/JobsPanelResources.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/components/JobsPanelResources/JobsPanelVolumes/JobsPanelVolumes.js
  src/elements/EnvironmentVariables/EnvironmentVariables.js
  src/elements/EnvironmentVariables/EnvironmentVariablesView.js
  src/elements/EnvironmentVariables/enviromnetVariables.scss
  src/elements/JobsPanelAdvancedTable/JobsPanelAdvancedTable.js
  src/elements/JobsPanelCredentialsAccessKey/JobsPanelCredentialsAccessKey.js
  src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
  src/elements/JobsPanelEnvironmentVariables/JobsPanelEnvironmentVariables.js
  src/elements/JobsPanelParametersTable/JobsPanelParametersTable.js
  src/elements/JobsPanelParametersTable/JobsPanelParametersTableView.js
  src/elements/JobsPanelTableAddItemRow/JobsPanelTableAddItemRow.js
  src/elements/JobsPanelTableRow/JobsPanelTableRow.js
  src/elements/JobsPanelTitle/JobsPanelTitle.js
  src/elements/PanelCredentialsAccessKey/PanelCredentialsAccessKey.js
  src/elements/PanelResourcesUnits/PanelResourcesUnits.js
  src/elements/VolumesTable/VolumesTable.js
  src/elements/VolumesTable/VolumesTableView.js
Labels: bug

#1281 Fix [Feature Set Panel] Error when change Partition checkboxes
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
Labels: bug

#1283 Impl [Jobs] Show the Spark UI URL in the spark Job
  src/components/Details/details.util.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/jobs.util.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/utils/parseJob.js
Labels: enhancement

#1285 Impl [UI] Add support modification of already existing function with different GPU type
  src/components/FunctionsPage/Functions.js
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanel/panelReducer.js
  src/components/JobsPanelResources/JobsPanelResources.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
  src/elements/PanelResourcesUnits/PanelResourcesUnits.js
  src/utils/panelResources.util.js
Labels: enhancement

#1287 Fix [Project settings] scrolling should be inside suggestion list in 'Invite new members' screen
  src/common/ChipInput/chipInput.scss
Labels: bug

#1289 Fix npm vulnerabilities
  package.json
Labels: Cleanup
