Repository mlrun/ui, pull requests merged in 2022-09, with the labels that each got.

#1384 Fix [Jobs] user can't use edit option for scheduler job
  src/common/Select/Select.js
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#1383 Fix [Feature Vector] Wrong presentation for description tooltips for long description text
  package.json
  src/common/TextArea/TextArea.js
  src/common/TextArea/textArea.scss
  src/components/DetailsInfo/detailsInfo.scss
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/featureSetsPanelTitle.scss
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/Project/ProjectDescription/ProjectDescription.js
  src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneral.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js
  src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
  src/elements/RegisterModelPopUp/RegisterModelPopUp.js
Labels: bug

#1371 Impl [UI] Redirect Nuclio UI back to MLRun UI when clicking on Projects
  src/layout/Navbar/Navbar.utils.js
  src/utils/parseUri.js
Labels: enhancement

#1385 Fix [UI] MLRun UI not accessible via `/` only via `/mlrun`
  src/index.js
Labels: bug

#1390 Revert "Impl [UI] Redirect Nuclio UI back to MLRun UI when clicking on Projects"
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/components/Project/ProjectOverview/ProjectOverview.util.js
  src/elements/ProjectFunctions/ProjectFunctions.js
  src/layout/Navbar/Navbar.utils.js
  src/utils/createConsumerGroupsContent.js
  src/utils/parseUri.js
Labels: revert

#1388 Fix [Models] Blank screen after clicking on model name
  src/components/DetailsInfo/DetailsInfoView.js
  src/utils/generateArtifacts.js
Labels: bug

#1392 Fix [Feature Store] App crash when trying to drill down or create new set
  src/components/DetailsInfo/DetailsInfoView.js
  src/utils/generateArtifacts.js
Labels: bug

#1396 Impl [UI] Redirect Nuclio UI back to MLRun UI when clicking on Projects
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/components/Project/ProjectOverview/ProjectOverview.util.js
  src/elements/ProjectFunctions/ProjectFunctions.js
  src/layout/Navbar/Navbar.utils.js
  src/utils/createConsumerGroupsContent.js
  src/utils/parseUri.js
Labels: documentation

#1395 Impl [UI] Redirect Nuclio UI back to MLRun UI when clicking on Projects
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/components/Project/ProjectOverview/ProjectOverview.util.js
  src/elements/ProjectFunctions/ProjectFunctions.js
  src/layout/Navbar/Navbar.utils.js
  src/utils/createConsumerGroupsContent.js
  src/utils/parseUri.js
Labels: enhancement

#1398 Impl [UI] Change implementation of the useBlockHistory hook
  src/components/Project/ProjectOverview/ProjectOverview.util.js
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/hooks/useBlockHistory.hook.js
  src/hooks/useModalBlockHistory.hook.js
Labels: enhancement

#1400 Fix [Monitor Workflows] Loader stuck when failed to fetch a function
  src/actions/functions.js
  src/common/ReactFlow/MlReactFlow.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
Labels: bug

#1401 Fix [Monitor Workflows] Loader stuck when failed to fetch a function
  src/actions/functions.js
  src/common/ReactFlow/MlReactFlow.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
Labels: bug

#1391 Fix [UI] blank screen on attempt to browse Projects
  public/index.html
  src/App.js
  src/components/ErrorBoundary/ErrorBoundary.js
  src/index.js
  src/lazyWithRetry.js
  src/setupProxy.js
Labels: bug

#1405 Impl [Models] Add option to edit labels for models
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/components/Details/Details.js
  src/components/Details/DetailsView.js
  src/components/Details/details.util.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/utils/generateArtifacts.js
Labels: enhancement

#1406 Impl [Models] Add option to edit labels for models
  src/actions/artifacts.js
  src/api/artifacts-api.js
  src/components/Details/Details.js
  src/components/Details/DetailsView.js
  src/components/Details/details.util.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/utils/generateArtifacts.js
Labels: enhancement

#1407 Impl [UI] add hover indication to labels apply check Icon
  src/elements/DetailsInfoItemChip/DetailsInfoItemChip.js
Labels: enhancement

#1408 Impl [UI] Change apply icon in details
  src/components/Details/details.scss
  src/elements/DetailsInfoItemChip/DetailsInfoItemChip.js
Labels: enhancement

#1410 Fix [Jobs & Functions] Error 400 for re-runing the serving ml function
  src/components/CreateJobPage/CreateJobPage.js
  src/components/FunctionsPage/Functions.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
Labels: bug

#1409 Fix [Monitor jobs] using optional chaining to prevent error due missing 'spec' property
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/utils/parseJob.js
Labels: bug

#1411 Impl [UI] useModalBlockHistory.hook refactoring
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/hooks/useBlockHistory.hook.js
  src/hooks/useModalBlockHistory.hook.js
Labels: enhancement
