Repository mlrun/ui, pull requests merged in 2022-10, with the labels that each got.

#1413 Fix [Labels] The 'space' key and value label should be restricted
  src/common/ChipCell/ChipCell.js
Labels: bug

#1412 Fix [Labels] The 'space' key and value label should be restricted
  src/common/ChipCell/ChipCell.js
Labels: bug

#1417 Fix [UI] small fixes
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/elements/DeployModelPopUp/DeployModelPopUp.js
Labels: bug

#1421 Impl [Models] add labels validation
  package.json
  src/elements/RegisterModelPopUp/RegisterModelPopUp.js
  src/utils/convertChipsData.js
Labels: enhancement

#1422 Impl [Artifacts, Dataset] Add labels to dataset and artifacts wizard
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
  src/elements/RegisterModelPopUp/RegisterModelPopUp.js
Labels: bug

#1424 Clean [Register Artifact] set initial Values on init
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
Labels: Cleanup

#1426 Fix [Artifacts] "Cannot read properties of undefined (reading 'extra_data')" on attempt to expand artifact
  src/actions/artifacts.js
Labels: bug

#1425 Impl [Artifacts] UI to work with new Artifact REST APIs
  src/api/artifacts-api.js
  src/api/projects-api.js
Labels: enhancement

#1428 Fix [Feature Store] Confirm dialog doesn't work properly
  src/components/Details/Details.js
  src/components/Details/details.util.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeaturesView.js
  src/components/DetailsRequestedFeatures/detailsRequestedFeatures.utils.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
  src/hooks/useBlockHistory.hook.js
Labels: bug

#1427 Impl [Feature store] add edit icon to description
  src/components/DetailsInfo/detailsInfo.scss
  src/elements/DetailsInfoItem/DetailsInfoItem.js
Labels: enhancement

#1420 Impl [UI] Add/Change target path to register model, dataset and artifacts wizard
  src/common/TargetPath/TargetPath.js
  src/common/TargetPath/targetPath.util.js
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
  src/elements/RegisterModelPopUp/RegisterModelPopUp.js
Labels: enhancement

#1431 Change target path density to normal
  src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
  src/elements/RegisterModelPopUp/RegisterModelPopUp.js
Labels: bug

#1432 Fix [UI] artifact/model registered via UI is using old format
  src/api/artifacts-api.js
  src/common/TargetPath/TargetPath.js
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
  src/elements/RegisterModelPopUp/RegisterModelPopUp.js
  src/elements/RegisterModelPopUp/registerModelPopUp.scss
Labels: bug

#1433 Fix [Feature store] update/delete labels
  src/api/featureStore-api.js
  src/components/FeatureStore/featureStore.util.js
Labels: bug

#1434 Fix [Monitor Workflows] Multiple error when failed to fetch a function
  src/common/ReactFlow/mlReactFlow.scss
  src/components/Workflow/Workflow.js
  src/scss/main.scss
  src/utils/getState.js
Labels: bug

#1435 Impl [chips] parseChipsData function for new Labels
  src/utils/convertChipsData.js
  src/utils/object.js
Labels: enhancement
