Repository mlrun/ui, pull requests merged in 2022-08, with the labels that each got.

#1353 Fix [UI] console error when using selectOptions
  src/common/Select/Select.js
  src/common/SplitButton/SplitButton.js
Labels: bug

#1354 Fix [Wizard] Does not close on navigation
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/elements/DeployModelPopUp/DeployModelPopUp.js
Labels: bug

#1356 Fix [Project secrets] Add Additional Information to Project Secrets screen
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecretsView.js
Labels: bug

#1358 Fix [Project secrets] Add Additional Information to Project Secrets screen
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecretsView.js
Labels: bug

#1359 Fix [UI] console error when using selectOptions
  src/common/DatePicker/DatePickerView.js
Labels: bug

#1361 Fix [Feature set] std column on statistics page is empty after ingest with spark engine
  src/components/DetailsStatistics/detailsStatistics.util.js
  src/utils/roundFloats.js
Labels: bug

#1357 Impl [Models] Revamp Register model wizard
  src/common/ChipCell/ChipCell.js
  src/common/ChipForm/ChipForm.js
  src/components/Models/Models.js
  src/components/Project/ProjectMonitor.js
  src/components/Project/ProjectMonitorView.js
  src/components/Project/project.utils.js
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/elements/RegisterModelPopUp/RegisterModelPopUp.js
  src/elements/RegisterModelPopUp/registerModelPopUp.scss
  src/hooks/useBlockHistory.hook.js
  src/utils/convertChipsData.js
Labels: enhancement

#1362 Fix [Artifacts] "Show Details" for artifacts with no "latest" tag is broken and forwards to the main projects screen
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsArtifacts/detailsArtifacts.util.js
Labels: bug

#1363 Fix [Artifacts] "Show Details" for artifacts with no "latest" tag is broken and forwards to the main projects screen
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsArtifacts/detailsArtifacts.util.js
Labels: bug

#1364 Impl [Project Overview] Register model wizard (project home)
  src/components/Models/Models.js
  src/components/Project/ProjectOverview/ProjectOverview.js
  src/components/Project/ProjectOverview/ProjectOverview.util.js
  src/elements/RegisterModelPopUp/RegisterModelPopUp.js
Labels: documentation

#1369 Fix [UI] Label value is not being displayed
  src/utils/roundFloats.js
Labels: bug

#1367 Fix [Jobs] 'Failed to fetch jobs' error appears on attempt to rerun job via UI
  src/api/jobs-api.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
Labels: bug

#1368 Fix [Jobs] 'Failed to fetch jobs' error appears on attempt to rerun job via UI
  src/api/jobs-api.js
  src/components/Jobs/Jobs.js
Labels: bug

#1370 Fix [Jobs] Wrong parsing of parameters
  src/components/Details/details.util.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/Jobs/jobs.util.js
  src/utils/createJobsContent.js
  src/utils/object.js
  src/utils/parseJob.js
Labels: bug

#1372 Fix [Models] No data for data for Unique, Top and Freq in the Statistics tab
  src/components/FeatureStore/FeatureSets/featureSets.util.js
  src/components/Models/models.util.js
Labels: bug

#1373 Fix [UI] Blank screen with TypeError after switching between iterations with open artifact preview screen
  src/components/DetailsArtifacts/DetailsArtifacts.js
Labels: bug

#1374 Fix [UI] Cannot read property 'tag' of undefined" on attempt to open artifacts tab
  src/components/DetailsArtifacts/detailsArtifacts.util.js
Labels: bug

#1375 Impl [tests] QA Sprint 140 Done
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/common.action.js
  tests/features/common/actions/graph.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/ml-functions.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/project-settings.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectPage.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/api.steps.js
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/artifacts.json
  tests/mockServer/data/entities.json
  tests/mockServer/data/featureSets.json
  tests/mockServer/data/featureVectors.json
  tests/mockServer/data/features.json
  tests/mockServer/data/funcs.json
  tests/mockServer/mock.js
Labels: tests

#1376 Impl [tests] QA Sprint 140 Done
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/common.action.js
  tests/features/common/actions/graph.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/ml-functions.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/project-settings.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectPage.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/api.steps.js
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/artifacts.json
  tests/mockServer/data/entities.json
  tests/mockServer/data/featureSets.json
  tests/mockServer/data/featureVectors.json
  tests/mockServer/data/features.json
  tests/mockServer/data/funcs.json
  tests/mockServer/mock.js
Labels: tests

#1378 Fix [Models] Missing class "details-item__data" the html for model
  src/elements/DetailsInfoItem/DetailsInfoItem.js
Labels: bug

#1377 Fix [UI] User can't use edit option for scheduler job
  src/components/FeatureSetsPanel/FeatureSetsPanelView.js
Labels: bug

#1380 [CI] Add copyright checker
  .github/workflows/ci.yaml
  .licenserc.json
Labels: enhancement

#1382 Fix [Artifacts] Artifacts not shown in UI although present in BE response
  src/utils/generateArtifacts.js
Labels: bug
