Repository mlrun/ui, pull requests merged in 2022-11, with the labels that each got.

#1436 Fix [Navbar] project home active state
  src/elements/NavbarLink/NavbarLink.js
  src/layout/Navbar/Navbar.utils.js
Labels: bug

#1437 Fix [Feature Set] error on attempt to open 'Feature set' 'Transformations' tab
  src/components/DetailsTransformations/DetailsTransformations.js
Labels: bug

#1439 Fix [Models] UI crash when clicking on function in 'Real Time Pipelines' tab
  src/components/Pipeline/Pipeline.js
Labels: bug

#1442 fix error length
  src/components/DetailsTransformations/DetailsTransformations.js
  src/components/Pipeline/Pipeline.js
Labels: bug

#1443 Fix [UI] styles
  src/common/CodeBlock/codeBlock.scss
  src/components/DetailsTransformations/ConfigSteps/ConfigSteps.js
  src/components/Project/project.scss
  src/components/ProjectsPage/projects.scss
  src/elements/ProjectCard/projectCard.scss
  src/layout/Header/Header.js
  src/layout/Header/header.scss
Labels: bug

#1447 Fix [Models] "Go back" browser button does not take effect when focused on "Models" tab
  src/App.js
Labels: bug

#1446 Fix [Projects] unexpected project cards resizing
  src/components/ProjectsPage/projects.scss
  src/elements/ProjectCard/projectCard.scss
Labels: bug

#1448 Fix [Models] register model fails with 'Model failed to initiate'
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/ModelsPage.context.js
  src/components/ModelsPage/ModelsPage.js
  src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
  src/components/ModelsPage/modelsPage.util.js
Labels: bug

#1449 Fix [Artifacts] tagging does not work properly
  src/components/Datasets/datasets.util.js
  src/components/Details/details.util.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfo.scss
  src/elements/DetailsInfoItem/DetailsInfoItem.js
Labels: bug

#1450 Fix [Models] Unnecessary option on artifact registry Target path
  src/common/TargetPath/TargetPath.js
  src/common/TargetPath/targetPath.util.js
  src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
  src/elements/RegisterModelPopUp/RegisterModelPopUp.js
Labels: bug

#1454 Fix [UI] Wrong navigation after deleting artifact/datasets tag
  src/components/Datasets/Datasets.js
  src/components/Files/Files.js
  src/components/ModelsPage/Models/Models.js
Labels: bug

#1455 Fix dependecies in useEffect
  src/common/TargetPath/TargetPath.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/ModelsPage.context.js
  src/components/ModelsPage/ModelsPage.js
Labels: bug

#1457 Fix [Functions] 'Request failed with status code 404' error appears on attempt to save new ML function
  src/components/FunctionsPanel/FunctionsPanel.js
Labels: bug

#1462 Fix double import
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
Labels: bug

#1461 Fix [Artifacts] information row is missing
  src/components/Datasets/Datasets.js
  src/components/Datasets/datasets.util.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
  src/components/FeatureStore/Features/Features.js
  src/components/Files/Files.js
  src/components/Files/files.util.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/models.util.js
  src/components/Table/TableHead.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/FeatureStoreTableRow/FeatureStoreTableRow.js
  src/elements/TableCell/TableCell.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/elements/TableProducerCell/TableProducerCell.js
  src/elements/TableTypeCell/TableTypeCell.js
  src/utils/createArtifactsContent.js
  src/utils/createFeatureStoreContent.js
  src/utils/generateTableContent.js
Labels: bug

#1463 Fix [Artifacts] Editing tag for model causes to changing tags for all models with this tag
  src/components/Datasets/datasets.util.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/models.util.js
  src/utils/artifacts.util.js
Labels: bug

#1460 Fix [Jobs] Unable to rerun mlrun job from dashboard - job parameter passed as string instead of float
  src/components/Jobs/jobs.util.js
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#1464 Fix [Features] Wrong presentation of expanded content
  src/elements/FeatureStoreTableRow/FeatureStoreTableRow.js
Labels: bug

#1465 Fix [Dataset/Model/Artifact] The added tag is presented only after refresh page
  src/components/Datasets/Datasets.js
  src/components/Datasets/datasets.util.js
  src/components/Files/Files.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/models.util.js
Labels: bug

#1468 Fix [Project Overview] "Create RT function" should navigate to "new function" wizard
  src/components/Project/ProjectOverview/ProjectOverview.util.js
Labels: bug

#1467 Fix [Projects] unexpected project cards resizing
  src/components/ProjectsPage/projects.scss
Labels: bug

#1466 Impl [Artifacts] filter tags list by artifact category
  src/actions/artifacts.js
  src/actions/filters.js
  src/api/artifacts-api.js
  src/components/Datasets/Datasets.js
  src/components/Files/Files.js
  src/components/ModelsPage/Models/Models.js
  src/constants.js
  src/hooks/useGetTagOptions.hook.js
Labels: enhancement

#1469 Fix [Feature Sets] Can't edit feature sets without a tag
  src/components/Details/Details.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureSets/FeatureSetsView.js
  src/components/FeatureStore/featureStore.util.js
Labels: bug

#1471 Impl [Feature sets] Add notification after feature set update
  src/components/FeatureStore/featureStore.util.js
Labels: enhancement

#1472 Fix [Projects] when clicking on Register Artifact button - the Projects screen becomes blank
  package.json
Labels: bug

#1470 Fix [Project home] Add runtime to function popup
  src/components/Project/ProjectOverview/ProjectOverview.util.js
  src/elements/NewFunctionPopUp/NewFunctionPopUp.js
Labels: bug

#1473 Fix [UI] Trimmed tooltips of dataset labels
  src/common/Chip/Chip.js
  src/common/ChipCell/ChipCell.js
  src/common/ChipCell/ChipCellView.js
  src/constants.js
  src/elements/HiddenChipsBlock/HiddenChipsBlock.js
  src/layout/Navbar/Navbar.js
  src/layout/Navbar/Navbar.scss
  src/layout/Page/Page.js
  src/scss/main.scss
Labels: bug

#1475 Impl [Artifacts] Replace `Redux` with `Redux Toolkit`
  src/actions/artifacts.js
  src/actions/featureStore.js
  src/actions/filters.js
  src/api/artifacts-api.js
  src/common/TargetPath/TargetPath.js
  src/components/Artifacts/Artifacts.js
  src/components/Artifacts/artifacts.scss
  src/components/Artifacts/artifactsData.json
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/Datasets/datasets.util.js
  src/components/Details/Details.js
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitle.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/Files/files.util.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/models.util.js
  src/components/ModelsPage/ModelsPage.context.js
  src/components/ModelsPage/ModelsPage.js
  src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
  src/constants.js
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
  src/elements/DeployModelPopUp/DeployModelPopUp.js
  src/elements/PreviewModal/PreviewModal.js
  src/elements/TableCell/TableCell.js
  src/hooks/useGetTagOptions.hook.js
  src/reducers/appReducer.js
  src/reducers/artifactReducer.js
  src/reducers/artifactsReducer.js
  src/reducers/artifactsToolkitReducer.js
  src/reducers/reducers.js
  src/reducers/redux.util.js
  src/reducers/tableReducer.js
  src/store/store.js
  src/store/toolkitStore.js
  src/utils/artifacts.util.js
Labels: enhancement, Cleanup

#1479 Fix [Project Setting] page crash on adding member
  src/common/ChipInput/ChipInput.js
Labels: bug

#1477 Impl [Notifications] Replace `Redux` with `Redux Toolkit`
  src/actions/notification.js
  src/common/Download/Download.js
  src/common/Notification/Notification.js
  src/common/TargetPath/TargetPath.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
  src/components/ConsumerGroup/ConsumerGroup.js
  src/components/ConsumerGroupsWrapper/ConsumerGroupsWrapper.js
  src/components/Datasets/Datasets.js
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureSets/featureSets.util.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
  src/components/FeatureStore/FeatureVectors/featureVectors.util.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/Files.js
  src/components/FunctionsPage/Functions.js
  src/components/Jobs/Jobs.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/components/Jobs/ScheduledJobs/scheduledJobs.util.js
  src/components/Jobs/jobs.util.js
  src/components/JobsPanel/JobsPanel.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/models.util.js
  src/components/Project/ProjectMonitor.js
  src/components/ProjectSettings/ProjectSettings.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projectsData.js
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/constants.js
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
  src/elements/DeployModelPopUp/DeployModelPopUp.js
  src/elements/FeaturesTablePanel/FeaturesTablePanel.js
  src/elements/NewFunctionPopUp/NewFunctionPopUp.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js
  src/elements/RegisterModelModal/RegisterModelModal.js
  src/layout/Page/Page.js
  src/reducers/notificationReducer.js
  src/utils/artifacts.util.js
Labels: enhancement, Cleanup

#1474 Fix [Artifacts] Wrong message for adding tag with already existed name
  src/api/artifacts-api.js
  src/components/Datasets/Datasets.js
  src/components/Files/Files.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/models.util.js
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
  src/reducers/artifactsReducer.js
Labels: bug

#1480 Fix [Artifacts] add existing tag name warning
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
Labels: bug

#1482 Fix [Artifacts] fix error message for duplicated tag name
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
Labels: bug

#1483 Fix [Artifacts] missing input validation logic in "edit tag" dialog
  scripts/mockServer.js
  src/common/Input/Input.js
  src/components/Details/details.util.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  tests/mockServer/mock.js
Labels: bug

#1485 Fix [Artifacts] The iterations are created for adding tag
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
Labels: bug
