Repository mlrun/ui, pull requests merged in 2022-02, with the labels that each got.

#1051 Impl UI cosmetic 0.10
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/common/TagFilter/tagFilter.scss
  src/common/Tip/tip.scss
  src/components/FeatureStore/featureStore.util.js
  src/elements/DetailsMenu/DetailsMenu.js
  src/elements/DetailsMenu/detailsMenu.scss
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js
  src/elements/ProjectSettingsGeneral/projectSettingsGeneral.scss
  src/elements/ProjectSettingsSource/ProjectSettingsSource.js
  src/elements/ProjectSettingsSource/projectSettingsSource.scss
  src/layout/Navbar/Navbar.scss
  src/layout/Navbar/Navbar.utils.js
Labels: enhancement

#1068 Fix [Models][Overview] Incorrect target_path in YAML file
  src/components/DetailsArtifacts/detailsArtifacts.util.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/utils/generateArtifactPreviewData.js
  src/utils/generateArtifacts.js
Labels: bug

#1074 Impl [Real-time Pipelines] Avoid presentation of duplicated names
  src/common/ReactFlow/mlReactFlow.scss
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/components/Pipeline/Pipeline.js
  src/components/Pipeline/PipelineView.js
  src/components/Pipeline/pipeline.scss
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/utils/createFunctionsContent.js
Labels: enhancement

#1073 [Jobs][Artifacts] UI crash on Artifact with type txt
  src/utils/createArtifactPreviewContent.js
Labels: bug

#1076 Fix [Feature Sets] Missing validation and tooltips in the Tag tips
  src/common/OptionsMenu/ValidationTemplate/ValidationTemplate.module.scss
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/featureSetsPanelTitle.scss
  src/utils/validationService.js
Labels: bug

#1077 Fix [Project Settings] Incorrect values
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js
  src/elements/ProjectSettingsGeneral/projectSettingsGeneral.utils.js
Labels: bug

#1078 Fix [UI][Real-time-pipelines] Expand button has wrong icon
  src/layout/Content/Content.js
Labels: bug

#1072 [Project][Settings] Source/Artifact incorrect behavior
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
Labels: bug

#1081 Fix [UI] [Feature Vector] User can set Label or Delete feature from `Selected Project' only in the 'Add to feature vector' screen
  src/actions/table.js
  src/elements/AddFeatureButton/AddFeatureButton.js
  src/elements/FeaturesTablePanel/FeaturesTablePanel.js
  src/reducers/tableReducer.js
Labels: bug

#1083 Fix [Feature set] User can't create Feature set with more than one version from UI
  src/api/featureStore-api.js
Labels: bug

#1084 Fix [Feature set]New tag presents in the Tags filter list after reload page.
  src/components/FeatureStore/FeatureStore.js
Labels: bug

#1087 Impl [UI] Remove 'beta' indicator from mlrun logo
  src/layout/Header/Header.js
Labels: enhancement

#1088 Fix [Jobs workflow report] The 'Running' status is not presented for pipeline steps
  src/common/ReactFlow/mlReactFlow.scss
  src/common/ReactFlow/mlReactFlow.util.js
  src/scss/colors.scss
  src/utils/getState.js
Labels: bug

#1090 Fix [Jobs] Add fix for jobs routing
  src/App.js
  src/components/Details/DetailsView.js
  src/components/Jobs/Jobs.js
  src/components/Jobs/JobsView.js
Labels: bug

#1091 Fix [UI][Feature Vector] Missing loader on Add to Feature Vector screen
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
Labels: bug

#1092 Fix [Feature Vector] MLRunAccessDeniedError` for creating Feature Vector by user where user is member with viewer role
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
Labels: bug

#1093 Impl [Feature Sets] Add Google storage to the data source dropdown in the feature store
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.util.js
Labels: enhancement

#1094 QA Sprint 134 done
  package.json
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/common.action.js
  tests/features/common/actions/graph.action.js
  tests/features/common/actions/tab-selector.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/commonPagesHeader.po.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/project-settings.po.js
  tests/features/common/page-objects/project.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectPage.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/features/support/hooks.js
  tests/mockServer/mock.js
Labels: tests

#1095 Fix [Artifacts] Click on show details doesn't open the right info
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
Labels: bug

#1096 Fix [Jobs] Filter by date resets when choosing a job
  src/components/Jobs/Jobs.js
Labels: bug

#1097 Fix [Jobs] The 'Run' job and Rerun job options are available for project user with role "viewer"
  src/actions/jobs.js
  src/common/ErrorMessage/ErrorMessage.js
  src/common/ErrorMessage/errorMessage.scss
Labels: bug

#1098 Fix [Jobs] MLRun-kit when re-running a job the UI automatically sets the default_artifact_path to v3io
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanel/panelReducer.js
  src/constants.js
Labels: bug

#1086 Impl [Project Settings] Screen Revamp
  src/actions/projects.js
  src/common/Chip/chip.scss
  src/common/ChipCell/chipCell.scss
  src/common/ChipForm/chipForm.scss
  src/common/Input/Input.js
  src/common/Input/Input.stories.js
  src/common/Input/input.scss
  src/common/KeyValueTable/KeyValueTable.js
  src/common/KeyValueTable/KeyValueTableView.js
  src/common/KeyValueTable/keyValueTable.scss
  src/common/OptionsMenu/ValidationTemplate/ValidationTemplate.js
  src/common/PopUpDialog/popUpDialog.scss
  src/common/TextArea/TextArea.js
  src/common/TextArea/textArea.scss
  src/components/Project/ProjectDescription/ProjectDescription.js
  src/components/Project/ProjectGoals/ProjectGoals.js
  src/components/Project/ProjectMonitor.js
  src/components/Project/ProjectMonitorView.js
  src/components/Project/project.scss
  src/components/ProjectSettings/ProjectSettings.js
  src/components/ProjectSettings/projectSettings.scss
  src/components/ProjectSettings/projectSettings.util.js
  src/constants.js
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
  src/elements/ChangeOwnerPopUp/changeOwnerPopUp.scss
  src/elements/ContentMenu/ContentMenu.js
  src/elements/ContentMenu/contentMenu.scss
  src/elements/CreateNewSecretPopUp/CreateNewSecretPopUp.js
  src/elements/CreateNewSecretPopUp/createNewSecretPopUp.scss
  src/elements/MembersPopUp/MembersPopUp.js
  src/elements/MembersPopUp/membersPopUp.scss
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js
  src/elements/ProjectSettingsGeneral/projectSettingsGeneral.scss
  src/elements/ProjectSettingsGeneral/projectSettingsGeneral.utils.js
  src/elements/ProjectSettingsMembers/ProjectSettingsMembers.js
  src/elements/ProjectSettingsMembers/ProjectSettingsMembers.scss
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecrets.js
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecrets.scss
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecrets.utils.js
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecretsView.js
  src/elements/ProjectSettingsSource/ProjectSettingsSource.js
  src/elements/ProjectSettingsSource/projectSettingsSource.scss
  src/elements/ValidationTemplate/ValidationTemplate.js
  src/elements/ValidationTemplate/ValidationTemplate.scss
  src/images/lock-icon.svg
  src/layout/Navbar/Navbar.js
  src/reducers/projectReducer.js
  src/scss/mixins.scss
  src/types.js
Labels: enhancement, Cleanup

#1100 Fix [Project Settings] Modal close button color
  src/common/PopUpDialog/popUpDialog.scss
Labels: bug

#1099 Fix [Models] Real-time pipeline view the rectangle are too small
  src/common/ReactFlow/mlReactFlow.scss
  src/common/ReactFlow/mlReactFlow.util.js
  src/layout/Content/content.scss
Labels: bug

#1101 Cleanup [navbar] change match props to projectName
  src/elements/NavbarLink/NavbarLink.js
  src/layout/Navbar/Navbar.js
  src/layout/Navbar/Navbar.utils.js
  src/layout/Page/PageView.js
Labels: Cleanup

#1102 Fix [General] UI bugs
  src/common/Input/Input.js
  src/components/ProjectsPage/projects.scss
  src/elements/ProjectSettingsMembers/ProjectSettingsMembers.js
Labels: bug, enhancement

#1103 Impl [Project Monitor] optimize the project overview screen
  src/actions/projects.js
  src/api/projects-api.js
Labels: enhancement

#1108 Fix [Settings] members discard button stays clickable no matter what action is done
  src/elements/MembersPopUp/MembersPopUp.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js
Labels: bug

#1110 Fix [Jobs] Monitor Jobs crash when undefined (reading 'value')
  src/components/Table/Table.js
  src/components/Table/TableView.js
Labels: bug

#1112 Fix [Jobs] Monitor Jobs crash when undefined (reading 'value') [Backport 0.10.x]
  src/components/Table/Table.js
  src/components/Table/TableView.js
Labels: bug

#1109 Fix [Settings] display members count
  src/common/KeyValueTable/keyValueTable.scss
  src/components/ProjectSettings/projectSettings.scss
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
  src/elements/ProjectSettingsMembers/ProjectSettingsMembers.js
Labels: bug

#1114 Fix [Models] Details panel closes unexpectedly
  src/components/FeatureStore/FeatureStore.js
  src/components/Files/Files.js
  src/components/Files/files.util.js
  src/components/Models/Models.js
  src/hooks/useGetTagOptions.hook.js
Labels: bug
