Repository mlrun/ui, pull requests merged in 2022-04, with the labels that each got.

#1186 Fix [Functions] Empty default value of Pod priority field
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
Labels: bug

#1187 Fix [Functions] The handler of ML function is empty for function deployed from Jupyter
  src/components/FunctionsPanel/FunctionsPanel.js
  src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
Labels: bug

#1189 Fix [Feature Vector] The Filter for "latest" tag presents all tags
  src/components/Datasets/Datasets.js
  src/components/FeatureStore/FeatureStore.js
  src/components/Files/Files.js
  src/components/Models/Models.js
Labels: bug

#1188 Fix [Feature Sets] Wrong default Path for Online and Offline Target store
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
  src/components/FeatureSetsPanel/FeatureSetsPanelView.js
  src/reducers/featureStoreReducer.js
Labels: bug

#1191 Fix [Consumer groups] Wrong value presents for Stream
  src/components/ConsumerGroups/consumerGroups.util.js
  src/utils/createConsumerGroupsContent.js
  src/utils/parseV3ioStreams.js
Labels: bug

#1192 Fix [MLRun] Pod priority UI values
  src/common/Select/Select.js
  src/components/JobsPanelResources/JobsPanelResources.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
  src/utils/generateFunctionPriorityLabel.js
Labels: bug

#1190 Fix [UI] layout in small resolutions
  src/common/ChipCell/ChipCell.js
  src/components/Models/models.util.js
  src/components/Project/project.scss
  src/components/ProjectSettings/projectSettings.scss
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projects.scss
  src/layout/Content/content.scss
  src/layout/Navbar/Navbar.scss
  src/layout/Page/PageView.js
  src/layout/Page/PageView.scss
  src/scss/main.scss
  src/utils/createFunctionsContent.js
Labels: bug

#1194 Fix [Models] Chips are not resized when toggling left menu
  src/common/ChipCell/ChipCell.js
  src/layout/Page/PageView.js
  src/utils/getTransitionEndEventName.js
Labels: bug

#1195 Fix [Feature Vector] Missing feature_label icon in the feature list after Feature vector creation
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
  src/components/DetailsRequestedFeatures/detailsRequestedFeatures.scss
  src/components/DetailsRequestedFeatures/detailsRequestedFeatures.utils.js
Labels: bug

#1197 Fix [UI] Pod priority is changed to default (Medium) after running a mlrun function
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#1196 Fix [Feature Set Panel] Problem with validation on save
  src/common/Combobox/Combobox.js
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelView.js
  src/components/FeatureSetsPanel/featureSetPanel.util.js
Labels: bug

#1199 Fix [Consumer groups] No data in consumer group report due to wrong API request
  src/utils/createConsumerGroupsContent.js
  src/utils/parseV3ioStreams.js
Labels: bug

#1198 Impl [UI] Support pod tolerations for all functions
  src/actions/functions.js
  src/actions/jobs.js
  src/components/Jobs/jobs.util.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanel/panelReducer.js
  src/components/JobsPanelResources/JobsPanelResources.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/constants.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
  src/elements/FunctionsPanelResources/functionsPanelResources.scss
  src/reducers/functionReducer.js
  src/reducers/jobReducer.js
  src/utils/panelResources.util.js
Labels: enhancement

#1200 Fix [Feature Store] Add to feature vector - Incorrect right panel height
  src/components/Table/Table.js
Labels: bug

#1201 Fix related to #1200
  src/components/Table/Table.js
  src/layout/Page/PageView.js
  src/layout/Page/PageView.scss
Labels: bug

#1205 Fix [Consumer groups] Unnecessary YAML file for consumer groups page
  src/components/ConsumerGroup/ConsumerGroup.js
  src/components/ConsumerGroup/consumerGroup.util.js
  src/components/ConsumerGroups/ConsumerGroups.js
  src/components/ConsumerGroups/consumerGroups.util.js
  src/components/Table/TableView.js
  src/elements/ConsumerGroupShardLagTableRow/ConsumerGroupShardLagTableRow.js
  src/elements/ConsumerGroupTableRow/ConsumerGroupTableRow.js
Labels: bug

#1206 Fix [Consumer groups] Consumer Group search should be insensitive
  src/components/ConsumerGroup/ConsumerGroup.js
  src/components/ConsumerGroups/ConsumerGroups.js
Labels: bug

#1204 Impl [tests] QA Sprint 136
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/api.actions.js
  tests/features/common/actions/input-with-autocomplete.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/components/input-with-autocomplete.component.js
  tests/features/common/components/table.component.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/commonPagesHeader.po.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/project-settings.po.js
  tests/features/common/page-objects/project.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectPage.feature
  tests/features/projectSettings.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/frontendSpec.json
  tests/mockServer/mock.js
Labels: tests

#1207 Impl [tests] QA Sprint 136
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/api.actions.js
  tests/features/common/actions/input-with-autocomplete.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/components/input-with-autocomplete.component.js
  tests/features/common/components/table.component.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/commonPagesHeader.po.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/project-settings.po.js
  tests/features/common/page-objects/project.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectPage.feature
  tests/features/projectSettings.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/frontendSpec.json
  tests/mockServer/mock.js
Labels: tests

#1208 Fix [Feature Vector] MLRunAccessDeniedError` for creating Feature Vector by user where user is member with viewer role
  src/elements/FeaturesTablePanel/FeaturesTablePanel.js
Labels: bug

#1212 Fix [UI] Create a feature set from the UI where the source is parqueton V3io fail
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
Labels: bug

#1213 Fix [Monitor jobs] Wrong iteration number
  src/components/Details/details.util.js
  src/components/Jobs/jobs.util.js
Labels: bug

#1210 Fix [UI] Table row - Keep 3 dots Icon visible while menu is open
  src/common/ActionsMenu/ActionsMenu.js
  src/common/ActionsMenu/actionsMenu.scss
  src/common/RoundedIcon/RoundedIcon.js
  src/common/RoundedIcon/roundedIcon.scss
Labels: enhancement

#1214 Fix [Functions] `MLRunAccessDeniedError` for creating ML Function by user where user is member with viewer role
  src/actions/featureStore.js
  src/actions/functions.js
  src/actions/jobs.js
  src/components/Jobs/Jobs.js
Labels: bug

#1218 Fix [Consumer group] drill down text when 0 streams
  src/components/ConsumerGroups/ConsumerGroups.js
Labels: bug

#1219 Fix [Consumer group] drill down text when 0 streams
  src/components/ConsumerGroups/ConsumerGroups.js
Labels: bug

#1220 Fix [MLRun] User can't reset to default CPU limit/request value
  src/common/Input/Input.js
  src/common/RangeInput/RangeInput.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/components/JobsPanelResources/jobsPanelResources.util.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
  src/elements/FunctionsPanelResources/functionsPanelResources.util.js
Labels: bug

#1221 Fix [MLRun] User can't reset to default CPU limit/request value
  src/common/Input/Input.js
  src/common/RangeInput/RangeInput.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/components/JobsPanelResources/jobsPanelResources.util.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
  src/elements/FunctionsPanelResources/functionsPanelResources.util.js
Labels: bug

#1216 Fix [Jobs] misleading 'PODS TOLERATION' in mlrun UI job wizard
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
  src/elements/FunctionsPanelResources/functionsPanelResources.scss
Labels: bug

#1217 Fix [Jobs] misleading 'PODS TOLERATION' in mlrun UI job wizard
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
  src/elements/FunctionsPanelResources/functionsPanelResources.scss
Labels: bug

#1226 Fix [Jobs Panel] Dataset input interaction in the jobs wizard is broken
  src/common/Combobox/Combobox.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/utils/panelPathScheme.js
Labels: bug

#1225 Fix [Jobs Panel] Dataset input interaction in the jobs wizard is broken
  src/common/Combobox/Combobox.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputs.js
  src/utils/panelPathScheme.js
Labels: bug

#1224 Fix [UI] Projects summaries show N/A in environment without Nuclio
  src/App.js
  src/common/Input/Input.js
  src/components/Project/ProjectMonitor.js
  src/components/Project/ProjectMonitorView.js
  src/components/ProjectsPage/Projects.js
  src/elements/ProjectFunctions/ProjectFunctions.js
  src/elements/ProjectSummaryCard/ProjectSummaryCard.js
  src/hooks/nuclioMode.hook.js
Labels: bug

#1223 Fix [UI] Projects summaries show N/A in environment without Nuclio
  src/App.js
  src/components/Project/ProjectMonitor.js
  src/components/Project/ProjectMonitorView.js
  src/components/ProjectsPage/Projects.js
  src/elements/ProjectFunctions/ProjectFunctions.js
  src/elements/ProjectSummaryCard/ProjectSummaryCard.js
  src/hooks/nuclioMode.hook.js
Labels: bug

#1227 Fix [UI] Projects summaries show N/A in environment without Nuclio
  src/components/Project/ProjectMonitorView.js
  src/elements/ProjectSummaryCard/ProjectSummaryCard.js
Labels: bug

#1228 Fix [UI] Projects summaries show N/A in environment without Nuclio
  src/components/Project/ProjectMonitorView.js
  src/elements/ProjectFunctions/ProjectFunctions.js
  src/elements/ProjectSummaryCard/ProjectSummaryCard.js
Labels: bug

#1229 Fix [Project Monitoring] The main project screen doesn't show the status for all running jobs
  src/actions/projects.js
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#1230 Fix [Project Monitoring] The main project screen doesn't show the status for all running jobs
  src/actions/projects.js
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#1231 Fix [Jobs Panel] The Pods Priority dropdown doesn't have selected value
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#1232 Fix [Jobs Panel] The Pods Priority dropdown doesn't have selected value
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#1240 Fix [UI] removed duplicated libraries
  package.json
Labels: Cleanup

#1241 Impl [UI] Missing unit in the New MLRun function and New job wizard and wrong handling of defaults
  src/common/Input/Input.js
  src/common/RangeInput/RangeInput.js
  src/components/FunctionsPanel/functionsPanel.scss
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanel/panelReducer.js
  src/components/JobsPanelAdvanced/JobsPanelAdvancedView.js
  src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
  src/components/JobsPanelParameters/JobsPanelParametersView.js
  src/components/JobsPanelResources/JobsPanelResources.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/components/JobsPanelResources/jobsPanelResources.util.js
  src/elements/EnvironmentVariables/EnvironmentVariablesView.js
  src/elements/FunctionsPanelAdvanced/FunctionsPanelAdvanced.js
  src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
  src/elements/FunctionsPanelEnvironmentVariables/FunctionsPanelEnvironmentVariablesView.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js
  src/elements/FunctionsPanelParameters/FunctionsPanelParametersView.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
  src/elements/FunctionsPanelResources/functionsPanelResources.scss
  src/elements/FunctionsPanelResources/functionsPanelResources.util.js
  src/elements/FunctionsPanelRuntime/FunctionsPanelRuntimeView.js
  src/elements/FunctionsPanelSecrets/FunctionsPanelSecretsView.js
  src/elements/FunctionsPanelSection/functionsPanelSection.scss
  src/elements/FunctionsPanelTopology/FunctionsPanelTopologyView.js
  src/elements/JobsPanelSection/JobsPanelSection.js
  src/elements/PanelResourcesUnits/PanelResourcesUnits.js
  src/elements/PanelResourcesUnits/panelResourcesUnits.scss
  src/elements/PanelSection/PanelSection.js
  src/elements/PanelSection/panelSection.scss
  src/reducers/functionReducer.js
  src/utils/panelResources.util.js
Labels: enhancement

#1239 Fix [UI] Header flicker while navigating
  package.json
  src/App.js
  src/common/Loader/loader.scss
  src/components/CreateJobPage/createJobPage.scss
  src/layout/Header/header.scss
  src/layout/Navbar/Navbar.scss
  src/layout/Page/Page.js
  src/layout/Page/PageView.js
  src/scss/main.scss
Labels: bug

#1242 Impl [UI] Missing unit in the New MLRun function and New job wizard and wrong handling of defaults
  src/utils/panelResources.util.js
Labels: enhancement

#1245 Fix [Jobs] Selecting a method in the new job panel cause a hang
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#1238 Impl [tests] QA Sprint 136 (new tests)
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common-tools/common-tools.js
  tests/features/common/actions/api.actions.js
  tests/features/common/actions/common.action.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/api.steps.js
  tests/features/step-definitions/steps.js
  tests/mockServer/mock.js
Labels: tests

#1246 Impl [tests] QA Sprint 136 Done
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common-tools/common-tools.js
  tests/features/common/actions/api.actions.js
  tests/features/common/actions/common.action.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/api.steps.js
  tests/features/step-definitions/steps.js
  tests/mockServer/mock.js
Labels: tests

#1248 [Bug] Fixed conflicting order between styles
  config/webpack.config.js
Labels: bug

#1247 Fix [Functions] missing spot drop down in update existing mlrun function screen
  src/components/FunctionsPanel/FunctionsPanel.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
  src/utils/parseFunction.js
Labels: bug

#1249 Fix [Schedule Job] The 'Request failed with status code 400' presents for same scheduler set
  src/actions/jobs.js
Labels: bug
