Repository mlrun/ui, pull requests merged in 2022-06, with the labels that each got.

#1290 Impl [Workflows] Change steps color in the workflow to reflect their status
  src/common/ReactFlow/MlReactFlow.js
  src/common/ReactFlow/mlReactFlow.scss
  src/components/Workflow/Workflow.js
Labels: enhancement

#1292 Fix [Models] Register model doesn't post Target path
  src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
Labels: bug

#1293 Fix [Models] Wrong naming convention for Model URI in overview screen
  src/utils/resources.js
Labels: bug

#1291 Cleanup [Feature store] Feature store refactoring
  src/App.js
  src/api/featureStore-api.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorView.js
  src/components/AddToFeatureVectorPage/addToFeatureVectorPage.util.js
  src/components/Details/Details.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureSets/FeatureSetsView.js
  src/components/FeatureStore/FeatureSets/featureSets.util.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
  src/components/FeatureStore/FeatureVectors/FeatureVectorsView.js
  src/components/FeatureStore/FeatureVectors/featureVectors.util.js
  src/components/FeatureStore/Features/Features.js
  src/components/FeatureStore/Features/FeaturesView.js
  src/components/FeatureStore/Features/features.util.js
  src/components/FeatureStore/featureStore.scss
  src/components/FeatureStore/featureStore.util.js
  src/components/FilterMenu/FilterMenu.js
  src/components/Jobs/Jobs.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorJobs/MonitorJobsView.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflowsView.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/components/Jobs/ScheduledJobs/ScheduledJobsView.js
  src/components/Jobs/ScheduledJobs/scheduledJobs.util.js
  src/components/Jobs/jobs.util.js
  src/components/Table/Table.js
  src/components/Table/TableHead.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/components/Workflow/Workflow.js
  src/components/Workflow/workflow.util.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/FeatureStoreTableRow/FeatureStoreTableRow.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/elements/JobTable/JobsTable.js
  src/elements/TableCell/TableCell.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/elements/TableLinkCell/tableLinkCell.scss
  src/hooks/groupContent.hook.js
  src/layout/Content/Content.js
  src/layout/Content/content.util.js
  src/utils/createFeatureStoreContent.js
  src/utils/createJobsContent.js
  src/utils/getUniqueIdentifier.js
Labels: Cleanup

#1296 Impl [tests] QA Sprint 138 Done
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common-tools/common-tools.js
  tests/features/common/actions/table.action.js
  tests/features/common/components/text-area.component.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectPage.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/backendSynchronizator.js
  tests/mockServer/data/modelEndpoints.json
  tests/mockServer/data/run.json
  tests/mockServer/data/runs.json
  tests/mockServer/mock.js
Labels: tests

#1297 Fix [Jobs] Resolve broken path
  src/components/Jobs/Jobs.js
Labels: bug

#1299 Fix [Jobs] Blank screen on trying to access Monitor Workflows
  src/components/Jobs/Jobs.js
Labels: bug

#1301 Fix [Jobs] Filters resets after selecting a job
  src/components/Jobs/MonitorJobs/MonitorJobsView.js
Labels: bug

#1300 Fix [ChipCell] prevent component re-render on tabs hover
  src/layout/Page/PageView.js
Labels: bug

#1302 Fix [Jobs] Run now button looks like drop down
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
Labels: bug

#1303 Fix [Jobs] Chips overflows table
  src/components/ConsumerGroups/consumerGroups.util.js
  src/components/Table/table.scss
  src/elements/TableLinkCell/TableLinkCell.js
  src/elements/TableLinkCell/tableLinkCell.scss
  src/utils/createFeatureStoreContent.js
  src/utils/createJobsContent.js
Labels: bug

#1304 Fix [Models] Downloaded model file from "Project-> models" has base64 format instead of pkl
  src/common/Download/Download.js
Labels: bug

#1305 Fix [Functions] Wrong Pods Priority value sent
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
Labels: bug

#1306 Fix [UI] blank screen on attempt to archive project
  package.json
  src/common/Select/Select.js
  src/components/Details/DetailsView.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeaturesView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelView.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/components/Jobs/Jobs.js
  src/components/Project/ProjectMonitorView.js
  src/components/Project/ProjectOverview/ProjectOverview.js
  src/components/ProjectsPage/ProjectsView.js
  src/elements/MembersPopUp/MembersPopUp.js
Labels: bug

#1308 Fix [Functions Panel] Issues with editing rows
  src/elements/EnvironmentVariables/AddEnvironmentVariablesRow.js
  src/elements/EnvironmentVariables/EditableEnvironmentVariablesRow.js
  src/elements/EnvironmentVariables/environmentVariables.util.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelSecrets/FunctionsPanelSecrets.js
Labels: bug

#1307 Impl [UI] Cosmetic 1.1.0
  src/common/ReactFlow/mlReactFlow.scss
  src/components/ArtifactsPreview/artifactsPreview.scss
  src/components/Datasets/Datasets.js
  src/components/Datasets/datasets.util.js
  src/components/Details/DetailsView.js
  src/components/Details/details.scss
  src/components/Details/details.util.js
  src/components/DetailsFeaturesAnalysis/DetailsFeaturesAnalysis.js
  src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.scss
  src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.util.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsResults/detailsResults.scss
  src/components/FeatureStore/Features/FeaturesView.js
  src/components/Files/Files.js
  src/components/Files/files.util.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projectsData.js
  src/utils/generateProducerDetailsInfo.js
  src/utils/parseJob.js
Labels: enhancement

#1311 Fix [Models endpoints] tip text mistake
  src/components/FeatureStore/FeatureSets/featureSets.util.js
Labels: bug

#1312 Fix [Models] The Model page isn't open when log_model run without tag
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/reducers/detailsReducer.js
Labels: bug

#1250 Impl [Models] Deploy model to a serving function
  .eslintrc.js
  config/webpack.config.js
  package.json
  src/common/Backdrop/Backdrop.js
  src/common/Backdrop/Backdrop.scss
  src/common/Input/Input.js
  src/common/Input/Input.stories.js
  src/common/Input/input.scss
  src/common/KeyValueTable/keyValueTable.scss
  src/common/Loader/loader.scss
  src/common/Modal/Modal.js
  src/common/Modal/Modal.scss
  src/components/DetailsRequestedFeatures/DetailsRequestedFeaturesView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
  src/components/Models/Models.js
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
  src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
  src/elements/DeployModelPopUp/DeployModelPopUp.js
  src/elements/DeployModelPopUp/deployModelPopUp.scss
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/elements/NewFunctionPopUp/NewFunctionPopUp.js
  src/elements/RegisterArtifactForm/RegisterArtifactForm.js
  src/index.js
  src/layout/Header/header.scss
Labels: enhancement

#1316 Fix [UI] Input and textarea style
  src/common/Input/input.scss
  src/common/TextArea/textArea.scss
  src/elements/ProjectSettingsGeneral/projectSettingsGeneral.scss
  src/scss/main.scss
Labels: bug

#1318 Fix [Workflows] App crash on Workflow re-run
  src/common/DatePicker/DatePickerView.js
  src/common/DatePicker/datePicker.scss
  src/components/Jobs/MonitorJobs/MonitorJobsView.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflowsView.js
  src/components/Jobs/ScheduledJobs/ScheduledJobsView.js
Labels: bug

#1320 Impl [Pkg] Support pushing to multiple registries in github actions build workflow
  .github/workflows/build.yaml
Labels: enhancement

#1322 Impl [tests] QA Sprint 139 Done
  package.json
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common-tools/common-tools.js
  tests/features/common/actions/api.actions.js
  tests/features/common/actions/input-group.action.js
  tests/features/common/actions/radio-button.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/components/text-area.component.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectPage.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/api.steps.js
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/modelEndpoints.json
  tests/mockServer/mock.js
Labels: tests
