Repository mlrun/ui, pull requests merged in 2022-01, with the labels that each got.

#1002 [Create new job] Add required to validation rules
  src/common/Breadcrumbs/Breadcrumbs.js
  src/common/Input/Input.js
  src/constants.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/utils/validationService.js
Labels: enhancement

#1003 [General] Wrong presentation for tooltips with new lines (fixed tooltip width)
  src/elements/TooltipTemplate/TextTooltipTemplate.js
Labels: bug

#1004 [Jobs Panel] Tip icon overflows container
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanelDataInputs/JobsPanelDataInputsView.js
  src/components/JobsPanelParameters/JobsPanelParametersView.js
Labels: bug

#1010 [Workflow jobs] Add highlighting to the connection lines
  src/common/ReactFlow/FloatingEdge.js
  src/common/ReactFlow/MlReactFlow.js
  src/common/ReactFlow/MlReactFlowEdge.js
  src/common/ReactFlow/mlReactFlow.scss
  src/common/ReactFlow/mlReactFlow.util.js
  src/components/DetailsTransformations/DetailsTransformations.js
  src/components/Pipeline/Pipeline.js
  src/components/Workflow/Workflow.js
  src/constants.js
Labels: enhancement

#1012 [General] Missing validation on panel
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitle.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelView.js
  src/components/FeatureSetsPanel/featureSetPanel.util.js
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/components/JobsPanelDataInputs/jobsPanelDataInputs.util.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/elements/FunctionsPanelAdvanced/FunctionsPanelAdvanced.js
  src/elements/FunctionsPanelCode/FunctionsPanelCode.js
  src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
  src/elements/FunctionsPanelRuntime/FunctionsPanelRuntime.js
  src/elements/FunctionsPanelRuntime/FunctionsPanelRuntimeView.js
  src/elements/JobsPanelDataInputsTable/JobsPanelDataInputsTable.js
  src/elements/NewFunctionPopUp/NewFunctionPopUp.js
  src/elements/PartitionFields/PartitionFields.js
Labels: bug

#1013 [Create Feature Set panel] Click on "Save"/ "Save and ingest" buttons doesn`t validate combobox
  src/common/Combobox/Combobox.js
Labels: bug

#1014 [Add to Feature Vector] Strange accordion button animation
  src/components/DetailsTransformations/detailsTransformations.scss
  src/elements/FeaturesTablePanel/featuresTablePanel.scss
Labels: bug

#1015 [General] Chip value overflows chip body
  src/common/ChipCell/ChipCellView.js
Labels: bug

#1016 Feature sets labels in the UI
  src/components/FeatureStore/featureStore.util.js
  src/utils/parseFeatureSets.js
Labels: bug

#1017 [Jobs workflow report] Rerun job failed with FileNotFoundError
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#1019 UI][Feature Vector] Tag setting issues for FV during creation and editing
  src/common/Tooltip/Tooltip.js
  src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
Labels: bug

#1024 Adding multiple labels from the UI doesn't work for a feature set
  src/components/Details/Details.js
  src/components/Details/details.util.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/DetailsInfo/detailsInfoReducer.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
  src/components/Project/ProjectMonitorView.js
  src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/elements/DetailsInfoItemChip/DetailsInfoItemChip.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
Labels: bug

#1021 Fix [project][general][setting][UI] aritfact path can't be saved
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js
Labels: bug

#1020 Fix [Projects] Tooltip text width and created time to UTC
  src/common/Tooltip/tooltip.scss
  src/components/Project/ProjectAction/ProjectAction.scss
  src/components/Project/ProjectOverview/ProjectOverview.scss
  src/components/ProjectsPage/projects.scss
  src/elements/TooltipTemplate/TextTooltipTemplate.js
  src/scss/colors.scss
  src/scss/main.scss
  src/utils/datetime.js
Labels: bug

#1023 Impl [Projects] Add labels to new project wizard
  src/actions/projects.js
  src/common/ChipCell/ChipCell.js
  src/common/ChipCell/ChipCellView.js
  src/components/Project/ProjectLabels/ProjectLabels.js
  src/components/Project/ProjectMonitor.js
  src/components/Project/ProjectMonitorView.js
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
  src/components/ProjectsPage/CreateProjectDialog/createProjectDialog.scss
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/constants.js
  src/elements/ProjectCard/ProjectCardView.js
  src/reducers/projectReducer.js
Labels: enhancement

#1031 [UI][Feature Vector] Delete Feature vector option is missing in the List of FVs screen
  src/actions/featureStore.js
  src/api/featureStore-api.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
  src/components/FilterMenu/FilterMenu.js
Labels: bug

#1041 QA sprint 132 done
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common-tools/common-tools.js
  tests/features/common/actions/common.action.js
  tests/features/common/actions/dropdown.action.js
  tests/features/common/actions/input-group.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/components/action-menu.component.js
  tests/features/common/components/breadcrumbs.component.js
  tests/features/common/components/combo-box.component.js
  tests/features/common/components/dropdown.component.js
  tests/features/common/components/input-group.component.js
  tests/features/common/components/label.component.js
  tests/features/common/components/number-input-group.component.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/ml-functions.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/project-settings.po.js
  tests/features/common/page-objects/project.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectPage.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/features/support/hooks.js
  tests/mockServer/backendSynchronizator.js
  tests/mockServer/mock.js
Labels: tests

#1040 [UI] Search for user in the 'Change owner' and 'Members' screens should be case insensitive
  src/elements/MembersPopUp/MembersPopUp.js
Labels: bug

#1044 Fix [Feature Sets] Wrong loader background
  src/actions/featureStore.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
  src/constants.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/FeatureStoreTableRow/FeatureStoreTableRow.js
  src/reducers/featureStoreReducer.js
Labels: bug

#1045 Fix [Jobs][Monitor] crash when "status.iterations" has a null value
  src/utils/resultsTable.js
Labels: bug

#1048 [Workflows] Wrong position of the graph
  src/common/ReactFlow/MlReactFlow.js
  src/components/JobsPage/Jobs.js
  src/components/Workflow/Workflow.js
Labels: bug

#1049 [UI][ML Function][Create Jobs] Does not open Action Menu for Volumes Table
  src/scss/mixins.scss
Labels: bug

#1057 [UI][Project Screen] Missing error message when archive action failed with error 403
  src/actions/projects.js
  src/components/ProjectsPage/Projects.js
Labels: bug

#1064 Impl [tests] Sprint 133
  package.json
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common-tools/common-tools.js
  tests/features/common-tools/utils.js
  tests/features/common/actions/api.actions.js
  tests/features/common/actions/common.action.js
  tests/features/common/actions/dropdown.action.js
  tests/features/common/actions/graph.action.js
  tests/features/common/actions/input-group.action.js
  tests/features/common/actions/input-with-autocomplete.action.js
  tests/features/common/actions/number-input-group.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/components/graph.component.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/ml-functions.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/project-settings.po.js
  tests/features/common/page-objects/project.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectPage.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/api.steps.js
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/features/support/hooks.js
  tests/mockServer/backendSynchronizator.js
  tests/mockServer/mock.js
Labels: tests
