Repository mlrun/ui, pull requests merged in 2022-03, with the labels that each got.

#1115 Impl [Consumer groups] Add a new report: Streaming consumer group for v3io stream
  src/App.js
  src/actions/nuclio.js
  src/api/nuclio.js
  src/common/Input/input.scss
  src/common/Modal/Modal.scss
  src/common/PopUpDialog/popUpDialog.scss
  src/common/RoundedIcon/roundedIcon.scss
  src/common/Search/Search.js
  src/common/Search/search.scss
  src/components/ConsumerGroup/ConsumerGroup.js
  src/components/ConsumerGroup/consumerGroup.util.js
  src/components/ConsumerGroups/ConsumerGroups.js
  src/components/ConsumerGroups/consumerGroups.util.js
  src/components/ConsumerGroupsWrapper/ConsumerGroupsWrapper.js
  src/components/Jobs/jobs.util.js
  src/components/Project/ProjectAction/ProjectAction.scss
  src/components/Project/ProjectMonitor.js
  src/components/Project/ProjectMonitorView.js
  src/components/Project/ProjectOverview/ProjectOverview.scss
  src/components/Project/project.scss
  src/components/ProjectsPage/projects.scss
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/constants.js
  src/elements/ConsumerGroupShardLagTableRow/ConsumerGroupShardLagTableRow.js
  src/elements/ConsumerGroupTableRow/ConsumerGroupTableRow.js
  src/elements/ContentMenu/contentMenu.scss
  src/elements/NavbarLink/NavbarLink.scss
  src/elements/PageHeader/PageHeader.js
  src/elements/PageHeader/pageHeader.scss
  src/elements/ProjectCard/projectCard.scss
  src/elements/ProjectSummaryCard/ProjectSummaryCard.js
  src/elements/TableCell/TableCell.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/httpClient.js
  src/layout/Navbar/Navbar.scss
  src/layout/Page/PageView.scss
  src/reducers/nuclioReducer.js
  src/reducers/projectReducer.js
  src/scss/main.scss
  src/scss/variables.scss
  src/utils/createConsumerGroupContent.js
  src/utils/createConsumerGroupsContent.js
  src/utils/generateTableContent.js
  src/utils/getUniqueIdentifier.js
  src/utils/parseV3ioStreamShardLags.js
  src/utils/parseV3ioStreams.js
Labels: enhancement

#1116 Fix [Realtime Pipelines] Duplicated real time function
  src/components/Models/models.util.js
Labels: bug

#1117 Impl [Project Members] revamp invite new member
  src/components/ProjectSettings/ProjectSettings.js
  src/elements/ChangeOwnerPopUp/changeOwnerPopUp.scss
  src/elements/MembersPopUp/MembersPopUp.js
  src/elements/MembersPopUp/membersPopUp.scss
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js
  src/elements/ProjectSettingsGeneral/projectSettingsGeneral.scss
  src/elements/ProjectSettingsMembers/ProjectSettingsMembers.js
Labels: enhancement

#1118 Impl [UI] Change to use versioned API paths
  src/httpClient.js
Labels: bug

#1119 Impl [Project Settings] Add a proper error message for the secret tab upon permission issue
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
  src/elements/MembersPopUp/MembersPopUp.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecrets.js
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecretsView.js
Labels: enhancement

#1120 Fix [UI][Feature Store] Wrong request for tags
  src/components/FeatureStore/FeatureStore.js
Labels: bug

#1122 Fix [Jobs] Monitor workflows shows small subset of the full list of workflows
  src/components/Jobs/Jobs.js
  src/components/Table/Table.js
Labels: bug

#1121 Fix [Jobs] Monitor workflows shows small subset of the full list of workflows
  src/components/Jobs/Jobs.js
  src/components/Table/Table.js
Labels: bug

#1123 Impl [Projects] card border color
  src/elements/ProjectCard/projectCard.scss
  src/scss/mixins.scss
Labels: enhancement

#1124 Fix [Jobs] Hyper parameters task run isn't presented properly
  src/api/jobs-api.js
Labels: bug

#1125 Fix [Settings] members has instead of have(plural) for other than one member
  src/elements/ProjectSettingsMembers/ProjectSettingsMembers.js
Labels: bug

#1127 Fix [Jobs] Hyper parameters task run isn't presented properly
  src/api/jobs-api.js
  src/components/Jobs/Jobs.js
Labels: bug

#1129 Impl [Jobs] MLRun Pods priority
  src/actions/functions.js
  src/actions/jobs.js
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/Jobs/jobs.util.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanel/panelReducer.js
  src/components/JobsPanelResources/JobsPanelNodeSelector/JobsPanelNodeSelector.js
  src/components/JobsPanelResources/JobsPanelResources.js
  src/components/JobsPanelResources/JobsPanelResourcesView.js
  src/components/JobsPanelResources/JobsPanelVolumes/JobsPanelVolumes.js
  src/constants.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
  src/elements/FunctionsPanelResources/functionsPanelResources.scss
  src/reducers/functionReducer.js
  src/reducers/jobReducer.js
  src/utils/parseFunction.js
Labels: enhancement

#1130 Fix [Jobs] The 'Schedule' options are available for project user with role "viewer"
  src/components/Jobs/Jobs.js
Labels: bug

#1128 Fix [Project secrets] once keys are added values appears empty
  src/common/KeyValueTable/KeyValueTableView.js
  src/common/KeyValueTable/keyValueTable.scss
  src/common/RoundedIcon/RoundedIcon.js
  src/common/RoundedIcon/roundedIcon.scss
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecrets.js
Labels: bug

#1131 Fix [Jobs] Loader doesn't appear
  src/components/DetailsLogs/DetailsLogs.js
Labels: bug

#1132 Fix [Project Monitor] Redirect to 'Projects' screen instead of staying in current project upon 'Register artifact'
  src/components/Project/ProjectMonitorView.js
Labels: bug

#1133 Fix [Settings] Missing Loader on Project Members
  src/common/DatePicker/DatePicker.js
  src/components/ProjectSettings/ProjectSettings.js
  src/elements/MembersPopUp/membersReducer.js
  src/elements/ProjectSettingsMembers/ProjectSettingsMembers.js
Labels: bug

#1134 Fix [Feature Vector] Missing Filters for Feature Set and Entity
  src/api/featureStore-api.js
  src/components/AddToFeatureVectorPage/addToFeatureVectorPage.util.js
  src/components/FilterMenu/FilterMenu.js
  src/constants.js
  src/reducers/filtersReducer.js
Labels: bug

#1135 Fix [Project Members] members tab exists in project settings when should not
  src/components/ProjectSettings/ProjectSettings.js
  src/components/ProjectSettings/projectSettings.util.js
  src/elements/ProjectSettingsMembers/ProjectSettingsMembers.js
Labels: bug

#1136 Fix [Feature Set] Feature set creation via UI failed with error 404
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FilterMenu/FilterMenu.js
Labels: bug

#1137 Fix [Project Settings Previous owner access annotation appears in owner settings section
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
  src/elements/ChangeOwnerPopUp/changeOwnerPopUp.scss
Labels: bug

#1143 Impl [Tests] Sprint 133 and 134 Done
  package.json
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common-tools/common-tools.js
  tests/features/common-tools/utils.js
  tests/features/common/actions/api.actions.js
  tests/features/common/actions/common.action.js
  tests/features/common/actions/dropdown.action.js
  tests/features/common/actions/graph.action.js
  tests/features/common/actions/input-group.action.js
  tests/features/common/actions/input-with-autocomplete.action.js
  tests/features/common/actions/number-input-group.action.js
  tests/features/common/actions/tab-selector.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/components/graph.component.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/commonPagesHeader.po.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/ml-functions.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/project-settings.po.js
  tests/features/common/page-objects/project.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectPage.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/api.steps.js
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/features/support/hooks.js
  tests/features/support/world.js
  tests/mockServer/mock.js
Labels: tests

#1138 Fix [Jobs] job run status is not being updated in "Monitor Jobs" tab
  src/api/jobs-api.js
  src/components/Jobs/Jobs.js
Labels: bug

#1139 Fix [Jobs] Clicking on artifacts return empty window and TypeError
  src/actions/jobs.js
Labels: bug

#1140 Fix [Jobs] Clicking on artifacts return empty window and TypeError
  src/actions/jobs.js
Labels: bug

#1144 Fix [Projects] Missing time indication for failed job/functions in the projects view
  src/elements/ProjectCard/projectCard.util.js
Labels: bug

#1145 Fix [Projects] Missing time indication for failed job/functions in the projects view
  src/elements/ProjectCard/projectCard.util.js
Labels: bug

#1146 Impl [tests] QA Sprint 135
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/dropdown.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects/commonPagesHeader.po.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/projectPage.feature
  tests/features/support/hooks.js
  tests/features/support/world.js
  tests/mockServer/backendSynchronizator.js
  tests/mockServer/mock.js
Labels: tests

#1149 Impl [tests] QA Sprint 135
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/dropdown.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects/commonPagesHeader.po.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/projectPage.feature
  tests/features/support/hooks.js
  tests/features/support/world.js
  tests/mockServer/backendSynchronizator.js
  tests/mockServer/mock.js
Labels: tests

#1148 Fix [Projects] Align the color of Create New button in projects > default
  src/components/Project/project.scss
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projects.scss
Labels: bug

#1150 Fix [Jobs] Missing No Data message
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsInputs/DetailsInputs.js
Labels: bug

#1147 Impl [Datasets] Move the dataset tab to the main menu
  src/App.js
  src/common/ActionsMenu/ActionsMenu.js
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/common/RoundedIcon/roundedIcon.scss
  src/components/Datasets/Datasets.js
  src/components/Datasets/datasets.util.js
  src/components/Details/Details.js
  src/components/Details/DetailsView.js
  src/components/Details/details.scss
  src/components/Details/details.util.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Project/ProjectMonitorView.js
  src/components/Table/TableView.js
  src/constants.js
  src/elements/DetailsMenu/detailsMenu.scss
  src/images/datasets-icon.svg
  src/layout/Navbar/Navbar.utils.js
  src/scss/main.scss
  src/utils/createArtifactsContent.js
  src/utils/generateTableContent.js
  src/utils/getUniqueIdentifier.js
  src/utils/parseUri.js
  src/utils/resources.js
  tests/features/common/page-objects/side-panel.po.js
Labels: enhancement

#1153 Fix [Projects] unclear error message on attempt to create project upon reaching projects amount limit
  src/actions/projects.js
  src/common/ErrorMessage/ErrorMessage.js
  src/common/ErrorMessage/errorMessage.scss
  src/common/PopUpDialog/popUpDialog.scss
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/components/FunctionsPanel/functionsPanel.scss
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.scss
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
  src/components/ProjectsPage/CreateProjectDialog/createProjectDialog.scss
  src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
  src/constants.js
Labels: bug

#1154 Fix [Jobs] App crashes on scheduled job deletion
  src/components/Jobs/Jobs.js
  src/utils/object.js
Labels: bug

#1155 Fix [Project Settings] Applying new owner should load main projects screen
  src/components/ProjectSettings/ProjectSettings.js
Labels: bug

#1156 Fix [Models] Empty features for model without feature vector
  src/components/Details/details.util.js
  src/components/DetailsMetadata/detailsMetadata.util.js
  src/components/DetailsStatistics/detailsStatistics.util.js
  src/components/Models/models.util.js
Labels: bug

#1158 Bug [Jobs workflow report] Wrong APIs are sent for all WF filters
  src/api/workflow-api.js
Labels: bug

#1157 Fix [Jobs workflow report] Wrong APIs are sent for all WF filters
  src/api/workflow-api.js
Labels: bug

#1159 Fix [Feature Set] Feature set creation via UI failed with error 404
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FilterMenu/FilterMenu.js
Labels: bug

#1162 Fix [Feature Vector] The Entity is missing in the FV presentation in UI
  src/components/Details/details.util.js
  src/components/FeatureStore/featureStore.util.js
  src/utils/createFeatureStoreContent.js
Labels: bug

#1164 Fix [Feature Vector] `MLRunAccessDeniedError` for creating Feature Set by user where user is member with viewer role
  src/actions/featureStore.js
  src/constants.js
Labels: bug

#1165 Fix [Monitor Workflows] The WF filter by name should work for part of name string
  src/api/workflow-api.js
  src/components/Jobs/JobsView.js
Labels: bug

#1163 Fix [Functions] The function status isn't updated by refresh button in the function drill down screen
  src/components/FunctionsPage/Functions.js
  src/components/JobsPanel/jobsPanel.util.js
  src/constants.js
  src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
  src/elements/FunctionsPanelCode/FunctionsPanelCode.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js
  src/utils/getFunctionLogs.js
  tests/features/common/actions/api.actions.js
Labels: bug

#1166 Impl [UI] Show default limits & requests for MLRun functions and services
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/JobsPanelView.js
  src/components/JobsPanel/jobsPanel.util.js
  src/components/JobsPanelResources/JobsPanelResources.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
Labels: enhancement

#1160 Impl [Consumer Groups] Show stream monitoring only for Iguazio systems and supporting nuclio versions
  src/actions/nuclio.js
  src/api/nuclio.js
  src/components/ConsumerGroupsWrapper/ConsumerGroupsWrapper.js
  src/components/Project/ProjectMonitor.js
  src/components/Project/ProjectMonitorView.js
  src/elements/PageHeader/PageHeader.js
  src/elements/PageHeader/pageHeader.scss
  src/utils/helper.js
  tests/mockServer/data/frontendSpec.json
Labels: enhancement

#1168 Fix [Artifact preview] Long names isn't cropped
  src/components/Details/details.scss
  src/elements/PreviewModal/PreviewModal.js
Labels: bug

#1169 Fix [Datasets] Show iterations checkbox doesn't work
  src/components/AddToFeatureVectorPage/addToFeatureVectorPage.util.js
  src/components/Datasets/Datasets.js
  src/components/Datasets/datasets.util.js
  src/components/FeatureStore/featureStore.util.js
Labels: bug

#1167 Impl [Project settings] align tabs view by Figma
  src/components/ProjectsPage/projects.scss
  src/elements/ContentMenu/contentMenu.scss
Labels: enhancement

#1174 Fix [Feature vector] Create Feature vector API failed when Feature tag inсludes dot
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
  src/utils/validationService.js
Labels: bug

#1171 Impl [Feature Vectors] Improve add/edit Alias Behavior
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
  src/components/DetailsRequestedFeatures/detailsRequestedFeatures.scss
  src/components/DetailsRequestedFeatures/detailsRequestedFeatures.utils.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Project/project.scss
  src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
  src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
  src/elements/FeaturesTablePanel/featuresTablePanel.scss
  src/elements/ProjectCard/ProjectCardView.js
  src/scss/main.scss
Labels: enhancement

#1175 Impl [UI] Replace "demo=true" flag
  src/App.js
  src/common/Breadcrumbs/Breadcrumbs.js
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functions.util.js
  src/components/Jobs/Jobs.js
  src/components/Jobs/jobs.util.js
  src/components/JobsPanelAdvanced/JobsPanelAdvanced.js
  src/components/JobsPanelAdvanced/JobsPanelAdvancedView.js
  src/components/Project/ProjectMonitor.js
  src/components/Project/ProjectMonitorView.js
  src/components/Project/ProjectOverview/ProjectOverview.js
  src/components/Project/ProjectOverview/ProjectOverview.util.js
  src/components/Table/Table.js
  src/elements/ContentMenu/ContentMenu.js
  src/elements/FunctionsPanelEnvironmentVariables/FunctionsPanelEnvironmentVariables.js
  src/elements/FunctionsPanelEnvironmentVariables/FunctionsPanelEnvironmentVariablesView.js
  src/elements/FunctionsPanelRuntime/FunctionsPanelRuntime.js
  src/elements/FunctionsPanelRuntime/FunctionsPanelRuntimeView.js
  src/elements/JobsPanelEnvironmentVariables/JobsPanelEnvironmentVariables.js
  src/elements/NewFunctionPopUp/NewFunctionPopUp.js
  src/elements/NewFunctionPopUp/newFuctionPopUp.util.js
  src/hooks/demoMode.hook.js
  src/hooks/mode.hook.js
  src/layout/Page/Page.js
  src/utils/createJobsContent.js
  src/utils/generateTableContent.js
  src/utils/helper.js
  src/utils/parseUri.js
  tests/features/step-definitions/steps.js
Labels: enhancement

#1177 Impl [Real-Time Pipelines] Add a `function` column
  src/components/Models/models.util.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/utils/createArtifactsContent.js
  src/utils/createFeatureStoreContent.js
  src/utils/createFunctionsContent.js
  src/utils/createJobsContent.js
Labels: enhancement

#1178 Fix [Jobs workflow report] The Jobs pipeline isn't refreshed while it's running
  src/actions/workflow.js
  src/components/Jobs/Jobs.js
  src/components/Jobs/jobs.util.js
  src/constants.js
  src/reducers/workflowReducer.js
Labels: bug

#1170 Fix [Details] tabs disappear when expanding a row
  src/components/Datasets/Datasets.js
  src/components/Datasets/datasets.util.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/Files.js
  src/components/Files/files.util.js
  src/components/Models/Models.js
  src/components/Models/models.util.js
  src/layout/Content/Content.js
Labels: bug

#1183 Fix [Functions] User can't change ml function pod priority from UI
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
Labels: bug

#1184 Fix [Feature Vectors] Missing No Data message
  src/components/Details/details.util.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
Labels: bug

#1185 Fix [Jobs Panel] Table headers font size are not aligned
  src/common/KeyValueTable/keyValueTable.scss
  src/scss/mixins.scss
Labels: bug
