Repository mlrun/ui, pull requests merged in 2023-03, with the labels that each got.

#1638 Fix [Feature Vectors] Duplicated items appearing after applying changes on Details pane
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
Labels: bug

#1639 Fix [Chips] In the table chips wrap on the second row
  src/common/Chip/Chip.js
Labels: bug

#1640 Fix [Feature store] misaligned headers in "Feature sets" screen
  src/components/Table/table.scss
  src/utils/createFeatureStoreContent.js
Labels: bug

#1641 Fix [Jobs] UI fails on attempt to re-run job
  src/elements/FormResourcesUnits/formResourcesUnits.util.js
Labels: bug

#1626 Fix [Models] Prevent deploy model option for non-serving function
  src/elements/DeployModelPopUp/DeployModelPopUp.js
  src/elements/DeployModelPopUp/deployModelPopUp.scss
Labels: bug

#1643 Fix [Models Endpoints] Histogram bars are not in place in the feature analysis tab
  src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.scss
  src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.util.js
Labels: bug

#1644 Fix [Features] Empty tooltip is shown if "Validator" field is empty
  src/elements/FeatureValidator/FeatureValidator.js
  src/elements/FeatureValidator/featureValidatior.utils.js
  src/elements/FeatureValidator/featureValidator.scss
Labels: bug

#1645 Fix [Schedule] Scheduled jobs are not shown
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/reducers/notificationReducer.js
  src/utils/createJobsContent.js
  src/utils/getState.js
  src/utils/parseJob.js
Labels: bug

#1646 Fix [Feature Sets] spacing between icons
  src/components/Table/table.scss
  src/elements/TableCell/TableCell.js
  src/utils/createFeatureStoreContent.js
Labels: bug

#1647 Fix [Models] Apply changes button isn't clickable
  src/components/ModelsPage/Models/models.util.js
  src/utils/convertChipsData.js
Labels: bug

#1648 Fix [Project Overview] Fix UI view in smaller resolutions
  src/common/ProjectDetailsHeader/ProjectDetailsHeader.js
  src/common/ProjectDetailsHeader/ProjectDetailsHeader.scss
  src/components/Project/ProjectOverview/ProjectOverview.scss
Labels: bug

#1650 Fix [Build] Fixed an error during project build
  src/reducers/notificationReducer.js
Labels: bug

#1651 Revert [Models] Adjust the Average Latency calculation in model endpoints tab
  src/utils/createArtifactsContent.js
Labels: revert

#1652 Fix [Details] loop of for unsaved changes warning
  src/components/Details/Details.js
  src/elements/TableCell/TableCell.js
Labels: bug

#1649 Fix [Artifacts] unable to set empty "Version tag"
  package.json
  src/components/Details/details.util.js
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
Labels: bug

#1653 Fix [Feature set] Wrong default path for offline target
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
Labels: bug

#1654 Fix [Monitor Jobs] 'No data to show' for dask job in 'Pods' tab
  src/components/Details/DetailsTabsContent/DetailsTabsContent.js
  src/components/DetailsPods/DetailsPods.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/jobs.util.js
  src/elements/TableProducerCell/TableProducerCell.js
  src/utils/parseJob.js
Labels: bug

#1655 Fix [Feature Set] unable to update description
  src/components/Details/details.util.js
Labels: bug

#1656 Fix [Feature set] Wrong default path for offline partition target
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
  src/reducers/featureStoreReducer.js
Labels: bug

#1658 Fix [Details] "Apply changes" button unexpectedly becomes disabled
  src/components/DetailsInfo/DetailsInfo.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
Labels: bug

#1657 Fix [General] "Something went wrong" displayed on attempt to click "Create feature set" from Project home
  src/actions/featureStore.js
  src/actions/functions.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardResources/JobWizardResources.js
  src/components/JobsPanel/jobsPanel.util.js
  src/elements/FunctionsPanelCode/FunctionsPanelCode.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/layout/Page/Page.js
  src/reducers/appReducer.js
  src/utils/getPreemptionMode.js
Labels: bug

#1660 Fix [Workflows] Change "Jobs" -> "Workflows" in UI
  src/utils/getNoDataMessage.js
Labels: bug

#1661 Fix [Datasets] Change "Artifact" -> "Dataset" in 2 places in UI
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/components/RegisterArtifactModal/messagesByKind.js
  src/components/RegisterArtifactPopup/RegisterArtifactPopup.js
  src/components/RegisterArtifactPopup/messagesByKind.js
  src/elements/RegisterArtifactForm/RegisterArtifactForm.js
  src/elements/RegisterArtifactForm/registerArtifactForm.scss
  src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
Labels: bug

#1662 Fix [Datasets] When size of an artifact is NA, the UI should display "NA", not "0 Bytes"
  src/utils/createArtifactsContent.js
Labels: bug

#1665 Fix [UI] frontendSpec failed pop-up keeps rendering
  src/layout/Page/Page.js
  src/reducers/appReducer.js
Labels: bug

#1663 Fix [Jobs] change 'Batch run" to 'New Job' in 1.3
  src/components/Jobs/Jobs.js
  src/components/Jobs/jobs.util.js
  src/components/Project/ProjectOverview/ProjectOverview.util.js
  src/components/Project/project.utils.js
Labels: bug

#1666 Fix [Feature set] Discard button for edit path doesn't work as expected
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
Labels: bug

#1667 Fix [Feature set] Wrong default path for offline target (fix)
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
Labels: bug

#1668 Fix [Jobs] "Pods not found..." appears upon refresh in "Pods" tab
  src/actions/details.js
  src/components/DetailsPods/DetailsPods.js
  src/constants.js
  src/reducers/detailsReducer.js
Labels: bug

#1669 Fix [Feature Set] Change The target path for partition parquet tooltip
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
Labels: bug

#1670 Fix [Jobs] change 'Batch run" to 'New Job' in 1.3 (fix)
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
Labels: bug

#1680 Fix [Target Path] UI should get "store://datasets/" format as an input to the function
  src/common/TargetPath/TargetPath.js
  src/common/TargetPath/targetPath.util.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.util.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSourceTable/FeatureSetsPanelDataSourceTable.js
  src/reducers/artifactsReducer.js
  src/utils/panelPathScheme.js
Labels: bug

#1681 Fix [Target Path] UI should get "store://datasets/" format as an input to the function `1.3.x`
  src/common/TargetPath/TargetPath.js
  src/common/TargetPath/targetPath.util.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.util.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSourceTable/FeatureSetsPanelDataSourceTable.js
  src/reducers/artifactsReducer.js
  src/utils/panelPathScheme.js
Labels: bug

#1671 Impl [Jobs] Empty string for pod status in case the status isn't Pending
  src/components/DetailsPods/DetailsPods.js
  src/components/DetailsPods/detailsPods.scss
  src/utils/generatePods.js
Labels: enhancement

#1674 Impl [Project Monitor] remove "Project Monitoring" layout change from demo mode
  src/components/Project/ProjectMonitor.js
  src/components/Project/ProjectMonitorView.js
Labels: enhancement

#1678 Impl [UI] Add 50th percentile (median) to stats
  src/components/DetailsStatistics/detailsStatistics.util.js
Labels: enhancement

#1682 Fix [Feature Set] Target path for partition parquet should be taken as Folder `1.3.x`
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
Labels: bug

#1673 Fix [Feature Set] Target path for partition parquet should be taken as Folder
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
Labels: bug

#1684 Fix [Project settings] "Something went wrong" during project creation
  src/reducers/projectReducer.js
Labels: bug

#1687 Fix [Feature Set] Tooltip icon is overlapping the input
  src/common/DatePicker/datePicker.scss
  src/common/TimePicker/timePicker.scss
Labels: bug

#1689 Impl [Models] Adjust the Average Latency calculation in model endpoints tab
  src/utils/createArtifactsContent.js
Labels: enhancement

#1690 Impl [Models] Adjust the Average Latency calculation in model endpoints tab `1.3.x`
  src/utils/createArtifactsContent.js
Labels: enhancement
