Repository mlrun/ui, pull requests merged in 2023-09, with the labels that each got.

#1889 Impl [Functions hub] Retrieve the hub catalog: MLRun UI should use the new Hub APIs (phase 1)
  src/actions/functions.js
  src/api/functions-api.js
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/constants.js
  src/reducers/functionReducer.js
  src/utils/generateTemplatesCategories.js
Labels: enhancement

#1892 Fix [UI] labels are failing validations upon "Batch Re-Run"
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
Labels: bug

#1893 Fix [Batch Run] CPU value in Resources panel increase/decrease by ones with "millicpu" type
  src/elements/FormResourcesUnits/FormResourcesUnits.js
Labels: bug

#1895 Impl [Batch Infer] Enable 'change image' or 'add a new requirements'
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
  src/constants.js
Labels: enhancement

#1899 Fix [Batch Run] The results empty for 'random' strategy with predefined maxerror param
  src/components/DetailsResults/DetailsResults.js
Labels: bug

#1898 Fix [Batch run] Redundant 'Are you sure?' dialog when changing the 'Method'
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
Labels: bug

#1897 Fix [Functions] The "Overwrite function" popup message appears for creation a function with a different tag
  src/actions/functions.js
  src/api/functions-api.js
  src/components/FunctionsPanel/FunctionsPanel.js
Labels: bug

#1894 Fix [Job Wizard] Uncheck predefined parameters
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#1900 Fix [Monitor Workflows] Missing padding in graph view details panel
  src/components/Details/details.scss
  src/components/DetailsInfo/detailsInfo.scss
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/components/Workflow/Workflow.js
Labels: bug

#1901 Fix [ML Functions] Capital letters on function name gives error
  src/actions/functions.js
  src/components/FunctionsPanel/FunctionsPanel.js
Labels: bug

#1902 Fix [Jobs] Inconsistency between "Results" in "Overview" vs "Results" tab
  src/utils/convertChipsData.js
  src/utils/object.js
Labels: bug

#1903 Fix [Batch run] Selected function isn't hinted
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
Labels: bug

#1907 Fix [Jobs] Allow to run and re-run functions only with `job` kind
  src/components/CreateJobPage/CreateJobPage.js
  src/components/FunctionsPage/Functions.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/jobs.util.js
  src/utils/generateTemplatesCategories.js
Labels: bug

#1908 Impl [Batch infer] Adjust batch infer to the new function
  src/components/JobWizard/JobWizard.js
Labels: enhancement

#1909 Fix [Jobs] redundant error on attempt to run job after deleting its function
  src/actions/jobs.js
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/components/Jobs/jobs.util.js
Labels: bug

#1906 Impl [General] Upgrade react-flow library from v8 to v11
  package.json
  src/App.js
  src/actions/nuclio.js
  src/common/ReactFlow/MlReactFlow.js
  src/common/ReactFlow/MlReactFlowEdge.js
  src/common/ReactFlow/MlReactFlowNode.js
  src/common/ReactFlow/mlReactFlow.util.js
  src/components/DetailsTransformations/DetailsTransformations.js
  src/components/Pipeline/Pipeline.js
  src/components/Pipeline/PipelineView.js
  src/components/Workflow/Workflow.js
Labels: enhancement, Cleanup

#1910 Fix [Batch run] Don't show incompatible "batch-inference" hub function
  src/utils/generateTemplatesCategories.js
Labels: bug

#1912 Fix [Jobs] error missing details when job fails to start
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
Labels: bug

#1913 Fix [Artifacts] Missing description data in Register requests
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
Labels: bug

#1916 Fix [Real Time Pipelines] all child funcs appear in the table and clicking on any one of them opens the same graph
  src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
Labels: bug

#1917 Fix [Feature Store] Target store checkboxes don't work properly
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/components/FeatureSetsPanel/UrlPath.js
Labels: bug

#1919 Fix [Feature Store] Target store checkboxes don't work properly `1.5.x`
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/components/FeatureSetsPanel/UrlPath.js
Labels: bug

#1920 Fix [Batch Run] Number input for int and float parameters is malfunctioning `1.5`
  src/common/ChipCell/ChipCell.js
  src/common/ChipCell/HiddenChipsBlock/HiddenChipsBlock.js
  src/common/ReactFlow/MlReactFlowEdge.js
  src/elements/FormDataInputsTable/FormDataInputsTable.js
  src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesTable.js
  src/elements/FormParametersTable/FormParametersTable.js
  src/elements/FormVolumesTable/FormVolumesTable.js
Labels: bug

#1921 Fix [Combobox] unable to pass model as data input using store path
  src/common/TargetPath/TargetPath.js
  src/common/TargetPath/targetPath.util.js
  src/components/FeatureSetsPanel/UrlPath.js
  src/components/FeatureSetsPanel/UrlPath.utils.js
  src/utils/panelPathScheme.js
Labels: bug

#1922 Fix [Combobox] unable to pass model as data input using store path `1.5.x`
  src/common/TargetPath/TargetPath.js
  src/common/TargetPath/targetPath.util.js
  src/components/FeatureSetsPanel/UrlPath.js
  src/components/FeatureSetsPanel/UrlPath.utils.js
  src/utils/panelPathScheme.js
Labels: bug

#1923 Fix [Features Analysis] Large float values are not presented
  src/common/Chart/MlChart.js
  src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.util.js
Labels: bug

#1924 Fix [Features Analysis] Large float values are not presented `1.5.x`
  src/common/Chart/MlChart.js
  src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.util.js
Labels: bug

#1925 Impl [Model endpoint] UI should display drift threshold and drift actual value
  src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
Labels: enhancement

#1926 Impl [Model endpoint] UI should display drift threshold and drift actual value `1.5.x`
  src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
Labels: enhancement

#1927 Fix [Batch run] Hide 'Build image' option, add message for 'Image name'
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
  src/scss/main.scss
Labels: bug

#1928 Fix [Batch run] Hide 'Build image' option, add message for 'Image name' `1.5`
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
  src/scss/main.scss
Labels: bug

#1932 Fix [Batch run] Changed parameter types aren't saved for rerun `1.5`
  src/components/JobWizard/JobWizard.util.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
Labels: bug

#1931 Fix [Batch run] Changed parameter types aren't saved for rerun
  src/components/JobWizard/JobWizard.util.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
Labels: bug

#1933 Fix [Jobs] UI is stuck on attempt to list runs for job with many runs `1.5.x`
  src/actions/jobs.js
  src/api/jobs-api.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/constants.js
Labels: bug

#1934 Fix [Jobs] UI is stuck on attempt to list runs for job with many runs
  src/actions/jobs.js
  src/api/jobs-api.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/constants.js
Labels: bug

#1938 Fix [Scheduled workflow] Workflow (and not job) should have different icon and minimal editing `1.5.x`
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/utils/parseJob.js
Labels: bug

#1935 Fix [Scheduled workflow] Workflow (and not job) should have different icon and minimal editing
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/utils/parseJob.js
Labels: bug

#1937 Fix [Jobs] Batch Model Endpoint => overview - model, function and Featureset links are broken
  src/components/Details/details.util.js
Labels: bug

#1936 Fix [Jobs] Batch Model Endpoint => overview - model, function and Featureset links are broken `1.5.x`
  src/components/Details/details.util.js
Labels: bug

#1940 Fix [Model Endpoints] Invalid Function URI link in model endpoints screen `1.5.x`
  src/components/Details/details.util.js
  src/utils/createArtifactsContent.js
  src/utils/generateFunctionDetailsLink.js
  src/utils/parseUri.js
Labels: bug

#1939 Fix [Model Endpoints] Invalid Function URI link in model endpoints screen
  src/components/Details/details.util.js
  src/utils/createArtifactsContent.js
  src/utils/generateFunctionDetailsLink.js
  src/utils/parseUri.js
Labels: bug

#1942 Fix [Feature set] the target store path is incorrect
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
Labels: bug

#1941 Fix [Feature set] the target store path is incorrect `1.5.x`
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
Labels: bug

#1945 Fix [Batch run] Mandatory parameters should be selected `1.5`
  src/components/JobWizard/JobWizard.util.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
Labels: bug

#1949 Fix [Batch run] Remove the '$' from Batch Inference version presentation
  src/components/JobWizard/JobWizard.util.js
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#1950 Fix [Batch run] Remove the '$' from Batch Inference version presentation `1.5.x`
  src/components/JobWizard/JobWizard.util.js
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#1951 Fix [Batch run] Batch run labels are incorrect `1.5`
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#1952 Fix [Batch run] Batch run labels are incorrect
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#1944 Impl [Wizard steps] Next to step should be clickable `1.5.x`
  src/actions/functions.js
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
Labels: enhancement

#1954 Fix [Batch Run] UI minor fix `1.5.x`
  src/common/Search/search.scss
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
  src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
  src/scss/main.scss
Labels: bug

#1956 Impl [Batch run] Add "monitoring" to categories mapping `1.5.x`
  src/components/JobWizard/JobWizard.util.js
Labels: enhancement

#1943 Impl [Wizard steps] Next to step should be clickable
  src/actions/functions.js
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
Labels: enhancement

#1955 Impl [Batch run] Add "monitoring" to categories mapping
  src/components/JobWizard/JobWizard.util.js
Labels: enhancement

#1961 Fix [Batch run] inputs issues
  src/components/DetailsInputs/DetailsInputs.js
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#1962 Fix [Batch run] inputs issues `1.5.x`
  src/components/DetailsInputs/DetailsInputs.js
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#1963 Fix [Datasets and Models] Filter by tag isn't performed when version tag was edited
  src/components/Datasets/Datasets.js
  src/components/ModelsPage/Models/Models.js
Labels: bug

#1964 Fix [Datasets and Models] Filter by tag isn't performed when version tag was edited `1.5.x`
  src/components/Datasets/Datasets.js
  src/components/ModelsPage/Models/Models.js
Labels: bug

#1965 Fix [Jobs] Missing scroll bar in jobs UI logs
  src/components/Details/details.scss
Labels: bug

#1967 Fix [Batch run] Mandatory parameters should be selected v2 `1.5.x`
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#1968 Fix [Batch run] Mandatory parameters should be selected v2
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#1969 Fix [Feature Sets Panel] Checking "Passthrough" unchecks "Online" target `1.5.x`
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
Labels: bug

#1970 Fix [Feature Sets Panel] Checking "Passthrough" unchecks "Online" target
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
Labels: bug

#1972 Fix [Batch Run] Number input for Max iterations, Max errors and Parallel runs is malfunctioning `1.5.x`
  src/components/JobWizard/JobWizardSteps/JobWizardHyperparameterStrategy/JobWizardHyperparameterStrategy.js
Labels: bug

#1959 Fix [Search] The search item list closing on scroll `1.5.x`
  src/common/Search/Search.js
  src/common/Search/search.scss
Labels: bug

#1960 Fix [Search] The search item list closing on scroll
  src/common/Search/Search.js
  src/common/Search/search.scss
Labels: bug

#1975 QA Sprint 147 done
  package.json
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/common.action.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/features/support/world.js
  tests/mockServer/data/artifacts.json
  tests/mockServer/data/itemsCatalog.json
  tests/mockServer/mock.js
Labels: tests

#1978 Impl [Tests] Sprint 147
  package.json
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/common.action.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/features/support/world.js
  tests/mockServer/data/artifacts.json
  tests/mockServer/data/itemsCatalog.json
  tests/mockServer/mock.js
Labels: tests

#1979 Impl [Tests] Sprint 147 `1.5.x`
  package.json
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/common.action.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/features/support/world.js
  tests/mockServer/data/artifacts.json
  tests/mockServer/data/itemsCatalog.json
  tests/mockServer/mock.js
Labels: tests

#1976 Fix [Jobs] Monitor job pods view use too broad api call
  src/actions/details.js
  src/api/details-api.js
  src/hooks/usePods.hook.js
Labels: bug

#1977 Fix [Jobs] Monitor job pods view use too broad api call `1.5.x`
  src/actions/details.js
  src/api/details-api.js
  src/hooks/usePods.hook.js
Labels: bug
