Repository mlrun/ui, pull requests merged in 2023-12, with the labels that each got.

#2087 Fix [UI] add the 'data-testid' for 'Add volume' and 'Add node selector' buttons
  src/components/JobWizard/JobWizardSteps/JobWizardResources/JobWizardResources.js
  src/elements/FormVolumesTable/FormVolumesTable.js
Labels: bug

#2104 Fix [Jobs] UI crash on 'pathname'
  src/components/DetailsInputs/DetailsInputs.js
Labels: bug

#2105 Fix [UI] add data-testid for elements in batch run wizard
  src/common/Input/Input.js
  src/common/Search/Search.js
  src/components/FilterMenuModal/FilterMenuModal.js
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/components/JobWizard/JobWizardSteps/JobWizardParameters/JobWizardParameters.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
  src/elements/FormDataInputsTable/FormDataInputsTable.js
  src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesTable.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
  src/elements/FormParametersTable/FormParametersTable.js
  src/elements/FormResourcesUnits/FormResourcesUnits.js
  src/elements/FormVolumesTable/FormVolumesTable.js
Labels: bug

#2102 Fix [Delete job] issues with job delete
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/jobs.util.js
Labels: bug

#2103 Fix [Project Settings] UI does not display pull_at_runtime project setting
  src/constants.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js
  src/elements/ProjectSettingsSource/ProjectSettingsSource.js
  src/elements/ProjectSettingsSource/projectSettingsSource.scss
  src/reducers/projectReducer.js
Labels: bug

#2101 QA Sprint 151 done
  tests/features/common-tools/common-consts.js
  tests/features/common-tools/common-tools.js
  tests/features/common/actions/common.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/components/combo-box.component.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/step-definitions/table.steps.js
  tests/mockServer/mock.js
Labels: tests

#2109 Fix [Models] Wrong preview presentation Part 1 - fixed bugs with click on name
  src/elements/ArtifactsExtraData/ArtifactsExtraData.js
Labels: bug

#1882 Impl [UI] Use the new artifacts v2 endpoints
  src/api/artifacts-api.js
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/elements/RegisterModelModal/RegisterModelModal.js
  src/httpClient.js
Labels: enhancement

#2112 Fix [Project Settings] "Members" tab is not present for user with "project security admin" policy
  src/components/ProjectSettings/projectSettings.util.js
Labels: bug

#2113 Fix [Batch Run] missing parameters and data inputs for Hub functions
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
Labels: bug

#2115 Fix [Feature Store] UI craches after checking the Partition checkbox.
  src/components/FeatureSetsPanel/UrlPath.js
Labels: bug

#2116 Fix [Feature Store] "Something went wrong." screen when add Feature Vector
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
Labels: bug

#2117 Fix [Train model] auto select "auto-trainer" function
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
Labels: bug

#2119 Revert [UI] Use the new artifacts v2 endpoints
  src/api/artifacts-api.js
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/elements/RegisterModelModal/RegisterModelModal.js
  src/httpClient.js
Labels: revert

#2118 Fix [Batch run] parameters values are deleted after updating type
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
Labels: bug

#2123 Fix [Artifacts] Table header is hidden during table scroll
  src/components/FeatureStore/featureStore.scss
  src/scss/main.scss
Labels: bug

#2121 Fix [Batch run] unable to re-run the job
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#2122 Fix [Feature Store] Features entity creation
  src/components/FeatureSetsPanel/FeatureSetsPanelSchema/FeatureSetsPanelSchema.js
  src/components/FeatureSetsPanel/FeatureSetsPanelSchema/FeatureSetsPanelSchemaView.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
Labels: bug

#2124 Fix [Batch run] Incorrect completion message
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizard.util.js
  src/components/SheduleWizard/ScheduleWizard.js
Labels: bug

#2114 QA Sprint 152 done
  tests/features/common-tools/common-consts.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/models.feature
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/artifacts.json
  tests/mockServer/mock.js
Labels: tests

#2127 Impl [Tests] Sprint 152 done
  tests/features/common-tools/common-consts.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/models.feature
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/artifacts.json
  tests/mockServer/mock.js
Labels: tests

#2128 Fix [Monitor Workflows] UI crash on attempt to browse "Inputs" tab
  src/components/DetailsInputs/detailsInputs.util.js
Labels: bug

#2129 Impl [Batch Run] Add "Current project" to MLRun Store Path Scheme autocoplete
  src/common/TargetPath/TargetPath.js
  src/common/TargetPath/targetPath.util.js
  src/components/Datasets/Datasets.js
  src/components/Files/Files.js
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizardSteps/JobWizardDataInputs/JobWizardDataInputs.js
  src/components/ModelsPage/Models/Models.js
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
  src/elements/FormDataInputsTable/FormDataInputsTable.js
  src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
  src/elements/RegisterModelModal/RegisterModelModal.js
  src/utils/panelPathScheme.js
Labels: enhancement

#2130 Fix [Model Train] display dataset URL conditionally
  src/components/Datasets/datasets.util.js
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
Labels: bug

#2131 Fix [Build logs] Logs refresh is blinking too fast
  src/actions/functions.js
  src/components/Details/details.scss
  src/components/DetailsLogs/DetailsLogs.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functions.util.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Project/ProjectMonitor.js
  src/utils/getFunctionLogs.js
Labels: bug

#2132 Fix [General] Increase cancel request timeout from 60sec to 2min
  src/constants.js
Labels: bug

#2133 Fix [Datasets][Preview] data displaying issue
  src/components/Table/table.scss
Labels: bug

#2120 Impl [UI] Use the new artifacts v2 endpoints
  src/api/artifacts-api.js
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/elements/RegisterModelModal/RegisterModelModal.js
  src/httpClient.js
Labels: enhancement

#2111 Impl [Register artifact] does not allow to provide tag
  src/api/artifacts-api.js
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
  src/elements/RegisterModelModal/RegisterModelModal.js
Labels: enhancement

#2135 Fix [Artifact preview] Artifacts with "sql" extension are not previewed
  src/utils/createArtifactPreviewContent.js
Labels: bug

#2139 QA Sprint 153 done
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/action-menu.action.js
  tests/features/common/actions/input-group.action.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/project.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectHomePage.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/iguazioSelf.json
  tests/mockServer/mock.js
Labels: tests

#2136 Fix [Train model] auto select "auto-trainer" function with "train" handler
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
Labels: bug

#2137 Fix [Breadcrumbs] The projects pages dropdown doesn't open up after model/dataset tag editing
  src/components/Datasets/Datasets.js
  src/components/ModelsPage/Models/Models.js
Labels: bug

#2138 Fix [Train model] validation fails for auto populated dataset
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#2141 Fix [Project monitoring] UI crash upon click on "Register artifact" via "Create new" dropdown
  src/components/Project/ProjectMonitor.js
Labels: bug

#2142 Fix [Batch Re-run] data inputs should be checked if they were used in running the job
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#2143 Fix [Artifacts Preview] Wrong table size
  src/components/ArtifactsPreview/artifactsPreview.scss
Labels: bug

#2144 Fix [Monitor Jobs] App crashes on Preview icon click
  src/elements/PreviewModal/PreviewModal.js
Labels: bug

#2145 Fix [Batch Run] change map to dict in parameters types
  src/components/JobWizard/JobWizard.util.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
  src/elements/FormParametersTable/formParametersTable.util.js
Labels: bug

#2146 Fix [Batch run] Align "function templates" with the "functions hub"
  src/components/JobWizard/JobWizard.util.js
  src/utils/generateTemplatesCategories.js
Labels: bug

#2148 Fix [Artifacts] Change text color of disabled Delete button to gray
  src/elements/ActionMenuItem/actionsMenuItem.scss
Labels: bug

#2149 Fix [Batch run] UI crash with "getBoundingClientRect"
  src/components/FilterMenuModal/FilterMenuModal.js
  src/components/JobWizard/JobWizard.js
Labels: bug

#2150 Fix [Models] data displaying issue
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/models.util.js
  src/components/Table/Table.js
  src/components/Table/TableHead.js
  src/components/Table/TableView.js
  src/scss/main.scss
  src/utils/createArtifactsContent.js
Labels: bug

#2151 Fix [Jobs] Delete job from the list view deletes single execution
  src/actions/jobs.js
  src/api/jobs-api.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/constants.js
Labels: bug

#2155 Impl [Datasets] label_column should be added to Dataset details panel
  src/components/Datasets/datasets.util.js
  src/components/Details/details.util.js
Labels: enhancement

#2156 Fix [Quick actions] crash upon click on Register artifact/dataset
  src/components/Project/ProjectOverview/ProjectOverview.util.js
Labels: bug

#2157 Fix [ML functions] Function selection issue with same hash
  src/components/FunctionsPage/Functions.js
Labels: bug

#2154 Fix [Feature Vectors] Error after expanding Feature Vectors item
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
  src/components/FeatureStore/FeatureVectors/featureVectors.util.js
Labels: bug

#2153 Fix [Jobs] "Delete" option should be hidden in the Action menu , when the job has status: Running/Pending
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/jobs.util.js
Labels: bug

#2152 Fix [Feature sets] UI crash on attempt to preview feature set
  src/components/DetailsPreview/DetailsPreview.js
Labels: bug

#2158 Fix [Workflows] Cannot read properties of null (reading toLowerCase) on attempt to filter workflows by status "All"
  src/utils/parseWorkflows.js
Labels: bug

#2159 Impl [Model endpoint] there should be a link to open Grafana and view full details
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/ModelsPage.context.js
Labels: enhancement

#2160 Fix [Artifacts] Show actions when table has horizontal scroll
  src/scss/main.scss
Labels: bug

#2163 Fix [Feature Vectors] UI crash upon searching by entity during feature vector creation
  src/components/Table/Table.js
Labels: bug

#2164 Fix [Feature Vectors] UI crash upon expanding feature during feature vector creation
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
Labels: bug

#2165 Impl [Artifacts] New artifact v2 api for artifact delete
  src/api/artifacts-api.js
  src/reducers/artifactsReducer.js
  src/utils/handleDeleteArtifact.js
Labels: enhancement

#2166 QA Sprint 154 done
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/api.actions.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/mockServer/mock.js
Labels: tests
