Repository mlrun/ui, pull requests merged in 2023-11, with the labels that each got.

#2057 Fix [Batch Run] Show function's inputs on re-run
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#2058 Revamp [Models/Datasets/Artifacts] change UI according to Figma new design
  src/components/ArtifactInfoSources/ArtifactInfoSources.js
  src/components/ArtifactInfoSources/artifactInfoSources.scss
  src/components/ArtifactsActionBar/ArtifactsActionBar.js
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/Datasets/datasets.util.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/DetailsInfo/detailsInfo.util.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/Models/models.util.js
  src/components/ModelsPage/ModelsPage.context.js
  src/components/ModelsPage/ModelsPage.js
  src/components/Table/TableHead.js
  src/elements/TableLinkCell/tableLinkCell.scss
  src/scss/main.scss
Labels: enhancement

#2061 QA Sprint 149 done
  tests/features/common-tools/common-consts.js
  tests/features/common/page-objects/commonPagesHeader.po.js
  tests/features/common/page-objects/project.po.js
  tests/features/datasets.feature
  tests/features/files.feature
  tests/features/models.feature
  tests/features/projectHomePage.feature
  tests/features/projectPage.feature
  tests/features/step-definitions/steps.js
  tests/mockServer/data/hubItemInference.json
  tests/mockServer/data/itemsCatalog.json
  tests/mockServer/data/mlrun/functions/batch_inference/batch_inference.yaml
  tests/mockServer/data/mlrun/functions/batch_inference_v2/batch_inference_v2.yaml
  tests/mockServer/mock.js
Labels: tests

#2060 Fix [Table] workflow name is not expandable
  src/components/Table/TableView.js
  src/elements/TableLinkCell/tableLinkCell.scss
  src/scss/main.scss
Labels: bug

#2051 Fix [Action Menu] Row background color on option hover
  src/common/ActionsMenu/ActionsMenu.js
  src/common/ActionsMenu/actionsMenu.scss
  src/components/Table/table.scss
  src/elements/ActionMenuItem/ActionsMenuItem.js
  src/elements/ActionMenuItem/actionsMenuItem.scss
  src/scss/main.scss
Labels: bug

#2059 Fix [Feature Store] inaccurate validation message for redis
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
Labels: bug

#2066 Impl [Batch Run] Model Training
  src/actions/functions.js
  src/common/NameFilter/nameFilter.scss
  src/common/TargetPath/targetPath.util.js
  src/components/ArtifactsActionBar/ArtifactsActionBar.js
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/Datasets/datasets.util.js
  src/components/Files/FilesView.js
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/jobWizardFunctionSelection.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/Project/ProjectOverview/ProjectOverview.util.js
  src/scss/main.scss
  src/utils/generateTemplatesCategories.js
  src/utils/panelPathScheme.js
Labels: enhancement

#2067 Impl [Job][Details] Add header in the Artifact, Input and Result tabs
  src/components/ArtifactsPreview/ArtifactsPreviewController.js
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/ArtifactsPreview/artifactsPreview.scss
  src/components/Datasets/DatasetsView.js
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsArtifacts/detailsArtifacts.scss
  src/components/DetailsArtifacts/detailsArtifacts.util.js
  src/components/DetailsInputs/DetailsInputs.js
  src/components/DetailsInputs/detailsInputs.scss
  src/components/DetailsInputs/detailsInputs.util.js
  src/components/DetailsResults/DetailsResults.js
  src/components/DetailsResults/detailsResults.scss
  src/components/Files/FilesView.js
  src/components/Jobs/Jobs.js
  src/components/ModelsPage/ModelsPage.js
  src/components/Table/table.scss
  src/elements/PreviewModal/PreviewModal.js
  src/hooks/useSortTable.hook.js
  src/layout/Content/Content.js
  src/scss/main.scss
  src/utils/getArtifactPreview.js
  src/utils/resultsTable.js
Labels: enhancement

#2062 Impl [Models] Metrics new look and feel in the table
  src/common/Download/DownloadItem.js
  src/common/Download/downloadContainer.scss
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsInputs/DetailsInputs.js
  src/components/DetailsResults/DetailsResults.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/modelsPage.scss
  src/components/Table/TableHead.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/components/Workflow/JobsFunctionsTableRow/JobsFunctionsTableRow.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/FeatureStoreTableRow/FeatureStoreTableRow.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/elements/JobsTableRow/JobsTableRow.js
  src/elements/TableCell/TableCell.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/elements/TableProducerCell/TableProducerCell.js
  src/elements/TableTypeCell/TableTypeCell.js
  src/hooks/groupContent.hook.js
  src/scss/main.scss
  src/utils/createArtifactsContent.js
  src/utils/createConsumerGroupContent.js
  src/utils/createConsumerGroupsContent.js
  src/utils/createFeatureStoreContent.js
  src/utils/createFunctionsContent.js
  src/utils/createJobsContent.js
Labels: enhancement

#2068 Fix [Artifacts] UI crash when artifact doesn't have a producer
  src/elements/TableProducerCell/TableProducerCell.js
  src/utils/createArtifactsContent.js
Labels: bug

#2069 Impl [Projects] Provide validation rules on labels
  src/actions/projects.js
  src/components/Details/details.util.js
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
  src/components/ProjectsPage/CreateProjectDialog/createProjectDialog.scss
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/constants.js
  src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
  src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesRow/FormEnvironmentVariablesRow.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
  src/elements/FormVolumesTable/formVolumesTable.util.js
  src/elements/PanelResourcesUnits/PanelResourcesUnits.js
  src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
  src/elements/RegisterModelModal/RegisterModelModal.js
  src/reducers/projectReducer.js
  src/scss/main.scss
Labels: enhancement

#2072 Fix [API] browser caching `1.5.x`
  src/httpClient.js
Labels: bug

#2070 Fix [API] browser caching
  src/httpClient.js
Labels: bug

#2065 Fix [Features] incorrect panel view when adding a feature `1.5.x`
  src/components/FeatureStore/featureStore.scss
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/elements/FeaturesTablePanel/featuresTablePanel.scss
Labels: bug

#2064 Fix [Features] incorrect panel view when adding a feature
  src/components/FeatureStore/featureStore.scss
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/elements/FeaturesTablePanel/featuresTablePanel.scss
Labels: bug

#2074 QA Sprint 150 done
  package.json
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/api.actions.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/frontendSpec.json
Labels: tests

#2075 Impl [Tests] Sprint 150 done
  package.json
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/api.actions.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/frontendSpec.json
Labels: tests

#2073 Fix [Project settings] Fix members tab display logic
  src/api/projects-iguazio-api.js
  src/components/ProjectSettings/ProjectSettings.js
  src/components/ProjectSettings/projectSettings.util.js
  src/elements/MembersPopUp/membersReducer.js
  src/elements/ProjectSettingsGeneral/projectSettingsGeneral.scss
  src/elements/ProjectSettingsMembers/ProjectSettingsMembers.js
Labels: bug

#2076 Fix [Project] Validation on project's description in UI
  src/components/Project/ProjectDescription/ProjectDescription.js
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
Labels: bug

#2077 Fix [Quick actions] Add breadcrumbs to Quick actions page
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/common/ProjectDetailsHeader/ProjectDetailsHeader.js
  src/common/ProjectDetailsHeader/ProjectDetailsHeader.scss
  src/components/Project/ProjectOverview/ProjectOverview.js
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projects.scss
Labels: bug

#2078 Fix [New function] No default for handler
  src/components/JobWizard/JobWizard.util.js
  src/constants.js
  src/elements/FunctionsPanelCode/FunctionsPanelCode.js
Labels: bug

#2079 Fix [UI] feature set usage example - missing import command & project value
  src/utils/generateUsageSnippets.js
Labels: bug

#2080 Fix [Functions] Default handler is not displayed for functions
  src/components/Details/details.util.js
  src/components/FunctionsPage/functions.util.js
  src/utils/createFunctionsContent.js
Labels: bug

#2081 Fix [Feature Store] Capitalize the first letter of the sentence in the Schema description.
  src/components/FeatureSetsPanel/FeatureSetsPanelSchema/FeatureSetsPanelSchemaView.js
Labels: bug

#2083 Fix [Functions panel] Show "Volumes" dropdown on function edit
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelResources/FunctionsPanelResourcesView.js
  src/utils/parseFunction.js
Labels: bug

#2085 Fix [Project settings] does not present Default image of a project
  src/constants.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js
  src/elements/ProjectSettingsGeneral/projectSettingsGeneral.scss
  src/elements/ProjectSettingsGeneral/projectSettingsGeneral.utils.js
Labels: bug

#2086 Fix [Batch run] Disable version selection on function run
  src/components/FunctionsPage/Functions.js
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
  src/constants.js
  src/utils/generateGroupLatestItem.js
Labels: bug

#2084 Fix [UI] presentation long-waiting UI operations
  src/actions/functions.js
  src/actions/jobs.js
  src/actions/workflow.js
  src/api/artifacts-api.js
  src/api/functions-api.js
  src/api/jobs-api.js
  src/api/workflow-api.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorView.js
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureSets/FeatureSetsView.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
  src/components/FeatureStore/FeatureVectors/FeatureVectorsView.js
  src/components/FeatureStore/Features/Features.js
  src/components/FeatureStore/Features/FeaturesView.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpointsView.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
  src/components/ModelsPage/RealTimePipelines/RealTimePipelinesView.js
  src/constants.js
  src/httpClient.js
  src/layout/Content/Content.js
  src/reducers/artifactsReducer.js
  src/utils/getNoDataMessage.js
  src/utils/largeResponseCatchHandler.js
Labels: bug

#2089 Fix [Breadcrumbs] page crash when project list is not loaded
  src/common/Breadcrumbs/Breadcrumbs.js
  src/elements/TableLinkCell/tableLinkCell.scss
Labels: bug

#2088 Fix [UI] create feature set - schema entities tool tip is not red
  src/common/Input/input.scss
Labels: bug

#2039 Impl [Artifact/Models/Datasets] Add option to delete artifacts , modes, dataset in the UI
  src/api/artifacts-api.js
  src/components/Datasets/Datasets.js
  src/components/Datasets/datasets.util.js
  src/components/Files/Files.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/models.util.js
  src/reducers/artifactsReducer.js
  src/utils/handleDeleteArtifact.js
Labels: enhancement

#2090 Impl [Models] Wrong preview presentation
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/ArtifactsPreview/ArtifactsPreviewController.js
  src/components/ArtifactsPreview/artifactsPreview.scss
  src/components/DetailsPreview/DetailsPreview.js
  src/elements/ArtifactsExtraData/ArtifactsExtraData.js
  src/elements/ArtifactsExtraData/artifactsExtraData.scss
  src/elements/PreviewModal/PreviewModal.js
  src/utils/getArtifactPreview.js
Labels: enhancement

#2091 Fix [Batch run] UI crash on attempt to schedule job
  src/actions/jobs.js
  src/components/JobWizard/JobWizard.js
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/constants.js
  src/reducers/jobReducer.js
Labels: bug

#2092 Fix [Projects] an attempt to delete / archive project redirects to project screen
  src/elements/ActionMenuItem/ActionsMenuItem.js
Labels: bug

#2094 Fix [Functions Panel] clicking on deploy should not try to build a new image
  src/components/FunctionsPanel/FunctionsPanel.js
Labels: bug

#2096 Fix [Batch run] remove the 'No data to show'
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
Labels: bug
