Repository mlrun/ui, pull requests merged in 2023-10, with the labels that each got.

#1983 Fix [Batch run] Labels issues on Bach run wizard `1.5.x`
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
Labels: bug

#1982 Fix [Batch run] Labels issues on Bach run wizard
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
Labels: bug

#1987 Fix [Projects] MLRun fails to delete project on the backend, but shows success in UI `1.5.x`
  src/actions/projects.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/projectsData.js
Labels: bug

#1985 Fix [Consumer groups] Table width `1.5.x`
  src/components/Details/details.scss
  src/components/Table/TableView.js
  src/components/Table/table.scss
Labels: bug

#1988 Fix [Jobs] print 400 error message when running local job `1.5.x`
  src/api/details-api.js
  src/components/Details/details.util.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/components/Jobs/jobs.util.js
  src/components/Workflow/Workflow.js
  src/constants.js
  src/elements/DeployModelPopUp/DeployModelPopUp.js
  src/elements/NewFunctionPopUp/NewFunctionPopUp.js
  src/elements/NewFunctionPopUp/newFuctionPopUp.util.js
  src/elements/TableTypeCell/TableTypeCell.js
  src/hooks/usePods.hook.js
  src/reducers/artifactsReducer.js
  src/reducers/functionReducer.js
  src/utils/createJobsContent.js
  src/utils/parseJob.js
  src/utils/parseWorkflows.js
Labels: bug

#1836 Fix [Projects] MLRun fails to delete project on the backend, but shows success in UI
  src/actions/projects.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/projectsData.js
Labels: bug

#1986 Fix [Consumer groups] Table width
  src/components/Details/details.scss
  src/components/Table/TableView.js
  src/components/Table/table.scss
Labels: bug

#1989 Fix [Jobs] print 400 error message when running local job
  src/api/details-api.js
  src/components/Details/details.util.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/components/Jobs/jobs.util.js
  src/components/Workflow/Workflow.js
  src/constants.js
  src/elements/DeployModelPopUp/DeployModelPopUp.js
  src/elements/NewFunctionPopUp/NewFunctionPopUp.js
  src/elements/NewFunctionPopUp/newFuctionPopUp.util.js
  src/elements/TableTypeCell/TableTypeCell.js
  src/hooks/usePods.hook.js
  src/reducers/artifactsReducer.js
  src/reducers/functionReducer.js
  src/utils/createJobsContent.js
  src/utils/parseJob.js
  src/utils/parseWorkflows.js
Labels: bug

#1993 Fix [Batch run] Selected function from the project list hint the same function from the hub `1.5.x`
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
Labels: bug

#1990 Fix [Feature Sets] Passthrough popup appears `1.5.x`
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
Labels: bug

#1992 Fix [Batch run] Selected function from the project list hint the same function from the hub
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
Labels: bug

#1991 Fix [Feature Sets] Passthrough popup appears
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
Labels: bug

#1997 Fix [Batch run] The wrong iMessage for dataset input path
  src/common/TargetPath/targetPath.util.js
Labels: bug

#1998 Fix [Batch Inference] The wrong iMessage for dataset input path `1.5.x`
  src/common/TargetPath/targetPath.util.js
Labels: bug

#2000 Fix [Jobs] Incorrect runs list is loaded after trying to load 'Heavy' runs `1.5.x`
  src/components/Jobs/MonitorJobs/MonitorJobs.js
Labels: bug

#1999 Fix [Jobs] Incorrect runs list is loaded after trying to load 'Heavy' runs
  src/components/Jobs/MonitorJobs/MonitorJobs.js
Labels: bug

#2002 Fix [Jobs] missing error reason when job abort fails `1.5.x`
  src/components/Jobs/jobs.util.js
Labels: bug

#2001 Impl [Notifications] Add closing/removing manually `1.5.x`
  src/common/Notification/Notification.js
  src/common/Notification/NotificationView.js
  src/common/Notification/notificationView.scss
Labels: enhancement

#1995 Fix [Jobs] missing error reason when job abort fails
  src/components/Jobs/jobs.util.js
Labels: bug

#1996 Impl [Notifications] Add closing/removing manually
  src/common/Notification/Notification.js
  src/common/Notification/NotificationView.js
  src/common/Notification/notificationView.scss
Labels: enhancement

#2004 Fix [Batch run] Show function's inputs on re-run and mark mandatory items `1.5.x`
  src/components/JobWizard/JobWizard.util.js
  src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
  src/elements/FormVolumesTable/FormVolumesRow/formVolumeRow.scss
  src/scss/main.scss
Labels: bug

#2003 Fix [Batch run] Show function's inputs on re-run and mark mandatory items
  src/components/JobWizard/JobWizard.util.js
  src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
  src/elements/FormVolumesTable/FormVolumesRow/formVolumeRow.scss
  src/scss/main.scss
Labels: bug

#2008 Fix [Jobs] Go back to list redirects to Overview page
  src/components/ModelsPage/RealTimePipelines/RealTimePipelinesView.js
  src/reducers/artifactsReducer.js
  src/utils/getCloseDetailsLink.js
Labels: bug

#2010 Fix [Filter] Add default "Apply" button `1.5.x`
  src/components/ArtifactsActionBar/ArtifactsActionBar.js
  src/components/FilterMenuModal/FilterMenuModal.js
  src/components/FilterMenuModal/HubCategoriesFilter/HubCategoriesFilter.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
Labels: bug

#2009 Fix [Filter] Add default "Apply" button
  src/components/ArtifactsActionBar/ArtifactsActionBar.js
  src/components/FilterMenuModal/FilterMenuModal.js
  src/components/FilterMenuModal/HubCategoriesFilter/HubCategoriesFilter.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
Labels: bug

#2011 Fix [ML functions] Function without a status is in a 'Creating' status `1.5.x`
  src/components/FunctionsPage/functions.util.js
  src/constants.js
  src/elements/FunctionsPanelGeneral/functionsPanelGeneral.scss
  src/scss/main.scss
  src/utils/getState.js
Labels: bug

#1994 Fix [ML functions] Function without a status is in a 'Creating' status
  src/components/FunctionsPage/functions.util.js
  src/constants.js
  src/elements/FunctionsPanelGeneral/functionsPanelGeneral.scss
  src/scss/main.scss
  src/utils/getState.js
Labels: bug

#2012 Fix [Batch inference] The model_path input only supports store paths
  src/common/TargetPath/targetPath.util.js
  src/constants.js
  src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
Labels: bug

#2013 Fix [Batch inference] The model_path input only supports store paths `1.5.x`
  src/common/TargetPath/targetPath.util.js
  src/constants.js
  src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
Labels: bug

#2014 Fix [Batch Run] App crashes on an attempt to delete Data input
  src/common/TargetPath/TargetPath.js
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#2015 Fix [Batch Run] App crashes on an attempt to delete Data input `1.5.x`
  src/common/TargetPath/TargetPath.js
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#2017 Fix [Batch run] Require mandatory data inputs and parameters before running the job `1.5.x`
  src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
  src/elements/FormDataInputsTable/FormDataInputsTable.js
  src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesRow/FormEnvironmentVariablesRow.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
  src/elements/FormParametersTable/FormParametersRow/formParametersRow.scss
  src/elements/FormParametersTable/FormParametersTable.js
  src/elements/FormVolumesTable/FormVolumesRow/FormVolumesRow.js
  src/scss/main.scss
Labels: bug

#2016 Fix [Batch run] Require mandatory data inputs and parameters before running the job
  src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
  src/elements/FormDataInputsTable/FormDataInputsTable.js
  src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesRow/FormEnvironmentVariablesRow.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
  src/elements/FormParametersTable/FormParametersRow/formParametersRow.scss
  src/elements/FormParametersTable/FormParametersTable.js
  src/elements/FormVolumesTable/FormVolumesRow/FormVolumesRow.js
  src/scss/main.scss
Labels: bug

#2020 Fix [Functions panel] The "Save" and "Deploy" buttons shouldn't be enabled `1.5.x`
  src/common/Input/input.scss
  src/common/RangeInput/RangeInput.js
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/PartitionFields/PartitionFields.js
Labels: bug

#1984 Impl [Navigation] Change project monitoring to be the default project view
  src/App.js
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/common/ProjectDetailsHeader/ProjectDetailsHeader.js
  src/constants.js
  src/elements/ProjectCard/ProjectCardView.js
  src/layout/Navbar/Navbar.utils.js
Labels: enhancement

#2022 Impl [Quick Links] Revamp tables quick links and action icons
  src/common/ActionsMenu/ActionsMenu.js
  src/common/ActionsMenu/actionsMenu.scss
  src/components/Datasets/Datasets.js
  src/components/Files/Files.js
  src/components/ModelsPage/Models/Models.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/scss/main.scss
  src/utils/copyToClipboard.js
  src/utils/createArtifactsContent.js
Labels: bug

#2023 Fix [Project Monitor] mlrun long run - GET to mlrun/api/v1/runs?.. fails with 504
  src/actions/projects.js
  src/elements/ProjectDataCard/ProjectDataCard.js
  src/elements/ProjectJobs/ProjectJobs.js
Labels: bug

#2024 Fix [Project Monitor] mlrun long run - GET to mlrun/api/v1/runs?.. fails with 504 `1.5.x`
  src/actions/projects.js
  src/elements/ProjectDataCard/ProjectDataCard.js
  src/elements/ProjectJobs/ProjectJobs.js
Labels: bug

#2025 Impl [Batch Inference] Add Tech preview text
  src/components/JobWizard/JobWizard.js
Labels: enhancement

#2026 Impl [Batch Inference] Add Tech preview text `1.5.x`
  src/components/JobWizard/JobWizard.js
Labels: enhancement

#2028 Fix [Navigation] Adjust Route to new path
  src/layout/Navbar/Navbar.utils.js
Labels: bug

#2027 Impl [Monitor Jobs] Add option to delete jobs in the UI
  src/actions/jobs.js
  src/api/jobs-api.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/constants.js
  src/reducers/jobReducer.js
Labels: enhancement

#2032 Fix [Batch run] "Next" button is disabled when hyperparams selected from file
  src/components/JobWizard/JobWizardSteps/JobWizardParameters/JobWizardParameters.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
  src/elements/FormParametersTable/FormParametersTable.js
Labels: bug

#2034 Fix [Project monitor] change quotes to parenthesis `1.5.x`
  src/components/Project/project.scss
  src/elements/ProjectDataCard/ProjectDataCard.js
Labels: bug

#2033 Fix [Project monitor] change quotes to parenthesis
  src/components/Project/project.scss
  src/elements/ProjectDataCard/ProjectDataCard.js
Labels: bug

#2035 Fix [Table] Bug with scroll
  src/components/Datasets/DatasetsView.js
  src/components/Files/FilesView.js
  src/components/Table/Table.js
Labels: bug

#2036 Fix [UI] Project monitoring - wrong filter for running jobs
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/elements/ProjectStatistics/ProjectStatistics.js
  src/reducers/filtersReducer.js
Labels: bug

#2038 Fix [Models/Datasets/Artifacts] Errors occur on opening actions menu
  src/common/ActionsMenu/ActionsMenu.js
  src/components/Datasets/Datasets.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureVectors/featureVectors.util.js
  src/components/FeatureStore/Features/Features.js
  src/components/Files/Files.js
  src/components/FunctionsPage/Functions.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
  src/components/ProjectsPage/projectsData.js
  src/components/Table/Table.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/types.js
Labels: bug

#2041 Impl [Tests] Sprint 148
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/input-group.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/mock.js
Labels: tests

#2040 Fix [Batch Run] UI should not try to fetch hub functions without navigating to "Hub" tab
  src/actions/functions.js
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/constants.js
  src/reducers/functionReducer.js
Labels: bug

#2043 Fix [UI] add data-testid for buttons in models/artifacts/datasets screens
  src/common/Accordion/Accordion.js
  src/common/ActionsMenu/ActionsMenu.js
  src/common/Breadcrumbs/Breadcrumbs.js
  src/common/KeyValueTable/KeyValueTableView.js
  src/components/ConsumerGroup/ConsumerGroup.js
  src/components/Datasets/Datasets.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsInputs/DetailsInputs.js
  src/components/DetailsPreview/DetailsPreview.js
  src/components/Files/Files.js
  src/components/FilterMenu/FilterMenu.js
  src/components/ModelsPage/Models/Models.js
  src/components/ProjectsPage/ProjectsView.js
  src/elements/FunctionsPanelTitle/FunctionsPanelTitle.js
  src/elements/JobsPanelTitle/JobsPanelTitleView.js
  src/layout/Navbar/Navbar.js
Labels: bug

#2044 Impl [Batch-run] improved handling of parameters
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardDataInputs/JobWizardDataInputs.js
  src/components/JobWizard/JobWizardSteps/JobWizardParameters/JobWizardParameters.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
  src/elements/FormDataInputsTable/FormDataInputsRow/FormDataInputsRow.js
  src/elements/FormDataInputsTable/FormDataInputsTable.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
  src/elements/FormParametersTable/FormParametersRow/formParametersRow.scss
  src/elements/FormParametersTable/FormParametersTable.js
Labels: enhancement

#2046 Fix [Project monitoring, Quick actions] Change instance name capitalization
  src/common/ProjectDetailsHeader/ProjectDetailsHeader.js
  src/elements/ProjectDataCard/ProjectDataCard.js
Labels: bug

#2047 Fix [Models] Actions aren't aligned
  src/common/ActionsMenu/actionsMenu.scss
  src/scss/main.scss
Labels: bug

#2052 Fix [Batch run] is broken for parameters-less functions `1.5.x`
  src/elements/FormDataInputsTable/FormDataInputsTable.js
  src/elements/FormParametersTable/FormParametersTable.js
Labels: bug

#2050 Impl [Wizards] should work as a single logical screen
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardAdvanced/JobWizardAdvanced.js
  src/components/JobWizard/JobWizardSteps/JobWizardDataInputs/JobWizardDataInputs.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/jobWizardFunctionSelection.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardHyperparameterStrategy/JobWizardHyperparameterStrategy.js
  src/components/JobWizard/JobWizardSteps/JobWizardParameters/JobWizardParameters.js
  src/components/JobWizard/JobWizardSteps/JobWizardResources/JobWizardResources.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
  src/constants.js
  src/elements/FormDataInputsTable/FormDataInputsTable.js
  src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesTable.js
  src/elements/FormParametersTable/FormParametersTable.js
  src/elements/FormResourcesUnits/FormResourcesUnits.js
  src/elements/FormVolumesTable/FormVolumesTable.js
Labels: enhancement

#2048 Impl [Artifacts] Move Overview "Sources" according to Figma
  src/actions/details.js
  src/components/ArtifactInfoSources/ArtifactInfoSources.js
  src/components/ArtifactInfoSources/artifactInfoSources.scss
  src/components/ArtifactInfoSources/artifactInfoSources.utils.js
  src/components/Datasets/datasets.util.js
  src/components/Details/details.util.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfo.util.js
  src/components/Files/Files.js
  src/components/Files/files.util.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpointsView.js
  src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/Models/models.util.js
  src/constants.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/reducers/detailsReducer.js
  src/utils/generateProducerDetailsInfo.js
  src/utils/isEveryObjectValueEmpty.js
Labels: enhancement

#2053 Fix [Action menu] App crash when trying to 'edit' an ML function
  src/elements/EnvironmentVariables/EnvironmentVariables.js
  src/elements/FunctionPanelTopologyModelTable/FunctionPanelTopologyModelTable.js
  src/elements/FunctionsPanelParameters/FunctionsPanelParameters.js
  src/elements/VolumesTable/VolumesTable.js
Labels: bug

#2049 Impl [Download]: Revamp Download by Figma
  src/common/Download/Download.js
  src/common/Download/DownloadContainer.js
  src/common/Download/DownloadItem.js
  src/common/Download/download.scss
  src/common/Download/downloadContainer.scss
  src/common/ProgressRing/ProgressRing.js
  src/common/ProgressRing/progressRing.scss
  src/components/Datasets/Datasets.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/Files/Files.js
  src/components/ModelsPage/Models/Models.js
  src/elements/PreviewModal/PreviewModal.js
  src/elements/TableCell/TableCell.js
  src/layout/Page/Page.js
  src/reducers/downloadReducer.js
  src/store/toolkitStore.js
  src/utils/createArtifactsContent.js
Labels: enhancement

#2055 Fix [General] Issue with UI build job
  src/common/Download/Download.js
  src/components/Datasets/Datasets.js
  src/components/Files/Files.js
  src/components/ModelsPage/Models/Models.js
Labels: bug
