Repository mlrun/ui, pull requests merged in 2023-08, with the labels that each got.

#1832 QA Sprint 144 done
  package.json
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/checkbox.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/models.feature
  tests/features/projectPage.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/features/support/world.js
Labels: tests

#1835 Impl [tests] Sprint 144
  package.json
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/checkbox.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/models.feature
  tests/features/projectPage.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/features/support/world.js
Labels: tests

#1833 Fix [Artifacts] v3io dir artifact blank preview
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/ArtifactsPreview/artifactsPreview.scss
Labels: bug

#1840 Fix [Batch Run] Scheduled jobs doesn't display all data
  src/actions/jobs.js
  src/api/jobs-api.js
  src/components/JobWizard/JobWizard.util.js
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/components/Jobs/ScheduledJobs/scheduledJobs.util.js
  src/constants.js
  src/reducers/jobReducer.js
Labels: bug

#1841 Impl [Functions] Create batch function - missing requirements section
  src/actions/functions.js
  src/components/FunctionsPanel/FunctionsPanel.js
  src/constants.js
  src/elements/FunctionsPanelCode/FunctionsPanelCode.js
  src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
  src/elements/FunctionsPanelCode/functionsPanelCode.scss
  src/reducers/functionReducer.js
  src/utils/string.js
Labels: enhancement

#1842 Fix [Batch run] The GPU resources card does not adapt to different screen sizes
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizardSteps/JobWizardAdvanced/JobWizardAdvanced.js
  src/components/JobWizard/JobWizardSteps/JobWizardDataInputs/JobWizardDataInputs.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/components/JobWizard/JobWizardSteps/JobWizardParameters/JobWizardParameters.js
  src/components/JobWizard/JobWizardSteps/JobWizardResources/JobWizardResources.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
  src/elements/FormResourcesUnits/formResourcesUnits.scss
Labels: bug

#1843 Fix [Batch run] Button 'Add volume' displays as 'Add custom parameter' for adding new volume during setting the resources in Batch Run
  src/elements/FormVolumesTable/FormVolumesTable.js
Labels: bug

#1844 Fix [Batch run] Incorrect tip message in Access Key form field during setting the resources in Batch Run
  src/elements/FormVolumesTable/formVolumesTable.util.js
Labels: bug

#1845 Fix [Batch run] No validation for a negative CPU value during setting the resources in Batch Run
  src/elements/FormResourcesUnits/FormResourcesUnits.js
Labels: bug

#1846 Fix [BatchRun] Inconsistent Fonts of Resource headers sections
  src/scss/main.scss
Labels: bug

#1848 Fix [Batch run] Request Payload does not contain env var value
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#1826 Fix [Batch run] add vertical scroll to function list
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/jobWizardFunctionSelection.scss
Labels: bug

#1849 Fix [Batch run] The chosen method should be present in the first row
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
Labels: bug

#1850 Fix [Batch run] incorrect "Add a node" button name in "Node selection" section of batch run
  src/components/JobWizard/JobWizardSteps/JobWizardResources/JobWizardResources.js
Labels: bug

#1851 Fix [Monitor Jobs] Error on navigating to job after deleting function
  src/components/Jobs/jobs.util.js
  src/components/Project/ProjectMonitor.js
Labels: bug

#1854 Fix [Batch Run] The Container and Resource Path fields for V3IO volume should not be mandatory
  src/elements/FormVolumesTable/formVolumesTable.util.js
Labels: bug

#1858 Fix [Jobs] UI does not show boolean result in "Monitor Jobs" -> "Results"
  src/components/DetailsResults/DetailsResults.js
Labels: bug

#1859 Fix [Jobs] Uncaught runtime errors screen
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/components/Jobs/jobs.util.js
Labels: bug

#1860 Fix [UI] expand button is visible when change project on the Datasets, Artifacts and Models pages
  src/components/Datasets/Datasets.js
  src/components/Files/Files.js
  src/components/ModelsPage/Models/Models.js
Labels: bug

#1861 Fix [Batch run] Error during schedule
  src/components/SheduleWizard/ScheduleWizard.js
  src/components/SheduleWizard/ScheduleWizardSimple.js
  src/components/SheduleWizard/scheduleWizard.scss
  src/constants.js
Labels: bug

#1862 Fix [Breadcrumbs] project search value persists after list closing
  src/common/Breadcrumbs/Breadcrumbs.js
  src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js
Labels: bug

#1863 Fix [Projects] search project is case sensitive
  src/common/Search/Search.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
Labels: bug

#1864 Fix [Details Statistics] The scrollbar appears for a few seconds
  src/common/Chart/mlChart.scss
Labels: bug

#1868 Fix [Feature set] inaccurate default path for redis
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
  src/components/FeatureSetsPanel/featureSetPanel.util.js
Labels: bug

#1866 Fix [Batch run] autofilled dataset store path is invalid
  src/common/TargetPath/targetPath.util.js
Labels: bug

#1867 Impl [Project home] Add Model Training Icon
  src/components/Project/ProjectOverview/ProjectOverview.util.js
Labels: enhancement

#1870 Fix [UI] "Type" inconsistency for databricks job
  src/components/Details/details.scss
  src/elements/TableTypeCell/TableTypeCell.js
Labels: bug

#1869 Fix [Feature set] minor Redis path fix
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/constants.js
Labels: bug

#1872 Fix [UI] Filter by tag isn't performed when version tag was edited
  src/components/Files/Files.js
Labels: bug

#1873 Fix [Consumer groups] UI does not show the right detalis
  src/App.js
  src/components/ConsumerGroup/ConsumerGroup.js
  src/utils/createConsumerGroupsContent.js
  tests/mockServer/data/nuclioStreams.json
Labels: bug

#1874 Fix [Batch run] Move `Type` for Env vars out of the staging mode
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardAdvanced/JobWizardAdvanced.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
  src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesRow/FormEnvironmentVariablesRow.js
  src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesTable.js
Labels: bug

#1875 Fix [Batch run] Add missing fields to volumes
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#1876 Fix [Batch Run] Run failed after edit/remove GPU limit from UI
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#1877 Fix [Batch run] Function param without type is being shown as "str"
  src/components/JobWizard/JobWizard.util.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
Labels: bug

#1879 Impl [Projects] Remove 'Export YAML' from demo mode
  src/components/ProjectsPage/projectsData.js
Labels: enhancement

#1885 Impl [Batch run] Utilize the new API for fetching the hub function
  src/actions/functions.js
  src/api/functions-api.js
  src/components/JobWizard/JobWizard.js
  src/constants.js
  src/reducers/functionReducer.js
Labels: enhancement

#1880 Fix [UI] The tag name "undefined" is automatically assigned when first time save tag without data
  src/components/Datasets/DatasetsView.js
  src/components/Files/FilesView.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
Labels: bug

#1883 Fix [Batch Run] The "handler"/"method" option is missing in UI in case the function has not "entry_points"
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
  src/elements/FunctionsPanelCode/FunctionsPanelCode.js
Labels: bug

#1884 Fix [Batch Run] The UI should prevent the "Max Iterations" field from being set unless the strategy is random
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardHyperparameterStrategy/JobWizardHyperparameterStrategy.js
  src/components/JobWizard/JobWizardSteps/JobWizardHyperparameterStrategy/jobWizardHyperparameterStrategy.util.js
  src/components/JobsPanelParameters/jobsPanelParameters.util.js
  src/constants.js
Labels: bug

#1886 Fix [Batch Run] It's not clear what the 'Hyper' toggle does
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/jobWizard.scss
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
  src/elements/FormParametersTable/FormParametersTable.js
Labels: bug

#1887 Fix [Batch Run] Remove "Custom" strategy from Hyperparameter strategy
  src/components/JobWizard/JobWizardSteps/JobWizardHyperparameterStrategy/jobWizardHyperparameterStrategy.util.js
Labels: bug

#1890 QA Sprint 145 done
  tests/features/common-tools/common-consts.js
  tests/features/common-tools/common-tools.js
  tests/features/common/actions/common.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/ml-functions.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectPage.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/mock.js
Labels: tests

#1891 Impl [tests] Sprint 145
  tests/features/common-tools/common-consts.js
  tests/features/common-tools/common-tools.js
  tests/features/common/actions/common.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/ml-functions.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectPage.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/mock.js
Labels: tests
