Repository mlrun/ui, pull requests merged in 2023-02, with the labels that each got.

#1601 Fix [Artifacts] Align 'Name' column in Artifacts and ML function view
  src/components/ConsumerGroup/consumerGroup.util.js
  src/components/ConsumerGroups/consumerGroups.util.js
  src/components/Details/DetailsView.js
  src/components/DetailsResults/DetailsResults.js
  src/components/DetailsResults/detailsResults.scss
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/elements/TableLinkCell/tableLinkCell.scss
  src/scss/main.scss
  src/utils/createArtifactsContent.js
  src/utils/createFeatureStoreContent.js
  src/utils/createFunctionsContent.js
  src/utils/createJobsContent.js
Labels: bug

#1606 Fix [Jobs] make default sort by 'Iter' in 'Results' tab
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/Details/details.util.js
Labels: bug

#1609 Fix [Monitor Workflow] "Switch to list view" returns empty screen
  src/actions/jobs.js
  src/actions/workflow.js
  src/api/jobs-api.js
  src/components/Details/details.util.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/constants.js
  src/reducers/jobReducer.js
  src/reducers/workflowReducer.js
Labels: bug

#1610 Fix [Project home] The tooltips description has been cut
  src/components/Project/ProjectOverview/ProjectOverview.util.js
Labels: bug

#1612 Fix [UI] Project screen shows empty list after an upgrade `1.2.x`
  src/api/app-api.js
  src/reducers/appReducer.js
Labels: bug

#1611 Fix [UI] Project screen shows empty list after an upgrade
  src/api/app-api.js
  src/reducers/appReducer.js
Labels: bug

#1615 Fix [Monitor Workflows] Filtering by status Error does not work for workflows in Failed state
  src/components/FilterMenu/filterMenu.settings.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
Labels: bug

#1616 Fix [Feature Store] unable to add features in 'Add to feature vector' dialog
  src/components/Table/table.scss
Labels: bug

#1613 Impl [UI] Support 'None' in project summaries response counters
  src/actions/projects.js
  src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.js
  src/utils/parseSummaryData.js
Labels: enhancement

#1617 Fix [Settings] Cannot add members to project
  src/components/ProjectSettings/ProjectSettings.js
Labels: bug

#1618 Fix [Jobs workflow] Back and Close buttons don't work when ui is opened from Jupyter link
  src/components/Jobs/Jobs.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/constants.js
Labels: bug

#1620 Impl [Monitor Workflow] Create new table row view for Run and Deploy
  src/common/ReactFlow/mlReactFlow.util.js
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/Details/details.util.js
  src/components/DetailsResults/DetailsResults.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/ModelsPage/Models/Models.js
  src/components/Table/Table.js
  src/components/Table/TableHead.js
  src/components/Table/TableView.js
  src/components/Workflow/JobsFunctionsTableRow/JobsFunctionsTableRow.js
  src/components/Workflow/Workflow.js
  src/components/Workflow/workflow.util.js
  src/elements/TableCell/TableCell.js
  src/hooks/useSortTable.hook.js
  src/utils/createJobsContent.js
  src/utils/generateTableContent.js
  src/utils/getUniqueIdentifier.js
  src/utils/parseJob.js
Labels: enhancement

#1619 Fix [Monitor Workflows] unable to open workflow graph/details
  src/actions/workflow.js
  src/api/workflow-api.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
Labels: bug

#1621 Fix [Workflows] Different artifact name in the list and in the preview screen
  src/components/DetailsArtifacts/DetailsArtifactsView.js
Labels: bug

#1622 Fix [Project Home] incorrect label names
  src/components/Project/ProjectOverview/ProjectOverview.util.js
Labels: bug

#1625 Fix [Project Settings] Duplicated keys error when adding same name members
  src/elements/MembersPopUp/MembersPopUp.js
Labels: bug

#1628 Fix [Functions] The function with not latest tag is presented on initialization
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
  src/components/Datasets/Datasets.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
  src/components/FeatureStore/Features/Features.js
  src/components/Files/Files.js
  src/components/FunctionsPage/Functions.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
  src/components/Table/Table.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/hooks/groupContent.hook.js
  src/layout/Content/Content.js
  src/utils/generateGroupLatestItem.js
Labels: bug

#1630 Fix [Workflow] Use `run_type` value instead of `type` in the table
  src/utils/createJobsContent.js
Labels: bug

#1629 Fix [Jobs] MLRunNotFoundError on job submit via UI from "saved" function
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#1631 Fix [Functions] Details Pane Header Too Short for Tab Content Width
  src/components/Details/details.scss
Labels: bug

#1632 Fix [Jobs/Workflows] screen should display the version tag
  src/actions/functions.js
  src/actions/jobs.js
  src/api/functions-api.js
  src/api/jobs-api.js
  src/components/Details/details.util.js
  src/components/FunctionsPage/functions.util.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/jobs.util.js
  src/constants.js
  src/reducers/functionReducer.js
  src/reducers/jobReducer.js
Labels: bug, enhancement

#1597 Fix [Models] Missing the "Duplicated tag" verification for updating tag
  src/actions/details.js
  src/api/artifacts-api.js
  src/common/ChipCell/ChipCellView.js
  src/common/ChipCell/ChipTooltip/ChipTooltip.js
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/Details/Details.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/Details/DetailsTabsContent/DetailsTabsContent.js
  src/components/Details/DetailsView.js
  src/components/Details/details.util.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureSets/FeatureSetsView.js
  src/components/FeatureStore/FeatureVectors/FeatureVectorsView.js
  src/components/FeatureStore/FeatureVectors/featureVectors.util.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/Models/models.util.js
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/constants.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/elements/DetailsInfoItemChip/DetailsInfoItemChip.js
  src/elements/HiddenChipsBlock/HiddenChipsBlock.js
  src/reducers/detailsReducer.js
  src/utils/artifacts.util.js
  src/utils/getChipLabelAndValue.js
Labels: bug

#1634 Fix [Workflows] Clicking on a pipeline graph step does not open details
  src/components/Workflow/Workflow.js
Labels: bug

#1635 Fix [Jobs] Hyper params run does not present artifacts iteration
  src/components/DetailsArtifacts/DetailsArtifacts.js
Labels: bug

#1636 Fix [Jobs] Artifacts name aren't displayed
  src/components/DetailsArtifacts/DetailsArtifactsView.js
Labels: bug

#1633 Impl [Batch Run] Align function selection by Figma
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/jobWizardFunctionSelection.scss
  src/elements/FunctionCardTemplate/FunctionCardTemplate.js
  src/elements/FunctionCardTemplate/functionCardTemplate.scss
Labels: enhancement
