Repository mlrun/ui, pull requests merged in 2023-07, with the labels that each got.

#1791 Fix [Project home] The "Job and workflow" link from project page navigates to Projects screen
  src/components/ProjectsPage/Projects.js
Labels: bug

#1793 Fix [Workflows] The "Undefined " API is sent and failed for rerun job from WF
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#1795 Impl [tests] Sprint 143
  package.json
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/api.actions.js
  tests/features/common/actions/dropdown.action.js
  tests/features/common/actions/input-group.action.js
  tests/features/common/actions/input-with-autocomplete.action.js
  tests/features/common/actions/tab-selector.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/commonPagesHeader.po.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/ml-functions.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/project.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectPage.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/frontendSpec.json
  tests/mockServer/data/funcs.json
  tests/mockServer/mock.js
Labels: tests

#1796 Impl [UI] Add attribute data-testid to the artifacts table row elements
  src/components/Datasets/DatasetsView.js
  src/components/FeatureStore/FeatureSets/FeatureSetsView.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/RealTimePipelines/RealTimePipelinesView.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/FeatureStoreTableRow/FeatureStoreTableRow.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/utils/generateTableRowTestId.js
Labels: enhancement

#1798 Impl [UI] Add attribute data-testid to the artifacts table row elements `1.4.x`
  src/components/Datasets/DatasetsView.js
  src/components/FeatureStore/FeatureSets/FeatureSetsView.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/RealTimePipelines/RealTimePipelinesView.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/FeatureStoreTableRow/FeatureStoreTableRow.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/utils/generateTableRowTestId.js
Labels: enhancement

#1799 Fix [Workflows] The "Undefined " API is sent and failed for rerun job from WF `1.4.x`
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/JobsPanel/JobsPanel.js
  src/components/JobsPanel/jobsPanel.util.js
Labels: bug

#1792 Impl [Job Wizard] Changes to Parameters table
  src/actions/functions.js
  src/actions/jobs.js
  src/common/DatePicker/datePicker.scss
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizard.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardAdvanced/JobWizardAdvanced.js
  src/components/JobWizard/JobWizardSteps/JobWizardDataInputs/JobWizardDataInputs.js
  src/components/JobWizard/JobWizardSteps/JobWizardHyperparameterStrategy/JobWizardHyperparameterStrategy.js
  src/components/JobWizard/JobWizardSteps/JobWizardHyperparameterStrategy/jobWizardHyperparameterStrategy.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardHyperparameterStrategy/jobWizardHyperparametersStrategy.scss
  src/components/JobWizard/JobWizardSteps/JobWizardParameters/JobWizardParameters.js
  src/components/JobWizard/JobWizardSteps/JobWizardResources/JobWizardResources.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
  src/components/JobWizard/jobWizard.scss
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/components/Jobs/ScheduledJobs/scheduledJobs.util.js
  src/components/Jobs/jobs.util.js
  src/components/Project/ProjectMonitor.js
  src/components/SheduleWizard/ScheduleWizardSimple.js
  src/constants.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
  src/elements/FormParametersTable/FormParametersTable.js
  src/elements/FormParametersTable/formParametersTable.util.js
  src/elements/FormResourcesUnits/FormResourcesUnits.js
  src/elements/FormResourcesUnits/formResourcesUnits.scss
  src/elements/FormVolumesTable/FormVolumesTable.js
  src/elements/MembersPopUp/MembersPopUp.js
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecrets.js
  src/reducers/jobReducer.js
  src/scss/main.scss
  src/types.js
Labels: enhancement

#1802 Impl [UI] Add attribute data-testid to the artifacts table row elements
  src/components/AddToFeatureVectorPage/AddToFeatureVectorView.js
  src/components/FeatureStore/FeatureVectors/FeatureVectorsView.js
  src/components/FeatureStore/Features/FeaturesView.js
  src/components/Files/FilesView.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpointsView.js
  src/components/Table/TableView.js
Labels: enhancement

#1801 Impl [UI] Add attribute data-testid to the artifacts table row elements
  src/components/AddToFeatureVectorPage/AddToFeatureVectorView.js
  src/components/FeatureStore/FeatureVectors/FeatureVectorsView.js
  src/components/FeatureStore/Features/FeaturesView.js
  src/components/Files/FilesView.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpointsView.js
  src/components/Table/TableView.js
Labels: enhancement

#1805 Fix [UI] Wrong navigation to the "Job and workflow"from new Project `1.4.x`
  src/actions/projects.js
Labels: bug

#1803 Fix [UI] Wrong navigation to the "Job and workflow"from new Project
  src/actions/projects.js
Labels: bug

#1806 Fix [UI] Preview table is hidden from view
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/DetailsPreview/DetailsPreview.js
  src/components/DetailsResults/DetailsResults.js
  src/scss/main.scss
  src/utils/createArtifactPreviewContent.js
Labels: bug

#1807 Fix [UI] Preview table is hidden from view `1.4.x`
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/DetailsPreview/DetailsPreview.js
  src/components/DetailsResults/DetailsResults.js
  src/scss/main.scss
  src/utils/createArtifactPreviewContent.js
Labels: bug

#1808 Fix [Feature Store] Input hint missing in URL_Combobox
  src/components/FeatureSetsPanel/UrlPath.utils.js
  src/utils/panelPathScheme.js
Labels: bug

#1811 Fix [Feature Store] Path formation for Online and Offline placeholder
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
Labels: bug

#1812 Impl [Batch run] Take the Batch run wizard out of the demo mode
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/Jobs/Jobs.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/components/Jobs/ScheduledJobs/scheduledJobs.util.js
  src/components/Jobs/jobs.util.js
  src/components/Project/ProjectMonitor.js
  src/components/Project/ProjectOverview/ProjectOverview.util.js
  src/components/Project/project.utils.js
Labels: enhancement

#1813 Impl [Batch inference] Add Batch Inference Icon to Project Home
  src/components/Project/ProjectOverview/ProjectOverview.util.js
Labels: enhancement

#1810 Fix [Tables] view, scroll, css
  src/common/TabsSlider/tabsSlider.scss
  src/components/ArtifactsPreview/ArtifactsPreview.js
  src/components/ArtifactsPreview/artifactsPreview.scss
  src/components/ArtifactsPreview/artifactsPreviewController.scss
  src/components/Details/Details.js
  src/components/Details/details.scss
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsArtifacts/detailsArtifacts.scss
  src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.scss
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/DetailsLogs/DetailsLogs.js
  src/components/DetailsMetadata/detailsMetadata.scss
  src/components/DetailsPods/DetailsPods.js
  src/components/DetailsPods/detailsPods.scss
  src/components/DetailsPreview/DetailsPreview.js
  src/components/DetailsRequestedFeatures/detailsRequestedFeatures.scss
  src/components/DetailsResults/detailsResults.scss
  src/components/DetailsStatistics/detailsStatistics.scss
  src/components/FilterMenu/filterMenu.scss
  src/components/Table/table.scss
  src/elements/TableLinkCell/tableLinkCell.scss
  src/elements/TableTop/tableTop.scss
  src/scss/main.scss
Labels: enhancement, Cleanup

#1820 Fix [Batch run] Buttons are missing in the categories-list popup dialog
  src/components/ArtifactsActionBar/ArtifactsFilters.js
  src/components/ArtifactsActionBar/artifactsFilters.scss
  src/components/FilterMenuModal/FilterMenuModal.js
  src/components/FilterMenuModal/filterMenuModal.scss
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
Labels: bug

#1821 Impl [Details] Change the view toggle icons
  package.json
  src/components/Details/DetailsHeader/DetailsHeader.js
Labels: enhancement

#1819 Fix [Feature set] Failed target store validation for create feature set
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
  src/components/FeatureSetsPanel/featureSetPanel.util.js
Labels: bug

#1814 Fix [Feature store] Add type Redis to online types list
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.scss
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
  src/constants.js
Labels: enhancement

#1816 Impl [Model Endpoints] Display function tag in model endpoint
  src/components/Details/details.util.js
  src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
Labels: enhancement

#1818 Fix [Batch run] Can't change the type in the existing Environment variables
  src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesRow/FormEnvironmentVariablesRow.js
Labels: bug

#1829 Fix [Batch Inference] last tab buttons are not as per requirement
  src/components/JobWizard/JobWizard.js
Labels: bug

#1825 Fix [UI] Filter with no result should include the labels
  src/utils/getNoDataMessage.js
Labels: bug

#1823 Fix [Batch run] an attempt to run "batch run" fails with "runtime error: (422) Reason: Unprocessable Entity"
  src/components/JobWizard/JobWizard.util.js
  src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesRow/FormEnvironmentVariablesRow.js
Labels: bug

#1822 Fix [Feature set] Error during schedule data source
  src/components/FeatureSetsPanel/ScheduleFeatureSet/ScheduleFeatureSet.js
  src/components/FeatureSetsPanel/ScheduleFeatureSet/ScheduleFeatureSetView.js
  src/components/FilterMenuModal/filterMenuModal.scss
  src/elements/ScheduleRecurring/scheduleRecurring.scss
Labels: bug

#1827 Impl [UI] Support DBFS as a data item
  src/common/Combobox/combobox.scss
  src/common/TargetPath/targetPath.util.js
  src/components/FeatureSetsPanel/UrlPath.js
  src/components/FeatureSetsPanel/UrlPath.utils.js
  src/constants.js
  src/scss/main.scss
Labels: enhancement
