Repository mlrun/ui, pull requests merged in 2024-02, with the labels that each got.

#2228 FIx [Feature store] Features displaying issues
  src/components/FeatureStore/FeatureStore.js
  src/constants.js
  src/elements/FeatureStoreTableRow/FeatureStoreTableRow.js
  src/scss/main.scss
  src/utils/createFeatureStoreContent.js
Labels: bug

#2229 Fix [Models] data displaying issue (reverted to the chips column)
  src/components/ModelsPage/Models/Models.js
  src/utils/createArtifactsContent.js
Labels: bug

#2230 Fix [Models] data displaying issue (reverted to the chips column) `1.6.x`
  src/components/ModelsPage/Models/Models.js
  src/utils/createArtifactsContent.js
Labels: bug

#2233 Fix [UI] Use abort_job endpoint to abort jobs from UI
  src/actions/jobs.js
  src/api/jobs-api.js
  src/api/tasks-api.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/jobs.util.js
  src/httpClient.js
  src/scss/main.scss
  src/utils/getState.js
  src/utils/parseJob.js
  src/utils/poll.util.js
  tests/mockServer/mock.js
Labels: bug

#2234 Fix [UI] Use abort_job endpoint to abort jobs from UI `1.6.x`
  src/actions/jobs.js
  src/api/jobs-api.js
  src/api/tasks-api.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/jobs.util.js
  src/httpClient.js
  src/scss/main.scss
  src/utils/getState.js
  src/utils/parseJob.js
  src/utils/poll.util.js
  tests/mockServer/mock.js
Labels: bug

#2236 Impl [Projects] new API for project deletion
  src/actions/projects.js
  src/api/projects-api.js
  src/api/tasks-api.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projects.util.js
  src/reducers/tasksReducer.js
  src/scss/main.scss
  src/store/toolkitStore.js
  src/utils/poll.util.js
  tests/mockServer/mock.js
Labels: enhancement

#2239 Impl [Projects] new API for project deletion `1.6.x`
  src/actions/projects.js
  src/api/projects-api.js
  src/api/tasks-api.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projects.util.js
  src/reducers/tasksReducer.js
  src/scss/main.scss
  src/store/toolkitStore.js
  src/utils/poll.util.js
  tests/mockServer/mock.js
Labels: enhancement

#2237 Fix [Batch Run] job pod fails to mount fuse when ran via UI
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#2238 Fix [Batch Run] job pod fails to mount fuse when ran via UI `1.6.x`
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#2232 Fix [Batch Run] Blank project screen after setting model target path
  src/actions/projects.js
  src/common/TargetPath/TargetPath.js
  src/common/TargetPath/targetPath.util.js
  src/components/FeatureSetsPanel/UrlPath.js
  src/components/FeatureSetsPanel/UrlPath.utils.js
  src/utils/parseTargetPath.js
Labels: bug

#2231 Fix [Jobs] Auto refresh screen not worked `1.6.x`
  src/components/FilterMenu/FilterMenu.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/constants.js
Labels: bug

#2235 Fix [Jobs] Auto refresh screen not worked
  src/components/FilterMenu/FilterMenu.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/constants.js
Labels: bug

#2241 Fix [Monitor jobs] Wrong selected item in "Artifacts" tab
  src/components/ArtifactsPreview/ArtifactsPreviewController.js
  src/components/Details/details.util.js
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsArtifacts/DetailsArtifactsView.js
  src/components/DetailsArtifacts/detailsArtifacts.util.js
  src/components/DetailsInputs/DetailsInputs.js
  src/components/DetailsInputs/detailsInputs.util.js
  src/elements/ArtifactsExtraData/ArtifactsExtraData.js
  src/utils/getArtifactPreview.js
Labels: bug

#2244 Fix [Jobs] Workflow screen is slow `1.6.x`
  src/common/DatePicker/DatePickerView.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/constants.js
  src/utils/datePicker.util.js
  src/utils/getNoDataMessage.js
Labels: bug

#2248 Impl [Functions] Functions created by SDK are in initialized state in the UI and need to be deployed
  src/common/ActionsMenu/ActionsMenu.js
  src/components/CreateJobPage/CreateJobPage.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/FunctionsPage/functions.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/jobs.util.js
  src/constants.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/utils/generateTemplatesCategories.js
Labels: enhancement

#2249 Impl [Functions] Functions created by SDK are in initialized state in the UI and need to be deployed `1.6.x`
  src/common/ActionsMenu/ActionsMenu.js
  src/components/CreateJobPage/CreateJobPage.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/FunctionsPage/functions.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/jobs.util.js
  src/constants.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/utils/generateTemplatesCategories.js
Labels: enhancement

#2243 Fix [Functions] Edit source button ui
  src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
Labels: bug

#2250 Fix [Models] unable to navigate to additional metrics (+)
  src/utils/createArtifactsContent.js
Labels: bug

#2251 Fix [Models] unable to navigate to additional metrics (+) `1.6.x`
  src/utils/createArtifactsContent.js
Labels: bug

#2252 Fix [Artifacts] page loader is getting stuck upon artifact register
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
  src/reducers/artifactsReducer.js
Labels: bug

#2253 Fix [Artifacts] page loader is getting stuck upon artifact register `1.6.x`
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
  src/reducers/artifactsReducer.js
Labels: bug

#2254 Fix [Artifacts] Add tooltip for disabled Delete action
  src/components/Datasets/datasets.util.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/models.util.js
Labels: bug

#2255 Fix [Artifacts] Add tooltip for disabled Delete action `1.6.x`
  src/components/Datasets/datasets.util.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/models.util.js
Labels: bug

#2256 Fix [Model training] model batch run scores are rounded in results view and not in models
  src/utils/createArtifactsContent.js
  src/utils/object.js
  src/utils/roundFloats.js
Labels: bug

#2257 Fix [Model training] model batch run scores are rounded in results view and not in models `1.6.x`
  src/utils/createArtifactsContent.js
  src/utils/object.js
  src/utils/roundFloats.js
Labels: bug

#2246 Fix [Jobs] change Abort Job confirm message
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
Labels: bug

#2247 Fix [Jobs] change Abort Job confirm message `1.6.x`
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
Labels: bug

#2262 Impl [Tests] QA Sprint 158 done
  tests/features/artifacts.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/action-menu.action.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/project.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectMonitoring.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/quickActions.feature
  tests/features/step-definitions/table.steps.js
  tests/mockServer/mock.js
Labels: tests

#2265 Fix [General] text on data query when there is no relevant data
  src/utils/getNoDataMessage.js
Labels: bug

#2266 Fix [General] text on data query when there is no relevant data `1.6.x`
  src/utils/getNoDataMessage.js
Labels: bug

#2267 Fix [Datasets] request is not sent when changing project via breadcrumbs
  src/components/Datasets/Datasets.js
Labels: bug

#2268 Fix [Datasets] request is not sent when changing project via breadcrumbs `1.6.x`
  src/components/Datasets/Datasets.js
Labels: bug

#2273 Fix [Datepicker] position should use window size
  src/common/DatePicker/DatePicker.js
  src/common/DatePicker/DatePickerView.js
  src/common/DatePicker/datePicker.scss
Labels: bug

#2271 Fix [Jobs] change Abort Job confirm message
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/jobs.util.js
Labels: bug

#2270 Fix [Jobs] change Abort Job confirm message `1.6.x`
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/jobs.util.js
Labels: bug

#2276 Fix [Monitor workflows] Set default filter to a week (and not 24 H)
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
Labels: bug

#2279 Fix [Monitor workflows] Set default filter to a week (and not 24 H) `1.6.x`
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
Labels: bug

#2277 Fix [Projects] Present the root cause when project deletion fails
  src/components/ProjectsPage/projects.util.js
Labels: bug

#2274 Fix [Artifacts] artifact-tags requests are not canceled when changing pages
  src/api/artifacts-api.js
  src/components/Datasets/Datasets.js
  src/components/Files/Files.js
  src/components/ModelsPage/Models/Models.js
  src/hooks/useGetTagOptions.hook.js
  src/reducers/artifactsReducer.js
  src/reducers/filtersReducer.js
Labels: bug

#2280 Revert [Functions] Functions created by SDK are in initialized state in the UI and need to be deployed `1.6.x`
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functions.util.js
Labels: revert

#2281 Impl [Functions] move 'Deploy' button for "Serving" function to demo mode `1.6.x`
  src/components/FunctionsPage/functions.util.js
Labels: bug, enhancement

#2283 Fix [Models] bad code snippet in "Failed to deploy model" dialog
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/models.util.js
Labels: bug

#2282 Fix [Models] bad code snippet in "Failed to deploy model" dialog `1.6.x`
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/models.util.js
Labels: bug

#2285 Fix [Datepicker] position should use window size
  src/common/DatePicker/DatePicker.js
  src/common/DatePicker/DatePickerView.js
  src/common/DatePicker/datePicker.scss
Labels: bug

#2286 Fix [Feature Store] Autofilled dataset store path does not present the dataset tags
  src/utils/panelPathScheme.js
Labels: bug

#2287 Fix [Jobs] Job overview details panel doesn't display using browsers forward button
  src/components/Jobs/MonitorJobs/MonitorJobs.js
Labels: bug

#2288 Fix [Real-Time Pipelines] Broken link to function overview
  src/elements/RealTimePipelinesTableRow/RealTimePipelinesTableRow.js
Labels: bug

#2289 Fix [Datasets] tooltip is not shown for short producer names
  src/elements/TableProducerCell/TableProducerCell.js
Labels: bug

#2291 Impl [Tests] QA Sprint 159 done
  tests/features/common-tools/common-consts.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectMonitoring.feature
  tests/features/quickActions.feature
  tests/features/step-definitions/table.steps.js
  tests/mockServer/mock.js
Labels: tests

#2297 Fix [Feature sets] The Wrong validation error for incorrect datasource format
  src/utils/panelPathScheme.js
Labels: bug

#2296 Fix [Schedule Jobs] Last run link is missing after running a scheduled job
  src/elements/TableLinkCell/TableLinkCell.js
  src/utils/createJobsContent.js
Labels: bug

#2261 Fix [UI] general styling
  src/components/Details/details.scss
  src/elements/ProjectStatistics/projectStatistics.scss
  src/elements/TableLinkCell/tableLinkCell.scss
  src/scss/main.scss
  src/utils/createArtifactsContent.js
Labels: bug

#2293 Fix [Project settings] no redirection after changing project owner
  src/components/ProjectSettings/ProjectSettings.js
Labels: bug

#2295 Fix [Project Settings] project members are counted incorrectly
  src/elements/MembersPopUp/membersReducer.js
  src/elements/ProjectSettingsMembers/ProjectSettingsMembers.js
Labels: bug

#2298 Fix [Quick Actions] Redundant 'Are you sure?' pop-up on Register artifacts form
  src/components/Project/ProjectOverview/ProjectOverview.util.js
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
Labels: bug

#2272 Fix [Project Monitoring] 'Models' widget in 'Project Monitoring' tab doesn't get updated
  src/components/Project/ProjectMonitorView.js
  src/components/Project/project.scss
  src/components/Project/project.utils.js
  src/elements/ProjectDataCard/ProjectDataCard.js
  src/elements/ProjectJobs/ProjectJobs.js
Labels: bug

#2299 Fix [Job Artifacts] incorrect Show Details link
  src/components/DetailsArtifacts/detailsArtifacts.util.js
Labels: bug

#2300 Fix [Artifacts] incorrect filter display after page refresh
  src/components/ArtifactsActionBar/ArtifactsActionBar.js
  src/components/FilterMenuModal/FilterMenuModal.js
  src/hooks/useGetTagOptions.hook.js
Labels: bug

#2301 Fix [Feature sets][Batch run] The Wrong validation error for incorrect datasource format
  src/common/TargetPath/targetPath.util.js
  src/utils/panelPathScheme.js
Labels: bug

#2302 Fix [Monitor Workflows] The 'Created At' filter doesn't keep the selected type
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
Labels: bug

#2304 Fix [Batch run] Display selected function on return to step 1
  src/common/Breadcrumbs/Breadcrumbs.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/jobWizardFunctionSelection.scss
  src/utils/scroll.util.js
Labels: bug

#2305 Fix [Projects] Redundant single quotes in delete project message
  src/components/ProjectsPage/projects.util.js
Labels: bug

#2306 Fix [Details result] unexpected "Iter" sorting in job "Results" tab
  src/components/Details/DetailsTabsContent/DetailsTabsContent.js
Labels: bug

#2307 Fix [Real-time pipeline] Graph is not clickable
  src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
  src/utils/createRealTimePipelinesContent.js
Labels: bug

#2309 Impl [Project setting] Provide validation rules on labels in UI
  src/actions/projects.js
  src/components/Project/ProjectDescription/ProjectDescription.js
  src/components/Project/ProjectGoals/ProjectGoals.js
  src/components/Project/ProjectName/ProjectName.js
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
  src/constants.js
  src/elements/ProjectSecretRow/ProjectSecretRow.js
  src/elements/ProjectSecretRow/projectSecretRow.scss
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneralView.js
  src/elements/ProjectSettingsGeneral/projectSettingsGeneral.scss
  src/elements/ProjectSettingsSource/ProjectSettingsSource.js
  src/elements/ProjectSettingsSource/projectSettingsSource.scss
  src/reducers/projectReducer.js
Labels: enhancement

#2310 Fix [ML functions] main row should remain fixed when scrolling the table
  src/components/Table/table.scss
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/elements/TableCell/TableCell.js
  src/elements/TableTypeCell/TableTypeCell.js
  src/scss/main.scss
  src/utils/createArtifactsContent.js
Labels: bug
