Repository mlrun/ui, pull requests merged in 2024-01, with the labels that each got.

#2169 Fix [Artifacts, Datasets, Models] successful deletion notification message
  src/utils/handleDeleteArtifact.js
Labels: bug

#2171 Fix [Filter] Tag list doesn't scroll in Filter by dialog
  src/common/FormTagFilter/formTagFilters.scss
  src/components/FilterMenuModal/FilterMenuModal.js
Labels: bug

#2147 Fix [Artifacts] missing delete confirmation message
  src/components/Datasets/datasets.util.js
  src/components/Files/files.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/components/ModelsPage/Models/models.util.js
Labels: bug

#2161 Fix [Monitor jobs] Unnecessary context: parameter presents in UI
  src/components/JobWizard/JobWizard.util.js
  src/utils/parseJob.js
Labels: bug

#2168 Fix [Batch run] fix labels validation
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
Labels: bug

#2174 Fix [Datasets] Change notification message on removing the tag
  src/utils/artifacts.util.js
Labels: bug

#2175 Fix [Quick actions] UI crash upon click on Register model, Define alerts, Run workflow or Create workflow
  src/components/Project/ProjectOverview/ProjectOverview.util.js
Labels: bug

#2178 [Fix [Models] Page stuck in a loading state
  src/components/Datasets/Datasets.js
  src/components/Files/Files.js
  src/components/ModelsPage/Models/models.util.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/hooks/useSortTable.hook.js
Labels: bug

#2172 Fix [Consumer groups] Table is empty although BE response is not empty
  src/components/AddToFeatureVectorPage/AddToFeatureVectorView.js
  src/components/ConsumerGroup/ConsumerGroup.js
  src/components/ConsumerGroups/ConsumerGroups.js
  src/components/Datasets/DatasetsView.js
  src/components/FeatureStore/FeatureSets/FeatureSetsView.js
  src/components/FeatureStore/FeatureVectors/FeatureVectorsView.js
  src/components/FeatureStore/Features/FeaturesView.js
  src/components/Files/FilesView.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
  src/components/Table/Table.js
  src/components/Workflow/Workflow.js
  src/utils/generateTableContent.js
Labels: bug

#2181 Fix [Artifacts] Page stuck in a loading state
  src/components/Datasets/datasets.util.js
  src/components/Files/files.util.js
  src/hooks/useSortTable.hook.js
Labels: bug

#2180 Fix [Table] Remove unnecessary class from table header
  src/components/DetailsResults/DetailsResults.js
  src/components/Table/TableHead.js
Labels: bug

#2182 Fix [Dataset] Add indication to dataset preview
  src/components/Details/details.scss
  src/components/DetailsPreview/DetailsPreview.js
  src/elements/PreviewModal/PreviewModal.js
  src/elements/PreviewModal/previewModal.scss
Labels: bug

#2183 Fix [Project settings] Members screen - does not take into account the owner
  src/components/ProjectSettings/ProjectSettings.js
  src/components/ProjectSettings/projectSettings.util.js
  src/constants.js
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
  src/elements/MembersPopUp/MembersPopUp.js
  src/elements/MembersPopUp/membersPopUp.util.js
  src/elements/ProjectSettingsMembers/ProjectSettingsMembers.js
  src/elements/ProjectSettingsMembers/ProjectSettingsMembers.scss
Labels: bug

#2184 Fix [Feature store] uniformity of tag filter labels
  src/components/FeatureStore/FeatureVectors/featureVectors.util.js
  src/components/FeatureStore/Features/features.util.js
Labels: bug

#2185 Fix [Model endpoints] Features analysis data missing
  src/components/DetailsInfo/DetailsInfo.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
Labels: bug

#2186 Fix [Artifacts] Change uniqueness validation and update messages
  src/api/artifacts-api.js
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/components/RegisterArtifactModal/messagesByKind.js
  src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
  src/elements/RegisterModelModal/RegisterModelModal.js
  src/utils/artifacts.util.js
  src/utils/createArtifact.util.js
Labels: bug

#2187 QA Sprint 155 done
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/api.actions.js
  tests/features/common/actions/common.action.js
  tests/features/common/actions/input-group.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects/commonPagesHeader.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/artifacts.json
  tests/mockServer/data/itemsCatalog.json
  tests/mockServer/data/mlrun/functions/auto_trainer/auto_trainer.yaml
  tests/mockServer/mock.js
Labels: tests

#2190 FIx [Filter] Filter by version tag 'All' doesn't provided after 'Add a tag' and 'Register' actions
  src/components/Datasets/Datasets.js
  src/components/Files/Files.js
  src/components/ModelsPage/Models/Models.js
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
  src/elements/RegisterModelModal/RegisterModelModal.js
Labels: bug

#2191 Fix [Job Artifacts, Results] add default sorting by name
  src/components/Details/DetailsTabsContent/DetailsTabsContent.js
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsResults/DetailsResults.js
Labels: bug

#2193 Fix [Feature Store] Source kind CSV feature set shouldn't be scheduled for UI
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
Labels: bug

#2194 Fix [Feature store] the search results message should include all search queries
  src/utils/getNoDataMessage.js
Labels: bug

#2195 Fix [Project Monitoring] Type and Status are not aligned
  src/elements/ProjectJobs/projectJobs.utils.js
Labels: bug

#2196 Fix [Project settings] "Owner updated successfully" message appears twice
  src/components/ProjectSettings/ProjectSettings.js
  src/components/ProjectsPage/ProjectsView.js
Labels: bug

#2197 Fix [Jobs|Funcs] Add message in case of accessing deleted item
  src/components/FunctionsPage/Functions.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
Labels: bug

#2198 Fix [Datasets] Add tag validation to Register dataset/artifact/model wizard
  src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
  src/elements/RegisterModelModal/RegisterModelModal.js
Labels: bug

#2199 Fix [Job Overview] Wrong function tags list
  src/actions/jobs.js
  src/components/Jobs/jobs.util.js
Labels: bug

#2200 Fix [Feature Store] Schedule content doesn't match the customized data
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
  src/components/FeatureSetsPanel/ScheduleFeatureSet/ScheduleFeatureSet.js
  src/components/FilterMenuModal/FilterMenuModal.js
  src/components/ScheduleJob/ScheduleJob.js
  src/utils/getDefaultSchedule.js
Labels: bug

#2202 Fix [Feature Store] Target store and Passthrough checkboxes don't work properly after closing pop-up dialog
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitle.js
Labels: bug

#2203 Fix [Model endpoints] incorrect version definition
  src/elements/RegisterArtifactModalForm/RegisterArtifactModalForm.js
  src/utils/createArtifactsContent.js
Labels: bug

#2205 Fix [Datasets] Dataset tag doesn't display on Datasets table in Name column
  src/elements/TableLinkCell/TableLinkCell.js
Labels: bug

#2207 Fix [ML functions] redundant scrollbar
  src/elements/FunctionsTableRow/FunctionsTableRow.js
Labels: bug

#2208 Fix [Breadcrumbs] malfunctioning if the project name matches the page name
  src/common/Breadcrumbs/Breadcrumbs.js
Labels: bug

#2209 Impl [Redirection] Wrong link redirection with invalid project name
  src/components/ConsumerGroupsWrapper/ConsumerGroupsWrapper.js
  src/components/CreateJobPage/CreateJobPage.js
  src/components/Jobs/Jobs.js
  src/components/Project/ProjectMonitor.js
  src/components/ProjectSettings/ProjectSettings.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/layout/Page/Page.js
Labels: bug

#2210 Fix [Delete Job] missing successful deletion notification message
  src/actions/jobs.js
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
Labels: bug

#2211 QA Sprint 156 done
  tests/features/common-tools/common-consts.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/projectHomePage.feature
  tests/features/projectsPage.feature
  tests/mockServer/mock.js
Labels: tests

#2170 Fix [Models] data displaying issue (headers)
  src/components/ModelsPage/Models/Models.js
  src/components/Table/TableHead.js
  src/utils/createArtifactsContent.js
Labels: bug

#2192 Fix [Batch Run] Access Key for a mount looks empty
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/JobWizard/JobWizard.util.js
  src/elements/FormVolumesTable/FormVolumesRow/FormVolumesRow.js
  src/elements/FormVolumesTable/formVolumesTable.util.js
Labels: bug

#2206 Fix [Batch Run][Feature Store] Offered tag for autofilled dataset store path does not match with dataset tag
  src/reducers/artifactsReducer.js
Labels: bug

#2213 Fix [Project monitoring] misleading artifacts counter in project monitoring screen
  src/components/Project/ProjectMonitorView.js
  src/elements/ProjectSummaryCard/ProjectSummaryCard.js
Labels: bug

#2216 Fix [Features] feature validator severity (warning and error) missing severity name
  src/elements/FeatureValidator/featureValidatior.utils.js
  src/utils/createFeatureStoreContent.js
Labels: bug

#2217 Fix [Project monitoring] misleading artifacts counter in project monitoring screen
  src/components/Project/ProjectMonitorView.js
  src/components/Project/project.scss
  src/elements/ProjectSummaryCard/ProjectSummaryCard.js
Labels: bug

#2218 Fix [Feature Vectors] enable editing of labels and description
  src/components/Details/details.util.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
Labels: bug

#2220 QA Sprint 157 done
  package.json
  tests/features/common-tools/common-consts.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/step-definitions/table.steps.js
  tests/mockServer/mock.js
Labels: tests

#2221 Impl [Tests] QA Sprint 157 done
  package.json
  tests/features/common-tools/common-consts.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/files.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/step-definitions/table.steps.js
  tests/mockServer/mock.js
Labels: tests

#2134 Fix [Jobs] Change 'runs' endpoint 'project name'
  src/actions/projects.js
  src/api/jobs-api.js
  src/api/projects-api.js
Labels: bug

#2219 Fix [Job Results] Uncaught TypeError: e.match is not a function
  src/hooks/useSortTable.hook.js
Labels: bug

#2222 Fix [Artifacts] different file size on the preview and list view
  src/elements/PreviewModal/PreviewModal.js
  src/elements/PreviewModal/previewModal.scss
  src/utils/createArtifactsContent.js
Labels: bug

#2223 Fix [Datasets] Artifacts sorting does not consider the year
  src/utils/datetime.js
Labels: bug

#2224 Impl [Artifacts][Models][Datasets] artifacts screen needs to change BE query behavior
  src/api/artifacts-api.js
  src/common/FormTagFilter/FormTagFilter.js
  src/common/FormTagFilter/formTagFilters.scss
  src/components/ArtifactsActionBar/ArtifactsActionBar.js
  src/components/ArtifactsActionBar/ArtifactsFilters.js
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/hooks/useGetTagOptions.hook.js
Labels: enhancement

#2226 Fix [Batch Run] Blank project screen after setting model target path
  package.json
  src/common/TargetPath/targetPath.util.js
Labels: bug

#2225 Impl [Artifacts][Models][Datasets] artifacts screen needs to change BE query behavior `1.6.x`
  src/api/artifacts-api.js
  src/common/FormTagFilter/FormTagFilter.js
  src/common/FormTagFilter/formTagFilters.scss
  src/components/ArtifactsActionBar/ArtifactsActionBar.js
  src/components/ArtifactsActionBar/ArtifactsFilters.js
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/hooks/useGetTagOptions.hook.js
Labels: enhancement

#2227 Fix [Batch Run] Blank project screen after setting model target path `1.6.x`
  src/common/TargetPath/targetPath.util.js
Labels: bug
