Repository mlrun/ui, pull requests merged in 2024-11, with the labels that each got.

#2858 Tests [Mock] Add mock for overwriting artifacts
  tests/mockServer/mock.js
Labels: tests

#2857 Tests [Mock] Update the mock with link redirection to a non-existent project
  tests/mockServer/mock.js
Labels: tests

#2856 Fix [Projects] Request 500 error message
  src/actions/projects.js
Labels: bug

#2855 Tests [Mock] Update mock for creating a function from UI
  tests/mockServer/mock.js
Labels: tests

#2854 Tests [Mock] Add mock for 'unhealthy' mlrun message appear
  src/httpClient.js
  tests/features/common-tools/common-tools.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/projectsPage.feature
  tests/features/support/hooks.js
  tests/mockServer/mock.js
Labels: tests

#2851 Fix [Monitor Jobs] results columns are too wide when result it long
  src/components/DetailsResults/DetailsResults.js
  src/utils/resultsTable.js
Labels: bug

#2807 Fix [UI] "add a tag" UI should not check uniqueness but rather update the existing tag `1.7.1`
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
Labels: bug

#2821 Impl [Jobs] Add reason for job failure in UI next to the red status indicator `1.7.1`
  src/common/ReactFlow/mlReactFlow.util.js
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/FilterMenu/filterMenu.settings.js
  src/components/FunctionsPage/functions.util.js
  src/components/Jobs/jobs.util.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/jobsMonitoring.util.js
  src/constants.js
  src/elements/FeatureValidator/featureValidatior.utils.js
  src/elements/ProjectCard/projectCard.util.js
  src/elements/ProjectFunctions/ProjectFunctions.js
  src/elements/ProjectStatistics/ProjectStatistics.js
  src/elements/WorkflowsTable/WorkflowsTable.js
  src/utils/createJobsContent.js
  src/utils/generateMonitoringData.js
  src/utils/getState.js
  src/utils/parseJob.js
Labels: enhancement

#2861 Impl [Feature Sets] create a request for each feature set `1.7.x`
  src/actions/featureStore.js
  src/api/featureStore-api.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureSets/FeatureSetsView.js
  src/components/FeatureStore/FeatureSets/featureSets.util.js
  src/constants.js
  src/reducers/featureStoreReducer.js
  tests/mockServer/mock.js
Labels: enhancement

#2860 Impl [Feature Sets] create a request for each feature set
  src/actions/featureStore.js
  src/api/featureStore-api.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureSets/FeatureSetsView.js
  src/components/FeatureStore/FeatureSets/featureSets.util.js
  src/constants.js
  src/reducers/featureStoreReducer.js
  tests/mockServer/mock.js
Labels: enhancement

#2862 Fix [Projects] Clicking on search text box in projects refreshes the screen `1.7.1`
  src/components/ProjectsPage/ProjectsView.js
  src/utils/generateMonitoringData.js
Labels: bug

#2853 Fix [Projects] Clicking on search text box in projects refreshes the screen
  src/components/ProjectsPage/ProjectsView.js
  src/utils/generateMonitoringData.js
Labels: bug

#2864 Fix [Monitoring] missing tooltips on counters `1.7.1`
  src/elements/ProjectsMonitoringCounters/JobsCounters.js
  src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
Labels: bug

#2865 Fix [Monitoring] missing tooltips on counters
  src/elements/ProjectsMonitoringCounters/JobsCounters.js
  src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
Labels: bug

#2866 Fix [Models] log model with a training set that has large number of columns fail to present model feature stats `1.7.1`
  src/common/Chart/MlChart.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/DetailsStatistics/DetailsStatistics.js
  src/components/DetailsStatistics/DetailsStatisticsTableRow.js
  src/components/DetailsStatistics/detailsStatistics.scss
  src/components/DetailsStatistics/detailsStatistics.util.js
  src/hooks/useVirtualization.hook.js
Labels: bug

#2867 Fix [Models] log model with a training set that has large number of columns fail to present model feature stats
  src/common/Chart/MlChart.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/DetailsStatistics/DetailsStatistics.js
  src/components/DetailsStatistics/DetailsStatisticsTableRow.js
  src/components/DetailsStatistics/detailsStatistics.scss
  src/components/DetailsStatistics/detailsStatistics.util.js
  src/hooks/useVirtualization.hook.js
Labels: bug

#2863 Fix [Breadcrumbs] Double scroll when selecting the last project
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/utils/scroll.util.js
Labels: bug

#2868 QA Sprint 172 done
  tests/features/MLFunction.feature
  tests/features/artifacts.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-monitoring.po.js
  tests/features/datasets.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/jobsMonitoring.feature
  tests/features/projectMonitoring.feature
Labels: tests

#2869 Fix [Job Inputs, Job Artifacts] opening a new tab outside the dashboard
  src/components/DetailsArtifacts/detailsArtifacts.util.js
  src/components/DetailsInputs/detailsInputs.util.js
  src/utils/generateStoreResourceLink.js
Labels: bug

#2871 Fix [Jobs] reason for job failure is not displayed `1.7.1`
  src/utils/parseJob.js
Labels: bug

#2872 Fix [Feature store, Models] Label editing action issues
  src/common/TabsSlider/TabsSlider.js
  src/components/Details/Details.js
  src/components/ModelsPage/Models/Models.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/elements/DetailsInfoItemChip/DetailsInfoItemChip.js
Labels: bug

#2873 Fix [Schedule] The job type is 'job' for any jobs : mpi, spark, etc
  src/components/FilterMenu/filterMenu.settings.js
  src/components/Jobs/ScheduledJobs/ScheduledJobsFilters.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoringFilters.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/jobsMonitoring.util.js
  src/components/ProjectsJobsMonitoring/ScheduledMonitoring/ScheduledMonitoringFilters.js
  src/hooks/useJobsPageData.js
  src/utils/createJobsContent.js
  src/utils/jobs.util.js
  src/utils/parseJob.js
Labels: bug

#2850 Cleanup [React] Replace createRef across the code
  src/App.js
  src/common/Accordion/Accordion.js
  src/common/Breadcrumbs/Breadcrumbs.js
  src/common/Breadcrumbs/BreadcrumbsStep/BreadcrumbsStep.js
  src/common/Breadcrumbs/BreadcrumbsStep/breadcrumbsStep.scss
  src/common/Breadcrumbs/breadcrumbs.scss
  src/common/Breadcrumbs/breadcrums.scss
  src/common/ChipForm/ChipForm.js
  src/common/Notification/Notification.js
  src/common/Notification/NotificationView.js
  src/common/Notification/notificationView.scss
  src/common/Notifications/Notification.js
  src/common/Notifications/Notifications.js
  src/common/Notifications/notification.scss
  src/common/Notifications/notifications.scss
  src/components/DetailsInfo/DetailsInfo.js
  src/components/ProjectSettings/projectSettings.util.js
  src/constants.js
  src/elements/MembersPopUp/MembersPopUp.js
  src/elements/MembersPopUp/MembersPopUpRow.js
  src/elements/ProjectCard/ProjectCard.js
Labels: Cleanup

#2877 Fix [Projects] Clicking on search text box in projects refreshes the screen
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
Labels: bug

#2878 Fix [Projects] Clicking on search text box in projects refreshes the screen `1.7.x`
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
Labels: bug

#2879 Fix [Artifacts] Change filters to use new component
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/Datasets/datasets.util.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/Models/models.util.js
  src/constants.js
  src/hooks/useInitialTableFetch.hook.js
  src/reducers/filtersReducer.js
Labels: bug

#2881 Fix [UI] Error displayed as a reason for failed job `1.7.1`
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/utils/getState.js
  src/utils/parseJob.js
Labels: bug

#2882 Fix [UI] Error displayed as a reason for failed job
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/utils/getState.js
  src/utils/parseJob.js
Labels: bug

#2885 Impl [UI Projects Alerts] Add Project Alerts page
  src/App.js
  src/components/ProjectsAlerts/ProjectsAlerts.js
  src/components/ProjectsAlerts/ProjectsAlertsView.js
Labels: enhancement

#2884 Fix [Project monitoring] Adjust layout according to Figma
  src/components/Project/project.scss
  src/elements/ProjectTable/projectTable.scss
Labels: bug

#2883 Fix [Jobs] Break filter row by resolution
  src/components/ProjectSettings/projectSettings.scss
  src/elements/ChangeOwnerPopUp/changeOwnerPopUp.scss
  src/elements/ProjectSettingsGeneral/projectSettingsGeneral.scss
  src/scss/main.scss
Labels: bug

#2890 Impl [Projects] Make the main cross project counters clickable
  src/components/Project/ProjectMonitorView.js
  src/components/ProjectsPage/ProjectsMonitoring/ProjectsMonitoring.js
  src/components/ProjectsPage/ProjectsMonitoring/projectsMonitoring.scss
  src/components/ProjectsPage/projects.util.js
  src/elements/ProjectsMonitoringCounters/AlertsCounters.js
  src/elements/ProjectsMonitoringCounters/JobsCounters.js
  src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
  src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
  src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
  src/reducers/projectReducer.js
Labels: enhancement

#2891 Impl [Projects][Monitor] Add Per-Project Total Alerts Count to ProjectCard
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projects.util.js
  src/constants.js
  src/elements/ProjectCard/ProjectCard.js
  src/elements/ProjectCard/ProjectCardView.js
  src/elements/ProjectCard/projectCard.scss
  src/reducers/projectReducer.js
Labels: enhancement

#2894 Fix [Feature store] fix paddings in action bar
  src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
Labels: bug

#2896 Impl [Realtime pipelines] Reduce load on UI and BE
  src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
  src/components/ModelsPage/RealTimePipelines/realTimePipelines.util.js
  src/components/Pipeline/Pipeline.js
Labels: enhancement
