Repository mlrun/ui, pull requests merged in 2024-10, with the labels that each got.

#2795 Fix [Artifacts] redundant request on expanding the artifact
  src/components/Datasets/Datasets.js
  src/components/Datasets/datasets.util.js
  src/components/Files/Files.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/models.util.js
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
  src/reducers/artifactsReducer.js
  src/utils/getUniqueIdentifier.js
Labels: bug

#2796 Fix [Jobs] run UI does not present run handler
  src/components/Details/details.util.js
  src/components/Jobs/jobs.util.js
Labels: bug

#2799 Fix [Jobs] run UI does not present run handler `1.7.x`
  src/components/Details/details.util.js
  src/components/Jobs/jobs.util.js
Labels: bug

#2797 Fix [ML Functions] There is no redirection to function overview pane
  src/components/FunctionsPage/Functions.js
Labels: bug

#2798 Fix [ML Functions] There is no redirection to function overview pane `1.7.x`
  src/components/FunctionsPage/Functions.js
Labels: bug

#2802 Fix [UI] Remove "Default handler" from app runtime function overview `1.7.x`
  src/components/FunctionsPage/functions.util.js
Labels: bug

#2801 Fix [UI] Remove "Default handler" from app runtime function overview
  src/components/FunctionsPage/functions.util.js
Labels: bug

#2803 Fix [Artifacts] the current artifact name is included in the request when switching between artifact pages
  src/components/ArtifactsActionBar/ArtifactsActionBar.js
Labels: bug

#2806 Fix [UI] "add a tag" UI should not check uniqueness but rather update the existing tag
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
Labels: bug

#2809 Fix [Workflows] Redirect to a non-existent project
  src/layout/Page/Page.js
  src/utils/link-helper.util.js
Labels: bug

#2810 Fix [Workflows] Redirect to a non-existent project `1.7.x`
  src/layout/Page/Page.js
  src/utils/link-helper.util.js
Labels: bug

#2812 Fix [Cross project] Wrong redirection from the breadcrumbs menu on the Jobs monitoring `1.7.x`
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js
Labels: bug

#2811 Fix [Cross project] Wrong redirection from the breadcrumbs menu on the Jobs monitoring
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js
Labels: bug

#2804 Fix [Projects] The 'Confirm message' is missing when deleting a project `1.7.x`
  src/components/ProjectsPage/Projects.js
Labels: bug

#2813 QA Sprint 170 done `1.7.x`
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/page-objects/jobs-monitoring.po.js
  tests/features/common/page-objects/project-settings.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/jobsMonitoring.feature
  tests/features/models.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/artifacts.json
  tests/mockServer/data/schedules.json
  tests/mockServer/dateSynchronization.js
  tests/mockServer/mock.js
Labels: tests

#2815 Fix [UI] displays delete project messages that are not related to the current user
  src/actions/projects.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/projects.util.js
  src/constants.js
  src/reducers/projectReducer.js
Labels: bug

#2816 Fix [UI] displays delete project messages that are not related to the current user `1.7.x`
  src/actions/projects.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/projects.util.js
  src/constants.js
  src/reducers/projectReducer.js
Labels: bug

#2805 Fix [UI] UI small fixes
  package.json
  src/common/Input/Input.js
  src/components/ActionBar/ActionBar.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
  src/components/FunctionsPage/Functions.js
  src/components/Project/project.utils.js
  src/components/ProjectSettings/projectSettings.scss
  src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
  src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
  src/scss/main.scss
Labels: bug

#2808 Fix [UI] UI small fixes `1.7.x`
  package.json
  src/common/Input/Input.js
  src/components/ActionBar/ActionBar.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
  src/components/FunctionsPage/Functions.js
  src/components/Project/project.utils.js
  src/components/ProjectSettings/projectSettings.scss
  src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
  src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
  src/scss/main.scss
Labels: bug

#2819 Fix [Cross project] Runs of type 'Job' displayed in the runs list of type 'mpijob' `1.7.x`
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
Labels: bug

#2818 Fix [Cross project] Runs of type 'Job' displayed in the runs list of type 'mpijob'
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
Labels: bug

#2820 Impl [Jobs] Add reason for job failure in UI next to the red status indicator
  src/utils/getState.js
  src/utils/parseJob.js
Labels: enhancement

#2822 Fix [JS] Projects.js useEffect warning
  src/components/ProjectsPage/Projects.js
Labels: bug

#2824 Fix [General] infinite loop when the BE endpoints return error
  src/httpClient.js
Labels: bug

#2825 Fix [General] infinite loop when the BE endpoints return error `1.7.x`
  src/httpClient.js
Labels: bug

#2828 Impl [Jobs] Add reason for job failure in UI next to the red status indicator
  src/common/ReactFlow/mlReactFlow.util.js
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/FilterMenu/filterMenu.settings.js
  src/components/FunctionsPage/functions.util.js
  src/components/Jobs/jobs.util.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/jobsMonitoring.util.js
  src/constants.js
  src/elements/FeatureValidator/featureValidatior.utils.js
  src/elements/ProjectCard/projectCard.util.js
  src/elements/ProjectFunctions/ProjectFunctions.js
  src/elements/ProjectStatistics/ProjectStatistics.js
  src/elements/WorkflowsTable/WorkflowsTable.js
  src/utils/createJobsContent.js
  src/utils/generateMonitoringData.js
  src/utils/getState.js
Labels: bug

#2830 Fix [Model Endpoints] take ~35 second to fetch data
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/utils/createArtifactsContent.js
Labels: bug

#2829 Fix [Model Endpoints] take ~35 second to fetch data `1.7.x`
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/utils/createArtifactsContent.js
Labels: bug

#2834 Fix [UI] Warning: findDOMNode is deprecated `1.7.x`
  src/common/Download/DownloadContainer.js
  src/common/Notification/Notification.js
Labels: bug

#2839 Fix [UI] Clear filter action doesn't trigger request `1.7.x`
  src/components/FilterMenuModal/FilterMenuModal.js
Labels: bug

#2837 Fix [UI] Warning icon overlay on input text `1.7.x`
  src/common/Input/Input.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
  src/elements/FeaturesTablePanel/FeaturesTablePanelView.js
  src/elements/FeaturesTablePanel/featuresTablePanel.scss
  src/elements/MembersPopUp/MembersPopUp.js
Labels: bug

#2826 Impl [NPM] Upgrade the Axios package
  package.json
Labels: dependencies

#2827 Impl [NPM] Upgrade webpack package in DRC
  package.json
Labels: dependencies

#2832 Fix [Projects] wrong Jobs monitoring counters
  src/components/ProjectsPage/projects.util.js
Labels: bug

#2835 Fix [UI] Clear filter action doesn't trigger request
  src/components/FilterMenuModal/FilterMenuModal.js
Labels: bug

#2838 Fix [UI] Warning icon overlay on input text
  src/common/Input/Input.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
  src/elements/FeaturesTablePanel/FeaturesTablePanelView.js
  src/elements/FeaturesTablePanel/featuresTablePanel.scss
  src/elements/MembersPopUp/MembersPopUp.js
Labels: bug

#2846 QA Sprint 171 done `1.7.x`
  package.json
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-monitoring.po.js
  tests/features/common/page-objects/ml-functions.po.js
  tests/features/common/page-objects/project-settings.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/datasets.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/jobsMonitoring.feature
  tests/features/models.feature
  tests/features/projectMonitoring.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/funcs.json
  tests/mockServer/data/run.json
  tests/mockServer/data/runs.json
  tests/mockServer/dateSynchronization.js
  tests/mockServer/mock.js
Labels: tests

#2847 Impl [Tests] QA Sprint 171 done
  package.json
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-monitoring.po.js
  tests/features/common/page-objects/ml-functions.po.js
  tests/features/common/page-objects/project-settings.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/datasets.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/jobsMonitoring.feature
  tests/features/models.feature
  tests/features/projectMonitoring.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/funcs.json
  tests/mockServer/data/run.json
  tests/mockServer/data/runs.json
  tests/mockServer/dateSynchronization.js
  tests/mockServer/mock.js
Labels: tests

#2843 Impl [Workflows] Add retry option for workflows
  package.json
  src/actions/workflow.js
  src/api/workflow-api.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/elements/WorkflowsTable/WorkflowsTable.js
Labels: enhancement, Require test

#2844 Fix [Project monitoring] Register model in demo mode with Unexpected Application Error
  src/components/Project/ProjectMonitor.js
Labels: bug

#2849 Fix [Settings] Change Node Selectors more info message
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
Labels: bug
