Repository mlrun/ui, pull requests merged in 2024-12, with the labels that each got.

#2898 Impl [Real time pipelines] Filter by 'function kind'
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
  src/reducers/artifactsReducer.js
Labels: enhancement

#2897 Fix [Batch run] Add validation checks for secrets in Batch run wizard
  src/elements/FormVolumesTable/formVolumesTable.util.js
Labels: bug

#2899 Fix [Workflows] Success message on failed request
  src/elements/WorkflowsTable/WorkflowsTable.js
Labels: bug

#2895 QA v`1.7.1`
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/common.action.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/project-settings.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
  tests/mockServer/mock.js
Labels: tests

#2905 Fix [Project settings] no message after being removed from project members
  src/components/ProjectSettings/ProjectSettings.js
  src/elements/MembersPopUp/MembersPopUp.js
Labels: bug

#2904 Impl [Jobs] Pagination
  package.json
  src/actions/jobs.js
  src/common/Chip/Chip.js
  src/common/Pagination/Pagination.js
  src/common/Pagination/pagination.scss
  src/common/TagFilter/TagFilter.js
  src/components/ActionBar/ActionBar.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorView.js
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureSets/FeatureSetsView.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
  src/components/FeatureStore/FeatureVectors/FeatureVectorsView.js
  src/components/FeatureStore/Features/Features.js
  src/components/FeatureStore/Features/FeaturesView.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/FunctionsPage/functions.util.js
  src/components/Jobs/Jobs.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/components/Workflow/Workflow.js
  src/constants.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/FeatureStoreTableRow/FeatureStoreTableRow.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/elements/JobsTable/JobsTable.js
  src/elements/TableCell/TableCell.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/hooks/groupContent.hook.js
  src/hooks/useFiltersFromSearchParams.hook.js
  src/hooks/useJobsPageData.js
  src/hooks/usePagination.hook.js
  src/layout/Content/Content.js
  src/layout/Content/content.util.js
  src/scss/main.scss
  src/types.js
  src/utils/createJobsContent.js
  src/utils/filter.util.js
  src/utils/jobs.util.js
  src/utils/link-helper.util.js
  src/utils/parseFunctions.js
  tests/mockServer/data/run.json
  tests/mockServer/data/runs.json
  tests/mockServer/mock.js
Labels: enhancement, Require test

#2903 Fix [Jobs] When running job of type local, we don't collect logs so "Logs" tab should not be displayed
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/jobs.util.js
  src/elements/JobsTable/jobsTable.util.js
  src/elements/WorkflowsTable/WorkflowsTable.js
Labels: bug

#2902 Fix [Jobs monitoring] "Past 24 hours" time filter is applied after click on "In process" jobs
  src/elements/ProjectsMonitoringCounters/JobsCounters.js
  src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
  src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
  src/utils/generateMonitoringData.js
Labels: bug

#2901 Fix [UI] project request is sent 3 times
  src/common/Breadcrumbs/Breadcrumbs.js
  src/common/Breadcrumbs/BreadcrumbsStep/BreadcrumbsStep.js
  src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js
Labels: bug

#2908 Impl [Projects Alerts] Add “Alerts Table”
  package.json
  src/App.js
  src/api/alerts-api.js
  src/components/Alerts/Alerts.js
  src/components/Alerts/AlertsFilters.js
  src/components/Alerts/AlertsView.js
  src/components/Alerts/alerts.scss
  src/components/Alerts/alerts.util.js
  src/components/ProjectsAlerts/ProjectsAlertsView.js
  src/components/Table/table.scss
  src/constants.js
  src/elements/AlertsTableRow/AlertsTableRow.js
  src/reducers/alertsReducer.js
  src/store/toolkitStore.js
  src/utils/createAlertsContent.js
  src/utils/parseAlert.js
  tests/mockServer/data/alerts.json
  tests/mockServer/mock.js
Labels: enhancement

#2900 Fix [Workflows] single-line display issue for pipeline and job errors
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/Details/details.scss
Labels: bug

#2906 Fix [Latam] UI failed to view large project yaml
  src/actions/projects.js
  src/components/JobWizard/JobWizard.js
  src/components/ProjectsPage/Projects.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
Labels: bug

#2911 Fix [Model Endpoints] Missing created time in the details header
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
Labels: bug

#2913 Impl [Jobs] Change runs grouping behavior
  src/App.js
  src/common/Pagination/Pagination.js
  src/components/Jobs/Jobs.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/jobs.util.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/components/Table/TableView.js
  src/elements/JobsTable/JobsTable.js
  src/elements/TableTop/tableTop.scss
  src/hooks/useJobsPageData.js
  src/hooks/usePagination.hook.js
  src/utils/createJobsContent.js
  src/utils/jobs.util.js
  src/utils/link-helper.util.js
Labels: enhancement, Require test

#2914 Impl [Pagination] Change functions grouping behavior
  src/App.js
  src/api/functions-api.js
  src/common/HistoryBackLink/historyBackLink.js
  src/common/HistoryBackLink/historyBackLink.scss
  src/components/ActionBar/ActionBar.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/FunctionsPage/functions.util.js
  src/constants.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/hooks/useInitialTableFetch.hook.js
  src/utils/createFunctionsRowData.js
  src/utils/filter.util.js
  src/utils/parseUri.js
  tests/mockServer/mock.js
Labels: enhancement, Require test

#2915 Fix [Scheduled jobs] delete schedule silently fails with MLRunAccessDeniedError
  src/api/jobs-api.js
  src/elements/ScheduledJobsTable/ScheduledJobsTable.js
  src/reducers/jobReducer.js
Labels: bug

#2912 Impl [VectorDB] new "Documents" page and navigation
  src/App.js
  src/components/Documents/Documents.js
  src/components/Documents/DocumentsView.js
  src/components/Documents/documents.util.js
  src/layout/Navbar/Navbar.utils.js
Labels: enhancement

#2919 Impl [Model Endpoints] Add mock for MM data-layout
  tests/mockServer/data/modelEndpoints.json
  tests/mockServer/mock.js
Labels: enhancement

#2920 Impl [VectorDB] Add "Documents" main table filters
  src/components/Documents/Documents.js
  src/components/Documents/DocumentsView.js
  src/components/Documents/documents.util.js
  src/constants.js
Labels: enhancement

#2917 Fix [Jobs Monitoring] Wrong number of the total jobs and workflows
  src/components/ProjectsPage/projects.util.js
  src/elements/ProjectsMonitoringCounters/JobsCounters.js
  src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
  src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
  src/utils/generateMonitoringData.js
Labels: bug

#2922 Fix [Workflows] Missing refresh after success rerun
  src/elements/WorkflowsTable/WorkflowsTable.js
Labels: bug

#2925 Imp [Alert Table] Update the getNoDataMessage function to support Alerts Table
  src/components/Alerts/alerts.util.js
  src/utils/getNoDataMessage.js
Labels: enhancement

#2926 Impl [Projects Alerts] Add Pagination Implementation for Alerts Table
  src/components/Alerts/Alerts.js
  src/components/Alerts/AlertsView.js
  src/elements/ProjectCard/projectCard.scss
  src/hooks/useAlertsPageData.js
  src/reducers/alertsReducer.js
  src/utils/createAlertsContent.js
  tests/mockServer/data/alerts.json
  tests/mockServer/data/summary.json
  tests/mockServer/mock.js
Labels: enhancement

#2927 Fix [Jobs and Workflows] active tab should not be clickable
  src/elements/ContentMenu/ContentMenu.js
  src/elements/ContentMenu/contentMenu.scss
Labels: bug

#2930 Fix [Models] Align the tabs on Models page
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
Labels: bug

#2931 Fix [UI] clickable tabs
  src/elements/ContentMenu/ContentMenu.js
Labels: bug

#2933 Fix [Alerts History] alerts activation page is broken
  src/reducers/alertsReducer.js
  src/utils/createAlertsContent.js
  src/utils/parseAlert.js
  tests/mockServer/mock.js
Labels: bug

#2932 Fix [Projects] Monitoring view by Figma
  src/components/ProjectsPage/ProjectsMonitoring/projectsMonitoring.scss
  src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
Labels: enhancement

#2928 Fix [Project settings] add debounce for owner input
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
Labels: bug

#2935 Impl [Alert Table] - Update the Notification Column According to New Design
  src/components/Table/table.scss
  src/elements/AlertsTableRow/AlertsTableRow.js
  src/elements/AlertsTableRow/AlertsTableRow.scss
  src/utils/createAlertsContent.js
  tests/mockServer/data/alerts.json
Labels: enhancement

#2934 Impl [VectorDB] Add breadcrumbs navigation
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/components/ActionBar/ActionBar.js
  src/constants.js
  src/layout/Navbar/Navbar.utils.js
Labels: bug

#2937 Impl [Pagination] Change artifacts grouping behavior
  src/App.js
  src/components/ActionBar/ActionBar.js
  src/components/ArtifactsActionBar/ArtifactsFilters.js
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/Datasets/datasets.util.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/Models/models.util.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/elements/DetailsPopUp/ArtifactPopUp/ArtifactPopUp.js
  src/scss/main.scss
  src/utils/artifacts.util.js
  src/utils/createArtifactsContent.js
  tests/mockServer/mock.js
Labels: enhancement

#2938 Impl [Functions] Pagination
  src/actions/functions.js
  src/common/Pagination/Pagination.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/FunctionsPage/functions.util.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/elements/JobsTable/JobsTable.js
  src/hooks/useJobsPageData.js
Labels: enhancement

#2939 Impl [VectorDB] Add Overview details tab
  src/App.js
  src/common/ActionsMenu/ActionsMenu.js
  src/components/Details/Details.js
  src/components/Details/DetailsTabsContent/DetailsTabsContent.js
  src/components/Details/details.util.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfo.util.js
  src/components/Documents/Documents.js
  src/components/Documents/DocumentsView.js
  src/components/Documents/documents.util.js
  src/constants.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
Labels: enhancement

#2940 Impl [VectorDB] Add Collections Details tab
  src/components/DetailsCollections/DetailsCollections.js
  src/components/DetailsCollections/detailsCollections.scss
Labels: enhancement

#2929 Fix [Schedule] applied filters not displayed after editing the job
  src/components/JobWizard/JobWizard.js
  src/components/ModelsPage/Models/Models.js
  src/components/Project/project.utils.js
  src/elements/JobsTable/JobsTable.js
  src/elements/ScheduledJobsTable/ScheduledJobsTable.js
  src/elements/WorkflowsTable/WorkflowsTable.js
Labels: bug

#2942 Fix [Alerts History] alerts activation page is broken
  src/elements/ProjectsMonitoringCounters/AlertsCounters.js
Labels: bug

#2936 Impl [Projects] move sort to the right
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projects.scss
  src/elements/ContentMenu/contentMenu.scss
Labels: enhancement

#2943 Fix [Jobs and Workflows] Runtime error for action menu Monitoring option
  src/components/Jobs/Jobs.js
Labels: bug

#2945 Fix [Artifacts] Inconsistent Display of Producer Info for Artifact Based on Producer Kind
  src/components/DetailsInfo/detailsInfo.util.js
Labels: bug

#2947 Impl [QA] Alert notifications data-testid
  src/utils/createAlertsContent.js
Labels: enhancement, tests

#2948 Impl [Project Monitoring] Alerts Counter component
  src/components/Project/ProjectMonitorView.js
  src/components/Project/project.scss
  src/elements/ProjectsMonitoringCounters/AlertsCounters.js
  src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
Labels: enhancement

#2952 Impl [Projects Alerts] Add “Application Type” to “Alert Table”
  src/App.js
  src/components/Alerts/Alerts.js
  src/components/Alerts/AlertsView.js
  src/components/Alerts/alerts.util.js
  src/components/Details/Details.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/Details/DetailsTabsContent/DetailsTabsContent.js
  src/components/Details/details.util.js
  src/components/DetailsDrillDownAlert/DetailsDrillDownAlert.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/DetailsInfo/detailsInfo.util.js
  src/components/DetailsLogs/Logs.js
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Table/table.scss
  src/constants.js
  src/elements/AlertsTableRow/AlertsTableRow.js
  src/elements/AlertsTableRow/AlertsTableRow.scss
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/utils/createAlertsContent.js
  src/utils/getUniqueIdentifier.js
  src/utils/link-helper.util.js
  tests/mockServer/data/alerts.json
Labels: enhancement

#2950 Impl [UI] Additional fix to #2948
  src/common/StatsCard/StatsCard.js
  src/common/StatsCard/statsCard.scss
  src/components/Project/ProjectMonitorView.js
  src/components/Project/project.scss
  src/components/ProjectsPage/ProjectsMonitoring/projectsMonitoring.scss
  src/elements/ProjectJobs/projectJobs.utils.js
  src/elements/ProjectSummaryCard/ProjectSummaryCard.js
  src/elements/ProjectsMonitoringCounters/AlertsCounters.js
  src/elements/ProjectsMonitoringCounters/JobsCounters.js
  src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
  src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
  src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
  src/utils/generateAlertsStats.js
Labels: enhancement

#2955 Impl [Artifacts] Pagination
  src/api/artifacts-api.js
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/Datasets/datasets.util.js
  src/components/Documents/Documents.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/Models/models.util.js
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
  src/elements/DetailsPopUp/ArtifactPopUp/ArtifactPopUp.js
  src/reducers/artifactsReducer.js
  src/utils/artifacts.util.js
Labels: enhancement

#2953 Fix [UI] unresponsive UI on project delete
  src/actions/projects.js
  src/components/ProjectSettings/ProjectSettings.js
  src/elements/ProjectCard/ProjectCardView.js
  src/elements/ProjectCard/projectCard.scss
  src/reducers/projectReducer.js
Labels: bug

#2956 Impl [Alert Table] Parameters configuration logic for alertApi
  src/api/alerts-api.js
  src/components/Alerts/Alerts.js
  src/components/Alerts/AlertsFilters.js
  src/components/Alerts/AlertsView.js
  src/components/Alerts/alerts.util.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/DetailsInfo/detailsInfo.util.js
  src/constants.js
  src/hooks/useAlertsPageData.js
  src/reducers/alertsReducer.js
  src/utils/createAlertsContent.js
  src/utils/generateAlertsStats.js
Labels: enhancement

#2959 Fix [Artifacts] wrong artifact details after click
  src/components/Datasets/datasets.util.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/Files/files.util.js
  src/components/FunctionsPage/functions.util.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/Models/models.util.js
  src/utils/artifacts.util.js
Labels: bug

#2960 Impl [VectorDB] Add pagination
  src/components/Documents/Documents.js
  src/components/Documents/DocumentsView.js
  src/components/Documents/documents.util.js
  src/reducers/artifactsReducer.js
Labels: enhancement

#2958 Impl [Artifacts] Prevents users from modifying the artifact's latest tag
  src/components/Datasets/datasets.util.js
  src/components/Details/details.util.js
  src/components/ModelsPage/Models/models.util.js
  src/components/Project/project.scss
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
Labels: enhancement

#2961 Fix [Documents] multiple bugs
  src/components/Details/details.util.js
  src/components/DetailsCollections/DetailsCollections.js
  src/components/DetailsCollections/detailsCollections.scss
  src/components/DetailsInfo/detailsInfo.scss
  src/components/Documents/Documents.js
  src/components/Documents/documents.util.js
  src/utils/getNoDataMessage.js
Labels: bug

#2963 Fix [Model Monitoring UI] Drift Status isn't been showed as it was
  src/utils/createArtifactsContent.js
Labels: bug

#2968 Impl [Alerts history] Add “Job Type” to “Alert Table”
  src/App.js
  src/components/Alerts/Alerts.js
  src/components/Alerts/AlertsView.js
  src/components/Alerts/alerts.util.js
  src/components/DetailsDrillDownAlert/AlertLogPopup.js
  src/components/DetailsDrillDownAlert/DetailsDrillDownAlert.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/DetailsInfo/detailsInfo.util.js
  src/components/Table/TableView.js
  src/elements/AlertsTableRow/AlertsTableRow.scss
  src/utils/createAlertsContent.js
  src/utils/getUniqueIdentifier.js
  tests/mockServer/data/alerts.json
Labels: enhancement

#2967 Impl [Alerts history] Notification summary "done" should be aligned to BE "success"
  src/utils/createAlertsContent.js
Labels: enhancement

#2966 Tests [Alerts history] Complete Implementation of getAlerts Controller Logic in Mock Server
  tests/mockServer/mock.js
Labels: tests

#2964 Fix [UI] Artifacts Fail showing html files
  src/common/Download/DownloadItem.js
  src/utils/getArtifactPreview.js
Labels: bug

#2969 Impl [Alerts Info] add notification tab
  src/App.js
  src/components/DetailsInfo/detailsInfo.util.js
  src/elements/AlertsTableRow/AlertsTableRow.scss
  src/utils/createAlertsContent.js
Labels: enhancement

#2970 Impl [Alerts history] Refactor "Trigger Criteria Time Period" Column View
  src/utils/createAlertsContent.js
Labels: enhancement

#2971 Impl [Alerts history] Add “Endpoint Type” to “Alert Table”
  src/components/DetailsDrillDownAlert/AlertLogsModal.js
  src/components/DetailsDrillDownAlert/DetailsAlertsMetrics.js
  src/components/DetailsDrillDownAlert/DetailsDrillDownAlert.js
  src/components/DetailsInfo/detailsInfo.scss
  src/elements/AlertsTableRow/AlertsTableRow.scss
  src/utils/createAlertsContent.js
Labels: enhancement

#2972 Fix [Model endpoints] Main table row height in details view
  src/components/ModelsPage/ModelEndpoints/modelEndpoints.scss
Labels: bug

#2965 Fix [Jobs and Workflows] Runtime error for action menu Monitoring option
  src/common/StatsCard/StatsCard.js
  src/components/Jobs/Jobs.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/jobs.util.js
  src/components/Project/project.scss
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/elements/JobsTable/JobsTable.js
  src/elements/JobsTable/jobsTable.util.js
  src/hooks/useJobsPageData.js
Labels: bug

#2973 Fix [Artifacts] Wrong redirection when clicking the 'Full View' button
  src/components/Details/DetailsHeader/DetailsHeader.js
Labels: bug

#2975 Fix [Artifacts] Version history items without tags fail to open
  src/utils/artifacts.util.js
Labels: bug

#2974 Fix [Artifacts] 'Filter by' pop-up issues on version history page
  src/components/ActionBar/ActionBar.js
  src/components/Documents/DocumentsView.js
  src/components/Files/FilesView.js
  src/components/FilterMenuModal/FilterMenuModal.js
  src/components/ModelsPage/Models/ModelsView.js
Labels: bug

#2976 Impl [Monitor Jobs] Changes for pagination with auto-refresh
  src/common/Pagination/Pagination.js
  src/components/ActionBar/ActionBar.js
  src/components/Jobs/Jobs.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/constants.js
  src/elements/JobsTable/JobsTable.js
  src/hooks/usePagination.hook.js
  src/reducers/filtersReducer.js
Labels: enhancement

#2977 Fix [Monitor Jobs] Auto refresh is broken
  src/components/Jobs/Jobs.js
Labels: bug

#2978 Tests [QA] v1.8.0-rc13
  tests/features/MLFunction.feature
  tests/features/artifacts.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
  tests/mockServer/data/artifacts.json
  tests/mockServer/mock.js
Labels: tests

#2979 Fix [Alerts history] Trigger criteria time period is "Null", expected "N/A"
  src/common/Pagination/pagination.scss
  src/components/DetailsInfo/detailsInfo.util.js
  src/elements/AlertsTableRow/AlertsTableRow.scss
Labels: bug

#2980 Fix [Pagination] next page is broken for ML functions. datasets, artifacts & models
  src/common/Pagination/Pagination.js
  src/components/Datasets/DatasetsView.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/Documents/DocumentsView.js
  src/components/Files/FilesView.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/Workflow/Workflow.js
  src/elements/JobsTable/JobsTable.js
  src/utils/jobs.util.js
  src/utils/link-helper.util.js
Labels: bug

#2982 Impl [Alerts history] Add “Expandable Alert Table” with Expanded Rows
  src/common/TabsSlider/TabsSlider.js
  src/components/ActionBar/ActionBar.js
  src/components/Alerts/Alerts.js
  src/components/Alerts/AlertsFilters.js
  src/components/Alerts/AlertsView.js
  src/components/Alerts/alerts.scss
  src/components/Alerts/alerts.util.js
  src/components/DetailsAlerts/DetailsAlerts.js
  src/components/DetailsDrillDownAlert/DetailsAlertsMetrics.js
  src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
  src/elements/AlertsTableRow/AlertsTableRow.js
  src/elements/AlertsTableRow/AlertsTableRow.scss
  src/hooks/useAlertsPageData.js
  src/utils/createAlertsContent.js
Labels: enhancement
