Repository mlrun/ui, pull requests merged in 2024-04, with the labels that each got.

#2370 Impl [Cross projects Jobs] Add breadcrumbs
  src/App.js
  src/common/Breadcrumbs/Breadcrumbs.js
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/elements/BreadcrumbsDropdown/breadcrumbsDropdown.scss
Labels: enhancement

#2368 Fix [Project settings] no redirection after being removed from project members `1.6.x`
  src/elements/MembersPopUp/MembersPopUp.js
  src/elements/MembersPopUp/membersPopUp.util.js
Labels: bug

#2371 Fix [Project settings] "select new owner" does not return full list of users when there are 100+ users in system `1.6.x`
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
Labels: bug

#2372 Fix [Project settings] "select new owner" does not return full list of users when there are 100+ users in system
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
Labels: bug

#2373 QA Sprint 162 done
  tests/features/MLFunction.feature
  tests/features/artifacts.feature
  tests/features/common/actions/common.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectMonitoring.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/quickActions.feature
  tests/features/step-definitions/table.steps.js
  tests/mockServer/mock.js
Labels: tests

#2375 Impl [Tetsts] QA Sprint 162 done
  tests/features/MLFunction.feature
  tests/features/artifacts.feature
  tests/features/common/actions/common.action.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectMonitoring.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/quickActions.feature
  tests/features/step-definitions/table.steps.js
  tests/mockServer/mock.js
Labels: tests

#2377 Fix [Workflow] Kubeflow pipeline Condition node appears incorrectly
  src/common/ReactFlow/MlReactFlowNode.js
  src/common/ReactFlow/mlReactFlow.scss
  src/common/ReactFlow/mlReactFlow.util.js
  src/components/Pipeline/Pipeline.js
  src/components/Workflow/Workflow.js
  src/components/Workflow/workflow.util.js
  src/constants.js
Labels: bug

#2383 Fix [Batch run] Provide default_function_pod_resources value `1.6.x`
  src/elements/FormResourcesUnits/FormResourcesUnits.js
  src/utils/helper.js
Labels: bug

#2384 Fix [Batch run] Provide default_function_pod_resources value
  src/elements/FormResourcesUnits/FormResourcesUnits.js
  src/utils/helper.js
Labels: bug

#2386 Fix [Batch Run] Default artifact path not sourced from frontend-spec `1.6.x`
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#2392 Fix [UI] Cross projects jobs page
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/components/ProjectsJobsMonitoring/projectsJobsMonitoring.scss
Labels: bug

#2388 Fix [Artifacts] Artifact/dataset “Copy URI” returns a wrong URI
  src/components/Datasets/datasets.util.js
  src/components/Details/Details.js
  src/components/DetailsArtifacts/detailsArtifacts.util.js
  src/components/DetailsInputs/detailsInputs.util.js
  src/components/Files/files.util.js
  src/components/Project/ProjectMonitor.js
  src/constants.js
  src/reducers/artifactsReducer.js
  src/utils/getUniqueIdentifier.js
  src/utils/parseUri.js
  src/utils/resources.js
Labels: bug

#2397 Fix [Artifacts] Rows jump during scrolling
  src/components/Datasets/DatasetsView.js
  src/components/Files/FilesView.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/hooks/useVirtualization.hook.js
  src/types.js
Labels: bug

#2395 Fix [Artifacts] An empty tag triggers the unique validation
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/elements/RegisterModelModal/RegisterModelModal.js
Labels: bug

#2394 Fix [UI] Missing header columns in the artifacts preview screens
  src/elements/PreviewModal/PreviewModal.js
Labels: bug

#2399 Impl [Settings] add to project setting the ability to define node selectors
  src/components/JobWizard/JobWizardSteps/JobWizardResources/JobWizardResources.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/jobsMonitoring.util.js
  src/constants.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
Labels: enhancement

#2396 Fix [UI] Notification messages overlap each other
  src/common/Download/DownloadContainer.js
  src/common/Download/downloadContainer.scss
  src/common/Notification/Notification.js
  src/common/Notification/notificationView.scss
Labels: bug

#2405 Fix [Jobs and workflows] filter by status is not applied when switching between jobs list/runs
  src/actions/workflow.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/constants.js
  src/reducers/workflowReducer.js
Labels: bug

#2407 Impl [Graphs] Add mini map
  package.json
  src/common/ReactFlow/MlReactFlow.js
  src/common/ReactFlow/MlReactFlowNode.js
  src/common/ReactFlow/mlReactFlow.scss
  src/common/ReactFlow/mlReactFlow.util.js
  src/components/Datasets/datasets.scss
  src/components/Pipeline/pipeline.scss
  src/components/Workflow/Workflow.js
  src/components/Workflow/workflow.scss
  src/scss/main.scss
Labels: enhancement

#2408 Fix [Artifacts] Move 'UID' to 'Producer' column
  src/common/FormTagFilter/FormTagFilter.js
  src/components/Datasets/datasets.util.js
  src/components/DetailsInfo/detailsInfo.util.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/models.util.js
  src/scss/main.scss
  src/utils/generateArtifacts.js
Labels: enhancement

#2414 Fix [ML-5922] Replace old constant name
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
Labels: bug

#2409 Impl [Artifacts] Delete artifacts doesn't work properly
  src/api/artifacts-api.js
  src/common/ActionsMenu/ActionsMenu.js
  src/components/Datasets/Datasets.js
  src/components/Datasets/datasets.util.js
  src/components/Files/Files.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/models.util.js
  src/constants.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/reducers/artifactsReducer.js
  src/utils/handleDeleteArtifact.js
Labels: enhancement

#2413 Fix [MLRun project] wrong error message when trying to create Fset (with ingest)
  src/actions/featureStore.js
Labels: bug

#2411 Fix [UI] The 'Save' and 'Save and Ingest' buttons should be switched to clickable after all set fields have passed UI validation
  src/common/Combobox/Combobox.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/components/FeatureSetsPanel/UrlPath.js
  src/components/FeatureSetsPanel/UrlPath.utils.js
  src/components/FeatureSetsPanel/urlPath.scss
Labels: bug

#2415 Fix [MLRun project] wrong error message when trying to create Fset (with ingest) (new message)
  src/actions/featureStore.js
Labels: bug

#2410 Fix [Date Picker] Wrong selected option after changing project
  src/components/FilterMenu/FilterMenu.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/elements/ProjectStatistics/ProjectStatistics.js
  src/reducers/filtersReducer.js
Labels: bug

#2416 Impl [UI] Projects dashboard - notify when mlrun isn't reachable
  package.json
  src/actions/projects.js
  src/common/PageActionsMenu/PageActionsMenu.js
  src/common/Search/Search.js
  src/common/Sort/Sort.js
  src/common/SplitButton/SplitButton.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projects.util.js
  src/constants.js
  src/elements/ContentMenu/ContentMenu.js
  src/elements/ContentMenu/contentMenu.scss
  src/httpClient.js
  src/reducers/projectReducer.js
Labels: bug

#2417 Impl [Cross projects Jobs] Add data table for Scheduled tab
  src/App.js
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoringJobs/ProjectsJobsMonitoringJobs.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoringScheduled/ProjectsJobsMonitoringScheduled.js
  src/components/ProjectsJobsMonitoring/ScheduledMonitoring/ScheduledMonitoring.js
  src/elements/ScheduledJobsTable/ScheduledJobsTable.js
  src/elements/ScheduledJobsTable/scheduledJobsTable.scss
  src/utils/createJobsContent.js
Labels: enhancement

#2418 Impl [Functions] Add 'Application' type info
  src/actions/functions.js
  src/api/mlrun-nuclio-api.js
  src/components/Details/DetailsTabsContent/DetailsTabsContent.js
  src/components/Details/details.scss
  src/components/Details/details.util.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/DetailsInfo/detailsInfo.util.js
  src/components/DetailsLogs/DetailsLogs.js
  src/components/DetailsLogs/Logs.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functions.util.js
  src/constants.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/reducers/functionReducer.js
  src/utils/getFunctionLogs.js
  src/utils/parseFunction.js
Labels: enhancement

#2419 Fix [ML functions] partial load: items flicker and fail to load
  src/components/FunctionsPage/FunctionsView.js
Labels: bug

#2420 Fix [Batch Run] Unexpected Application Error screen
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
Labels: bug

#2421 Fix [General] filters results are not displayed until scroll or refresh
  src/hooks/useVirtualization.hook.js
Labels: bug

#2423 Impl [Functions] Add 'Application' type info
  package.json
  src/components/DetailsInfo/DetailsInfoView.js
  src/elements/TableTypeCell/TableTypeCell.js
Labels: enhancement

#2425 Fix [Modal wizard] Back and forward browser navigation does not automatically close the form
  src/hooks/useModalBlockHistory.hook.js
Labels: bug

#2426 Fix [Artifacts] Uniqueness validation warning message doesn't specify the type of artifact being overwritten
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/elements/RegisterModelModal/RegisterModelModal.js
  src/utils/createArtifact.util.js
Labels: bug
