Repository mlrun/ui, pull requests merged in 2024-09, with the labels that each got.

#2695 Fix [Batch Run] parameters type options issues
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#2697 Fix [Feature store] inconsistent "You do not have permission to create a new feature set." error message
  src/actions/featureStore.js
Labels: bug

#2698 Fix [Model Endpoints] view YAML missing feature stats data
  src/actions/modelEndpoints.js
  src/components/Details/DetailsTabsContent/DetailsTabsContent.js
  src/components/DetailsDriftAnalysis/DetailsDriftAnalysis.js
  src/components/DetailsFeaturesAnalysis/DetailsFeaturesAnalysis.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/FunctionsPage/functions.util.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
  src/constants.js
  src/reducers/artifactsReducer.js
  src/reducers/detailsReducer.js
  src/utils/parseModelEndpoints.js
Labels: bug

#2699 Fix [Projects] add unique class name instead of removed project-card__labels
  src/elements/ProjectCard/ProjectCardView.js
Labels: bug

#2700 Fix [Workflows] UI - show detailed error message from pipeline
  src/elements/WorkflowsTable/WorkflowsTable.js
Labels: bug

#2701 Fix [Batch Run] unable to update parameter
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
Labels: bug

#2702 Fix [Functions] hide `Build and run` action
  src/components/FunctionsPage/functions.util.js
Labels: bug

#2704 Fix [CI/CD] Branch Regex Pattern in CI Workflow
  .github/workflows/ci.yaml
Labels: tests

#2705 Impl [Projects] Jobs monitoring 'scheduled' with type=All is inaccessible without filter
  src/components/ProjectsPage/projects.util.js
  src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
  src/utils/generateMonitoringData.js
Labels: enhancement

#2706 Fix [Batch run] Unify categories names
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#2709 Fix [UI] Popup closes on tooltip click
  src/elements/MetricsSelector/MetricsSelector.js
Labels: bug

#2703 Fix [Artifacts] GET /artifacts fails with 'Multiple rows were found when one or none was required' when listing artifacts
  src/api/artifacts-api.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/reducers/artifactsReducer.js
  src/utils/artifacts.util.js
  src/utils/searchArtifactItem.js
  tests/mockServer/mock.js
Labels: bug

#2712 Fix [Real time pipelines] UI crash `Cannot destructure property width of e.__rf as it is undefined` when clicking on real-time pipeline name
  src/common/ReactFlow/mlReactFlow.util.js
Labels: bug

#2714 Fix [UI] Overflow Issue in "Features Analysis" Table Header
  src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.scss
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
Labels: bug

#2715 Fix [Jobs and workflows] Hide “node selector” from details view when the function is of type “Dask”
  src/components/Jobs/jobs.util.js
  src/elements/JobsTable/jobsTable.util.js
Labels: bug

#2716 Fix [UI] Page crash when VPN is offline
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/JobWizard/JobWizard.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/utils/projects.js
Labels: bug

#2723 Tests [Mock] Add mock to not allowed to create/update internal secrets (with mlrun key)
  tests/mockServer/mock.js
Labels: tests

#2724 Fix [Jobs] no status for "Terminating" state for workflow
  src/scss/main.scss
  src/utils/getState.js
Labels: bug

#2725 Fix [Artifacts] unexpected application error on full view
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/elements/JobsTable/JobsTable.js
Labels: bug

#2727 Fix [Artifacts] Download notification popup is hidden
  src/App.js
  src/common/Download/downloadContainer.scss
  src/layout/Page/Page.js
Labels: bug

#2728 Fix [Workflows] The 'name-contains' query parameter is missing
  src/api/workflow-api.js
Labels: bug

#2726 Fix [Feature sets] project name is missing from the request url when navigating between feature sets
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/hooks/useInitialTableFetch.hook.js
  src/utils/createFeatureStoreContent.js
Labels: bug

#2730 Fix [Feature sets] project name is missing from the request url when navigating between feature sets
  src/components/FeatureStore/FeatureSets/FeatureSets.js
Labels: bug

#2731 Fix [Project monitoring] Missing notification for failed requests
  src/components/Project/ProjectMonitor.js
  src/components/Project/ProjectOverview/ProjectOverview.js
  src/components/Project/project.utils.js
Labels: bug

#2729 Fix [Projects] misleading error in "Create new project" dialog when project create fails
  src/actions/projects.js
  src/common/ErrorMessage/ErrorMessage.js
  src/common/ErrorMessage/errorMessage.scss
Labels: bug

#2735 Fix [Project monitoring] requests are not canceled when changing pages
  src/actions/nuclio.js
  src/actions/projects.js
  src/api/nuclio.js
  src/api/projects-api.js
  src/components/Project/ProjectMonitor.js
  src/elements/ProjectFunctions/ProjectFunctions.js
  src/elements/ProjectJobs/ProjectJobs.js
Labels: bug

#2736 Fix [Project Jobs Monitoring] Change filtering by project name
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
Labels: bug

#2737 Fix [Models] incorrect delete confirmation message
  src/components/ModelsPage/Models/models.util.js
Labels: bug

#2745 Fix [Job Inputs] incorrect Show Details link
  src/components/DetailsInputs/DetailsInputs.js
Labels: bug

#2744 Fix [Feature store] row remains open after taking action on feature vector
  src/components/FeatureStore/FeatureVectors/FeatureVectorsView.js
Labels: bug

#2743 Fix [Models endpoints monitoring, metrics] add a tooltip to disabled metrics selector
  src/elements/MetricsSelector/MetricsSelector.js
Labels: bug

#2742 Impl [Artifacts] Add mock for GET `artifacts` request
  tests/mockServer/mock.js
Labels: enhancement, tests

#2741 Fix [Models] Avoid showing functions that has no graph in the real_time_pipeline tab
  src/components/Pipeline/Pipeline.js
Labels: bug

#2690 Fix [Functions] "This function either does not exist or was deleted" notification after applying filter
  src/components/ActionBar/ActionBar.js
  src/components/ConsumerGroup/ConsumerGroup.js
  src/components/ConsumerGroups/ConsumerGroups.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/FunctionsPage/functions.util.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ScheduledMonitoring/ScheduledMonitoring.js
  src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoring.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/reducers/filtersReducer.js
  src/utils/createFunctionsRowData.js
  src/utils/getNoDataMessage.js
Labels: bug

#2752 Fix [Breadcrumbs] Archived projects are displayed in the projects dropdown selection `1.7.x`
  src/actions/projects.js
  src/common/Breadcrumbs/Breadcrumbs.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/projects.util.js
  src/constants.js
Labels: bug

#2751 Fix [Security][UI] detected vulnerabilities in Link component `1.7.x`
  src/common/TabsSlider/TabsSlider.js
  src/components/Details/DetailsHeader/DetailsHeader.js
Labels: bug

#2749 Fix [Jobs and Workflows] Name match issue `1.7.x`
  src/App.js
  src/common/Breadcrumbs/Breadcrumbs.js
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/components/Jobs/Jobs.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoring.js
  src/components/Workflow/workflow.util.js
  src/constants.js
  src/utils/createJobsContent.js
  src/utils/generateMonitoringData.js
Labels: bug

#2748 Fix [Models] Change models filter by label to case insensitive `1.7.x`
  src/components/ArtifactsActionBar/ArtifactsFilters.js
  src/components/FilterMenu/FilterMenu.js
  tests/mockServer/mock.js
Labels: bug

#2717 Fix [Models] Change models filter by label to case insensitive
  src/components/ArtifactsActionBar/ArtifactsFilters.js
  src/components/FilterMenu/FilterMenu.js
  tests/mockServer/mock.js
Labels: bug

#2734 Fix [Jobs and Workflows] Name match issue
  src/App.js
  src/common/Breadcrumbs/Breadcrumbs.js
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/components/Jobs/Jobs.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoring.js
  src/components/Workflow/workflow.util.js
  src/constants.js
  src/utils/createJobsContent.js
  src/utils/generateMonitoringData.js
Labels: bug

#2740 Fix [Security][UI] detected vulnerabilities in Link component
  src/common/TabsSlider/TabsSlider.js
  src/components/Details/DetailsHeader/DetailsHeader.js
Labels: bug

#2746 Fix [Feature store] table is not updated after applying changes to feature vector
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
Labels: bug

#2747 Fix [Breadcrumbs] Archived projects are displayed in the projects dropdown selection
  src/actions/projects.js
  src/common/Breadcrumbs/Breadcrumbs.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/projects.util.js
  src/constants.js
Labels: bug

#2762 Fix [UI] App crashes on opening Function/Models details `1.7.x`
  src/common/TabsSlider/TabsSlider.js
  src/components/Datasets/Datasets.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/Details/details.util.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
  src/components/Files/Files.js
  src/components/FunctionsPage/Functions.js
  src/components/Jobs/Jobs.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/Models/Models.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/jobsMonitoring.util.js
  src/components/Workflow/Workflow.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/elements/JobsTable/JobsTable.js
  src/elements/WorkflowsTable/WorkflowsTable.js
  src/layout/Content/Content.js
  src/layout/Page/Page.js
  src/utils/createArtifactsContent.js
  src/utils/createFeatureStoreContent.js
  src/utils/createJobsContent.js
  src/utils/createRealTimePipelinesContent.js
  src/utils/generateLinkToDetailsPanel.js
  src/utils/getCloseDetailsLink.js
  src/utils/handleRedirect.js
  src/utils/isDetailsTabExists.js
  src/utils/link-helper.util.js
Labels: bug

#2753 Fix [UI] MLRun Artifact/Job Linking Broken
  src/components/ArtifactInfoSources/ArtifactInfoSources.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/DetailsInfo/detailsInfo.util.js
  src/components/DetailsInputs/DetailsInputs.js
  src/components/DetailsInputs/detailsInputs.util.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/utils/generateStoreResourceLink.js
  tests/mockServer/data/artifacts.json
Labels: bug

#2758 Fix [Artifacts] "big" artifacts preview fails with 504 after 3m
  package.json
  src/api/artifacts-api.js
  src/common/Download/Download.js
  src/common/Download/DownloadItem.js
  src/common/Download/download.scss
  src/components/ArtifactsPreview/ArtifactsPreviewController.js
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/ArtifactsPreview/artifactsPreview.scss
  src/components/Datasets/datasets.util.js
  src/components/DetailsAnalysis/DetailsAnalysis.js
  src/components/DetailsArtifacts/detailsArtifacts.util.js
  src/components/DetailsPreview/DetailsPreview.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/models.util.js
  src/constants.js
  src/elements/ArtifactsExtraData/ArtifactsExtraData.js
  src/elements/PreviewModal/PreviewModal.js
  src/elements/TableCell/TableCell.js
  src/utils/createArtifactPreviewContent.js
  src/utils/getArtifactPreview.js
  tests/mockServer/data/artifacts/csv_mock_data.csv
  tests/mockServer/data/featureSets.json
  tests/mockServer/data/frontendSpec.json
  tests/mockServer/mock.js
Labels: bug

#2759 Fix [Artifacts] "big" artifacts preview fails with 504 after 3m `1.7.x`
  package.json
  src/api/artifacts-api.js
  src/common/Download/Download.js
  src/common/Download/DownloadItem.js
  src/common/Download/download.scss
  src/components/ArtifactsPreview/ArtifactsPreviewController.js
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/ArtifactsPreview/artifactsPreview.scss
  src/components/Datasets/datasets.util.js
  src/components/DetailsAnalysis/DetailsAnalysis.js
  src/components/DetailsArtifacts/detailsArtifacts.util.js
  src/components/DetailsPreview/DetailsPreview.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/models.util.js
  src/constants.js
  src/elements/ArtifactsExtraData/ArtifactsExtraData.js
  src/elements/PreviewModal/PreviewModal.js
  src/elements/TableCell/TableCell.js
  src/utils/createArtifactPreviewContent.js
  src/utils/getArtifactPreview.js
  tests/mockServer/data/artifacts/csv_mock_data.csv
  tests/mockServer/data/featureSets.json
  tests/mockServer/data/frontendSpec.json
  tests/mockServer/mock.js
Labels: bug

#2761 Fix [Project monitoring] requests are not canceled when changing pages `1.7.x`
  src/actions/projects.js
  src/reducers/projectReducer.js
Labels: bug

#2763 Fix [React] add missing dependencies
  src/components/ActionBar/ActionBar.js
Labels: bug

#2764 Fix [React] add missing dependencies `1.7.x`
  src/components/ActionBar/ActionBar.js
Labels: bug

#2772 Fix [General] unexpected redirection to the Home page after click on tab `1.7.x`
  src/common/TabsSlider/TabsSlider.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/Workflow/Workflow.js
  src/elements/JobsTable/JobsTable.js
Labels: bug

#2768 Fix [General] unexpected redirection to the Home page after click on tab
  src/common/TabsSlider/TabsSlider.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/Workflow/Workflow.js
  src/elements/JobsTable/JobsTable.js
Labels: bug

#2767 Fix [Feature vectors] project name is missing from the request for tags `1.7.x`
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
Labels: bug

#2766 Fix [Feature vectors] project name is missing from the request for tags
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
Labels: bug

#2770 Fix [Models] latest tag is assigned after simultaneous removal of the tag and labels `1.7.x`
  src/components/ModelsPage/Models/models.util.js
Labels: bug

#2769 Fix [Models] latest tag is assigned after simultaneous removal of the tag and labels
  src/components/ModelsPage/Models/models.util.js
Labels: bug

#2773 Fix [Model Monitoring] fix model metrics multiple date values on metrics screen selection `1.7.x`
  src/components/MetricChart/MetricChart.js
  src/components/MetricChart/metricChart.util.js
  src/utils/getMetricChartConfig.js
Labels: bug

#2775 Fix [Workflows] Abort among Actions on workflow jobs with statuses completed / error / aborted `1.7.x`
  src/components/Jobs/jobs.util.js
  src/elements/WorkflowsTable/WorkflowsTable.js
Labels: bug

#2774 Fix [Workflows] Abort among Actions on workflow jobs with statuses completed / error / aborted
  src/components/Jobs/jobs.util.js
  src/elements/WorkflowsTable/WorkflowsTable.js
Labels: bug

#2777 Fix [Job Artifacts] project name is missing from the request url after click on Artifacts tab `1.7.x`
  src/components/DetailsArtifacts/DetailsArtifacts.js
Labels: bug

#2776 Fix [Job Artifacts] project name is missing from the request url after click on Artifacts tab
  src/components/DetailsArtifacts/DetailsArtifacts.js
Labels: bug

#2779 Fix [CE] project link is broken fails to browse to project UI
  src/index.js
Labels: bug

#2778 Fix [CE] project link is broken fails to browse to project UI `1.7.x`
  src/index.js
Labels: bug

#2780 Fix [Artifacts] Unable to delete artifacts when overriding secrets
  src/api/artifacts-api.js
Labels: bug

#2781 Fix [Artifacts] Unable to delete artifacts when overriding secrets `1.7.x`
  src/api/artifacts-api.js
  src/common/TabsSlider/TabsSlider.js
Labels: bug

#2786 Fix [Projects Settings] There is no request to update the 'Pull at runtime' checkbox `1.7.x`
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
Labels: bug

#2785 Fix [Projects Settings] There is no request to update the 'Pull at runtime' checkbox
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
Labels: bug

#2784 Fix [ML Functions] Redundant notification appears
  src/components/FunctionsPanel/FunctionsPanel.js
Labels: bug

#2783 Fix [Projects] The 'Confirm message' is missing when deleting a project
  src/components/ProjectsPage/Projects.js
Labels: bug

#2782 QA Sprint 169 done `1.7.x`
  tests/features/MLFunction.feature
  tests/features/artifacts.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/page-objects/jobs-monitoring.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/jobsMonitoring.feature
  tests/features/projectMonitoring.feature
  tests/features/projectsPage.feature
  tests/features/quickActions.feature
  tests/mockServer/mock.js
Labels: tests

#2789 Fix [Functions] wrong list after "Build and run"
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsView.js
Labels: bug

#2790 Fix [Functions] wrong list after "Build and run" `1.7.x`
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsView.js
Labels: bug

#2792 Fix [Functions] deleted ML function stays in the list after successful deletion `1.7.x`
  src/components/FunctionsPage/Functions.js
Labels: bug

#2791 Fix [Functions] deleted ML function stays in the list after successful deletion
  src/components/FunctionsPage/Functions.js
Labels: bug

#2793 Fix [Projects] click on archived project redirects to "Active" projects screen
  src/common/Breadcrumbs/Breadcrumbs.js
  src/layout/Content/Content.js
  src/layout/Page/Page.js
  src/utils/link-helper.util.js
Labels: bug

#2794 Fix [Projects] click on archived project redirects to "Active" projects screen `1.7.x`
  src/common/Breadcrumbs/Breadcrumbs.js
  src/layout/Content/Content.js
  src/layout/Page/Page.js
  src/utils/link-helper.util.js
Labels: bug
