Repository mlrun/ui, pull requests merged in 2024-05, with the labels that each got.

#2427 Impl [UI] Revamp Ml function page
  src/components/ActionBar/ActionBar.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsFilters.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/FunctionsPage/functions.util.js
  src/constants.js
  src/reducers/filtersReducer.js
Labels: enhancement

#2430 Fix [Job wizard] unexpected change in 'Default artifact path' in 'Batch Run' wizard `1.6.x`
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#2428 Impl [Functions] Add new Logs for 'Application' type
  src/components/Details/DetailsTabsContent/DetailsTabsContent.js
  src/components/DetailsLogs/DetailsLogs.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functions.util.js
Labels: enhancement

#2429 Fix [Functions] error message 'This function either does not exist or was deleted' displays when searching for function by name
  src/components/FunctionsPage/Functions.js
Labels: bug

#2431 Fix [Preview modal] cosmetic fixes
  src/elements/PreviewModal/PreviewModal.js
  src/elements/PreviewModal/previewModal.scss
Labels: bug

#2432 Fix [MLRun project] wrong error message when trying to create Fset
  src/actions/featureStore.js
Labels: bug

#2433 Fix [Node Selector] Different naming convention for Node Selector key between Nuclio and Project setting/ Mlrun func
  package.json
Labels: bug

#2435 Fix [Jobs and workflows] filters are not applied when switching between jobs
  src/components/FilterMenu/FilterMenu.js
Labels: bug

#2437 Impl [Project][Secrets] Add new Secrets table with validation
  package.json
  src/actions/projects.js
  src/constants.js
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecrets.js
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecrets.scss
  src/elements/ProjectSettingsSecrets/ProjectSettingsSecretsView.js
  src/reducers/projectReducer.js
Labels: enhancement

#2434 Impl [UI] Incorrect texts across the app
  src/actions/featureStore.js
  src/actions/projects.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizard.util.js
  src/components/Jobs/jobs.util.js
  src/components/Project/ProjectMonitor.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/projects.util.js
  src/elements/FeaturesTablePanel/FeaturesTablePanel.js
  src/elements/JobsTable/JobsTable.js
  src/elements/ScheduledJobsTable/ScheduledJobsTable.js
  src/elements/WorkflowsTable/WorkflowsTable.js
  src/utils/artifacts.util.js
  src/utils/getNoDataMessage.js
  src/utils/jobs.util.js
Labels: enhancement

#2436 Fix [Models] revisit 'Failed to deploy model' dialog
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/models.util.js
  src/components/ModelsPage/modelsPage.scss
Labels: bug

#2438 Fix [Artifacts] artifact-tags requests are not canceled when changing pages
  src/hooks/useGetTagOptions.hook.js
  src/reducers/artifactsReducer.js
  src/reducers/filtersReducer.js
  src/utils/parseArtifacts.js
Labels: bug

#2439 Impl [Jobs] List artifacts of a specific run
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsArtifacts/detailsArtifacts.util.js
Labels: enhancement

#2441 Fix [Dropdown] Option list closes on scroll
  src/components/FilterMenuModal/FilterMenuModal.js
  src/utils/checkElementsPosition.utils.js
Labels: bug

#2442 Fix [Breadcrumbs] request is not sent when changing project
  src/components/ModelsPage/Models/Models.js
  src/hooks/useGetTagOptions.hook.js
Labels: bug

#2444 Fix [Batch Run] The request is not sent if there are no scheduled jobs
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
Labels: bug

#2446 Fix [Models] revisit 'Failed to deploy model' dialog
  src/components/ModelsPage/Models/models.util.js
Labels: bug

#2448 Fix [Feature Vectors] Incorrect display of Requested Features
  src/common/TagFilter/TagFilterDropdown.js
  src/components/ActionBar/ActionBar.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeaturesView.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/scss/main.scss
Labels: bug

#2449 Fix [Monitor Jobs] time in the Start Time filter is not updated
  src/components/FilterMenu/FilterMenu.js
Labels: bug

#2452 Impl [Models endpoints monitoring] Metrics dropdown selector
  src/actions/details.js
  src/api/details-api.js
  src/components/Details/Details.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/Details/DetailsTabsContent/DetailsTabsContent.js
  src/components/Details/details.scss
  src/components/DetailsMetrics/DetailsMetrics.js
  src/components/DetailsMetrics/detailsMetrics.utils.js
  src/components/DetailsMetrics/metricsMock.js
  src/constants.js
  src/elements/MetricsSelector/MetricsSelector.js
  src/elements/MetricsSelector/metricsSelector.scss
  src/elements/MetricsSelector/metricsSelector.utils.js
  src/reducers/detailsReducer.js
  src/types.js
Labels: enhancement

#2454 Fix [UI] Build error due to console.log
  src/components/DetailsMetrics/DetailsMetrics.js
Labels: bug

#2451 Impl [Functions] Ability to delete a remote function from DB using UI
  src/actions/functions.js
  src/api/functions-api.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/FunctionsPage/functions.util.js
  src/constants.js
  src/elements/ProjectTable/projectTable.scss
  src/utils/getState.js
  src/utils/parseFunction.js
Labels: enhancement

#2450 Fix [Jobs monitoring] 'Any time' date picker filter doesn't work correctly
  src/components/ActionBar/ActionBar.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
Labels: bug

#2445 Fix [Jobs and workflows] filter by time does not correctly mark selected option
  src/common/DatePicker/DatePicker.js
  src/components/FilterMenu/FilterMenu.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/elements/JobsTable/JobsTable.js
  src/reducers/filtersReducer.js
Labels: bug

#2456 Fix [Jobs and Workflows] hide 'No data to show' message during artifacts loading `1.6.x`
  src/components/DetailsArtifacts/DetailsArtifacts.js
Labels: bug

#2457 Fix [Jobs] Run status contains full artifacts in response for api/v1/run/{project}/{uid}
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#2458 Fix [Jobs] Run status contains full artifacts in response for api/v1/run/{project}/{uid} `1.6.x`
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#2459 Impl [Cross projects Jobs] Use 'project_summaries' endpoint for counters
  src/actions/projects.js
  src/components/ActionBar/ActionBar.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
  src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoring.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsMonitoring/ProjectsMonitoring.js
  src/components/ProjectsPage/projects.util.js
  src/elements/ProjectCard/projectCard.util.js
  src/elements/ProjectsMonitoringCounters/JobsCounters.js
  src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
  src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
  src/utils/generateMonitoringData.js
Labels: enhancement

#2461 Fix [Model endpoints per project] Remove metric selector mock data
  src/actions/details.js
  src/components/DetailsMetrics/DetailsMetrics.js
  src/components/DetailsMetrics/metricsMock.js
Labels: bug

#2465 Fix [Jobs] List artifacts of a specific run with iterations `1.6.x`
  src/components/DetailsArtifacts/DetailsArtifacts.js
Labels: bug

#2464 Fix [Jobs] List artifacts of a specific run with iterations
  src/components/DetailsArtifacts/DetailsArtifacts.js
Labels: bug

#2462 Fix [Schedule Job] when edit a schedule job by default the schedule change to every 10 minute `1.6.x`
  src/components/SheduleWizard/scheduleWizard.util.js
Labels: bug

#2466 Impl [Functions] Add `api-gateways` request for Application type
  src/actions/functions.js
  src/api/mlrun-nuclio-api.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/FunctionsPage/functions.util.js
  src/constants.js
  src/reducers/functionReducer.js
  src/utils/parseFunction.js
  src/utils/parseFunctions.js
Labels: enhancement

#2447 Impl [Artifacts] Delete single artifact data
  package.json
  src/api/artifacts-api.js
  src/components/Files/files.util.js
  src/elements/DeleteArtifactPopUp/DeleteArtifactPopUp.js
  src/elements/DeleteArtifactPopUp/deleteArtifactPopUp.scss
  src/reducers/artifactsReducer.js
  src/utils/handleDeleteArtifact.js
Labels: enhancement

#2470 Impl [Cross projects Jobs] Support multiple status selection
  src/actions/jobs.js
  src/common/FormOnChange/FormOnChange.js
  src/common/TargetPath/TargetPath.js
  src/components/ActionBar/ActionBar.js
  src/components/ArtifactsActionBar/ArtifactsFilters.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeaturesView.js
  src/components/FilterMenu/filterMenu.settings.js
  src/components/FilterMenuModal/HubCategoriesFilter/HubCategoriesFilter.js
  src/components/FunctionsPage/FunctionsFilters.js
  src/components/JobWizard/JobWizardSteps/JobWizardAdvanced/JobWizardAdvanced.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoringFilters.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ScheduledMonitoring/ScheduledMonitoring.js
  src/components/ProjectsJobsMonitoring/ScheduledMonitoring/ScheduledMonitoringFilters.js
  src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoringFilters.js
  src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
  src/elements/DeleteArtifactPopUp/DeleteArtifactPopUp.js
  src/elements/DeployModelPopUp/DeployModelPopUp.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/elements/DetailsInfoItemChip/DetailsInfoItemChip.js
  src/elements/FormEnvironmentVariablesTable/FormEnvironmentVariablesRow/FormEnvironmentVariablesRow.js
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.js
  src/elements/FormResourcesUnits/FormResourcesUnits.js
  src/elements/FormVolumesTable/FormVolumesRow/FormVolumesRow.js
  src/elements/MetricsSelector/MetricsSelector.js
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/reducers/filtersReducer.js
  src/utils/generateMonitoringData.js
Labels: enhancement

#2469 Impl [UI Model Monitoring Per Project] - Limit timeframe to 1 month
  src/common/DatePicker/DatePicker.js
  src/common/DatePicker/DatePickerView.js
  src/common/DatePicker/datePicker.scss
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/Details/details.scss
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FilterParameters.js
  src/components/FilterMenu/filterMenu.scss
  src/elements/MetricsSelector/MetricsSelector.js
  src/elements/MetricsSelector/metricsSelector.scss
  src/types.js
  src/utils/datePicker.util.js
Labels: enhancement

#2473 Fix [UI] When showing lists of jobs and workflows, time frame of "any time" should not be considered a filter
  src/utils/getNoDataMessage.js
Labels: bug

#2474 Tests [QA] v1.7.0-rc17
  package.json
  tests/features/artifacts.feature
  tests/features/common-tools/common-consts.js
  tests/features/common-tools/common-tools.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/files.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/pipelines.json
  tests/mockServer/data/summary.json
Labels: tests

#2476 Fix [Workflow] Wrong redirection
  src/common/ReactFlow/mlReactFlow.scss
  src/elements/WorkflowsTable/WorkflowsTable.js
Labels: bug

#2477 Impl [Projects] Remove cross-project jobs counters from demo
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/ProjectsView.js
Labels: enhancement

#2478 Impl [Model endpoints] Remove Metrics tab from demo flag
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
Labels: enhancement

#2479 Fix [Cross projects Jobs and Workflows] Redundant indication on the "Filter by"
  src/utils/generateMonitoringData.js
Labels: bug

#2480 Fix [Feature Sets Panel] Tooltip warning icon displays over the input text
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/featureSetsPanelDataSource.scss
Labels: bug

#2481 Fix [Cross project Jobs] Misc bugs
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/components/Workflow/Workflow.js
  src/utils/createJobsContent.js
Labels: bug

#2482 Fix [UI] do not show "Failed to delete" status in UI
  src/elements/ProjectTable/projectTable.scss
  src/utils/getState.js
  src/utils/parseFunction.js
Labels: bug

#2483 Fix [Artifacts] Sorting with an expanded row doesn't display table data correctly
  src/components/Datasets/DatasetsView.js
  src/components/FeatureStore/FeatureSets/FeatureSetsView.js
  src/components/FeatureStore/Features/FeaturesView.js
  src/components/Files/FilesView.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/Models/ModelsView.js
Labels: bug

#2484 Fix [Models] date picker does not not working correct
  src/components/Details/Details.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/reducers/detailsReducer.js
Labels: bug

#2485 Fix [Jobs and workflows] filter by time does not correctly mark selected option
  src/common/DatePicker/DatePicker.js
Labels: bug

#2487 Fix [Functions] loading gets stuck after expanding row
  src/hooks/useVirtualization.hook.js
Labels: bug

#2488 Fix [Functions] expanded rows data is not updated after Refresh
  src/components/FunctionsPage/Functions.js
Labels: bug

#2489 Fix [Functions] Unexpected error during functions deletion
  src/components/FunctionsPage/functions.util.js
Labels: bug

#2490 Fix [Feature sets panel] inconsistent notification upon success/failure
  src/actions/featureStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureSetsPanel/FeatureSetsPanelView.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureSets/featureSets.util.js
  src/components/Project/ProjectMonitor.js
  src/constants.js
  src/reducers/featureStoreReducer.js
Labels: bug

#2491 Fix [Batch run] unexpected change in 'Default artifact path'
  src/components/JobWizard/JobWizard.util.js
Labels: bug

#2492 Fix [Project Settings] hide project level node selectors on unsupported igz versions
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/elements/ProjectSettingsGeneral/projectSettingsGeneral.utils.js
Labels: bug

#2493 Fix [Artifacts] Filter by 'All' tag reverts to 'latest'
  src/components/ArtifactsActionBar/ArtifactsActionBar.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/ModelsPage/Models/models.util.js
  src/elements/DetailsInfoItemChip/DetailsInfoItemChip.js
Labels: bug

#2494 Fix [Metrics] Wrong selected metrics when connection is slow
  src/actions/details.js
  src/api/details-api.js
  src/components/DetailsMetrics/DetailsMetrics.js
  src/reducers/detailsReducer.js
Labels: bug

#2486 Fix [Artifacts] disable download for not allowed prefixes in artifact/dataset/model path
  src/components/Datasets/datasets.util.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/models.util.js
Labels: bug

#2495 Impl [Models endpoints monitoring] Graph over time
  src/actions/details.js
  src/components/DetailsMetrics/DetailsMetrics.js
  src/components/DetailsMetrics/DetailsMetrics.scss
  src/components/DetailsMetrics/detailsMetrics.utils.js
  src/components/MetricChart/MetricChart.js
  src/components/MetricChart/metricChart.util.js
  src/constants.js
  src/utils/getHistogramChartConfig.js
  src/utils/getMetricChartConfig.js
Labels: enhancement

#2497 Fix [Functions] function build logs for untagged function
  src/components/Details/DetailsTabsContent/DetailsTabsContent.js
  src/components/DetailsLogs/DetailsLogs.js
  src/components/FunctionsPage/functions.util.js
Labels: bug

#2498 Fix [Artifacts] No warning message for big response `1.6.x`
  src/httpClient.js
Labels: bug
