Repository mlrun/ui, pull requests merged in 2024-07, with the labels that each got.

#2561 Fix [Job Artifacts] Drilling from a run's artifact tab to a specific artifact results is a full query
  src/components/ArtifactsActionBar/ArtifactsActionBar.js
  src/components/Datasets/Datasets.js
  src/components/DetailsArtifacts/detailsArtifacts.util.js
  src/components/Files/Files.js
  src/components/FilterMenuModal/FilterMenuModal.js
  src/components/ModelsPage/Models/Models.js
  src/hooks/artifacts.hook.js
Labels: bug

#2559 Fix [Models, Artifacts, Datasets] Tag UID is rewritten after updating labels
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/elements/RegisterModelModal/RegisterModelModal.js
Labels: bug

#2558 Fix [Feature store] overlay error pop up is not displayed upon 403 for "Save and Ingest"
  src/actions/featureStore.js
Labels: bug

#2557 Fix [UI] partition by "project_and_name" instead of "name" when list runs
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
Labels: bug

#2556 Fix [Functions] move 'Deploy' button for 'Serving' function to demo mode
  src/components/FunctionsPage/functions.util.js
Labels: bug

#2547 Impl [Artifacts|Datasets|Models] Reduce load on UI on list requests
  src/api/artifacts-api.js
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/Datasets/datasets.util.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/Files/files.util.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functions.util.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/Models/models.util.js
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/elements/RegisterModelModal/RegisterModelModal.js
  src/reducers/artifactsReducer.js
  src/utils/artifacts.util.js
  src/utils/parseArtifacts.js
Labels: enhancement

#2544 Fix [UI] The application crashes when opening a preview of the 105 MB artifact.
  src/components/ArtifactsPreview/ArtifactsPreviewView.js
  src/components/ArtifactsPreview/artifactsPreview.scss
  src/utils/getArtifactPreview.js
Labels: bug

#2562 Impl [UI] Align API GW usage across all nuclio sub-types
  src/actions/functions.js
  src/api/mlrun-nuclio-api.js
  src/components/ActionBar/ActionBar.js
  src/components/DetailsInfo/detailsInfo.scss
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/FunctionsPage/functions.util.js
  src/constants.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/reducers/functionReducer.js
  src/utils/parseFunction.js
  src/utils/parseFunctions.js
  tests/mockServer/data/funcs.json
Labels: enhancement

#2563 Fix [UI] Add mock for application Runtime
  tests/mockServer/data/funcs.json
  tests/mockServer/mock.js
Labels: bug

#2564 Impl [Models endpoints monitoring, metrics] Use "Apply" button to get all selected metrics
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/elements/MetricsSelector/MetricsSelector.js
  src/elements/MetricsSelector/metricsSelector.scss
Labels: enhancement

#2565 Fix [Feature Store] Add 'space' validation into the artifact name part of the path
  src/common/TargetPath/targetPath.util.js
  src/components/FeatureSetsPanel/UrlPath.utils.js
Labels: bug

#2566 Fix [Features] Table layout issue
  src/elements/FeatureStoreTableRow/FeatureStoreTableRow.js
  src/scss/main.scss
Labels: bug

#2567 Fix [Artifacts, Functions] selected item is missing from the list of visible items
  src/components/Datasets/Datasets.js
  src/components/Files/Files.js
  src/components/FunctionsPage/Functions.js
  src/components/ModelsPage/Models/Models.js
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/hooks/useVirtualization.hook.js
  src/utils/parseArtifacts.js
Labels: bug

#2568 Fix [Jobs monitoring, scheduled] 'No jobs found.' when filtering for the 'Past 24 hours'
  src/utils/generateMonitoringData.js
Labels: bug

#2570 Fix [Artifacts, Functions] selected item is missing from the list of visible items
  src/hooks/useVirtualization.hook.js
Labels: bug

#2569 UI ci orkor
  ui_ci.groovy
Labels: enhancement, tests

#2571 Fix [Model Endpoints] previous project data shown after request cancellation
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
Labels: bug

#2572 Fix [Features] Remove ‘Targets’ column from Features table
  src/utils/createFeatureStoreContent.js
Labels: bug

#2574 Fix [UI] Requests aren't send when project was changed
  src/components/FilterMenu/FilterMenu.js
Labels: bug

#2573 Fix [Feature store] features request not cancelled on FV creation
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorView.js
  src/components/FeatureStore/Features/Features.js
  src/components/FeatureStore/Features/features.util.js
Labels: bug

#2577 Fix [UI] bad behavior during automatic refresh in project "General" settings page
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
Labels: bug

#2578 Fix [Create Vector] UI partial load
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorView.js
Labels: bug

#2579 Fix [Artifacts|Datasets|Models] Load artifact issues
  src/utils/artifacts.util.js
Labels: bug

#2580 Fix [ML Functions] Actions "Run", "Edit", "View YAML" don't work
  src/components/FunctionsPage/Functions.js
Labels: bug

#2583 Fix [Model endpoints] multiple duplicates of items during scroll
  src/utils/getUniqueIdentifier.js
Labels: bug

#2584 Tests [UI] Add mock for download with allowed prefixes on Artifacts/Datasets/Models
  tests/mockServer/data/artifacts.json
  tests/mockServer/data/artifacts/html_mock_data.html
  tests/mockServer/data/artifacts/image_mock_data.png
  tests/mockServer/data/artifacts/json_mock_data.json
  tests/mockServer/data/artifacts/text_mock_data.txt
  tests/mockServer/data/artifacts/yaml_mock_data.yaml
  tests/mockServer/mock.js
Labels: tests

#2585 Fix [Artifacts] expended rows not collapsing when switching projects
  src/components/Datasets/Datasets.js
  src/components/Files/Files.js
  src/components/FunctionsPage/Functions.js
  src/components/ModelsPage/Models/Models.js
Labels: bug

#2587 Fix [Feature vectors] incorrect marking of label column
  src/components/DetailsRequestedFeatures/DetailsRequestedFeaturesView.js
Labels: bug

#2588 Fix [Models Endpoints Monitoring, Metrics] clear search results when switching model endpoints
  src/elements/MetricsSelector/MetricsSelector.js
Labels: bug

#2589 Fix [Functions] Add mock for GET `functions` request
  src/components/FunctionsPage/functions.util.js
  tests/mockServer/mock.js
Labels: bug

#2552 Fix [Metrics] UI metrics UX fix
  src/actions/details.js
  src/actions/modelEndpoints.js
  src/api/artifacts-api.js
  src/api/details-api.js
  src/api/modelEndpoints-api.js
  src/common/ActionsMenu/ActionsMenu.js
  src/common/TabsSlider/tabsSlider.scss
  src/components/Details/Details.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/Details/details.scss
  src/components/DetailsMetrics/DetailsMetrics.js
  src/components/DetailsMetrics/DetailsMetrics.scss
  src/components/DetailsMetrics/IncvocationMetricCard.js
  src/components/FeatureStore/FeatureStore.js
  src/components/FunctionsPage/functions.util.js
  src/components/Jobs/Jobs.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ProjectsJobsMonitoring/projectsJobsMonitoring.scss
  src/elements/MetricsSelector/metricsSelector.scss
  src/reducers/artifactsReducer.js
  src/scss/main.scss
Labels: bug

#2591 Fix [Models Endpoints Monitoring, Metrics] metrics are deselected after click on Apply button
  src/elements/MetricsSelector/MetricsSelector.js
Labels: bug

#2592 Fix [Models Endpoints Monitoring, Metrics] displaying single value as a point on Invocation and Metric graph
  src/components/MetricChart/MetricChart.js
Labels: bug

#2593 Fix [Functions/Feature Sets panel] Labels are not validated properly
  src/actions/featureStore.js
  src/actions/functions.js
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitle.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelView.js
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/constants.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneral.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js
  src/reducers/featureStoreReducer.js
  src/reducers/functionReducer.js
  tests/mockServer/data/frontendSpec.json
Labels: bug

#2595 Impl [UI] Delete single artifact data
  src/components/Datasets/datasets.util.js
  src/elements/DeleteArtifactPopUp/DeleteArtifactPopUp.js
  src/utils/notifications.util.js
  tests/mockServer/mock.js
Labels: enhancement

#2596 Fix [Workflows, cross-projects] Project name doesn't specify for Batch re-run
  src/elements/WorkflowsTable/WorkflowsTable.js
Labels: bug

#2581 Fix [Models Endpoints Monitoring, Metrics] add the date to the tooltips in addition to the value
  src/components/DetailsMetrics/DetailsMetrics.js
  src/components/DetailsMetrics/DetailsMetrics.scss
  src/components/DetailsMetrics/IncvocationMetricCard.js
  src/components/DetailsMetrics/detailsMetrics.util.js
  src/components/MetricChart/metricChart.util.js
  tests/mockServer/data/metrics.json
  tests/mockServer/mock.js
Labels: bug

#2594 Fix [Models endpoints monitoring, metrics] The scroll is disappeared when collapsed the Endpoint call count
  src/components/DetailsMetrics/DetailsMetrics.js
  src/components/DetailsMetrics/DetailsMetrics.scss
  src/components/DetailsMetrics/IncvocationMetricCard.js
  src/components/DetailsMetrics/detailsMetrics.util.js
Labels: bug

#2598 Impl [Models endpoints monitoring, metrics] Use "Clear" button to unselect all metrics
  src/elements/MetricsSelector/MetricsSelector.js
  src/elements/MetricsSelector/metricsSelector.scss
Labels: enhancement

#2599 Fix [MM Endpoints] Updates - clarify view and support 1.7 data
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsInfo/detailsInfo.util.js
  src/utils/createArtifactsContent.js
Labels: bug

#2600 Fix [Projects] Cannot scroll while data is fetched
  src/components/ProjectsPage/ProjectsView.js
  src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
Labels: bug

#2601 Fix [Models Endpoints Monitoring, Metrics] Percentage change calculation for Invocation graph
  package.json
  src/components/DetailsMetrics/DetailsMetrics.scss
  src/components/DetailsMetrics/IncvocationMetricCard.js
  src/components/DetailsMetrics/detailsMetrics.util.js
Labels: bug

#2597 Fix [Project Monitoring] change general status indicator title
  src/components/ProjectsPage/ProjectsMonitoring/ProjectsMonitoring.js
  src/elements/ProjectsMonitoringCounters/JobsCounters.js
  src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
  src/utils/generateMonitoringData.js
Labels: bug

#2603 Fix [Models endpoints monitoring, metrics] The "Choose metrics to view endpoint’s data" empty card is missing when the metrics are unselected
  src/components/DetailsMetrics/DetailsMetrics.js
  src/components/DetailsMetrics/DetailsMetrics.scss
Labels: bug

#2604 Fix [Jobs, cross-project] Incorrect multiple status filter number
  src/utils/generateMonitoringData.js
Labels: bug

#2605 Fix [Feature vectors] 403 Forbidden error on PUT /feature-vectors/{name}/references/{reference}
  src/components/FeatureStore/featureStore.util.js
Labels: bug

#2606 Impl [Models Endpoints Monitoring, Metrics] Change X-Axis Label to Display Bin Range
  src/components/DetailsMetrics/DetailsMetrics.js
  src/components/DetailsMetrics/detailsMetrics.util.js
  src/components/MetricChart/metricChart.util.js
  src/elements/MetricsSelector/MetricsSelector.js
Labels: bug, enhancement

#2607 Impl [Artifacts] Delete artifact without a tag
  src/api/artifacts-api.js
  src/components/Datasets/datasets.util.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/models.util.js
  src/elements/DeleteArtifactPopUp/DeleteArtifactPopUp.js
  src/reducers/artifactsReducer.js
  src/utils/getUniqueIdentifier.js
  src/utils/handleDeleteArtifact.js
  tests/mockServer/data/artifacts.json
  tests/mockServer/mock.js
Labels: enhancement

#2608 Fix [Cross Project - Internal Job view] Wrong Filter By Type list
  src/components/FilterMenu/filterMenu.settings.js
Labels: bug

#2609 Fix [Models endpoints monitoring, metrics] increase the distance between metric histogram and line chart
  src/components/DetailsMetrics/DetailsMetrics.js
  src/components/DetailsMetrics/DetailsMetrics.scss
  src/components/DetailsMetrics/IncvocationMetricCard.js
Labels: bug

#2610 Fix [Batch Run, Function wizard] Number input for CPU is malfunctioning
  src/elements/FormResourcesUnits/formResourcesUnits.util.js
  src/utils/panelResources.util.js
Labels: bug

#2611 Fix [Artifacts] The 'Retry' deletion request does not include 'deletion_strategy' data
  src/utils/handleDeleteArtifact.js
Labels: bug

#2612 Fix [Feature Store] "Discard changes" does not enable the "Save" and "Save and ingest" buttons
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/components/FunctionsPanel/FunctionsPanel.js
Labels: bug

#2613 Fix [Models endpoints monitoring, metrics] Y-Axis Labels Absent in Expanded Invocation Graph
  src/utils/getMetricChartConfig.js
Labels: bug

#2616 Fix [Models endpoints monitoring, metrics] metric histogram chart does not display 100% of values
  src/components/DetailsMetrics/DetailsMetrics.js
Labels: bug

#2615 Fix [Feature vectors] features version tags aren't changed when changing the project
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorView.js
Labels: bug

#2617 Fix [Feature Vectors] Unify the conditions for the 'Tag' field
  package.json
  src/components/JobWizard/JobWizard.js
  src/components/Project/ProjectOverview/ProjectOverview.util.js
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
  src/components/ProjectsPage/Projects.js
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
  src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
  src/elements/DeployModelPopUp/DeployModelPopUp.js
  src/elements/RegisterModelModal/RegisterModelModal.js
Labels: bug

#2619 Fix [UI] Copy URI on model screen not working
  src/utils/copyToClipboard.js
Labels: bug

#2620 Fix [UI] update `Dockerfile` base image
  Dockerfile
Labels: bug

#2622 Fix [Models endpoints monitoring, metrics] metrics selector freezes when changing pages
  src/App.js
  src/common/Loader/LoaderForSuspenseFallback.js
Labels: bug

#2623 Impl [Functions] Add `Date` and `Show untagged` filters
  src/api/functions-api.js
  src/common/NameFilter/NameFilter.js
  src/components/ActionBar/ActionBar.js
  src/components/Datasets/datasets.util.js
  src/components/Files/files.util.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FilterMenuModal/FilterMenuModal.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsFilters.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/FunctionsPage/functions.util.js
  src/components/ModelsPage/Models/models.util.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ScheduledMonitoring/ScheduledMonitoring.js
  src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoring.js
  src/constants.js
  src/elements/ContentMenu/contentMenu.scss
  src/reducers/filtersReducer.js
  src/types.js
  src/utils/datePicker.util.js
  src/utils/generateMonitoringData.js
  src/utils/getNoDataMessage.js
  tests/mockServer/mock.js
Labels: enhancement

#2626 Fix [Workflows, cross-project] Add a loader to the workflow requests
  src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoring.js
  src/elements/WorkflowsTable/WorkflowsTable.js
Labels: bug

#2628 Fix [Jobs, Workflows - cross project] Filter by 'Status' options should always be set
  src/common/StatusFilter/StatusFilter.js
  src/components/FilterMenu/filterMenu.settings.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoringFilters.js
  src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoringFilters.js
  src/components/ProjectsJobsMonitoring/projectsJobsMotinoring.util.js
  src/constants.js
  src/types.js
Labels: bug

#2629 Fix [Models] The loader is absent when clicking on the "Deploy' button in the table view
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/reducers/artifactsReducer.js
Labels: bug

#2630 Fix [UI] Incorrect job execution list for jobs when `jobname1` is part of `jobname2`
  src/actions/jobs.js
Labels: bug

#2631 Fix [UI] App runtime - clicking on code entry point does not return the response
  src/elements/DetailsInfoItem/DetailsInfoItem.js
Labels: bug

#2627 Tests [QA] v1.7.0-rc32
  package.json
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/support/world.js
  tests/mockServer/data/artifacts.json
  tests/mockServer/data/frontendSpec.json
  tests/mockServer/dateSynchronization.js
  tests/mockServer/mock.js
Labels: tests

#2633 Fix [Artifacts] filtering models by name doesn't work
  src/components/Datasets/Datasets.js
  src/components/Files/Files.js
  src/components/ModelsPage/Models/Models.js
  src/hooks/artifacts.hook.js
Labels: bug
