Repository mlrun/ui, pull requests merged in 2024-03, with the labels that each got.

#2313 Fix [Monitor Workflows] Change title on Batch re-run wizard
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
Labels: bug

#2315 Fix [Project Settings] Validation on parameter - trailing white spaces
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
Labels: bug

#2316 Fix [Artifacts] refine UI text for Register Artifact
  src/utils/createArtifact.util.js
Labels: bug

#2317 Fix [Quick link] Error message on menu open
  src/components/Datasets/datasets.util.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/models.util.js
Labels: bug

#2319 Fix [Model Endpoint] Set empty version value when endpoint_type is router
  src/utils/createArtifactsContent.js
Labels: bug

#2320 Fix [Job] missing preview for dataset provided with a tag
  src/components/DetailsInputs/DetailsInputs.js
Labels: bug

#2321 Fix [Artifacts] requests are not canceled when changing pages
  src/httpClient.js
Labels: bug

#2324 Fix [Jobs] Change "Aborted" job status color
  src/scss/main.scss
Labels: bug

#2325 Fix [Features] Incorrect cells in expanded table rows
  src/components/FeatureStore/Features/Features.js
Labels: bug

#2326 Fix [Project settings] project owner changes to the last user in the list instead of the selected user
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
Labels: bug

#2328 Fix [UI] add the 'data-testid' for model table cells
  src/components/Table/TableHead.js
  src/elements/TableCell/TableCell.js
  src/elements/TableLinkCell/TableLinkCell.js
  src/elements/TableProducerCell/TableProducerCell.js
  src/elements/TableTypeCell/TableTypeCell.js
  src/utils/createArtifactsContent.js
  src/utils/generateTableRowTestId.js
Labels: bug

#2332 Fix [Project Settings] "Invite New Members" does not return full list of users `1.6.x`
  src/elements/MembersPopUp/MembersPopUp.js
Labels: bug

#2331 Fix [Project Settings] "Invite New Members" does not return full list of users
  src/elements/MembersPopUp/MembersPopUp.js
Labels: bug

#2334 Impl [Tests] QA Sprint 161 done
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common-tools/common-tools.js
  tests/features/common-tools/utils.js
  tests/features/common/actions/input-group.action.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/ml-functions.po.js
  tests/features/common/page-objects/project-settings.po.js
  tests/features/datasets.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectMonitoring.feature
  tests/features/projectSettings.feature
  tests/features/projectsPage.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/projects.json
  tests/mockServer/data/secretKeys.json
  tests/mockServer/mock.js
Labels: tests

#2330 Fix [FormChipCell] issues with labels
  src/common/ActionsMenu/ActionsMenu.js
  src/common/DatePicker/DatePicker.js
  src/common/DatePicker/DatePickerView.js
Labels: bug

#2314 Impl [Feature Vectors] add a labels column in Feature Vector creation
  src/utils/createFeatureStoreContent.js
Labels: bug

#2336 Fix [Model endpoints] UI crash upon navigating to model endpoints tab
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
Labels: bug

#2339 Fix [Artifacts] refine UI text for Register Artifact
  src/utils/createArtifact.util.js
Labels: bug

#2338 Fix [UI] Filters row broken in small resolutions
  src/common/TabsSlider/tabsSlider.scss
  src/elements/ContentMenu/contentMenu.scss
  src/scss/main.scss
Labels: bug

#2341 Fix [Artifacts] Not all artifacts are being displayed
  src/hooks/useVirtualization.hook.js
Labels: bug

#2347 Fix [UI] Workflows execution are listed from old to new `1.6.x`
  src/api/workflow-api.js
Labels: bug

#2343 Fix [Project settings] 'Members' tab not shown for groups with admin privileges `1.6.x`
  src/components/ProjectSettings/projectSettings.util.js
  src/constants.js
Labels: bug

#2346 Fix [UI] Workflows execution are listed from old to new
  src/api/workflow-api.js
Labels: bug

#2344 Fix [Project settings] 'Members' tab not shown for groups with admin privileges
  src/components/ProjectSettings/projectSettings.util.js
  src/constants.js
Labels: bug

#2348 Fix [ML Functions] Command column should be renamed
  src/components/FunctionsPage/functions.util.js
  src/utils/createFunctionsContent.js
Labels: bug

#2342 Fix [Feature Vectors] Provide validation rules on labels
  src/elements/CreateFeatureVectorPopUp/CreateFeatureVectorPopUp.js
  src/elements/CreateFeatureVectorPopUp/createFeatureVectorPopUp.scss
Labels: bug

#2352 Impl [Cross projects Jobs] Add counters per tab
  package.json
  src/App.js
  src/actions/projects.js
  src/common/StatsCard/StatsCard.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoringJobs/ProjectsJobsMonitoringJobs.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoringScheduled/ProjectsJobsMonitoringScheduled.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoringWorkflows/ProjectsJobsMonitoringWorkflows.js
  src/components/ProjectsJobsMonitoring/projectsJobsMonitoring.scss
  src/components/ProjectsJobsMonitoring/projectsJobsMotinoring.util.js
  src/constants.js
  src/elements/JobsMonitoringStatsCard/JobsMonitoringStatsCard.js
  src/elements/JobsMonitoringStatsCard/jobsMonitoringStatsCard.scss
  src/elements/ProjectsMonitoringCounters/JobsCounters.js
  src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
  src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
  src/hooks/useFetchData.hook.js
  src/reducers/projectReducer.js
  src/utils/generateMonitoringData.js
Labels: enhancement

#2361 Impl [UI Model Monitoring Per Project] Add 3 new tabs
  src/components/Details/DetailsTabsContent/DetailsTabsContent.js
  src/components/DetailsApplication/DetailsApplications.js
  src/components/DetailsEventList/DetailsEventsList.js
  src/components/DetailsMetrics/DetailsMetrics.js
  src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
  src/constants.js
Labels: enhancement

#2351 Fix [Project settings] project owner changes to the last user in the list instead of the selected user `1.6.x`
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
Labels: bug

#2354 Fix [Project settings] 'Members' tab not shown for groups with admin privileges `1.6.2`
  src/components/ProjectSettings/projectSettings.util.js
  src/constants.js
Labels: bug

#2355 Fix [Project settings] project owner changes to the last user in the list instead of the selected user `1.6.2`
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
Labels: bug

#2356 Fix [Project settings] no redirection after changing project owner `1.6.2`
  src/components/ProjectSettings/ProjectSettings.js
Labels: bug

#2357 Fix [Project Settings] "Invite New Members" does not return full list of users `1.6.2`
  src/elements/MembersPopUp/MembersPopUp.js
Labels: bug

#2360 Fix [Project settings] Group with 'Project security admin' policy cannot see members tab of projects
  src/components/ProjectSettings/ProjectSettings.js
  src/components/ProjectSettings/projectSettings.util.js
Labels: bug

#2362 Fix [Project settings] Group with 'Project security admin' policy cannot see members tab of projects `1.6.x`
  src/components/ProjectSettings/ProjectSettings.js
  src/components/ProjectSettings/projectSettings.util.js
Labels: bug

#2363 Fix [Project settings] no redirection after changing project owner `1.6.x`
  src/components/ProjectSettings/ProjectSettings.js
Labels: bug

#2359 Fix [Project settings] Group with 'Project security admin' policy cannot see members tab of projects `1.6.2`
  src/components/ProjectSettings/ProjectSettings.js
  src/components/ProjectSettings/projectSettings.util.js
Labels: bug

#2365 Fix [Project settings] Unable to change myself from 'admin' role in project `1.6.x`
  src/components/ProjectSettings/ProjectSettings.js
  src/elements/MembersPopUp/MembersPopUp.js
  src/elements/MembersPopUp/membersReducer.js
  src/elements/ProjectSettingsMembers/ProjectSettingsMembers.js
Labels: bug
