Repository mlrun/ui, pull requests merged in 2025-01, with the labels that each got.

#2990 Fix [UI] Artifacts Fail showing html files when stored as "s3" `1.7.x`
  src/common/Download/DownloadItem.js
  src/utils/getArtifactPreview.js
Labels: bug

#2985 Fix [Alerts history] Trigger criteria time period format not correct - Month instead Minute
  src/components/DetailsInfo/detailsInfo.util.js
  src/utils/createAlertsContent.js
Labels: bug

#2986 Fix [Pagination] Current page shouldn't be clickable
  src/common/Pagination/Pagination.js
Labels: bug

#2987 Fix [Alerts history] "Failed to retrieve data " when click on Job ID from Alert page
  src/components/Details/details.util.js
Labels: bug

#2988 Fix [Alerts history] logs popup header should not scroll
  src/components/DetailsDrillDownAlert/AlertLogsModal.js
  src/elements/AlertsTableRow/AlertsTableRow.scss
Labels: bug

#2989 Fix [Alerts history] remove "Entity Type" column in per project view
  src/components/DetailsDrillDownAlert/AlertLogPopup.js
  src/utils/createAlertsContent.js
Labels: bug

#2991 Fix [Function] Revert and fix for empty Batch run on function run
  src/components/FunctionsPage/functions.util.js
  src/components/JobWizard/JobWizard.js
  src/reducers/jobReducer.js
Labels: bug

#2992 Tests [Documents] Failed request on mock
  tests/mockServer/mock.js
Labels: tests

#2995 Fix [Job Artifacts] artifacts tab fails to load for workflow job
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/JobWizard/JobWizard.js
  src/components/Jobs/Jobs.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoring.js
  src/elements/JobsTable/JobsTable.js
  src/elements/WorkflowsTable/WorkflowsTable.js
  src/reducers/jobReducer.js
Labels: bug

#2994 Fix [Functions, Artifacts, Jobs] Unexpected redirection
  src/common/Pagination/Pagination.js
  src/components/Datasets/DatasetsView.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/Documents/DocumentsView.js
  src/components/Files/FilesView.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/Workflow/Workflow.js
  src/elements/JobsTable/JobsTable.js
  src/utils/jobs.util.js
  src/utils/link-helper.util.js
Labels: bug

#2996 Fix [UI] add "Documents" support to data input path
  src/common/TargetPath/targetPath.util.js
  src/components/FeatureSetsPanel/UrlPath.utils.js
  src/utils/panelPathScheme.js
Labels: bug

#2998 Fix [Job Artifacts] artifacts tab fails to load for workflow job
  src/components/DetailsArtifacts/DetailsArtifacts.js
Labels: bug

#2999 Fix [Jobs] Use `labels` filter for job type
  src/hooks/useJobsPageData.js
  src/reducers/jobReducer.js
Labels: bug

#3001 Fix [Documents] GET ../artifact-tags request is not being made upon navigating to documents tab
  src/components/Documents/Documents.js
  src/reducers/filtersReducer.js
Labels: bug

#3003 Fix [Functions, Artifacts, Jobs] Unexpected redirection
  src/common/Pagination/Pagination.js
  src/components/Datasets/DatasetsView.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/Documents/DocumentsView.js
  src/components/Files/FilesView.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/Workflow/Workflow.js
  src/elements/JobsTable/JobsTable.js
  src/utils/jobs.util.js
  src/utils/link-helper.util.js
Labels: bug

#3007 Fix [Artifacts] Add `best iteration` checkbox to filters
  src/components/ArtifactsActionBar/ArtifactsFilters.js
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/Datasets/datasets.util.js
  src/components/Documents/Documents.js
  src/components/Documents/DocumentsView.js
  src/components/Documents/documents.util.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/Models/models.util.js
Labels: bug

#2993 Impl [Model endpoints] Add user messages and information relating to sampling rate
  src/common/TabsSlider/tabsSlider.scss
  src/components/Details/details.util.js
  src/components/DetailsMetrics/DetailsMetrics.js
  src/components/DetailsMetrics/DetailsMetrics.scss
  src/components/DetailsMetrics/InvocationsMetricCard.js
  src/components/DetailsMetrics/NoMetricData.js
  src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.js
  tests/features/common-tools/common-consts.js
  tests/mockServer/data/modelEndpoints.json
Labels: enhancement

#2997 Fix [Documents] Adjust columns width
  src/elements/BreadcrumbsDropdown/breadcrumbsDropdown.scss
  src/utils/createArtifactsContent.js
Labels: bug

#3002 Fix [UI] Move analyses tabs to Demo mode in `1.8.0`
  src/components/Datasets/Datasets.js
  src/components/Datasets/datasets.util.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureSets/featureSets.util.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
  src/components/FeatureStore/FeatureVectors/featureVectors.util.js
Labels: bug

#3004 Fix [Alerts history] filtering by project name doesn't work
  src/common/Download/DownloadItem.js
  src/components/Alerts/Alerts.js
  src/components/Alerts/AlertsFilters.js
  src/components/Alerts/alerts.util.js
  src/components/DetailsAlerts/DetailsAlerts.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoringFilters.js
  src/components/Table/table.scss
  src/constants.js
  src/hooks/useAlertsPageData.js
  src/utils/getNoDataMessage.js
Labels: bug

#3005 Fix [Project Settings, Projects] The second 'confirm message' is missing when deleting a non-empty project
  src/api/projects-api.js
  src/components/ProjectSettings/ProjectSettings.js
  src/components/ProjectsPage/ProjectsView.js
  src/components/ProjectsPage/projects.util.js
Labels: bug

#3006 Fix [Documents] 'Model was updated successfully' appears upon updating document labels
  src/components/Documents/documents.util.js
Labels: bug

#3009 Fix [Job Artifacts] same artifact opens for all artifacts on Show Details click
  src/components/DetailsArtifacts/detailsArtifacts.util.js
  src/elements/DetailsPopUp/ArtifactPopUp/ArtifactPopUp.js
Labels: bug

#3010 Fix [Alerts] Pagination Error Due to Failed API Response
  src/hooks/useAlertsPageData.js
Labels: bug

#3011 Fix [Alerts] The alert details pane doesn't close when navigating through pagination
  src/components/Alerts/AlertsView.js
  src/constants.js
  src/utils/link-helper.util.js
Labels: bug

#3016 Fix [Job Artifacts] UI crash on attempt to download artifact
  src/common/CopyToClipboard/CopyToClipboard.js
  src/common/Download/Download.js
Labels: bug

#3017 Fix [Alerts History] details header width
  src/components/DetailsInfo/detailsInfo.scss
Labels: bug

#3019 Fix [UI] data-ellipsis isn't working in details view
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  tests/mockServer/mock.js
Labels: bug

#3020 Fix [Details popup] doesn't close on back navigation
  src/common/BlockerSpy/BlockerSpy.js
  src/common/YamlModal/YamlModal.js
  src/components/Details/Details.js
  src/elements/DetailsPopUp/DetailsPopUp.js
Labels: bug

#3021 Fix [Batch run] UI crash when use the Batch run button
  src/reducers/jobReducer.js
Labels: bug

#3013 Fix [Pagination] No redirection to the first BE page
  src/components/Datasets/Datasets.js
  src/components/Datasets/datasets.util.js
  src/components/Documents/Documents.js
  src/components/Documents/documents.util.js
  src/components/Files/Files.js
  src/components/Files/files.util.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functions.util.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/models.util.js
  src/elements/JobsTable/JobsTable.js
  src/hooks/usePagination.hook.js
  src/utils/jobs.util.js
Labels: bug

#3015 Fix [Schedule job] missing job status
  src/elements/JobsTableRow/JobsTableRow.js
  src/elements/TableCell/TableCell.js
Labels: bug

#3022 Fix [Alerts history] Alerts notifications icons need tooltip
  src/utils/createAlertsContent.js
Labels: bug

#3014 Fix [Cross-project] The request for Jobs monitoring is missing in the breadcrumbs menu
  src/elements/BreadcrumbsDropdown/BreadcrumbsDropdown.js
  src/elements/BreadcrumbsDropdown/breadcrumbsDropdown.scss
Labels: bug

#2880 Impl [Notifications] Add abilities to notification
  src/common/Download/DownloadContainer.js
  src/common/Download/downloadContainer.scss
  src/common/Notifications/Notification.js
  src/common/Notifications/notification.scss
  src/common/Notifications/notifications.scss
  src/hooks/useTimeout.js
  src/scss/main.scss
Labels: enhancement

#3024 Fix [Jobs] remove redundant 'Project:' filter label
  src/utils/getNoDataMessage.js
Labels: bug

#3025 Fix [Monitor Jobs] filter by time reset when navigating between pages
  src/components/Jobs/Jobs.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/ScheduledJobs/ScheduledJobs.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ScheduledMonitoring/ScheduledMonitoring.js
  src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoring.js
Labels: bug

#3028 Fix [Feature Store] Setting filters does not close the details panel
  src/components/ActionBar/ActionBar.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorView.js
  src/components/Alerts/AlertsView.js
  src/components/Datasets/DatasetsView.js
  src/components/Documents/DocumentsView.js
  src/components/FeatureStore/FeatureSets/FeatureSetsView.js
  src/components/FeatureStore/FeatureVectors/FeatureVectorsView.js
  src/components/FeatureStore/Features/FeaturesView.js
  src/components/Files/FilesView.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/Jobs/Jobs.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/elements/JobsTable/JobsTable.js
Labels: bug

#3032 Fix [Artifacts] trying to preview deleted dataset causes UI error
  src/components/Datasets/datasets.util.js
  src/components/Documents/documents.util.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/models.util.js
Labels: bug

#3033 Fix [Artifacts] Uncaught runtime error for artifact source path
  src/components/ArtifactInfoSources/ArtifactInfoSources.js
  src/components/ArtifactInfoSources/artifactInfoSources.scss
Labels: bug

#3037 Fix [Alerts History] details header width
  src/components/DetailsInfo/detailsInfo.scss
  src/components/DetailsInfo/detailsInfo.util.js
Labels: bug

#3038 Fix [Alerts history] Event type title not clear for system/model performance
  src/components/Alerts/AlertsFilters.js
  src/components/Alerts/alerts.util.js
Labels: bug

#3030 Fix [Add to feature vector] The Project dropdown closes the Filter by pop-up
  package.json
  src/components/AddToFeatureVectorPage/AddToFeatureVectorFilters.js
Labels: bug

#3039 Impl [Project monitoring] Change list to 7 days
  src/components/Project/project.scss
  src/elements/ProjectDataCard/ProjectDataCard.js
  src/elements/ProjectJobs/ProjectJobs.js
Labels: enhancement

#3034 Fix [Project monitoring] Jobs and workflows section height
  src/components/Project/ProjectMonitorView.js
  src/scss/main.scss
Labels: bug

#3044 Impl [Alerts history] Add alerts to navigation
  src/App.js
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/components/Alerts/AlertsView.js
  src/components/DetailsDrillDownAlert/DetailsAlertsMetrics.js
  src/components/DetailsInfo/detailsInfo.scss
  src/constants.js
  src/elements/AlertsTableRow/AlertsTableRow.scss
  src/hooks/useAlertsPageData.js
  src/layout/Navbar/Navbar.js
  src/utils/createAlertsContent.js
  src/utils/generateAlertsStats.js
Labels: enhancement

#3042 Fix [Artifacts] add partition-by if Tag filter is set to "all"
  src/common/HistoryBackLink/historyBackLink.scss
  src/components/Datasets/Datasets.js
  src/components/Documents/Documents.js
  src/components/Files/Files.js
  src/components/ModelsPage/Models/Models.js
Labels: bug

#3043 Fix [Batch run] The 'Clear' option doesn't reset the category list filter
  src/components/FilterMenuModal/FilterMenuModal.js
  src/components/FilterMenuModal/HubCategoriesFilter/HubCategoriesFilter.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
Labels: bug

#3041 Fix [Projects] 'Archive' button is not clickable
  src/components/ProjectsPage/Projects.js
Labels: bug

#3046 Fix [Jobs] Use backend next run time filter
  src/hooks/useJobsPageData.js
  src/reducers/jobReducer.js
  tests/mockServer/mock.js
Labels: bug

#3035 Fix [UI] loading spinner is stuck upon deleting non empty project
  src/components/Project/project.scss
  src/components/ProjectsPage/projects.util.js
Labels: bug

#3047 Impl [Pagination] Opening an object through a URL should show the object, even if it is not on the paginated list
  package.json
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/Datasets/datasets.util.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/Details/details.scss
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/Documents/Documents.js
  src/components/Documents/DocumentsView.js
  src/components/Documents/documents.util.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/Files/files.util.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/FunctionsPage/functions.util.js
  src/components/Jobs/Jobs.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/Models/models.util.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/components/Table/TableView.js
  src/elements/FunctionsTableRow/FunctionsTableRow.js
  src/elements/JobsTable/JobsTable.js
  src/hooks/useJobsPageData.js
  src/reducers/artifactsReducer.js
  src/utils/artifacts.util.js
  src/utils/createArtifactsContent.js
  src/utils/createFunctionsRowData.js
  src/utils/generateMessage.util.js
  src/utils/jobs.util.js
Labels: enhancement

#3048 Fix [UI] 'All' projects option id conflicts with project name
  src/components/Alerts/alerts.util.js
  src/components/FilterMenu/filterMenu.settings.js
  src/constants.js
  src/hooks/useAlertsPageData.js
  src/utils/getNoDataMessage.js
Labels: bug

#3050 Fix [Jobs] Main list fails to refresh after run deletion
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/Datasets/datasets.util.js
  src/components/Documents/Documents.js
  src/components/Documents/DocumentsView.js
  src/components/Documents/documents.util.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/Files/files.util.js
  src/components/Jobs/Jobs.js
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/Jobs/MonitorJobs/monitorJobs.util.js
  src/components/Jobs/jobs.util.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/Models/models.util.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/elements/DeleteArtifactPopUp/DeleteArtifactPopUp.js
  src/elements/JobsTable/JobsTable.js
  src/elements/WorkflowsTable/WorkflowsTable.js
  src/hooks/useJobsPageData.js
  src/hooks/useRefreshAfterDelete.hook.js
  src/utils/handleDeleteArtifact.js
Labels: bug

#3052 Fix [Jobs and Workflows, Jobs Monitoring] The 'Auto Refresh' issues
  src/components/ActionBar/ActionBar.js
  src/components/Jobs/Jobs.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/reducers/filtersReducer.js
Labels: bug

#3049 Fix [Labels] Missing labels in artifacts / feature sets popups
  src/components/Details/Details.js
  src/components/Details/DetailsTabsContent/DetailsTabsContent.js
  src/components/Details/details.util.js
  src/components/DetailsDrillDownAlert/DetailsDrillDownAlert.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
Labels: bug

#3055 Impl [Alerts history] Opening an alert through a URL should show the object, even if it is not on the paginated list
  src/api/alerts-api.js
  src/components/Alerts/Alerts.js
  src/components/Alerts/AlertsView.js
  src/components/Alerts/alerts.util.js
  src/hooks/useAlertsPageData.js
  src/reducers/alertsReducer.js
Labels: enhancement

#3053 Fix [Feature sets] add default sorting by `updated`
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/utils/createFeatureStoreContent.js
Labels: bug

#3058 Fix [Feature store] row expansion request should consider all applied filters
  src/actions/featureStore.js
  src/api/featureStore-api.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
  src/components/FeatureStore/Features/Features.js
Labels: bug

#3059 Fix [Create vector] tags request should be send when changing project
  src/components/AddToFeatureVectorPage/AddToFeatureVectorFilters.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorView.js
Labels: bug

#3061 Fix [UI] notification is too big and goes off the screen
  src/common/Notifications/Notification.js
  src/common/Notifications/notification.scss
  src/common/Notifications/notifications.scss
Labels: bug

#3062 Fix [UI] "Failed to retrieve model data" on attempt to click on "Show details" of run artifact
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/detailsInfo.util.js
  src/elements/DetailsPopUp/ArtifactPopUp/ArtifactPopUp.js
Labels: bug

#3060 Fix [UI] Change all green buttons to blue
  package.json
  src/common/DatePicker/DatePickerView.js
  src/common/EditorModal/EditorModalView.js
  src/components/Datasets/DatasetsView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelView.js
  src/components/FeatureSetsPanel/ScheduleFeatureSet/ScheduleFeatureSetView.js
  src/components/FeatureStore/FeatureSets/FeatureSetsView.js
  src/components/FeatureStore/FeatureVectors/FeatureVectorsView.js
  src/components/FeatureStore/Features/FeaturesView.js
  src/components/Files/FilesView.js
  src/components/FilterMenuModal/FilterMenuModal.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizardSteps/JobWizardRunDetails/JobWizardRunDetails.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/Project/ProjectOverview/ProjectOverview.util.js
  src/components/Project/project.scss
  src/components/Project/project.utils.js
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
  src/components/ProjectsPage/ProjectsView.js
  src/components/RegisterArtifactModal/RegisterArtifactModal.js
  src/components/ScheduleJob/ScheduleJobView.js
  src/components/SheduleWizard/ScheduleWizard.js
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
  src/elements/ChangeOwnerPopUp/ChangeOwnerPopUp.js
  src/elements/DeployModelPopUp/DeployModelPopUp.js
  src/elements/MembersPopUp/MembersPopUp.js
  src/elements/MetricsSelector/MetricsSelector.js
  src/elements/NewFunctionPopUp/NewFunctionPopUp.js
  src/elements/RegisterModelModal/RegisterModelModal.js
  src/utils/defaultCloseModalHandler.js
Labels: bug

#3064 Fix [Model Endpoints] Selected element doesn't highlighted
  src/elements/ArtifactsTableRow/ArtifactsTableRow.js
  src/utils/getUniqueIdentifier.js
Labels: bug

#3065 Fix [Workflows] Missing Artifacts for Workflow Run in Artifact Tab
  src/components/DetailsArtifacts/DetailsArtifacts.js
Labels: bug

#3066 Fix [Scheduled Jobs] Wrong hash and tag displayed on detail function pane
  src/elements/DetailsPopUp/FunctionPopUp/FunctionPopUp.js
Labels: bug
