Repository mlrun/ui, pull requests merged in 2025-07, with the labels that each got.

#3316 Fix [Project monitoring] Consumer Group button leads to home page
  src/elements/ProjectFunctions/ProjectFunctions.jsx
Labels: bug

#3321 Fix [Batch run] hyper switch discards user input
  src/elements/FormParametersTable/FormParametersRow/FormParametersRow.jsx
Labels: bug

#3327 Fix [Artifacts] Filter data is reset in edit artifact mode
  src/components/ActionBar/ActionBar.jsx
  src/components/FilterMenuModal/FilterMenuModal.jsx
Labels: bug

#3328 Impl [Applications metrics] update "Model endpoints with detections" chart according to the new requirements
  src/common/MlChart/MlChart.jsx
  src/components/MonitoringApplicationsPage/MonitoringApplications/MEPsWithDetections.jsx
  src/components/MonitoringApplicationsPage/MonitoringApplications/monitoringApplications.util.js
  src/components/MonitoringApplicationsPage/MonitoringApplicationsPage.util.jsx
  src/components/MonitoringApplicationsPage/monitoringApplicationsPage.scss
  src/reducers/monitoringApplicationsReducer.js
  src/utils/getChartConfig.jsx
Labels: enhancement

#3329 Fix [UI] Incorrect behavior when adding a tag with a tag name that already exists in another object in the same project
  src/components/Datasets/datasets.util.jsx
  src/components/Details/details.util.js
  src/components/Files/files.util.jsx
  src/components/ModelsPage/Models/models.util.jsx
  src/components/RegisterArtifactModal/RegisterArtifactModal.jsx
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.jsx
  src/elements/RegisterModelModal/RegisterModelModal.jsx
  src/reducers/detailsReducer.js
  src/scss/main.scss
  src/utils/artifacts.util.js
  src/utils/createArtifact.util.js
Labels: bug

#3323 Impl [UI] Remove "Quick Action" page
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/components/Project/ProjectMonitor.jsx
  src/constants.js
  src/layout/Navbar/navbar.util.jsx
Labels: enhancement, Cleanup

#3322 Impl [Project monitoring] Alignment of UI for design consistency
  src/components/Project/project.scss
  src/elements/ProjectDataCard/ProjectDataCard.jsx
  src/elements/ProjectFunctions/ProjectFunctions.jsx
  src/elements/ProjectJobs/ProjectJobs.jsx
  src/elements/ProjectJobs/projectJobs.utils.js
  src/elements/ProjectStatistics/ProjectStatistics.jsx
  src/elements/ProjectStatistics/projectStatistics.scss
  src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.jsx
Labels: enhancement

#3320 Tests [Terminate] Add mock for terminate functionality
  tests/mockServer/mock.js
Labels: tests

#3332 Fix [LLM prompts] Application error on Arguments tab
  src/api/artifacts-api.js
  src/components/Details/DetailsPromptTemplate/ArgumentsTab.jsx
  src/components/Details/DetailsPromptTemplate/PromptTab.jsx
Labels: bug

#3333 Impl [Projects] Counter box alignment
  src/common/ProjectDetailsHeader/ProjectDetailsHeader.jsx
  src/components/FilterMenu/filterMenu.settings.js
  src/components/Project/project.utils.jsx
  src/components/ProjectsPage/ProjectsMonitoring/ProjectsMonitoring.jsx
  src/components/ProjectsPage/ProjectsMonitoring/projectsMonitoring.scss
  src/components/ProjectsPage/projects.util.jsx
  src/elements/ProjectJobs/projectJobs.utils.js
  src/elements/ProjectStatistics/ProjectStatistics.jsx
  src/elements/ProjectsMonitoringCounters/ApplicationCounters.jsx
  src/elements/ProjectsMonitoringCounters/ArtifactsCounters.jsx
  src/elements/ProjectsMonitoringCounters/RunsCounters.jsx
  src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.jsx
  src/elements/ProjectsMonitoringCounters/WorkflowsCounters.jsx
  src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
  src/utils/generateMonitoringData.js
Labels: enhancement

#3335 Tests [Mock] Add mock for owner component
  tests/mockServer/data/iguazioProjects.json
  tests/mockServer/data/iguazioSelf.json
  tests/mockServer/data/iguazioUserRelations.json
  tests/mockServer/data/projects.json
Labels: tests

#3336 Tests [QA] v1.10.0-rc8
  package.json
  tests/features/MLFunction.feature
  tests/features/alertsMonitoring.feature
  tests/features/artifacts.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/dropdown.action.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/monitoring-app.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/datasets.feature
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/jobsMonitoring.feature
  tests/features/monitoringApp.feature
  tests/features/projectMonitoring.feature
  tests/features/projectsPage.feature
  tests/features/quickActions.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
Labels: tests

#3339 Fix [Counters] data-testid for running / failed runs counter
  src/elements/ProjectsMonitoringCounters/ArtifactsCounters.jsx
  src/elements/ProjectsMonitoringCounters/JobsCounters.jsx
  src/elements/ProjectsMonitoringCounters/RunsCounters.jsx
  src/elements/ProjectsMonitoringCounters/WorkflowsCounters.jsx
Labels: bug

#3341 Fix [Workflows] Retry option should not be available during "In Process" states
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.jsx
Labels: bug

#3342 Impl [LLM Prompt Artifact] Change UI view for Prompt template
  src/common/ExpandableText/ExpandableText.jsx
  src/common/ExpandableText/expandableText.scss
  src/common/SearchNavigator/SearchNavigator.jsx
  src/common/SearchNavigator/searchNavigator.util.jsx
  src/components/Details/DetailsGenerationConfiguration/DetailsGenerationConfiguration.jsx
  src/components/Details/DetailsGenerationConfiguration/detailsGenerationConfiguration.scss
  src/components/Details/DetailsPromptTemplate/ArgumentsTab.jsx
  src/components/Details/DetailsPromptTemplate/PromptTab.jsx
  src/components/Details/DetailsPromptTemplate/detailsPromptTemplate.scss
  src/layout/Navbar/navbar.util.jsx
Labels: enhancement

#3344 Fix [Workflows] Revise text of "Terminating" notification
  src/components/Workflow/workflow.util.js
Labels: bug

#3345 Fix [Projects] Incorrect counter data on project cards for N/A projects
  src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.jsx
Labels: bug

#3346 Fix [Counters] runs and workflows counters are missing stats__counter class
  src/elements/ProjectsMonitoringCounters/ApplicationCounters.jsx
  src/elements/ProjectsMonitoringCounters/ArtifactsCounters.jsx
  src/utils/generateMonitoringData.js
Labels: bug

#3349 Impl [LLM prompts] llm-prompt MEP will link to the llm-prompt artifact and not to the model artifact
  src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.jsx
Labels: enhancement

#3350 Fix [LLM Prompt Artifact] Broken view of content when typing search
  src/components/Details/DetailsPromptTemplate/detailsPromptTemplate.scss
Labels: bug

#3348 Fix [Projects, Monitoring container, Cross projects] Change text on project card info
  src/elements/ProjectsMonitoringCounters/AlertsCounters.jsx
  src/elements/ProjectsMonitoringCounters/RunsCounters.jsx
  src/elements/ProjectsMonitoringCounters/WorkflowsCounters.jsx
Labels: bug

#3353 Tests [Counters] Add mock for project monitoring counters
  tests/mockServer/data/summary.json
Labels: tests

#3356 Fix [Terminate wf] The terminate workflow option is not available for Project user with admin and editor permissions
  src/api/projects-iguazio-api.js
  src/components/Workflow/workflow.util.js
Labels: bug
