Repository mlrun/ui, pull requests merged in 2025-06, with the labels that each got.

#3276 Fix [Scheduled] Unexpected application error when editing a scheduled job
  src/components/JobWizard/JobWizard.jsx
  src/hooks/useJobsPageData.js
Labels: bug

#3277 Fix [Projects, Jobs] Unexpected redirection to the Projects page when clicking on tabs
  src/elements/ContentMenu/ContentMenu.jsx
  src/elements/ContentMenu/contentMenu.scss
Labels: bug

#3279 Impl [Monitoring application] Add Model endpoints with detection chart
  src/common/MlChart/MetricChart/MetricChart.jsx
  src/components/DetailsMetrics/MetricsCards/InvocationsMetricCard.jsx
  src/components/MonitoringApplicationsPage/MonitoringApplications/MEPsWithDetections.jsx
  src/components/MonitoringApplicationsPage/MonitoringApplications/MonitoringApplications.jsx
  src/components/MonitoringApplicationsPage/MonitoringApplications/monitoringApplications.util.js
  src/components/MonitoringApplicationsPage/monitoringApplicationsPage.scss
  src/utils/getChartConfig.jsx
Labels: enhancement

#3280 Impl [Monitoring application] Add Model Endpoints metrics
  src/App.jsx
  src/common/HistoryBackLink/historyBackLink.jsx
  src/common/MlChart/HistogramChart/HistogramChart.jsx
  src/common/MlChart/MlChart.jsx
  src/common/MlChart/mlChart.scss
  src/components/ApplicationMetrics/ApplicationMetrics.jsx
  src/components/ApplicationMetrics/ApplicationMetrics.scss
  src/components/DetailsMetrics/DetailsMetrics.jsx
  src/components/DetailsMetrics/DetailsMetrics.scss
  src/components/DetailsMetrics/detailsMetrics.util.jsx
  src/components/MonitoringApplicationsPage/MonitoringApplications/MonitoringApplications.jsx
  src/components/MonitoringApplicationsPage/MonitoringApplicationsPage.jsx
  src/elements/MetricsSelector/MetricsSelector.jsx
  src/elements/MetricsSelector/metricsSelector.scss
  src/reducers/detailsReducer.js
  tests/mockServer/data/metrics.json
Labels: enhancement

#3285 Impl [Workflows] Add "Terminate" Button to Monitor Workflow – Main and Details
  package.json
  src/api/workflow-api.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.jsx
  src/components/Workflow/Workflow.jsx
  src/components/Workflow/workflow.scss
  src/components/Workflow/workflow.util.js
  src/elements/WorkflowsTable/WorkflowsTable.jsx
  src/reducers/projectReducer.js
  src/scss/main.scss
Labels: enhancement

#3291 Mock [UI] Update mock
  tests/mockServer/data/artifacts.json
  tests/mockServer/mock.js
Labels: tests

#3293 Fix [Jobs] console error of prop type
  src/elements/JobsTable/JobsTable.jsx
Labels: bug

#3292 Fix [Artifacts] Artifacts without a tag are not being filtered as expected
  src/api/artifacts-api.js
  tests/mockServer/mock.js
Labels: bug

#3289 Fix [Feature store] pages crash after creating feature set / vector with specific name
  src/components/FunctionsPageOld/FunctionsOld.jsx
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.jsx
  src/elements/ProjectJobs/projectJobs.utils.js
  src/utils/getUniqueIdentifier.js
  tests/mockServer/mock.js
Labels: bug

#3295 Tests [QA] v1.10.0-rc4
  tests/features/common-tools/common-consts.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/llm-prompts.po.js
  tests/features/common/page-objects/monitoring-app.po.js
  tests/features/llmPrompts.feature
  tests/features/monitoringApp.feature
  tests/features/projectMonitoring.feature
  tests/features/projectsPage.feature
Labels: tests

#3278 Fix [ML functions] Uncaught Runtime Error when loading ML functions with large data set
  src/components/FunctionsPageOld/FunctionsOld.jsx
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.jsx
  src/reducers/functionReducer.js
Labels: bug

#3300 Impl [Workflows] Add test IDs for Terminate button
  src/components/Workflow/Workflow.jsx
Labels: enhancement

#3301 Impl [Project monitoring] Update Statistic section in Per-project page
  src/elements/ProjectDataCard/ProjectDataCard.jsx
  src/elements/ProjectFunctions/ProjectFunctions.jsx
  src/elements/ProjectJobs/ProjectJobs.jsx
  src/elements/ProjectJobs/projectJobs.utils.js
  src/elements/ProjectStatistics/ProjectStatistics.jsx
  src/elements/ProjectStatistics/projectStatistics.scss
  src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.jsx
Labels: enhancement

#3305 Fix [Jobs, Projects] Confirmation messages don't appear on pages other than Jobs
  src/components/ProjectsPage/Projects.jsx
Labels: bug

#3304 Fix [Artifacts, Functions] closing details tab for specific item triggers incorrect page redirect
  src/common/Pagination/Pagination.jsx
  src/components/ActionBar/ActionBar.jsx
  src/components/Artifacts/Artifacts.jsx
  src/components/Artifacts/ArtifactsTable.jsx
  src/components/FunctionsPage/FunctionsView.jsx
  src/utils/link-helper.util.js
Labels: bug

#3303 Fix [ProjectStatisticsCounter] Numbers Should not overflow the circle
  src/elements/ProjectCard/projectCard.scss
  src/elements/ProjectStatisticsCounter/ProjectStatisticsCounter.jsx
Labels: bug

#3288 Fix [Documents] Error occurs on enter Documents page
  src/components/Documents/Documents.jsx
Labels: bug

#3312 Impl [UI] Jobs/Runs display retry
  src/components/Details/details.util.js
  src/components/Jobs/jobs.util.js
  src/utils/createJobsContent.js
  src/utils/parseJob.js
  tests/mockServer/data/run.json
  tests/mockServer/data/runs.json
Labels: enhancement

#3310 Fix [Monitoring app] UI alignment and text updates for Figma consistency
  src/components/MonitoringApplicationsPage/MonitoringApplications/MonitoringApplicationCounters/MonitoringApplicationCard/MonitoringApplicationCard.jsx
  src/components/MonitoringApplicationsPage/MonitoringApplications/MonitoringApplicationCounters/monitoringApplicationCounters.scss
  src/components/MonitoringApplicationsPage/MonitoringApplications/MonitoringApplicationCounters/monitoringApplicationCounters.util.jsx
  src/components/MonitoringApplicationsPage/MonitoringApplications/MonitoringApplications.jsx
  src/components/MonitoringApplicationsPage/MonitoringApplications/monitoringApplications.util.js
Labels: bug

#3311 Fix [Artifacts] Add a confirmation pop-up
  src/components/Details/DetailsHeader/DetailsHeader.jsx
Labels: bug

#3314 Impl [Workflows] Add mock for retry functionality
  src/components/Details/details.util.js
  tests/mockServer/mock.js
Labels: enhancement, tests

#3315 Fix [Project settings] Project secrets are not displayed
  src/reducers/projectReducer.js
Labels: bug
