Repository mlrun/ui, pull requests merged in 2025-03, with the labels that each got.

#3150 Fix [Artifacts] 404 on get artifact after deleting all versions
  src/components/Datasets/Datasets.js
  src/components/Datasets/datasets.util.js
  src/components/Documents/Documents.js
  src/components/Documents/documents.util.js
  src/components/Files/Files.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/models.util.js
  src/hooks/useRefreshAfterDelete.hook.js
  src/utils/handleDeleteArtifact.js
Labels: bug

#3153 Fix [Batch Run] Filtering is impacted after redirection following batch run start
  src/components/JobWizard/JobWizard.js
  src/elements/JobsTable/JobsTable.js
  src/hooks/useFiltersFromSearchParams.hook.js
Labels: bug

#3154 Tests [QA] v1.8.0-rc33
  tests/features/alerts.feature
  tests/features/alertsMonitoring.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/page-objects/commonPagesHeader.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/project.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/projectMonitoring.feature
  tests/features/step-definitions/steps.js
Labels: tests

#3155 Fix [Artifacts] Enhance clarity of messages after overwriting
  src/utils/artifacts.util.js
Labels: bug

#3158 Fix [Artifacts] "Failed to fetch artifacts" appears in 'Batch run' -> 'Data inputs'
  src/api/artifacts-api.js
Labels: bug

#3159 Fix [Artifacts] Unexpected full view popup opening
  src/utils/link-helper.util.js
Labels: bug

#3160 Fix [Batch Run] Filtering is impacted after redirection following batch run start
  src/elements/JobsTable/JobsTable.js
  src/hooks/useFiltersFromSearchParams.hook.js
  src/hooks/useJobsPageData.js
Labels: bug

#3161 Fix [Feature sets] add sorting by updated date to expanded rows
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/utils/datetime.js
  src/utils/parseFeatures.js
Labels: bug

#3162 Fix [Feature vectors] align version tag with other filter fields
  src/common/FormTagFilter/formTagFilters.scss
Labels: bug

#3163 Fix [Jobs Monitoring] Filters reset to default values
  src/hooks/useJobsPageData.js
Labels: bug

#3156 Fix [Model monitoring] collapsed metrics graphs
  src/components/DetailsDrillDownAlert/DetailsAlertsMetrics.js
  src/components/DetailsMetrics/DetailsMetrics.js
  src/components/DetailsMetrics/DetailsMetrics.scss
Labels: bug

#3165 Fix [Artifacts] update "Deleting artifact failed" message when deleting artifact by "Viewer" user
  src/reducers/artifactsReducer.js
Labels: bug

#3166 Fix [Job inputs] incorrect category used for get artifacts request
  src/components/DetailsInputs/DetailsInputs.js
Labels: bug

#3168 Fix [UI] model endpoint displayed with ":" and "latest" tag if not generated through serving func
  src/components/Details/details.util.js
  src/utils/createArtifactsContent.js
Labels: bug

#3169 Fix [Project settings] Shifted tabs elements
  src/elements/ContentMenu/ContentMenu.js
Labels: bug

#3172 Fix [UI] hide 'Owner' in Project monitoring and quick-actions screens on CE
  src/common/ProjectDetailsHeader/ProjectDetailsHeader.js
Labels: bug

#3174 Fix [Models] On UI deploy model, deploy fails for function with custom tag
  src/api/artifacts-api.js
  src/api/functions-api.js
Labels: bug

#3175 Fix [CE] do not show "v3io" as legit path on CE
  src/common/TargetPath/targetPath.util.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/featureSetsPanelTargetStore.util.js
  src/components/FeatureSetsPanel/UrlPath.utils.js
  src/elements/FormVolumesTable/FormVolumesTable.js
  src/elements/FormVolumesTable/formVolumesTable.util.js
  src/elements/VolumesTable/VolumesTable.js
  src/elements/VolumesTable/volumesTable.util.js
  src/reducers/featureStoreReducer.js
Labels: bug

#3176 Fix [Jobs and Workflows, Jobs Monitoring] The 'Auto Refresh' issues
  src/components/ActionBar/ActionBar.js
  src/components/Jobs/Jobs.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/elements/JobsTable/JobsTable.js
  src/hooks/useJobsPageData.js
  src/hooks/usePagination.hook.js
Labels: bug

#3180 Fix [Alerts] The 'alert-activations' request is missing
  src/components/Details/DetailsTabsContent/DetailsTabsContent.js
Labels: bug

#3124 Fix [Artifacts] Add a confirmation pop-up
  src/components/ActionBar/ActionBar.js
  src/components/Datasets/datasets.util.js
  src/components/Details/Details.js
  src/components/Details/details.util.js
  src/components/Documents/documents.util.js
  src/components/FeatureStore/FeatureVectors/featureVectors.util.js
  src/components/Files/files.util.js
  src/components/ModelsPage/Models/models.util.js
  src/elements/ActionMenuItem/ActionsMenuItem.js
Labels: bug

#3151 Fix [Settings] Error occurs on refresh setting page
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
Labels: bug

#3173 Fix [Projects Alerts] Severity tab text should use ellipsis on small screens
  src/utils/createAlertsContent.js
Labels: bug

#3179 Fix [Project Settings] Unknown error on entering project settings
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
Labels: bug

#3181 Impl [Tabs] Use page tabs in details view
  src/common/TabsSlider/TabsSlider.js
  src/common/TabsSlider/tabsSlider.scss
  src/elements/ContentMenu/ContentMenu.js
  src/elements/ContentMenu/contentMenu.scss
  src/scss/main.scss
Labels: Cleanup

#3183 Fix [Alerts] Projects all option appears in no data message
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoringFilters.js
  src/components/ProjectsJobsMonitoring/ProjectsJobsMonitoring.js
  src/components/ProjectsJobsMonitoring/ScheduledMonitoring/ScheduledMonitoringFilters.js
  src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoring.js
  src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoringFilters.js
  src/hooks/useJobsPageData.js
  src/reducers/workflowReducer.js
  src/utils/getNoDataMessage.js
  src/utils/jobs.util.js
Labels: bug

#3184 Fix [UI] Icons width changes on small screen resolution
  src/elements/ProjectsMonitoringCounters/AlertsCounters.js
  src/elements/ProjectsMonitoringCounters/JobsCounters.js
  src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
  src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
  src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
Labels: bug

#3152 Fix [UI] fix "findDOMNode is deprecated" error across the app
  package.json
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStoreView.js
  src/elements/PartitionFields/PartitionFields.js
Labels: bug
