Repository mlrun/ui, pull requests merged in 2025-09, with the labels that each got.

#3400 Fix [Artifacts] Selected artifact shifts out of view after opening detail pane
  package.json
  src/components/Alerts/Alerts.jsx
  src/components/Artifacts/Artifacts.jsx
  src/components/FunctionsPage/Functions.jsx
  src/elements/JobsTable/JobsTable.jsx
Labels: bug

#3412 Fix [Monitoring app] Preselected metrics issues
  src/components/ApplicationMetrics/ApplicationMetrics.jsx
  src/components/DetailsMetrics/DetailsMetrics.scss
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.jsx
  src/reducers/detailsReducer.js
  tests/mockServer/data/metrics.json
  tests/mockServer/data/modelEndpoints.json
  tests/mockServer/mock.js
Labels: bug

#3414 Fix [ESLint] Add `import/named` rule, fix eslint warnings
  eslint.config.mjs
  package.json
  src/common/MlChart/MlChart.jsx
  src/components/RegisterArtifactModal/RegisterArtifactModal.jsx
  src/elements/DetailsPopUp/ArtifactPopUp/ArtifactPopUp.jsx
  src/elements/RegisterModelModal/RegisterModelModal.jsx
Labels: bug, dependencies

#3409 Fix [Counters] UI crash - TypeError: Cannot read properties of undefined (reading 'endpoint_alerts_count')
  src/components/ProjectsPage/projects.util.jsx
  src/elements/ProjectCard/projectCard.util.js
  src/elements/ProjectJobs/projectJobs.utils.js
  src/elements/ProjectsMonitoringCounters/AlertsCounters.jsx
Labels: bug

#3415 Fix [Projects Monitoring] Titles formatting and filtering defaults
  src/utils/generateMonitoringData.js
Labels: bug

#3418 Fix [Download] Issues with the download container
  src/common/Download/DownloadContainer.jsx
  src/common/Download/downloadContainer.scss
Labels: bug

#3419 Fix [Counters] Add info icon to cross-project and project-screen
  src/elements/PageHeader/pageHeader.scss
Labels: bug

#3428 Fix [CE] UI crash in monitoring-app screen
  src/utils/createApplicationContent.jsx
Labels: bug

#3432 Fix [Alerts] Multiple issues on Alerts tab in Model Endpoints page
  src/components/Alerts/alerts.util.js
  src/components/DetailsAlerts/DetailsAlerts.jsx
  src/components/ModelsPage/ModelEndpoints/modelEndpoints.util.jsx
  src/elements/AlertsTable/alertsTable.scss
Labels: bug

#3433 Fix [Monitoring app] Application view starts in middle of page after drill-down
  src/components/MonitoringApplicationsPage/MonitoringApplicationsPage.jsx
Labels: bug

#3434 Fix [LLM prompt ] Failure message not clear when try to add exist tag to prompt artifact
  src/components/LLMPrompts/llmPrompts.util.jsx
  src/constants.js
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.jsx
  src/utils/artifacts.util.js
  src/utils/createArtifact.util.js
Labels: bug

#3436 Fix [Monitoring app] Change MEP with detections request
  src/api/monitoringApplications-api.js
Labels: bug

#3438 Fix [Artifacts] Download notification not interactable
  src/common/Download/DownloadItem.jsx
  src/common/Download/downloadContainer.scss
Labels: bug

#3440 Tests [QA] v1.10.0-rc27
  package.json
  tests/features/common-tools/common-consts.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/monitoring-app.po.js
  tests/features/common/page-objects/project.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/jobsMonitoring.feature
  tests/features/models.feature
  tests/features/monitoringApp.feature
  tests/features/projectMonitoring.feature
  tests/features/projectsPage.feature
  tests/mockServer/data/run.json
  tests/mockServer/data/runs.json
Labels: tests

#3445 Fix [UI] Adjust 'Monitoring app' css
  src/components/ApplicationMetrics/ApplicationMetrics.scss
  src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
Labels: bug

#3449 Fix [Model endpoints] Update mock for model endpoint filtering by mode
  tests/mockServer/data/modelEndpoints.json
  tests/mockServer/mock.js
Labels: bug

#3451 Fix [Scheduled job] Missing loader on deletion
  src/elements/ScheduledJobsTable/ScheduledJobsTable.jsx
  src/reducers/jobReducer.js
Labels: bug
