Repository mlrun/ui, pull requests merged in 2025-02, with the labels that each got.

#3070 Fix [Feature store, Models] Label editing action issues
  src/components/Details/Details.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/Table/Table.js
  src/constants.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/elements/DetailsInfoItemChip/DetailsInfoItemChip.js
  src/elements/DetailsPopUp/ArtifactPopUp/ArtifactPopUp.js
  src/reducers/appReducer.js
Labels: bug

#3069 Tests [UI] QA v1.8.0-rc26
  package.json
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/common.action.js
  tests/features/common/page-objects.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/pipelines.json
  tests/mockServer/data/piplineIDs.json
  tests/mockServer/mock.js
Labels: tests

#3073 Fix [UI] Page navigation blocked by Notification pop-up
  src/common/Notifications/notifications.scss
Labels: bug

#3075 Fix [Workflows] Once the button is pressed, the UI should disable the button for 5 seconds, and then re-query the workflow status
  src/elements/WorkflowsTable/WorkflowsTable.js
Labels: bug

#3074 Fix [Feature Store] Feature Sets panel component warning
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
Labels: bug

#3067 Impl [Alerts history] Alerts counter - background color when no alerts
  src/elements/ProjectsMonitoringCounters/AlertsCounters.js
  src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
Labels: enhancement

#3078 Fix [Alerts] The Event type filter doesn't align with the Entity type option
  src/components/Alerts/AlertsFilters.js
Labels: bug

#3080 Fix [Artifacts] Uncaught runtime error for artifact source path
  src/common/CopyToClipboard/CopyToClipboard.js
  src/components/DetailsInfo/detailsInfo.util.js
Labels: bug

#3077 Fix [Jobs] Table row render issue
  src/common/Chip/Chip.js
Labels: bug

#3072 Fix [UI] small css changes
  src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.scss
  src/components/DetailsMetrics/DetailsMetrics.scss
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
  src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
Labels: bug

#3083 Fix [Features] Failed to open feature set
  src/components/Details/details.util.js
Labels: bug

#3084 Impl [Model Endpoints Alerts Tab] Remove Filters and Pagination Component
  src/components/Alerts/AlertsView.js
  src/components/Alerts/alerts.scss
  src/components/Alerts/alerts.util.js
  src/components/DetailsAlerts/DetailsAlerts.js
  src/components/DetailsInfo/detailsInfo.scss
  src/constants.js
  src/hooks/useAlertsPageData.js
  src/reducers/alertsReducer.js
Labels: enhancement

#3081 Fix [Project Monitoring] Missing notification for "last 7 days" if no jobs are displayed
  src/elements/ProjectDataCard/ProjectDataCard.js
Labels: bug

#3079 Fix [UI] Sometimes Default Node Selector isn't present on The Project Setting screen
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
Labels: bug

#3088 Fix [Wizard] batch run - back/next buttons does not look like "button"
  package.json
Labels: bug

#3086 Tests [QA] v1.8.0-rc31
  tests/features/MLFunction.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/table.action.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/ml-functions.po.js
  tests/features/common/page-objects/side-panel.po.js
  tests/features/featureStore.feature
  tests/features/step-definitions/steps.js
  tests/features/step-definitions/table.steps.js
  tests/mockServer/data/featureSets.json
  tests/mockServer/mock.js
Labels: tests

#3085 Fix [UI] "All changes will be lost" pop up appears upon artifact register / job schedule
  src/components/Details/Details.js
Labels: bug

#3089 Fix [Feature vector] No redirection expected after creation
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
Labels: bug

#3090 Fix [Functions] wrong message after creating new function
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPanel/FunctionsPanel.js
Labels: bug

#3092 Fix [Artifacts] 404 on get artifact after deleting the tag
  src/components/Datasets/Datasets.js
  src/components/Documents/Documents.js
  src/components/Files/Files.js
  src/components/ModelsPage/Models/Models.js
  src/hooks/useRefreshAfterDelete.hook.js
Labels: bug

#3093 Fix [Pagination] shifted "Showing ... " indicator at the bottom of a list
  src/common/Pagination/pagination.scss
Labels: bug

#3094 Tests [UI] Update mock to align links view
  tests/mockServer/data/artifacts.json
  tests/mockServer/data/funcs.json
  tests/mockServer/data/modelEndpoints.json
  tests/mockServer/data/nuclioFunctions.json
  tests/mockServer/data/run.json
  tests/mockServer/data/runs.json
Labels: tests

#3087 Fix [Alerts] The Event type filter doesn't align with the Entity type option
  src/components/Alerts/AlertsFilters.js
Labels: bug

#3068 Infra [Docker] update build base image to `20-alpine`
  Dockerfile
Labels: Infrastructure

#3082 Infra [Feature store] Move Redux to RTK
  src/actions/featureStore.js
  src/common/TargetPath/targetPath.util.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
  src/components/FeatureSetsPanel/FeatureSetsPanel.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSource.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FeatureSetsPanelDataSourceView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelDataSource/FilterParameters.js
  src/components/FeatureSetsPanel/FeatureSetsPanelSchema/FeatureSetsPanelSchema.js
  src/components/FeatureSetsPanel/FeatureSetsPanelSchema/FeatureSetsPanelSchemaView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitle.js
  src/components/FeatureSetsPanel/FeatureSetsPanelTitle/FeatureSetsPanelTitleView.js
  src/components/FeatureSetsPanel/FeatureSetsPanelView.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureSets/featureSets.util.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
  src/components/FeatureStore/FeatureVectors/featureVectors.util.js
  src/components/FeatureStore/Features/Features.js
  src/components/FeatureStore/Features/features.util.js
  src/components/FeatureStore/featureStore.util.js
  src/components/Project/ProjectMonitor.js
  src/constants.js
  src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
  src/elements/DetailsPopUp/FeatureSetPopUp/FeatureSetPopUp.js
  src/elements/FeaturesTablePanel/FeaturesTablePanel.js
  src/reducers/featureStoreReducer.js
  src/reducers/filtersReducer.js
Labels: Infrastructure

#3096 Fix [Alerts] The alert details pane doesn't close when navigating through pagination
  src/components/Alerts/AlertsView.js
Labels: bug

#3097 Fix [Alerts history] Fix Redundant Job Logs Requests on Refresh Button in ActionBar Component
  src/components/Alerts/Alerts.js
Labels: bug

#3098 Fix [Artifacts, Feature Store, Documents] Edit mode issues
  src/components/ActionBar/ActionBar.js
  src/components/ArtifactsActionBar/ArtifactsFilters.js
  src/components/Datasets/DatasetsView.js
  src/components/Details/Details.js
  src/components/Documents/DocumentsView.js
  src/components/Files/FilesView.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/Table/Table.js
  src/components/Table/TableView.js
Labels: bug

#3100 Fix [Projects Alerts] Details do not reopen after closing
  src/components/Alerts/Alerts.js
Labels: bug

#3102 Tests [UI] Update the mock to include artifacts sorting with parameters
  tests/mockServer/data/artifacts.json
  tests/mockServer/data/artifactsTags.json
  tests/mockServer/mock.js
Labels: tests

#3103 Cleanup [Model endpoints metrics] DetailsMetrics Code Optimization
  src/common/MlChart/HistogramChart/HistogramChart.js
  src/common/MlChart/HistogramChart/histogramChart.scss
  src/common/MlChart/MetricChart/MetricChart.js
  src/common/MlChart/MetricChart/metricChart.scss
  src/common/MlChart/MetricChart/metricChart.util.js
  src/common/MlChart/MlChart.js
  src/components/DetailsDrillDownAlert/DetailsAlertsMetrics.js
  src/components/DetailsFeaturesAnalysis/DetailsFeaturesAnalysis.js
  src/components/DetailsMetrics/DetailsMetrics.js
  src/components/DetailsMetrics/DetailsMetrics.scss
  src/components/DetailsMetrics/MetricsCards/ApplicationMetricCard.js
  src/components/DetailsMetrics/MetricsCards/InvocationsMetricCard.js
  src/components/DetailsMetrics/MetricsCards/NoMetricData.js
  src/components/DetailsStatistics/DetailsStatistics.js
  src/components/DetailsStatistics/DetailsStatisticsTableRow.js
  src/components/Jobs/jobs.util.js
  src/components/MetricChart/MetricChart.js
  src/components/MetricChart/metricChart.util.js
  src/components/Project/project.scss
  src/constants.js
  src/scss/main.scss
  src/utils/getChartConfig.js
  src/utils/getHistogramChartConfig.js
  src/utils/getMetricChartConfig.js
Labels: Cleanup

#3104 Fix [Model-Monitoring] UI can't access the model of the model endpoint
  src/elements/DetailsPopUp/ArtifactPopUp/ArtifactPopUp.js
  src/utils/parseUri.js
Labels: bug

#3105 Fix [Jobs and Workflows, Jobs Monitoring] The 'Auto Refresh' issues
  src/components/Jobs/MonitorJobs/MonitorJobs.js
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.js
  src/elements/JobsTable/JobsTable.js
Labels: bug

#3106 Fix [Workflows] The "Retry" button doesn't work the second time for a "completed" workflow without using 'Refresh' button
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/constants.js
Labels: bug

#3099 Fix [Alerts] The Event type filter doesn't align with the Entity type option
  src/common/TabsSlider/tabsSlider.scss
  src/components/Alerts/AlertsFilters.js
  src/components/DetailsStatistics/detailsStatistics.scss
  src/components/FunctionsPage/functions.scss
  src/elements/PreviewModal/previewModal.scss
  src/scss/main.scss
Labels: bug

#3108 Fix [Workflows] The "Retry" button doesn't work the second time for a "completed" workflow without using 'Refresh' button
  src/scss/main.scss
  src/utils/getState.js
  src/utils/parseWorkflows.js
Labels: bug

#3110 Fix [Artifacts] Enhance clarity of messages after overwriting
  src/elements/DetailsPopUp/FunctionPopUp/FunctionPopUp.js
  src/utils/artifacts.util.js
Labels: bug

#3111 Fix [Feature Sets Panel] changing default path for online target does not take effect when creating feature set
  src/components/FeatureSetsPanel/FeatureSetsPanelTargetStore/FeatureSetsPanelTargetStore.js
Labels: bug

#3113 Fix [Alerts details model endPoint] Missing redirect
  src/components/DetailsAlerts/DetailsAlerts.js
Labels: bug

#3114 Fix [Artifacts] Logging model artifact from s3 fails to show in the UI
  src/utils/getArtifactPreview.js
Labels: bug

#3116 Fix [Feature store] row expansion request should consider all applied filters
  src/api/featureStore-api.js
Labels: bug

#3119 Fix [Feature store] row expansion request should consider all applied filters
  src/api/featureStore-api.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
  src/reducers/featureStoreReducer.js
Labels: bug

#3120 Fix [Jobs Monitoring] Run detail pane request is missing
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoringFilters.js
  src/utils/jobs.util.js
Labels: bug

#3121 Fix [Alerts] The alert details pane doesn't close after filtering
  src/components/Alerts/AlertsView.js
Labels: bug

#3122 Fix [Model endpoints] Change logic to get model function according to BE changes
  src/api/functions-api.js
  src/components/Details/details.util.js
  src/elements/DetailsPopUp/FunctionPopUp/FunctionPopUp.js
  src/utils/createArtifactsContent.js
  src/utils/link-helper.util.js
Labels: bug

#3125 Fix [Functions] redirect to Projects page after click on untagged function
  src/elements/AlertsTableRow/AlertsTableRow.js
  src/elements/FunctionsTableRow/FunctionsTableRowOld.js
Labels: bug

#3123 Fix [Workflows] Change a tooltip for retry action
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
Labels: bug

#3127 Fix [Jobs and Workflows, Jobs Monitoring] The 'Auto Refresh' issues
  src/elements/JobsTable/JobsTable.js
Labels: bug

#3129 Fix [Projects settings] missing delete project button in project setting screen on CE
  src/components/ProjectSettings/ProjectSettings.js
Labels: bug

#3130 Fix [Model endpoint] incorrect function returned for request with uid
  src/components/Details/details.util.js
  src/elements/DetailsPopUp/FunctionPopUp/FunctionPopUp.js
  src/utils/createArtifactsContent.js
  src/utils/link-helper.util.js
Labels: bug

#3131 Fix [Workflows] sometimes workflows are sorted in reverse order from oldest to newest
  src/elements/WorkflowsTable/WorkflowsTable.js
Labels: bug

#3132 Fix [Job Artifacts] the same artifact is opened on changing iterations
  src/components/Details/DetailsHeader/DetailsHeader.js
Labels: bug

#3128 Fix [Artifacts] redundant actions in artifacts pop ups
  src/elements/DetailsPopUp/ArtifactPopUp/ArtifactPopUp.js
Labels: bug

#3126 Fix [Project settings] remove "Owner" in CE project settings
  src/elements/ProjectSettingsGeneral/ProjectSettingsGeneral.js
Labels: bug

#3133 Fix [Project Settings] missing delete project button in project setting screen on CE
  src/components/ProjectSettings/ProjectSettings.js
Labels: bug

#3135 Fix [UI] Deprecated endpoints for runs and jobs
  src/api/jobs-api.js
  tests/mockServer/mock.js
Labels: bug

#3136 Fix [Artifacts] Issues applying changes in Full View
  src/common/Pagination/pagination.scss
  src/components/Details/Details.js
  src/components/ModelsPage/Models/ModelsView.js
Labels: bug

#3137 Tests [UI] Add mock data for BE pagination pages
  tests/mockServer/data/projects.json
  tests/mockServer/data/summary.json
  tests/mockServer/dataGenerators.js
  tests/mockServer/mock.js
Labels: tests

#3138 Fix [UI] Applied filters are added to the navigation history
  src/components/ActionBar/ActionBar.js
Labels: bug

#3139 Fix [Artifacts] issue with artifacts order
  src/utils/filterArtifacts.js
Labels: bug

#3118 Fix [CE] link to "Real time functions" (nuclio) is broken when accessing mlrun UI via http
  src/constants.js
  src/index.js
Labels: bug

#3141 Fix [Job Artifacts] the same artifact is opened on changing iterations
  src/api/artifacts-api.js
  src/components/DetailsArtifacts/detailsArtifacts.util.js
Labels: bug

#3142 Fix [Artifacts] 'Add a tag' pop-up triggers a redundant refresh
  src/elements/AddArtifactTagPopUp/AddArtifactTagPopUp.js
  src/reducers/artifactsReducer.js
Labels: bug

#3143 Fix [Alerts history] incorrect metrics graphs positioning
  src/components/DetailsDrillDownAlert/DetailsAlertsMetrics.js
  src/components/DetailsDrillDownAlert/DetailsDrillDownAlert.js
  src/components/DetailsMetrics/DetailsMetrics.js
Labels: bug

#3144 Add [Alerts] Model endpoint redirect should filter by entity
  src/components/Alerts/AlertsFilters.js
  src/components/Alerts/AlertsView.js
  src/components/Alerts/alerts.util.js
  src/components/DetailsAlerts/DetailsAlerts.js
  src/reducers/alertsReducer.js
Labels: bug
