Repository mlrun/ui, pull requests merged in 2025-05, with the labels that each got.

#3255 Fix [Projects] 'Are you sure?' pop-up is missing
  package.json
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.jsx
  src/components/ProjectsPage/ProjectsView.jsx
Labels: bug

#3256 Fix [Projects] 'Are you sure?' pop-up is missing `1.9.x`
  package.json
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
  src/components/ProjectsPage/ProjectsView.js
Labels: bug

#3257 Fix [Projects] 'Are you sure?' pop-up is missing `1.8.x`
  package.json
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
  src/components/ProjectsPage/ProjectsView.js
Labels: bug

#3258 Fix [GitHub] Vulnerabilities after migration to Vite
  .github/workflows/build.yaml
  .github/workflows/ci.yaml
  generate-release-notes.js
  src/common/ActionsMenu/actionsMenu.scss
  src/common/Input/Input.jsx
  src/components/AddToFeatureVectorPage/AddToFeatureVectorView.jsx
  src/components/FeatureStore/FeatureVectors/FeatureVectors.jsx
  src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.jsx
  src/types.js
Labels: bug

#3260 Fix [GitHub] Vulnerabilities after migration to Vite (v2)
  .github/workflows/ci.yaml
Labels: bug

#3259 Fix [Navbar] Pin Icon and additional links position should remain fixed
  src/layout/Navbar/Navbar.jsx
  src/layout/Navbar/Navbar.scss
Labels: bug

#3261 Fix [Artifacts] click on "X" in Delete artifact? dialog does not take effect
  src/elements/DeleteArtifactPopUp/DeleteArtifactPopUp.jsx
Labels: bug

#3262 Fix [Artifacts] click on "X" in Delete artifact? dialog does not take effect `1.9.x`
  src/elements/DeleteArtifactPopUp/DeleteArtifactPopUp.js
Labels: bug

#3263 Fix [Artifacts] click on "X" in Delete artifact? dialog does not take effect `1.8.x`
  src/elements/DeleteArtifactPopUp/DeleteArtifactPopUp.js
Labels: bug

#3265 Tests [QA] v1.10.0-rc1_2
  package.json
  tests/features/MLFunction.feature
  tests/features/artifacts.feature
  tests/features/common/page-objects.js
  tests/features/common/page-objects/commonPagesHeader.po.js
  tests/features/common/page-objects/ml-functions.po.js
  tests/features/common/page-objects/monitoring-app.po.js
  tests/features/datasets.feature
  tests/features/documents.feature
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/llmPrompts.feature
  tests/features/models.feature
  tests/features/monitoringApp.feature
  tests/features/projectMonitoring.feature
  tests/features/projectSettings.feature
  tests/features/quickActions.feature
  tests/features/step-definitions/table.steps.js
Labels: tests

#3266 Impl [Vistra] Add more informative message when user trying to create a project and he does not have developer permission
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.jsx
  src/reducers/projectReducer.js
Labels: enhancement

#3267 Fix [Alerts] Request is periodically skipped
  src/components/DetailsDrillDownAlert/DetailsAlertsMetrics.jsx
Labels: bug

#3272 Impl [Project Monitoring] Move Consumer Groups to Real-Time Section
  src/components/Project/ProjectMonitor.jsx
  src/components/Project/ProjectMonitorView.jsx
  src/elements/ProjectFunctions/ProjectFunctions.jsx
Labels: enhancement

#3269 Fix [Jobs, Projects] Confirmation messages don't appear on pages other than Jobs
  src/components/Jobs/MonitorJobs/MonitorJobs.jsx
  src/components/ProjectsJobsMonitoring/JobsMonitoring/JobsMonitoring.jsx
Labels: bug

#3270 Fix [Scheduled] The project name is undefined
  src/components/Details/DetailsHeader/DetailsHeader.jsx
  src/components/Details/DetailsTabsContent/DetailsTabsContent.jsx
  src/components/DetailsPods/DetailsPods.jsx
  src/elements/DetailsPopUp/JobPopUp/JobPopUp.jsx
  src/hooks/usePods.hook.js
  src/reducers/detailsReducer.js
  tests/mockServer/data/runs.json
Labels: bug

#3271 Fix [Job] Incorrect link in the job run uid status
  src/App.jsx
  src/elements/JobsTable/JobsTable.jsx
  src/hooks/useJobsPageData.js
  src/utils/jobs.util.js
Labels: bug

#3273 Tests [QA] v1.10.0-rc2
  tests/features/MLFunction.feature
  tests/features/alertsMonitoring.feature
  tests/features/artifacts.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/dropdown.action.js
  tests/features/common/page-objects/commonPagesHeader.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/project-settings.po.js
  tests/features/common/page-objects/project.po.js
  tests/features/common/page-objects/projects.po.js
  tests/features/datasets.feature
  tests/features/documents.feature
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectMonitoring.feature
  tests/features/quickActions.feature
  tests/features/step-definitions/steps.js
  tests/mockServer/data/alerts.json
Labels: tests
