Repository mlrun/ui, pull requests merged in 2025-04, with the labels that each got.

#3185 Impl [Projects Alerts] Separate AlertView component for Projects-Alerts and Alerts-Tab
  src/components/Alerts/Alerts.js
  src/components/Alerts/AlertsView.js
  src/components/DetailsAlerts/DetailsAlerts.js
  src/elements/AlertsTable/AlertsTable.js
  src/elements/AlertsTable/alertsTable.scss
  src/elements/AlertsTableRow/AlertsTableRow.js
  src/elements/AlertsTableRow/AlertsTableRow.scss
  src/hooks/useAlertsPageData.js
  src/hooks/useRefreshAlerts.hook.js
Labels: Cleanup

#3187 Fix [Feature vectors] usage example `1.8.x`
  src/utils/generateUsageSnippets.js
Labels: bug

#3188 Fix [Feature vectors] usage example `1.9.x`
  src/utils/generateUsageSnippets.js
Labels: bug

#3190 Fix [Jobs monitoring] failed to load job artifact preview
  src/components/DetailsPreview/DetailsPreview.js
Labels: bug

#3192 Fix [Jobs monitoring] failed to load job artifact preview `1.9.x`
  src/components/DetailsPreview/DetailsPreview.js
Labels: bug

#3191 Fix [Jobs monitoring] failed to load job artifact preview `1.8.x`
  src/components/DetailsPreview/DetailsPreview.js
Labels: bug

#3189 Fix [Functions] Missing "Version tag" in the function popup screen
  src/components/Details/details.util.js
Labels: bug

#3157 Impl [Details] Move Redux to RTK
  package.json
  src/actions/details.js
  src/actions/modelEndpoints.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorPage.js
  src/components/AddToFeatureVectorPage/AddToFeatureVectorView.js
  src/components/Alerts/Alerts.js
  src/components/Datasets/Datasets.js
  src/components/Datasets/DatasetsView.js
  src/components/Details/Details.js
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/Details/DetailsTabsContent/DetailsTabsContent.js
  src/components/Details/details.util.js
  src/components/DetailsArtifacts/DetailsArtifacts.js
  src/components/DetailsDrillDownAlert/DetailsAlertsMetrics.js
  src/components/DetailsDrillDownAlert/DetailsDrillDownAlert.js
  src/components/DetailsInfo/DetailsInfo.js
  src/components/DetailsInfo/DetailsInfoView.js
  src/components/DetailsMetrics/DetailsMetrics.js
  src/components/DetailsRequestedFeatures/DetailsRequestedFeatures.js
  src/components/Documents/Documents.js
  src/components/Documents/DocumentsView.js
  src/components/FeatureStore/FeatureSets/FeatureSets.js
  src/components/FeatureStore/FeatureSets/FeatureSetsView.js
  src/components/FeatureStore/FeatureVectors/FeatureVectors.js
  src/components/FeatureStore/FeatureVectors/FeatureVectorsView.js
  src/components/FeatureStore/Features/Features.js
  src/components/FeatureStore/Features/FeaturesView.js
  src/components/Files/Files.js
  src/components/Files/FilesView.js
  src/components/FilterMenu/FilterMenu.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/FunctionsView.js
  src/components/FunctionsPageOld/FunctionsOld.js
  src/components/FunctionsPageOld/FunctionsViewOld.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/ModelsPage/ModelEndpoints/ModelEndpoints.js
  src/components/ModelsPage/Models/Models.js
  src/components/ModelsPage/Models/ModelsView.js
  src/components/ModelsPage/RealTimePipelines/RealTimePipelines.js
  src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoring.js
  src/components/Table/Table.js
  src/components/Table/TableView.js
  src/components/Workflow/Workflow.js
  src/elements/DetailsInfoItem/DetailsInfoItem.js
  src/elements/DetailsInfoItemChip/DetailsInfoItemChip.js
  src/elements/DetailsPopUp/JobPopUp/JobPopUp.js
  src/elements/JobsTable/JobsTable.js
  src/elements/ScheduledJobsTable/ScheduledJobsTable.js
  src/elements/WorkflowsTable/WorkflowsTable.js
  src/hooks/usePods.hook.js
  src/reducers/detailsReducer.js
Labels: Cleanup, Infrastructure

#3182 Impl [Functions] Move Redux to RTK
  src/actions/functions.js
  src/components/FunctionsPage/Functions.js
  src/components/FunctionsPage/functions.util.js
  src/components/FunctionsPageOld/FunctionsOld.js
  src/components/FunctionsPageOld/functionsOld.util.js
  src/components/FunctionsPanel/FunctionsPanel.js
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/components/JobWizard/JobWizard.js
  src/components/JobWizard/JobWizardSteps/JobWizardFunctionSelection/JobWizardFunctionSelection.js
  src/components/Jobs/MonitorWorkflows/MonitorWorkflows.js
  src/components/Jobs/MonitorWorkflows/monitorWorkflows.util.js
  src/components/Jobs/jobs.util.js
  src/components/ModelsPage/RealTimePipelines/realTimePipelines.util.js
  src/components/Project/ProjectMonitor.js
  src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/WorkflowsMonitoring.js
  src/components/ProjectsJobsMonitoring/WorkflowsMonitoring/workflowsMonitoring.util.js
  src/components/Workflow/Workflow.js
  src/elements/FunctionPanelTopologyModelTable/FunctionPanelTopologyModelTable.js
  src/elements/FunctionsPanelAdvanced/FunctionsPanelAdvanced.js
  src/elements/FunctionsPanelCode/FunctionsPanelCode.js
  src/elements/FunctionsPanelCode/FunctionsPanelCodeView.js
  src/elements/FunctionsPanelEnvironmentVariables/FunctionsPanelEnvironmentVariables.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneral.js
  src/elements/FunctionsPanelGeneral/FunctionsPanelGeneralView.js
  src/elements/FunctionsPanelParameters/FunctionsPanelParameters.js
  src/elements/FunctionsPanelParameters/functionsPanelParameters.util.js
  src/elements/FunctionsPanelResources/FunctionsPanelResources.js
  src/elements/FunctionsPanelSecrets/FunctionsPanelSecrets.js
  src/elements/FunctionsPanelTopology/FunctionsPanelTopology.js
  src/elements/NewFunctionPopUp/NewFunctionPopUp.js
  src/elements/PanelCredentialsAccessKey/PanelCredentialsAccessKey.js
  src/elements/ScheduledJobsTable/ScheduledJobsTable.js
  src/elements/WorkflowsTable/WorkflowsTable.js
  src/reducers/functionReducer.js
  src/utils/getFunctionLogs.js
Labels: Cleanup, Infrastructure

#3202 Fix [Project settings] The Delete project button is not clickable `1.8.x`
  src/components/ProjectSettings/ProjectSettings.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/projects.util.js
Labels: bug

#3203 Fix [Project settings] The Delete project button is not clickable `1.9.x`
  src/components/ProjectSettings/ProjectSettings.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/projects.util.js
Labels: bug

#3204 Fix [Project settings] The Delete project button is not clickable
  src/components/ProjectSettings/ProjectSettings.js
  src/components/ProjectsPage/Projects.js
  src/components/ProjectsPage/projects.util.js
Labels: bug

#3200 Fix [Batch run] unexpected application error when searching functions `1.8.x`
  src/common/Search/Search.js
  src/utils/string.js
Labels: bug

#3193 Fix [Mock] No db_key, uid, tag in artifact details
  src/common/TabsSlider/TabsSlider.js
  tests/mockServer/data/run.json
  tests/mockServer/data/runs.json
Labels: bug

#3194 Fix [Mock] No db_key, uid, tag in artifact details
  src/common/TabsSlider/TabsSlider.js
  tests/mockServer/data/run.json
  tests/mockServer/data/runs.json
Labels: bug

#3196 Fix [Preview popup] Wrong table header
  src/elements/PreviewModal/PreviewModal.js
Labels: bug

#3205 Fix [ML functions] "This function either does not exist or was deleted" notification after applying filter
  src/components/FunctionsPageOld/FunctionsOld.js
Labels: bug

#3206 Fix [ML functions] "This function either does not exist or was deleted" notification after applying filter `1.8.x`
  src/components/FunctionsPageOld/FunctionsOld.js
Labels: bug

#3208 Fix [Alerts] Metrics data does not displayed
  src/components/DetailsDrillDownAlert/DetailsAlertsMetrics.js
Labels: bug

#3198 Fix [Details] continuous movement of the header when reducing the screen size
  src/components/Details/DetailsHeader/DetailsHeader.js
  src/components/Details/details.scss
Labels: bug

#3216 Bump axios from `1.7.4` to `1.8.2` in the npm_and_yarn group across 1 directory `1.8.x`
  package.json
Labels: dependencies

#3217 Bump axios from `1.7.4` to `1.8.2` in the npm_and_yarn group across 1 directory `1.9.x`
  package.json
Labels: dependencies

#3221 Fix [UI] function remains in UI after it was deleted `1.8.x`
  src/components/FunctionsPageOld/FunctionsOld.js
Labels: bug

#3222 Fix [UI] function remains in UI after it was deleted `1.9.x`
  src/components/FunctionsPageOld/FunctionsOld.js
Labels: bug

#3224 QA v1.10.0
  tests/features/artifacts.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/actions/tab-selector.action.js
  tests/features/common/page-objects/commonPagesHeader.po.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/common/page-objects/interactive-popup.po.js
  tests/features/common/page-objects/jobs-and-workflows.po.js
  tests/features/common/page-objects/models.po.js
  tests/features/featureStore.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/projectsPage.feature
  tests/mockServer/data/alerts.json
  tests/mockServer/data/artifacts.json
  tests/mockServer/data/metrics.json
  tests/mockServer/mock.js
Labels: tests

#3219 Fix [Projects] render issues
  src/elements/ContentMenu/ContentMenu.js
  src/elements/ProjectsMonitoringCounters/AlertsCounters.js
  src/elements/ProjectsMonitoringCounters/JobsCounters.js
  src/elements/ProjectsMonitoringCounters/ScheduledJobsCounters.js
  src/elements/ProjectsMonitoringCounters/WorkflowsCounters.js
  src/elements/ProjectsMonitoringCounters/projectsMonitoringCounters.scss
  src/reducers/functionReducer.js
  src/scss/main.scss
Labels: bug

#3220 Fix [Feature store] Checkbox is not clickable
  src/elements/PanelCredentialsAccessKey/PanelCredentialsAccessKey.js
Labels: bug

#3225 Fix [Model endpoints] render issue with histogram on the Features analysis tab
  src/common/MlChart/MlChart.js
  src/components/DetailsFeaturesAnalysis/DetailsFeaturesAnalysis.js
  src/components/DetailsFeaturesAnalysis/detailsFeaturesAnalysis.scss
Labels: bug

#3218 Fix [Monitor Workflows] Wrong broken link redirection
  src/common/Breadcrumbs/Breadcrumbs.js
  src/layout/Page/Page.js
  src/utils/link-helper.util.js
Labels: bug

#3227 Fix [ML functions] "This function either does not exist or was deleted" notification after applying filter
  src/components/FunctionsPageOld/FunctionsOld.js
Labels: bug

#3228 Fix [ML functions] "This function either does not exist or was deleted" notification after applying filter `1.9.x`
  src/components/FunctionsPageOld/FunctionsOld.js
Labels: bug

#3229 Fix [ML functions] "This function either does not exist or was deleted" notification after applying filter `1.8.x`
  src/components/FunctionsPageOld/FunctionsOld.js
Labels: bug

#3215 Fix [Action bar] request is sent despite "name' filter is invalid
  src/common/NameFilter/NameFilter.js
Labels: bug

#3211 Impl [Nuclio store] Move Redux to RTK
  src/actions/nuclio.js
  src/common/Notifications/notification.scss
  src/components/ConsumerGroup/ConsumerGroup.js
  src/components/ConsumerGroupsWrapper/ConsumerGroupsWrapper.js
  src/components/DetailsLogs/DetailsLogs.js
  src/components/DetailsPods/DetailsPods.js
  src/components/Project/ProjectMonitor.js
  src/components/ProjectsPage/Projects.js
  src/constants.js
  src/elements/AddToFeatureVectorPopUp/AddToFeatureVectorPopUp.js
  src/elements/FunctionsPanelRuntime/FunctionsPanelRuntime.js
  src/elements/ProjectFunctions/ProjectFunctions.js
  src/reducers/nuclioReducer.js
  src/store/toolkitStore.js
Labels: Cleanup, Infrastructure

#3232 Tests [QA] v1.10.0
  tests/features/artifacts.feature
  tests/features/common-tools/common-consts.js
  tests/features/common/page-objects/feature-store.po.js
  tests/features/common/page-objects/info-pane.po.js
  tests/features/datasets.feature
  tests/features/jobsAndWorkflows.feature
  tests/features/models.feature
  tests/features/support/hooks.js
  tests/mockServer/data/alerts.json
Labels: tests

#3233 Fix [Feature store & Functions panels] Checkbox is not clickable
  src/components/FunctionsPanel/FunctionsPanelView.js
  src/elements/PanelCredentialsAccessKey/PanelCredentialsAccessKey.js
Labels: bug

#3231 Impl [Monitoring application] Add Monitoring application page
  package.json
  src/App.js
  src/common/Breadcrumbs/breadcrumbs.util.js
  src/common/DatePicker/DatePicker.js
  src/components/ActionBar/ActionBar.js
  src/components/MonitoringApplication/MonitoringApplication.js
  src/components/MonitoringApplication/monitoringApplication.scss
  src/components/MonitoringApplication/monitoringApplication.util.js
  src/constants.js
  src/layout/Navbar/Navbar.utils.js
  src/utils/datePicker.util.js
Labels: enhancement

#3235 Bump MLRun version to `1.10.0`
  package.json
Labels: Infrastructure

#3236 Fix [Details Popup] Redundant pending data displayed in details function header
  src/components/Details/DetailsHeader/DetailsHeader.jsx
  src/elements/DetailsPopUp/JobPopUp/JobPopUp.jsx
  src/hooks/usePods.hook.js
  src/reducers/detailsReducer.js
Labels: bug

#3237 Fix [Artifacts] Align the behavior in the the labels and description editing mode
  src/components/Details/details.scss
  src/elements/DetailsInfoItemChip/DetailsInfoItemChip.jsx
Labels: bug

#3239 Fix [UI] misc bugs
  src/common/TabsSlider/TabsSlider.jsx
  src/elements/ContentMenu/ContentMenu.jsx
  src/scss/main.scss
Labels: bug

#3238 Fix [Artifacts] Path dropdown doesn't close when clicking outside the field
  package.json
  src/common/ChipForm/ChipForm.jsx
  src/common/Input/Input.jsx
  src/common/SplitButton/SplitButton.jsx
  src/common/TextArea/TextArea.jsx
Labels: bug

#3247 Fix [Artifacts] Path dropdown doesn't close when clicking outside the field `1.8.x`
  package.json
Labels: bug

#3248 Fix [Artifacts] Path dropdown doesn't close when clicking outside the field `1.9.x`
  package.json
Labels: bug

#3244 Fix [Alerts] The alert details pane doesn't close when switching between pages
  src/components/Alerts/Alerts.jsx
Labels: bug

#3240 Fix [Projects] 'Are you sure?' pop-up is missing `1.8.x`
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
Labels: bug

#3241 Fix [Projects] 'Are you sure?' pop-up is missing
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.jsx
Labels: bug

#3242 Fix [Projects] 'Are you sure?' pop-up is missing `1.9.x`
  src/components/ProjectsPage/CreateProjectDialog/CreateProjectDialog.js
Labels: bug

#3249 Fix [Artifacts] Artifact view shows only one row when filtering by "All Tags" `1.9.x`
  src/common/FormTagFilter/FormTagFilter.js
  src/components/ArtifactsActionBar/ArtifactsFilters.js
  src/components/Datasets/DatasetsView.js
  src/components/Documents/DocumentsView.js
  src/components/Files/FilesView.js
  src/components/FilterMenu/filterMenu.settings.js
  src/components/ModelsPage/Models/ModelsView.js
  src/hooks/useFiltersFromSearchParams.hook.js
Labels: bug

#3250 Fix [Artifacts] Artifact view shows only one row when filtering by "All Tags"
  src/common/FormTagFilter/FormTagFilter.jsx
  src/components/ArtifactsActionBar/ArtifactsFilters.jsx
  src/components/Datasets/DatasetsView.jsx
  src/components/Documents/DocumentsView.jsx
  src/components/Files/FilesView.jsx
  src/components/FilterMenu/filterMenu.settings.js
  src/components/ModelsPage/Models/ModelsView.jsx
  src/hooks/useFiltersFromSearchParams.hook.js
Labels: bug

#3251 Fix [UI] Notification duration line resets when navigating between pages `1.8.x`
  src/common/Loader/LoaderForSuspenseFallback.js
Labels: bug

#3252 Fix [UI] Notification duration line resets when navigating between pages `1.9.x`
  src/common/Loader/LoaderForSuspenseFallback.js
Labels: bug

#3253 Fix [UI] Notification duration line resets when navigating between pages
  src/common/Loader/LoaderForSuspenseFallback.jsx
Labels: bug
